### ISSUE TITLE
Check stats and improve layout

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#103]
The stats kinda look iffy.

Layout could be somewhat improved. The last time I tried graphs I gave up. Perhaps try again.

**Comment by judhat2** [comment]
Is there a way to make the tables to be in some kind of order.  I am referring to the 'History and Stats' page.  It has tables that list the avg. response times, avg. results shares, avg. indexer access success, and the NZB downloads per indexer. In addition, the Indexer statuses on the search page seems to be in a random order. Perhaps, it can be listed alphabetically, numerically, or by indexer priority?

Also, the 'System -> Backups' list is not in order by date.

My OCD is making me crazy looking at those unorganized tables. :)

**Comment by theotherp** [comment]
That I can do.

**Comment by judhat2** [comment]
Thanks! The stats look good. I appreciate it. If it's not too much trouble, can the indexer list and the indexer statuses on the main search page be sorted, too, since those seen most often?

**Comment by theotherp** [comment]
The indexer statuses should already be sorted.

**Comment by judhat2** [comment]
Hmmm, it doesn't appear to be on mine. How were those supposed to be sorted? Alphabetically, number of results, or response time? I noticed that the indexer statuses are listed in the same order as the indexer list with the check boxes, if that means anything.

![image](https://cloud.githubusercontent.com/assets/3536802/16540581/bc50a58a-40a4-11e6-853a-491fa62b79c0.png)

**Comment by theotherp** [comment]
Hah! They're sorted, just by case(N,O,S and a,l,m,n).

**Comment by judhat2** [comment]
Ah! I see that now.

**Comment by theotherp** [comment]
There you go.

**Comment by judhat2** [comment]
Thanks!

**Comment by theotherp** [comment]
Already done with graphs and shit.
