### ISSUE TITLE
A trailing slash in the base url can cause a loop which prevents loading the interface

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#105]
Tried to update from 0.0.1a48  to 0.0.1a49

When I tried to restart, I got the error message "too many redirects". I tried to restart my Ubuntu server and restarted my client (Mac mini, OS X). Tried with my iPad, same message. 

I did not get any errormessage on my server:
```
Setting base path to /opt/nzbhydra
Starting main program
usage: nzbhydra.py [-h] [--config CONFIG] [--database DATABASE] [--host HOST]
[--port PORT] [--nobrowser] [--daemon]

NZBHydra

optional arguments:
-h, --help show this help message and exit
--config CONFIG Settings file to load
--database DATABASE Database file to load
--host HOST Host to run on
--port PORT Port to run on
--nobrowser Don't open URL on startup
--daemon Run as daemon. *nix only
Loading settings from settings.cfg
2016-01-15 15:14:30,634 - INFO - nzbhydra - Started
2016-01-15 15:14:30,635 - INFO - nzbhydra - Daemonizing...
Setting base path to /opt/nzbhydra
Initial start. Starting subprocess in loop
Subprocess returned with code 0. Exiting.
```

**Comment by theotherp** [comment]
Have you tried starting it again a couple of times?

**Comment by Hobbabobba** [comment]
I tried it again for several times, incl. of a complete reboot of the server. no luck, same problem.

**Comment by theotherp** [comment]
Too bad. I'll check it out later. Sorry for the troubles.

**Comment by theotherp** [comment]
Ah can you try not running it as a daemon?

**Comment by Hobbabobba** [comment]
sorry, forgot to tell you :) i already tried not to run it as a daemon (had the idea, that maybe this way i can see some kind of error message).

**Comment by theotherp** [comment]
Too bad, I had hoped that could be it.

What's that last output? It looks like it's working? Or is that when you get the error message in the browser?

**Comment by theotherp** [comment]
It seems you're using a reverse proxy. Could you try to open the local address?

**Comment by Hobbabobba** [comment]
i tried the local address, same problem. After I started hydra, i got the message "too many redirects" in my browser (on 3 different computers).

**Comment by theotherp** [comment]
I just pushed some new code to develop. No auto update, just replace the old nzbhydra.py with the latest one: https://raw.githubusercontent.com/theotherp/nzbhydra/develop/nzbhydra.py

Then start with the command line parameter "--disablerestarter" and see if it works.

**Comment by Hobbabobba** [comment]
tried it. no errormessages (all the messages are the same) and "too many redirects"

**Comment by theotherp** [comment]
Hm... Delete the base url value, start and try opening the local address. It has to be related to the latest changes in the reverse proxy handling or something like that.

**Comment by Hobbabobba** [comment]
if i leave the base-url empty it works!

**Comment by theotherp** [comment]
All right, that's something. Too bad, I had hoped to have found a solution that works.

What's the structure of the base url and what do you use for the reverse proxy.

For comparison here's my apache setting:

    ProxyPass /nzbhydra/ http://localhost:5060/nzbhydra/
    ProxyPassReverse /nzbhydra/ http://localhost:5060/nzbhydra/

and my base url:
    https://12.345.67.78:8000/nzbhydra

**Comment by Hobbabobba** [comment]
i did not install a reverse proxy. just opened one port on my router for hydra, to let a friend us it, too.
if you access https://www.myip.com:9703  it will take you to the internal ip (192.168.0.128) and port 5075

the setting for my base url is https://www.myip.com:9703/   and it worked for several weeks

**Comment by theotherp** [comment]
Oh ok I didn't even think of that possibility. I guess I can find a way to test that locally and work on a fix. Stay tuned.

**Comment by theotherp** [comment]
Alright, I can already reproduce the error; that's the first step.

**Comment by Hobbabobba** [comment]
:+1:

**Comment by theotherp** [comment]
Remove the trailing slash from the base url.

**Comment by Hobbabobba** [comment]
works! thank you so much and sorry for the slash...

**Comment by theotherp** [comment]
Not a problem, I'll add some code that hopefully prevents this in the future.
