### ISSUE TITLE
Reverse Proxy Woes....

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#106]
Running reverse proxy - Hydra is running in a docker container.

![image](https://cloud.githubusercontent.com/assets/370860/12360159/6ec6d214-bb73-11e5-8680-f4ca44a76f84.png)

![image](https://cloud.githubusercontent.com/assets/370860/12360170/79e083fc-bb73-11e5-8ac4-5cca302f8e27.png)

When navigating to the proxy URL (http://example.com/nzbhydra/) I am being redirected to the IP:Port

Am I missing something here?

**Comment by theotherp** [comment]
Try

    ProxyPass /nzbhydra/ http://192.168.1.188:5075/nzbhydra/
    ProxyPassReverse /nzbhydra/ 192.168.1.188:5075/nzbhydra/

and then set the base url to 

http://www.yourdomain.com/nzbhydra

**Comment by theotherp** [comment]
Although I have to say I have no idea how docker plays into this, I've never used it.

**Comment by kylerw** [comment]
Using that syntax, do you keep it within the Location tag like I have? 


All my other services are in Docker Containers as well and play nicely so I wouldn't think it has anything to do with that. The only difference is, the Host listed in Hydra won't be the one used in the Apache config (it will be the IP of the Host the container is running on).

**Comment by theotherp** [comment]
MIne is in VirtualHost, missed that.

I know very little about reverse proxies and apache - enough to get mine running but not enough to give any support.

In any case you need to set the base url the url exposed by your apache, e.g. http://www.mydomain.com/nzhydra

**Comment by kylerw** [comment]
Ok, that did it. I used: 

![image](https://cloud.githubusercontent.com/assets/370860/12361197/f381b22a-bb79-11e5-8f39-f9594df577a4.png)


and then adjusted the base url as you suggested to:

http://mydomain.com/nzbhydra

(no trailing slash)

**Comment by theotherp** [comment]
That means it's working now or...?

**Comment by kylerw** [comment]
Yes, all good. Thanks for the guidance.
