### ISSUE TITLE
Year in Movies search

### ISSUE THREAD

**Issue by soundtrackgeek** [theotherp/nzbhydra#107]
Love NZBHydra and use it daily. Awesome! Is it possible to add a year in parentheses for movie search. Sometimes it's hard to judge by the small thumbnail posters what movie it is. A lot of movies have the same name so a small thing like that would be amazing. Thanks!

**Comment by theotherp** [comment]
Yeah I tried that once and it didn't work properly, will try again ☺

**Comment by soundtrackgeek** [comment]
Thanks! It's the little things, but if you can do it, it will make a world of difference :)

**Comment by soundtrackgeek** [comment]
![movies](https://cloud.githubusercontent.com/assets/14198271/12378802/1b10f0cc-bd4a-11e5-80f5-41cd086c6cc6.PNG)
Just updated to 1a52, but still don't see it. Maybe it doesn't work properly like you said?

**Comment by theotherp** [comment]
Do ctrl f5

**Comment by soundtrackgeek** [comment]
I did. Also tried in a few different browser (2 which I've never used it before, Edge and IE 11). Usually I use Firefox. However what I did do to make it work was cancel it in my cmd window and start it again manually (instead of just using it straight after it updated. Then it worked. Awesome! Thanks.

**Comment by theotherp** [comment]
That's weird. Will check if a restart if needed but it should not.
