### ISSUE TITLE
Installation on NAS (especially Synology)

### ISSUE THREAD

**Issue by Morktral** [theotherp/nzbhydra#108]
Hi there,

it would be great if there would be a package to install it directly on a NAS. For me it would be great to be a Synology

**Comment by theotherp** [comment]
Somebody else might do that but I can't.

**Comment by cornz** [comment]
I'm pretty sure it should work fine with a docker container. Maybe I'm able to test this on the weekend but can't guarantee it

**Comment by Morktral** [comment]
Unfortunatly Docker runs not on all NAS

**Comment by EZarnosky** [comment]
If you want this as a package why not request it from SynoCommunity? They do a good job getting stuff working for Synology devices. https://github.com/SynoCommunity/spksrc

**Comment by WilliamJBrown** [comment]
I have managed to get this running on synology but sadly when I restart the unit or container it loses all data. Have to set up every time I reboot the NAS. Any ideas?

**Comment by theotherp** [comment]
Have you checked the logs? It's possible that hydra cannot write the config file.

**Comment by theotherp** [comment]
See #166.
