### ISSUE TITLE
No ebooks found from nZEDb indexer

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#110]
When I am searching for an ebook from my newznab+ indexer, i get results. For my nZEDb-indexer, no ebook is found at all (when searching for the "ebook" category; when i do a general search without choosing the category ebooks, i get results).

I tried it with the (free) indexer ```http://nzedb.6box.me/``` and have the same problem.

**Comment by albino1** [comment]
Maybe a category problem?  NN uses `7020` for ebooks and nZEDb uses `8010`.  Taking a quick glance at the code I think @theotherp only included 7020.

**Comment by theotherp** [comment]
Of course they use different categories... Will take a look on sunday.

**Comment by albino1** [comment]
Looking at the code in https://github.com/theotherp/nzbhydra/commit/506acda5d9c24d767b8eb10629d4dbd44534d1da it seems like you just tacked nZEDb's `8010` on to Newznab's `7020`.  Some NN indexers, Dog for instance, use `8010` as a junk category.  I'm not sure if that matters for how you're searching, but I thought I'd mention it.

**Comment by theotherp** [comment]
Yeah it's a low effort fix. I'm considering adding a mapping of categories for every specific indexer but that will take some time. 

You'll probably only do query based searches on ebooks and using the author in that will most likely weed out of the spam / crap that way so I think it's OK.

**Comment by albino1** [comment]
Yeah, I agree.  The odds of there being a match in the junk category is pretty low.
