### ISSUE TITLE
FR: Clear Log from the GUI

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#112]
Right now my log goes all the way back more than a month and it's getting pretty cumbersome.  I was wondering if maybe you could add a way to clear the log without having to manually delete the file.  In particular I think this would be helpful for debugging.

**Comment by theotherp** [comment]
It should already rotate to a new file after 1 mb. So you only have one huge log file?

**Comment by albino1** [comment]
Ah, okay, it's around 800kb right now, so I'm sure it will clean itself up in the next week or so.  Thanks.

**Comment by theotherp** [comment]
I might change it to timed rotation, perhaps every 7 days. I think that's what sonarr does. My log probably rotates more often because I have debug level set, so it gets bigger faster.

**Comment by albino1** [comment]
Also, I only use NZBHydra manually, so I imagine people that are sending it a ton of API requests have their logs filling up and rotating a lot more often than I do.
