### ISSUE TITLE
Slow Load on Remote Access

### ISSUE THREAD

**Issue by imadunatic** [theotherp/nzbhydra#114]
I'll preface this by saying that my server sits behind a blazing 1mbps upload; however, I notice that initial load times for hydra are in the area of 45-60 seconds if accessing remotely. Is this possibly a config issue on my end or just the limit of my connection? Is Hydra uploading a cache of some sorts  to the remote client during this time?

**Comment by theotherp** [comment]
Is it behind a reverse proxy? Nginx or apache? Chrome or Firefox?

In my tests I noticed that using Chrome to access hydra behind an SSL nginx proxy the load was very, very slow, yes. No idea why though,

**Comment by theotherp** [comment]
As an experiment try activating the threaded server in the config.

**Comment by theotherp** [comment]
I'll also think about adding uWSGI or something similar so hydra can be run on a proper server.

**Comment by imadunatic** [comment]
No reverse proxy, just a DDNS in both Firefox and Chrome. I haven't tried direct ip:port yet to rule that out.  I'll activate the threaded server first, then see if direct IP makes a difference. 

This is by no means a problem, just wanted to make sure I didn't do something that would cause it.

**Comment by theotherp** [comment]
Out of the box there aren't too many ways to configure that wrong (I hope). I think there's a problem somehow, but network stuff definitely isn't my strong suit. I'll try to look into it, it shouldn't be slow :-)

**Comment by imadunatic** [comment]
No difference really with the threaded server. I'm going to leave it enabled just for Alpha testing purposes; if anything pops up, I'll post here. I'm gonna say you can close this, because I can't really nail down what it's doing in those 45 seconds, I more or less just wanted to make sure it wasn't a known issue with certain browsers if I configured something a certain way. 

Thanks again @theotherp .

**Comment by theotherp** [comment]
Oohh I know what's up. Or think I know. Can't verify, will confirm later.

**Comment by theotherp** [comment]
You could just block the image with an ad blocker...

**Comment by imadunatic** [comment]
That's what I'm currently doing. Thanks again for all the help. If I can do any testing, please let me know.

**Comment by theotherp** [comment]
First load per session or first load ever?

**Comment by imadunatic** [comment]
First load per session.

**Comment by imadunatic** [comment]
Also, if I have a session open, and I open a new one in another tab (without closing the first), the behavior persists for the initial loading.

**Comment by theotherp** [comment]
Too bad. I was at work, taking a dump, and thought I'd had a heureka moment. Anyway, keep this open. I'll try to analyze it soon.

**Comment by theotherp** [comment]
@imadunatic Please try changing your "Host" in the main settings from "0.0.0.0" to "127.0.0.1" or to your public IP. If that's possible.

I could reproduce the problem, but only locally, where accessing localhost with Chrome and HTTPS caused the site to be very slow.

**Comment by imadunatic** [comment]
Hmmmm... That might be the problem. I currently have my host set to the internal static IP for my server, and nothing for my base URL.... Changing the host to 127.0.0.1 didn't effect the load time remotely, and locally (through teamviewer as I'm not home) it loads instantly. 

So, is it because I have nothing set in my base URL for external access?

**Comment by theotherp** [comment]
Nah, the base URL is basically (hah) only needed if you use a reverse proxy and access hydra via a subfolder (like https://whatever/nzbhydra).

Go to the "static\js" subfolder and delete the .map files. If the files aren't cached you load about 10Mb of data with every first session request. With 1Mbit that can take a while. See if that helps.

You could also open the developer tools in your browser (F12), open the network tab and then do the first load of hydra. Check where the time is lost. Send me a screenshot if you like. This is what a "normal" request should look like: ![Network tab](http://i.imgur.com/8lHAcCx.png)

**Comment by albino1** [comment]
Interesting enough that I thought I'd mention it... on my local machine with NZB Hydra running if I access the URL as:

`http://127.0.0.1:5075/`

It takes less than a second to load.

However, if I access it as my actual external IP on the same machine:

`http://123.45.67.89:5075/`

It takes almost 13 seconds to load with `search.html` and `favicon.ico` loading after everything else and taking the final 6 seconds.  Even on a regular F5 reload the external IP version takes 7 seconds to reload the page whereas the localhost version takes only 600ms.

I tried replicating this with NZBMegaSearch and with SABnzbd, but both the localhost version and the external IP version load in under 1 second.

**Comment by albino1** [comment]
Screenshots in case they're helpful:

Localhost:

![al-nzbhydra-loading-01](https://cloud.githubusercontent.com/assets/12164957/12565526/a884b982-c369-11e5-9720-73cb7bf9e1cb.jpg)

External IP:

![al-nzbhydra-loading-02](https://cloud.githubusercontent.com/assets/12164957/12565528/ab124dae-c369-11e5-8e95-922255bda15f.jpg)

**Comment by albino1** [comment]
Looking at the second screenshot now, I might have misread it and it's actually taking almost 19 seconds for the initial load.

**Comment by imadunatic** [comment]
Yep.... It's my blazing fast 1mbps upload. 

This is local: 
![local](https://cloud.githubusercontent.com/assets/7814913/12567355/8ac0ac44-c38c-11e5-8459-528b6675c4db.JPG)

This is Remote
![remote](https://cloud.githubusercontent.com/assets/7814913/12567359/9465e322-c38c-11e5-9c40-998bb853177e.JPG)

The 4mb alllibs.js file in a perfect world would take 35 seconds to upload.  I'm gonna guess nothing I can do about this other than email Larry and Sergey and see if they want to drop me in some fiber?

**Comment by theotherp** [comment]
Thank's for the analysises, guys.

@imadunatic Nah, I think my cache control is broken. Either it never worked or I broke it with my cache breaker (how ironic). I never tested it properly (oops) and never noticed because I only access hydra locally and on my 100Mbps dedi. I'll try to fix it tonight.

**Comment by theotherp** [comment]
Alright, I found the issue. Resources were never cached... My bad. With the next push loading should be a lot faster, at least over a slow connection, and safe about 4.5MB bandwidth...

**Comment by imadunatic** [comment]
That's great news @theotherp . Thanks again for the work on this, I'll keep an eye out for when it's ready to test.

**Comment by theotherp** [comment]
Alright, if you want you can get it from develop. I changed a lot in the update process and what not, so there is the chance that something gets broken... Your call.

**Comment by imadunatic** [comment]
I'll do a backup tonight and try the develop. You gave fair warning that it's in alpha. Worst case I can always roll back.

**Comment by imadunatic** [comment]
Seems to cache properly now, first run results in a 4mb upload, next run loads from cache. 

I did notice that trying to run the dev branch silently results in this: 
```
2016-01-26 20:23:24,357 - INFO - nzbhydra - Started
2016-01-26 20:23:24,357 - INFO - config - Migrating config
2016-01-26 20:23:24,357 - INFO - config - Copying backup of settings to settings.cfg.2016-01-27.bak
2016-01-26 20:23:24,357 - INFO - config - Migrating config to version 5
2016-01-26 20:23:24,357 - INFO - config - Converting repository base URL
2016-01-26 20:23:24,357 - INFO - config - Migration of config to version 5 finished
2016-01-26 20:23:24,357 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-01-26 20:23:24,357 - INFO - indexers - Loaded indexer DogNZB
2016-01-26 20:23:24,357 - INFO - indexers - Loaded indexer OZNZB
2016-01-26 20:23:24,372 - INFO - indexers - Loaded indexer PFMonkey
2016-01-26 20:23:24,372 - INFO - indexers - Loaded indexer Althub
2016-01-26 20:23:24,372 - INFO - indexers - Loaded indexer Dusky
2016-01-26 20:23:24,372 - INFO - nzbhydra - Starting web app on 192.168.1.21:6327
2016-01-26 20:23:24,372 - ERROR - nzbhydra - Fatal error occurred
Traceback (most recent call last):
  File "G:\Github\nzbhydra\nzbhydra.pyw", line 138, in run
    if config.mainSettings.baseUrl.get() is not None and config.mainSettings.baseUrl.get() != "":
  File "G:\Github\nzbhydra\nzbhydra\config.py", line 74, in __getattribute__
    return super(Category, self).__getattribute__(*args, **kwargs)
AttributeError: 'MainSettings' object has no attribute 'baseUrl'
```
And it won't run. Running normally (from .py) and it starts and seems to work fine. Config issue on my end or something else?

**Comment by theotherp** [comment]
Yeah, the .pyw is a hack to get it to run windowless in windows. It's not part of the distribution, so when nzbhydra.py is updated you're still running the old version. Fear not, I'm planning to release a proper windows release this week - although with the release of The Witness yesterday and Rise of the Tomb Raider tomorrow, who knows.

**Comment by imadunatic** [comment]
I'll bite.... cloning now. I'll let you know if anything weird pops up.

**Comment by imadunatic** [comment]
It appears the windows release is doing the 4mb upload thing on every access(not sure if this was supposed to be fixed  in the windows release or not?)

![capture](https://cloud.githubusercontent.com/assets/7814913/12617119/3e6ab654-c4dc-11e5-9fca-3b66535f4f1f.JPG)

**Comment by imadunatic** [comment]
Well, on closer inspection it appears I broke something. I just shut down the windows version, fired the version up that was loading from cache last night and it's back to reloading on every access instead of from cache. Same as before, if I open a new window, navigate to hydra and let it load, then open a new window, navigate to hydra, it will fully load the 4mb file again. 

This is present in both releases.

**Comment by theotherp** [comment]
Nah, it should keep the cache. This internal or external?

Nevertheless, if that is the only bug you found in the windows release I'm happy :-) Are you using the tray tool? Does it work?

**Comment by theotherp** [comment]
I'll try to get this fixed, but I need a break. All programming and no play makes me a dull boy. Gimme a couple of days.

**Comment by imadunatic** [comment]
External currently. If I have time tonight I'll play around with Chome locally. 

Running the tray tool; works great, nice to have right click access from the desktop to hydra. Remotely accessing hydra on Firefox is awesome too. Loads instantly, searches are quick too. 

No rush on any of this. Just trying to help debug if I can; it's working great. Thanks again.

**Comment by theotherp** [comment]
Alright. Unfortunately this isn't completely solved. Assets are still loaded every time on my dedi. But it works locally and with a locally run apache proxy. No idea what's going on. I'm hoping for a flash of genius.

**Comment by imadunatic** [comment]
I've been using the windows version, and accessing it remotely using Firefox has been flawless. The slow load is mysteriously tied to chrome.

**Comment by theotherp** [comment]
Oh well, even more questions. That's good enough for me for now.

**Comment by theotherp** [comment]
By the way, I minified the alllibs.js which reduces its size from 4MB to 1MB which should help ;-)

**Comment by theotherp** [comment]
@imadunatic Hey, I changed caching again. Please let me know if your problem persists.

**Comment by imadunatic** [comment]
@theotherp Just updated, I will test Monday when I get to work...  I've got my other box on remote API and it's working great even through the reverse proxy. You're doing marvelous work with this.
