### ISSUE TITLE
no results on Spotweb

### ISSUE THREAD

**Issue by spants** [theotherp/nzbhydra#115]
I do not get any results on a local spotweb instance
Here is a call and a result for Logans Run:

        http://192.168.1.22:2080/spotweb/api?t=movie&apikey=****APIKEY*****&&imdbid=0074812

Result:

        <?xml version="1.0" encoding="utf-8"?>
        <rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/">
          <channel>
            <atom:link href="http://192.168.1.22:2080/spotweb/api" rel="self" type="application/rss+xml"/>
            <title>Spotweb Index</title>
            <description>Spotweb Index API Results</description>
            <link>http://192.168.1.22:2080/spotweb/</link>
            <language>en-gb</language>
            <webMaster>****userid*****</webMaster>
            <category/>
            <image>
              <url>http://192.168.1.22:2080/spotweb/images/spotnet.gif</url>
              <title>Spotweb Index</title>
              <link>http://192.168.1.22:2080/spotweb/</link>
              <description>SpotWeb Index API Results</description>
            </image>
            <newznab:response offset="0" total="7"/>
            <item>
              <title>Logan&amp;#039;s Run (1976) HQ 720p DD 5.1 NL Subs</title>
              <guid isPermaLink="false">ESOSxziB5WAYyalVgTP8M@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=ESOSxziB5WAYyalVgTP8M@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Sun, 24 Jan 2016 19:30:45 +0000</pubDate>
              <category>Image &gt; DivX</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=ESOSxziB5WAYyalVgTP8M@spot.net&amp;apikey=****APIKEY*****" length="3960401206" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="3960401206"/>
              <newznab:attr name="poster" value="SluweSjakie@spot.net"/>
              <newznab:attr name="comments" value="8"/>
            </item>
            <item>
              <title>Logan&amp;#039;s Run (1976) DD 5.1 NL Subs</title>
              <guid isPermaLink="false">Hv5ntZ7sSiguRF8VQaZqE@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=Hv5ntZ7sSiguRF8VQaZqE@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Sat, 13 Jun 2015 11:19:30 +0000</pubDate>
              <category>Image &gt; DVD5</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=Hv5ntZ7sSiguRF8VQaZqE@spot.net&amp;apikey=****APIKEY*****" length="4150462317" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="4150462317"/>
              <newznab:attr name="poster" value="SluweSjakie@spot.net"/>
              <newznab:attr name="comments" value="14"/>
            </item>
            <item>
              <title>Logan&amp;#039;s Run (1976) HQ MP3 NL Subs</title>
              <guid isPermaLink="false">xcZExvQj3W43BB8VQGmZn@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=xcZExvQj3W43BB8VQGmZn@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Sat, 13 Jun 2015 11:15:49 +0000</pubDate>
              <category>Image &gt; DivX</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=xcZExvQj3W43BB8VQGmZn@spot.net&amp;apikey=****APIKEY*****" length="2030305569" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="2030305569"/>
              <newznab:attr name="poster" value="SluweSjakie@spot.net"/>
              <newznab:attr name="comments" value="3"/>
            </item>
            <item>
              <title>Logan&amp;#039;s Run (1976) 1080p AAC 2.0 / 5.1 NL Subs x264</title>
              <guid isPermaLink="false">4fGWtcLWHawpQ98VQEdXG@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=4fGWtcLWHawpQ98VQEdXG@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Sat, 13 Jun 2015 11:12:04 +0000</pubDate>
              <category>Image &gt; x264HD</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=4fGWtcLWHawpQ98VQEdXG@spot.net&amp;apikey=****APIKEY*****" length="2402417612" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2040"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="2402417612"/>
              <newznab:attr name="poster" value="SluweSjakie@spot.net"/>
              <newznab:attr name="comments" value="20"/>
            </item>
            <item>
              <title>Logan&amp;#039;s run (1976)</title>
              <guid isPermaLink="false">V9BpFFSkVxgBevQUw7gsi@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=V9BpFFSkVxgBevQUw7gsi@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Thu, 24 Jul 2014 11:16:22 +0000</pubDate>
              <category>Image &gt; DivX</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=V9BpFFSkVxgBevQUw7gsi@spot.net&amp;apikey=****APIKEY*****" length="760922758" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="760922758"/>
              <newznab:attr name="poster" value="Jikje@spot.net"/>
              <newznab:attr name="comments" value="10"/>
            </item>
            <item>
              <title>Logan&amp;#039;s Run (1976) nl sub</title>
              <guid isPermaLink="false">qppErX3HbPIKlpCUAARV0@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=qppErX3HbPIKlpCUAARV0@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Sat, 01 Sep 2012 18:55:44 +0000</pubDate>
              <category>Image &gt; DVD5</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=qppErX3HbPIKlpCUAARV0@spot.net&amp;apikey=****APIKEY*****" length="4423147665" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="4423147665"/>
              <newznab:attr name="poster" value="badfan69@spot.net"/>
              <newznab:attr name="comments" value="20"/>
            </item>
            <item>
              <title>Logan&amp;#039;s Run (1976)</title>
              <guid isPermaLink="false">KqDXFGQ7Zh0UPznTQAInE@spot.net</guid>
              <link>http://192.168.1.22:2080/spotweb/api?t=g&amp;id=KqDXFGQ7Zh0UPznTQAInE@spot.net&amp;apikey=****APIKEY*****</link>
              <pubDate>Thu, 02 Jun 2011 21:10:40 +0000</pubDate>
              <category>Image &gt; DVD5</category>
              <enclosure url="http://192.168.1.22:2080/spotweb/api?t=g&amp;id=KqDXFGQ7Zh0UPznTQAInE@spot.net&amp;apikey=****APIKEY*****" length="4542389088" type="application/x-nzb"/>
              <newznab:attr name="category" value="2000"/>
              <newznab:attr name="category" value="2030"/>
              <newznab:attr name="subs" value="dutch"/>
              <newznab:attr name="size" value="4542389088"/>
              <newznab:attr name="poster" value="breezer2000@spot.net"/>
              <newznab:attr name="comments" value="10"/>
            </item>
          </channel>
        </rss>

**Comment by theotherp** [comment]
Well, to my defense, the description is part of the newznab standard result (I think).

I'll make it optional.
