### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#117]
It might be worth adding a robots.txt or anything else that would block search engines from crawling and displaying NZB Hydra installations that people have accidentally left open on the web.

**Comment by theotherp** [comment]
The meta tag

     <meta name="robots" content="noindex" />

in [index.html](https://github.com/theotherp/nzbhydra/blob/master/templates/index.html) already [takes care of that](https://en.wikipedia.org/wiki/Noindex).

**Comment by albino1** [comment]
Sorry about that, thanks!

**Comment by theotherp** [comment]
No worries.
