### ISSUE TITLE
PSA: If GUI doesn't work or NZB grabs via API don't work after the latest update

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#121]
Only applies to installations behind a reverse proxy.

Open your settings.cfg and in the "main" section fill the "urlBase" and "externalUrl" values, e.g.
"/nzbhydra" and "https://www.mydomain.com/nzbhydra".

**Comment by Cozza38** [comment]
Removing my existing settings and re-entering them into the GUI-based config worked for me. Thank you :)

**Comment by theotherp** [comment]
Alright. I had tested the migration extensively but apparently not enough -.-

**Comment by imadunatic** [comment]
@theotherp , can you merge this fix with the windows release? Just set up a reverse proxy today, and noticed this behavior, updated to the latest commit on my non-windows branch and it's fixed.

**Comment by theotherp** [comment]
I forgot anybody is using that...

**Comment by imadunatic** [comment]
LOL. I was only using it for testing.... Running from source on Windows 10 works fine too.

**Comment by theotherp** [comment]
Will merge soon and probably go to beta on the weekend.

**Comment by poopfist** [comment]
Hi, not sure if this issue is related, or if it's NZBHydra or nginx causing the problem.

I'm running NZBHydra behind an nginx reverse proxy. I followed the guide at https://github.com/theotherp/nzbhydra/wiki/Reverse-proxies-and-URLs and have my location section exactly as it appears in the guide. When I navigate to the page in a browser, this is all I see: http://i.imgur.com/OJqmmVs.png.

My other services(sonarr, nzbget, etc) work fine behind the proxy. Thanks for any help you can give.

**Comment by Cozza38** [comment]
Try doing a hard refresh (ctrl+f5) or clear cache.

**Comment by poopfist** [comment]
Tried hard refresh and clearing cache and see the same thing happen. It takes a very long time to load after a hard refresh.

**Comment by poopfist** [comment]
Solved it. Since I'm using a nonstandard port to connect externally, I had to add it to the nginx config in the X-Forwarded-Host line. Weird, that none of the other services need it.

**Comment by theotherp** [comment]
SB, sonarr, sabNZBd, CP and NZB Hydra all use different web frameworks so they're not really comparable. It's probably possible to get it to work without forwarding but I didn't manage to do so.

For what it's worth [the wiki](https://github.com/theotherp/nzbhydra/wiki/Reverse-proxies-and-URLs) says how to config nginx properly.

**Comment by poopfist** [comment]
The wiki is a proper nginx config if you're running ssl on 443, but since I was using a different port it wasn't being forwarded properly so I had to add it like: "proxy_set_header X-Forwarded-Host $host:12345;".

Anyways, thanks @theotherp for NZBHydra!
