### ISSUE TITLE
too many results with the movie imdb search

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#124]
I performed this search while selecting the Movies category.  `Movie search request with args {u'indexers': u'Althub|DogNZB|Drunken Slug|NzbCat|PirateNzb|nzbgeek|pfmonkey', u'category': u'Movies', u'minage': None, u'title': u'Creed', u'imdbid': None, u'maxage': None, u'minsize': 500, u'maxsize': 20000, u'tmdbid': u'312221', u'offset': 0, u'query': None}`

Two of the indexers, pfmonkey and althub, use the `t=search` instead of `t=movie`.  This returns all the results that match 'creed' and not the specific movie with the imdb id of 3076658. 
`2016-02-03 15:51:47,513 - DEBUG - search_module - Requesting https://drunkenslug.com/api?apikey=<APIKEY>&t=movie&extended=1&offset=0&limit=100&cat=2000&password=<PASSWORD>&imdbid=3076658 with timeout 10`
`2016-02-03 15:51:47,517 - DEBUG - search_module - Requesting https://api.althub.co.za/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&cat=2000&password=<PASSWORD>&q=Creed with timeout 10`
`2016-02-03 15:51:47,528 - DEBUG - search_module - Requesting https://pfmonkey.com/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&cat=2000&password=<PASSWORD>&q=Creed with timeout 10`
`2016-02-03 15:51:47,532 - DEBUG - search_module - Requesting https://piratenzb.com/api?apikey=<APIKEY>&t=movie&extended=1&offset=0&limit=100&cat=2000&password=<PASSWORD>&imdbid=3076658 with timeout 10`
`2016-02-03 15:51:48,714 - DEBUG - search_module - Successfully loaded URL https://nzb.cat/api?apikey=<APIKEY>&t=movie&extended=1&offset=0&limit=100&cat=2000&password=<PASSWORD>&imdbid=3076658`

I checked in the indexer config and those 2 indexers didn't have the search type "IMBD" enabled.  Is that the expected search behavior if the IMBD id is not supported?

**Comment by theotherp** [comment]
Do you have query generation enabled? Then yes. If not, no.

**Comment by judhat2** [comment]
Ah, ok. I did have that enabled.  I didn't think about that. Actually, I wasn't for sure how that option worked.  Good to know. Disabling that option worked. Thanks!

**Comment by theotherp** [comment]
Yeah, that's one of the problems with having so many options. I'll write a wiki / FAQ for some of that stuff.
