### ISSUE TITLE
nzbget can't authenticate with nzbhydra

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#125]
I am getting this error in NZBget after I send an nzb to it from nzbhydra.  It adds the nzb to nzbget successfully. 
`URL nzb.name.720p.WEB-DL.x264 @ 192.168.1.5 failed: HTTP/1.0 401 UNAUTHORIZED`

NZBhydra's log has this:
`WARNING - web - IP 192.168.1.5 failed to authenticate. The last time was at 2016-02-03 14:45:34. This was his 1. failed login attempt`

I have **NZB adding type** set to '_send link_' and **NZB access type** set to '_redirect to indexer_'. 
'_Proxy nzbs from indexer_' gives the same error.  If I set the **NZB adding type** to '_upload NZB_' it successfully downloads. I assume that works since it doesn't have to communicate with nzbhydra after that.

What do I need to do to authenticate it?  It was working before.  I am not sure when it stopped working. I can take the same url that is sent to NZBget and paste it in my browser, and it will download the nzb. For now, I will just use the '_upload NZB_' option.

**Comment by theotherp** [comment]
Can reproduce. Stay tuned.

**Comment by judhat2** [comment]
:+1:
