### ISSUE TITLE
Sonarr receiving 404 Not found when Trying to grab NZB File

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#129]
As a result my Hydra indexer is then disabled in Sonarr.

error: 

16-2-9 19:05:07.4|Warn|HttpClient|HTTP Error - Res: [GET] http://url.com/getnzb?apikey=<removed>&id=(indexer:nzb.su,indexerguid:'16dd351e6fe00c86a83db7283049ea67',searchid:2692,title:The.X-Files.S10E04.REAL.PROPER.720p.HDTV.x264-TURBO) : 404.NotFound
16-2-9 19:05:07.5|Error|Nzbget|Downloading nzb for episode 'The.X-Files.S10E04.REAL.PROPER.720p.HDTV.x264-TURBO' failed (http://url.com/getnzb?apikey=<removed>&id=(indexer:nzb.su,indexerguid:'16dd351e6fe00c86a83db7283049ea67',searchid:2692,title:The.X-Files.S10E04.REAL.PROPER.720p.HDTV.x264-TURBO))

NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://url.com/getnzb?apikey=<removed>&id=(indexer:nzb.su,indexerguid:'16dd351e6fe00c86a83db7283049ea67',searchid:2692,title:The.X-Files.S10E04.REAL.PROPER.720p.HDTV.x264-TURBO)]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) <0x402ba430 + 0x0048b> in <filename unknown>:0 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) <0x402ba3f0 + 0x0002b> in <filename unknown>:0 
  at NzbDrone.Core.Download.UsenetClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) <0x4004ec30 + 0x000fa> in <filename unknown>:0

**Comment by theotherp** [comment]
Set your external URL in the config ("http://url.com/nzbhydra/") (I tested it ;-)) or enable "Use local address in API results".

**Comment by kylerw** [comment]
@theotherp that's what's weird. It works 99% of the time but every now and then it errors like we see here.

**Comment by theotherp** [comment]
You mean it sometimes builds the wrong URL, missing the "/nzbhydra"?

**Comment by kylerw** [comment]
@theotherp That's correct.

**Comment by theotherp** [comment]
That's.... weird.
