### ISSUE TITLE
I'm sorry, but how do I install this on Windows?

### ISSUE THREAD

**Issue by EhGneissGuy** [theotherp/nzbhydra#131]
I have no clue what I'm doing. I've cloned it using Git, that's far as I've gotten.

Edit: Nevermind, just found the binary section.

**Comment by theotherp** [comment]
Yeah, usually you would just run nzbhydra.py with python 2.7. The binaries are not official yet and not regularly updated. I recommend running from source.
Download the source: https://github.com/theotherp/nzbhydra/archive/master.zip and extract it to any folder. Rename "nzbhydra.py" to "nzbhydra.pyw" and open it with your python.exe (from https://www.python.org/download/releases/2.7/ ). That way you don't have the console window open as long as the tool is running.
