### ISSUE TITLE
Base URL set incorrectly?

### ISSUE THREAD

**Issue by JosephDuffy** [theotherp/nzbhydra#132]
First of all, I love NZB Hydra. I've currently got it setup behind an Nginx reverse proxy. In my settings I have:

URL base: /hydra/
External URL: https://my.domain/hydra/

However, when I go to https://my.domain/hydra/, the value for the base url is set to `/`:

    <base href="//my.domain/">

Looking at the code, it would appear the logic for this is performed in [web.py line 62-73](https://github.com/theotherp/nzbhydra/blob/9b52c44845cc3c169e9b4affbc65bed4b9c8861b/nzbhydra/web.py#L62). I don't know much Python, so for now I've just commented out lines 64-72 and manually set line 63 to:

    environ["MY_URL_BASE"] = "/hydra/"

I'm not sure what needs to be done, but it'd be nice if a config change/code change would mean I don't have to change the source :)

**Comment by theotherp** [comment]
Please try "/hydra" as URL base (without trailing slash).

**Comment by JosephDuffy** [comment]
I have tried it without the trailing slash, but the base url is still `//my.domain/`

**Comment by theotherp** [comment]
That's weird, I have basically the same setup (just with "nzbhydra" instead of "hydra") and it works fine.

Do you forward host etc as described here: https://github.com/theotherp/nzbhydra/wiki/Reverse-proxies-and-URLs ?

**Comment by JosephDuffy** [comment]
That's fixed it! I had to change

    proxy_pass http://127.0.0.1:5075/;

to

    proxy_pass http://127.0.0.1:5075/hydra/;

Forgive my silliness!

**Comment by theotherp** [comment]
Alright, glad to hear it's working.
