### ISSUE TITLE
Error: Http request configuration url must be a string

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#133]
Just updated to 7c39e91, and now everytime I do a search, my search box turns into this.  
![image](https://cloud.githubusercontent.com/assets/3536802/13186676/a7029ab8-d78a-11e5-804b-debbc98e3d56.png)
There is nothing in the log, but I get this error in Chrome's console:
```
Error: [$http:badreq] Http request configuration url must be a string.  Received: {"_string":"internalapi/search?query=ufc&indexers=DogNZB%7Cusenet-crawler&category=All","_parts":{"protocol":null,"username":null,"password":null,"hostname":null,"urn":null,"port":null,"path":"internalapi/search","query":"query=ufc&indexers=DogNZB%7Cusenet-crawler&category=All","fragment":null,"duplicateQueryParameters":false,"escapeQuerySpace":true},"_deferred_build":false}
```

**Comment by theotherp** [comment]
Where the fuck did that come from...

**Comment by theotherp** [comment]
Sorry about that.

**Comment by judhat2** [comment]
Thanks for the quick fix!

**Comment by judhat2** [comment]
Updated and the search is working, however I am getting a similar error when I try to retrieve an nfo.
```
Error: [$http:badreq] Http request configuration url must be a string.  Received: {"_string":"","_parts":{"protocol":null,"username":null,"password":null,"hostname":null,"urn":null,"port":null,"path":"internalapi/getnfo","query":"indexer=nzbgeek&guid=14fe159aea50f8344e91583b49b37b1a","fragment":null,"duplicateQueryParameters":false,"escapeQuerySpace":true},"_deferred_build":true}
```

**Comment by theotherp** [comment]
Damn.

**Comment by theotherp** [comment]
Thanks for testing.

**Comment by vinodkus** [comment]
I am facing same type of issue.
I am calling
   .when("/HTML/students/:id", {
            templateUrl: "/Templates/studentDetails.html",
            controller: "studentDetailsController"
    })
and

.controller("studentDetailsController", function ($scope, $http, $routeParams) {
    $http.get({
        url: "/Service/StudentService.asmx/GetStudent",
        method: "get",
        params:{ id: $routeParams.id}
    }).then(function (response) {
        $scope.student = response.data;
    })
})

but getting error like
Error: $http:badreq
Bad Request Configuration

Http request configuration url must be a string.  Received: {"url":"/Service/StudentService.asmx/GetStudent","method":"get","params":{

Control is not going to method GetStudent.
What could be the reason and its solution.
Please help me asap.

Thanks in Advance
Vinod

**Comment by theotherp** [comment]
That's not my code, can't help you with your homework. Ask on SO.
