### ISSUE TITLE
show on search 

### ISSUE THREAD

**Issue by jusplainrob** [theotherp/nzbhydra#134]
just update to version 0.0.1a65 
now get the following message :

An error occured :
500: INTERNAL SERVER ERROR
showOnSearch

Traceback (most recent call last):
  File "c:\hydra\libs\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\hydra\libs\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\hydra\nzbhydra\web.py", line 272, in wrapped_function
    return f(*args, **kwargs)
  File "c:\hydra\nzbhydra\web.py", line 825, in internalapi_getsafeconfig
    return jsonify(config.getSafeConfig())
  File "c:\hydra\nzbhydra\config.py", line 452, in getSafeConfig
    indexers.extend([{"name": x["name"], "preselect": x["preselect"], "enabled": x["enabled"], "showOnSearch": x["showOnSearch"] and x["accessType"] != "external"} for x in settings["indexers"]["newznab"]])
KeyError: u'showOnSearch'

**Comment by theotherp** [comment]
Please send me your settings.cfg. Remove all API keys and host / external URL / other sensitive settings.

**Comment by aaearon** [comment]
Just discovered this project and added a single newznab indexer (nzb.su) and get this same error. Only changes from default should be the addition of nzb.su

Here is the gist: https://gist.github.com/aaearon/b91622be34b2c5a89595

**Comment by theotherp** [comment]
Right, it only happens with newly added indexers. Fix coming soon.

**Comment by theotherp** [comment]
@aaearon Bad first impression, sorry about that.
