### ISSUE TITLE
don't ship SSL certificate

### ISSUE THREAD

**Issue by redlulz** [theotherp/nzbhydra#139]
There's no point in shipping a certificate and the corresponding key. Using this certificate is as secure as not using SSL at all. If a user wants to use SSL, they need to generate their own key pair.

**Comment by theotherp** [comment]
Alright.

**Comment by redlulz** [comment]
no, Sabnzbd doesn't ship a certificate but generates one on-the-fly, see https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L1398

**Comment by theotherp** [comment]
Oh, good to know. Thanks.
