### ISSUE TITLE
systemd service file?

### ISSUE THREAD

**Issue by sanderant** [theotherp/nzbhydra#141]
I'm building a new box with this on along with other tools. I'd like it to start automatically as opposed to running it in tmux session (which is what I do now).

**Comment by theotherp** [comment]
Try http://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/

**Comment by sanderant** [comment]
That was helpful it would be good if you could include samples in the git repo. Just a suggestion.

**Comment by theotherp** [comment]
I included a link in the WIKI. I try to include only what I can support and I wouldn't be able to help anybody with the upstart files. But I might include it in the readme for better visibility.

**Comment by sanderant** [comment]
Thanks again. I just got it going again I should have checked the wiki first. Another area I'm looking at is how to move the config between machines. I see the settings.cfg, but how would I move the database?

Lastly I don't know if you ever saw this, but something completely different, yet similar in a tiny bit https://github.com/jparkerweb/Low_Voltage_Generator different language, and dead links, but just in case you look at other types of projects.

Thanks again for all your hard work. I am a fan!

**Comment by theotherp** [comment]
Database is stored in nzbhydra.db
