### ISSUE TITLE
"download selected" button downloads more than is selected.

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#144]
I haven't been able to narrow down exactly what happens, but, if generally it's something like this:

when looking at a list of search results, I click the box to select all, then go through and click to deselect certain items.  then click the 'download selected' button.

things that were deselected get added to my sabnzbd queue.

if I only mark certain items, then it seems to only download those.

**Comment by theotherp** [comment]
Can reproduce.

**Comment by theotherp** [comment]
This is so much more complicated that I though. Giving up for now, will come back to it later.
