### ISSUE TITLE
Search result interface changes

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#145]
I don't have the widest browser window, not wanting to take up all my screen with browser (I'm doing other things too, ya know ;) )  and when looking at the search screen, the max age entry block overlays the size text, so that all I see is an "e" poking out from behind the age blocks.

also, after searching, could the indexer stats be below the results?  less scrolling down to get to what I'm there for in the first place.

I've only been playing with this for a day, but really do like it.

**Comment by theotherp** [comment]
Yeah sorry, my primary screen is 2560 and my secondary 1200 pixels wide, so I often forget to check with smaller resolutions/sizes.

**Comment by theotherp** [comment]
Could please post a screen shot?

**Comment by diamaunt** [comment]
here ya go: 
![nzb hydra - mozilla firefox_022](https://cloud.githubusercontent.com/assets/17405120/13231847/a70a98f6-d971-11e5-9ef2-9d61c1670c8a.png)
just happened to be 1111x970 pixels.

**Comment by theotherp** [comment]
Oh, I thought you meant the search results. Yeah, got it.

**Comment by diamaunt** [comment]
I think the search results are ok width wise, 

however, could the 'indexer statuses' be below the search results? having them compressed is certainly better and I won't complain any further if the decision is is to leave them above the search results.  (I have now updated to 1a.76)

**Comment by theotherp** [comment]
Yeah, I prefer to have them on top.

**Comment by theotherp** [comment]
Rest will be done with #189.
