### ISSUE TITLE
RFE: more meaningful error message.

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#146]
Initially, I picked the 'nzb key' from sab, and didn't test the connection, when I tried to send a nzb there, I got a popup that said: 
An error occured :
500: INTERNAL SERVER ERROR

Expecting value: line 1 column 1 (char 0)

it wasn't very helpful.  I did figure out what the problem was, in the end, though.

**Comment by theotherp** [comment]
See https://github.com/theotherp/nzbhydra/issues/31

**Comment by theotherp** [comment]
In return, if you could tell me what your original problem was instead of "I did figure out what the problem was", that would be helpful ;-)

**Comment by diamaunt** [comment]
Sorry, I said originally that I'd picked the 'nzb' key from the sab page, instead of the 'all access' key.  so perhaps something on the page where you configure sab that says which of the two api keys is needed.

**Comment by theotherp** [comment]
I can add to sabnbd with either API key. If I don't provide an API key I get a message that I need to provide either that or a username. When I enter an invalid address I get an error box. So I don't know what you did to cause the problem you describe. Without being able to reproduce it I cannot fix it, sorry. Thanks for the feedback anyway.

**Comment by diamaunt** [comment]
I added the nzb only the second one on the sab page) key, not the main API key, and i forgot to hit the test button. I just clicked "save", and hydra saved the key, then I did a search, and clicked the SAB button, whereupon I got the error.

if I use the nzb only key, operation to sab fails, if i use the master api key, it works.
