### ISSUE TITLE
RFE: don't automatically restart after upgrade.

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#147]
On my system,  (Solaris) a system process starts, stops and monitors background processes.   if the process dies, then the system immediately restarts it.  I believe that systemd on linux has similar auto restart functionality.

I believe this will cause conflict with the automatic restart after updates.

could the internal update process be changed to add a "shutdown or restart after update" option? either a button selection, or perhaps a configurable option?

as it is, if I update while nzbhydra is under OS control, then it will try to restart, AND the OS will try to restart it too.   if it updates and shuts down, then the OS will fire it up fresh.

**Comment by theotherp** [comment]
Can you add a switch to not restart with exit code 0?

**Comment by diamaunt** [comment]
even if that were possible, I don't think that would work, because then the program would not be under OS control when it came up again.   so if it DID crash afterwards, it wouldn't get restarted.

maybe I can automate the updating through the OS control... what does the update do besides a git pull?  perhaps I could do that with a shell script?

**Comment by theotherp** [comment]
Git pull and restart, that's it. 

I think sabNZBd and SickBeard behave the same way (shutdown and start a new instance), do you have any experience with them?

So I could add a switch to disable restarting after an update but then the update wouldn't be complete.

**Comment by diamaunt** [comment]
I have sab running under the same facility (called SMF or Service Management Facility), but I normally just do manual sab updates.   shut down service, move old version out of the way  (incase new version goes BOOM) unzip new version, restart service.

I hadn't noticed a built in updater for sab.  maybe I've been missing out :dancer: 
I can easily script a git pull restart... then just tell SMF to refresh hydra.  

thanks.

**Comment by theotherp** [comment]
Alright, I will close this for now. 

I usually try not to push updates too often but the significant changes in the codebase last week and the latest influx of new users ended in a lot of bugs (fixes). Usually minor updates should be pushed about once a week, major updates once a month or so. You should be fine with not updating for longer periods.
