### ISSUE TITLE
unable to start

### ISSUE THREAD

**Issue by phairplay** [theotherp/nzbhydra#148]
hi ive just downloaded your tool and im unable to get it to start

c:\NZBHydra>python nzbhydra.py
Setting base path to c:\NZBHydra
Traceback (most recent call last):
  File "nzbhydra.py", line 28, in <module>
    from furl import furl
  File "c:\NZBHydra\libs\furl\__init__.py", line 17, in <module>
    from .furl import *
  File "c:\NZBHydra\libs\furl\furl.py", line 13, in <module>
    from posixpath import normpath
  File "c:\NZBHydra\libs\posixpath.py", line 19, in <module>
    from genericpath import _unicode
ImportError: cannot import name _unicode

c:\NZBHydra>python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>>
to confirm i am running 2.7.9

can you please help

**Comment by theotherp** [comment]
As a workaround, how about using the windows release?

**Comment by phairplay** [comment]
Windows release working okay
Many thanks
