### ISSUE TITLE
 500: INTERNAL SERVER ERROR accessType

### ISSUE THREAD

**Issue by WodKa78** [theotherp/nzbhydra#149]
As discussed before receive this message on the search page also Just found out the Config button gives no response anymore.

files:

[hydra log and settings.zip](https://github.com/theotherp/nzbhydra/files/141990/hydra.log.and.settings.zip)

Thanks for looking into it

**Comment by WodKa78** [comment]
Just found out the Config button also gives no response anymore

**Comment by theotherp** [comment]
Uhm, kinda embarrassing, but how did you upload that file?

Anyway, [this is the updated settings.cfg](https://gist.github.com/theotherp/bb6e8b9f46d06cebeb53). You need to put your API keys, usernames, etc. back, save it and restart hydra. Try if it works.

**Comment by WodKa78** [comment]
Perfect, working again :) 

Don't really understand the question, you mean how i uploaded the file to Github?

**Comment by theotherp** [comment]
Yes...

**Comment by WodKa78** [comment]
![image](https://cloud.githubusercontent.com/assets/17422816/13245881/33a92a96-da4b-11e5-95fb-866369cdd9e7.png)

**Comment by theotherp** [comment]
Oh... -.- Thanks.

**Comment by WodKa78** [comment]
welcome
