### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#153]
Hopefully better looking than the old one...

**Comment by alienx2** [comment]
+1

**Comment by theotherp** [comment]
[nzbhydra logo.zip](https://github.com/theotherp/nzbhydra/files/212780/nzbhydra.logo.zip)

**Comment by PoppinTaco** [comment]
Loving the theme so far!

**Comment by theotherp** [comment]
Aw, thank you!

**Comment by albino1** [comment]
Just started using it and I like it a lot.  Well done!
