### ISSUE TITLE
Error when trying to load more results

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#161]
![image](https://cloud.githubusercontent.com/assets/3536802/13358187/63492f00-dcf1-11e5-9c05-b5731c31930c.png)
After I do a search, sometimes I see this button to load more searches.  I clicked on it and got this error:
```
TypeError: lastExecutedQuery.removeQuery is not a function
    at Object.loadMore (http://192.168.1.5:5075/static/js/nzbhydra.js:1062:27)
    at http://192.168.1.5:5075/static/js/nzbhydra.js:1259:27
    at processQueue (http://192.168.1.5:5075/static/js/alllibs.js:24763:28)
    at http://192.168.1.5:5075/static/js/alllibs.js:24779:27
    at Scope.$eval (http://192.168.1.5:5075/static/js/alllibs.js:26031:28)
    at Scope.$digest (http://192.168.1.5:5075/static/js/alllibs.js:25847:31)
    at Scope.$apply (http://192.168.1.5:5075/static/js/alllibs.js:26139:24)
    at http://192.168.1.5:5075/static/js/alllibs.js:27964:36
    at completeOutstandingRequest (http://192.168.1.5:5075/static/js/alllibs.js:15015:10)
    at http://192.168.1.5:5075/static/js/alllibs.js:15292:7 
    undefined(anonymous function) @ alllibs.js:22447
```

**Comment by theotherp** [comment]
Got it.

**Comment by judhat2** [comment]
Thanks, again.
What kind of results are being hidden?  I can't seem to figure out which additional results are being shown. Just curious.

**Comment by theotherp** [comment]
Say you have three indexers which each returned 100 results and the information that it has a total of 200 results. You have 300 results "right now" and now that there are 300 more. The first 100 are shown and on clicking "Load more" you get the next 100 and next 100. Then there are no more results already cached so we ask each indexer for the next 100.

Also if you defined a min/max age/size and an indexer doesn't support filtering by that then any result outside the defined range is hidden by the GUI.

**Comment by judhat2** [comment]
Thanks for explaining it. That makes sense now.
