### ISSUE TITLE
Error when trying to get anonymized versions of the log and settings

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#162]
Thanks for all the recent updates!
When I tried test the 'Log and settings' button in the 'Bugreport' section, I got just a blank page.  The log said this:
```
2016-02-27 11:07:22,821 - DEBUG - backup_debug - Writing log to temp file /root/nzbhydra/debug/logfile.txt
2016-02-27 11:07:22,826 - ERROR - web - 'ascii' codec can't encode character u'\xe1' in position 903968: ordinal not in range(128)
Traceback (most recent call last):
  File "nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "nzbhydra/nzbhydra/web.py", line 267, in wrapped_function
    return f(*args, **kwargs)
  File "nzbhydra/nzbhydra/web.py", line 826, in internalapi_getdebugginginfos
    debuggingInfos = getDebuggingInfos()
  File "nzbhydra/nzbhydra/backup_debug.py", line 86, in getDebuggingInfos
    textfile.write(al)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 903968: ordinal not in range(128)
```
And this is in the browser console:
```
http://removed:8085/jsonrpc Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
```

**Comment by theotherp** [comment]
Aaaaargh I fucking hate encoding errors.

**Comment by theotherp** [comment]
Could you please post your log file so I can test with it.

**Comment by judhat2** [comment]
It works now on master after the log rotated to a new file. I renamed nzbhydra.log.1 back to nzbhydra.log and got the error again.  I have attached the problem log file. [nzbhydra.log.txt](https://github.com/theotherp/nzbhydra/files/149242/nzbhydra.log.txt)

I switched over to the develop branch, and received this error with the problem log file: 
`An error occured while creating the debugging infos: 'ascii' codec can't decode byte 0xc3 in position 850848: ordinal not in range(128)`

**Comment by judhat2** [comment]
I got that error in the browser window itself

**Comment by theotherp** [comment]
Yeah, that's correct, I added a notification so you just don't get a blank page. 
Thanks for the log file, "unfortunately" it works fine for me.

**Comment by judhat2** [comment]
Well, it works for me now on the master and develop branch with a new log file. So, maybe this can be closed?

**Comment by theotherp** [comment]
As soon as a text with the wrong encoding is written to the log file the problem will return. Encoding with Python 2.7 is kind of a pain in the ass and I always just ignored it, hoping for the best. That now comes back to haunt me. We'll see, I'll leave this open.

**Comment by theotherp** [comment]
Ok, I'm an idiot, I tested the wrong function. Can reproduce now -.-

**Comment by theotherp** [comment]
Should be fixed now. No idea if my approach is 100% correct but it works (for now).

**Comment by judhat2** [comment]
Working for me, too. Thanks!
