### ISSUE TITLE
500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by alienx2** [theotherp/nzbhydra#163]
I dont know what this happen after update to new version. before was okay.

Error said:

> An error occured :
> 500: INTERNAL SERVER ERROR
> 
> accessType

![screenshot_09](https://cloud.githubusercontent.com/assets/1681482/13378246/d5b010e2-de39-11e5-84e1-eea2c57ef9c4.png)

log:
```
Setting base path to /tmp/mnt/TOSHIBA/entware/etc/nzbhydra
usage: nzbhydra.py [-h] [--config CONFIG] [--database DATABASE]
                   [--logfile LOGFILE] [--host HOST] [--port PORT]
                   [--nobrowser] [--daemon] [--pidfile PIDFILE]

NZBHydra

optional arguments:
  -h, --help           show this help message and exit
  --config CONFIG      Settings file to load
  --database DATABASE  Database file to load
  --logfile LOGFILE    Log file. If set overwrites config value
  --host HOST          Host to run on
  --port PORT          Port to run on
  --nobrowser          Don't open URL on startup
  --daemon             Run as daemon. *nix only
  --pidfile PIDFILE    PID file. Only relevant with daemon argument
Loading settings from settings.cfg
2016-02-28 08:43:10,603 - INFO - nzbhydra - Started
2016-02-28 08:43:10,723 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-02-28 08:43:11,099 - INFO - indexers - Loaded indexer 6box
2016-02-28 08:43:11,124 - INFO - indexers - Loaded indexer NZBCat
2016-02-28 08:43:11,148 - INFO - indexers - Loaded indexer Drunken Slug
2016-02-28 08:43:11,316 - INFO - indexers - Loaded indexer OZNZB
2016-02-28 08:43:11,336 - INFO - indexers - Loaded indexer UsenetCrawler
2016-02-28 08:43:11,360 - INFO - indexers - Loaded indexer LuluNZB
2016-02-28 08:43:11,393 - INFO - nzbhydra - Starting web app on 0.0.0.0:5075
2016-02-28 08:43:11,532 - INFO - nzbhydra - Go to http://127.0.0.1:5075 for the frontend
2016-02-28 08:43:17,087 - ERROR - web - u'accessType'
Traceback (most recent call last):
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/nzbhydra/web.py", line 267, in wrapped_function
    return f(*args, **kwargs)
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/nzbhydra/web.py", line 819, in internalapi_getsafeconfig
    return jsonify(config.getSafeConfig())
  File "/tmp/mnt/TOSHIBA/entware/etc/nzbhydra/nzbhydra/config.py", line 538, in getSafeConfig
    indexers.extend([{"name": x["name"], "preselect": x["preselect"], "enabled": x["enabled"], "showOnSearch": x["showOnSearch"] and x["accessType"] != "external"} for x in settings["indexers"]["newznab"]])
KeyError: u'accessType'
2016-02-28 08:43:17,319 - INFO - update - git output: git version 2.6.3
```

**Comment by theotherp** [comment]
Please open your settings.cfg and for every newznab indexer add the line 

    "accessType": "both", 

like so:

    "newznab": [
            {
                "accessType": "both", 
                "apikey": "apikey", 
                "enabled": true, 
                "host": "https://nzbs.org", 
                "name": "NZBs.org", 
                "preselect": false, 
                "score": 11, 
                "search_ids": [
                    "rid", 
                    "tvdbid", 
                    "tvmazeid", 
                    "imdbid"
                ], 
                "showOnSearch": true, 
                "timeout": 20
            }, 
            {
                "accessType": "both", 
                "apikey": "apikey", 
                "enabled": false, 
                "host": "https://api.nzb.su", 
                "name": "nzb.su", 
                "preselect": true, 
                "score": 0, 
                "search_ids": [
                    "imdbid", 
                    "rid", 
                    "tvdbid"
                ], 
                "showOnSearch": true, 
                "timeout": null
            }
        ],

**Comment by theotherp** [comment]
Apparently in some cases I don't understand yet the migration from the old config fails. Will check it out.

**Comment by theotherp** [comment]
Also, please post the section of your log file from when you updated.

**Comment by alienx2** [comment]
now it working. thanks =)

**Comment by theotherp** [comment]
You mean with code I pushed to develop?

**Comment by alienx2** [comment]
Yes.. i saw there was missing "accessType": "both", in settings.cfg (which created by old version).. then i followed your instruction.. i guess old version didnt made it.

**Comment by nuddyd** [comment]
Having same error - while doing an API search or normal search

08-17 14:40:16 ERROR[hpotato.core.plugins.base] Failed opening url in Newznab: http://localhost:5075/api?imdbid=1392214&apikey=xxx&t=movie&extended=1 Traceback (most recent call last): ReadTimeout: HTTPConnectionPool(host='localhost', port=5075): Read timed out. (read timeout=30) 

My settings do have above command

Any solution?

**Comment by theotherp** [comment]
@nuddyd Create a new issue and post your log.

**Comment by nuddyd** [comment]
I have created an issue - Some movies throwing - failed opening url in Newznab #6747
But I think no one replied :(
