### ISSUE TITLE
Feature Request: Synology Package Installer

### ISSUE THREAD

**Issue by Elfman72** [theotherp/nzbhydra#166]
First off, I thanks for the great program!  Use it very frequently.  Was wondering if at some point, you'd be able to contribute this to [SynoCommunity](https://synocommunity.com/). These guys package up apps like Sonarr, SABNzbd, CouchPotato, among many others. to be installed onto Synology NAS boxes.  I know this will lie low on your priority list but wanted to at least put it on your radar.  Thanks for Hydra! Loving the progress and updates.

I have created the request on their Git page as well.
https://github.com/SynoCommunity/spksrc/issues/2164

**Comment by theotherp** [comment]
I can't provide that because I don't have a synology on which I could test it. But if anybody would be willing to do so I'd help as good as I can.

**Comment by adchevrier** [comment]
I just made a PR for this : https://github.com/SynoCommunity/spksrc/pull/2168

**Comment by theotherp** [comment]
Nice, thank you!

**Comment by Elfman72** [comment]
Much thanks!  I can test it on my DS1815+ once it is ready.

**Comment by theotherp** [comment]
Mhmm sorry, can't tell anything from looking at the source. You guys will need to just test it.

**Comment by adchevrier** [comment]
@Elfman72 You can easily build it from source (just checkout my branch and then `make` in `spk/nzbhydra`).
If you prefer I've uploaded the compiled version here: https://drive.google.com/file/d/0BwGcVEYr7HaeRDRBb2l5V0xZOE0/view?usp=sharing (but you should always prefer building it yourself :P )

**Comment by foXaCe** [comment]
@adchevrier hello, I make your spk but refuses to run on my DS1511 + ? where the log file ?
