### ISSUE TITLE
ignore words aren't working

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#169]
The ignore words don't seem to be working for me anymore.  I am on debcafb, and I get results that have not excluded the results that have the ignore words.  Is this function working for anyone else?

[nzbhydra-debuginfo-2016-03-06-20-35.zip](https://github.com/theotherp/nzbhydra/files/160278/nzbhydra-debuginfo-2016-03-06-20-35.zip)

**Comment by theotherp** [comment]
Sorry about that. Do a git pull.

**Comment by judhat2** [comment]
Thanks! Working now
