### ISSUE TITLE
Odd error - TypeError: Must be unicode, not str

### ISSUE THREAD

**Issue by kylerw** [theotherp/nzbhydra#170]
NZBHydra

optional arguments:
  -h, --help           show this help message and exit
  --config CONFIG      Settings file to load
  --database DATABASE  Database file to load
  --logfile LOGFILE    Log file. If set overwrites config value
  --host HOST          Host to run on
  --port PORT          Port to run on
  --nobrowser          Don't open URL on startup
  --daemon             Run as daemon. *nix only
  --pidfile PIDFILE    PID file. Only relevant with daemon argument
Loading settings from settings.cfg
Traceback (most recent call last):
  File "nzbhydra.py", line 167, in <module>
    run(args)
  File "nzbhydra.py", line 86, in run
    config.save(settings_file)  # Write any new settings back to the file
  File "/config/hydra/nzbhydra/config.py", line 506, in save
    f.write(json.dumps(settings, ensure_ascii=False, indent=4, sort_keys=True))
TypeError: must be unicode, not str

**Comment by kylerw** [comment]
Pinned it down to the settings.cfg file being saved empty or recreated on restart... not sure how or why....

**Comment by theotherp** [comment]
Could you please post the log and config (before it was empty ;-))? See the system tab to get an anonymized version as ZIP which you can attach here.
