### ISSUE TITLE
Git Pull asks for HTTPS login details

### ISSUE THREAD

**Issue by rubycerebra** [theotherp/nzbhydra#174]
Looks like the address is SSH and therefore needs login details. Can this be changed please as I can't update. Cheers.

**Comment by theotherp** [comment]
Uhm what. That's the first time I hear about it and the auto-update via Git has been in the system for months. Will do some tests.

**Comment by rubycerebra** [comment]
My fault was cloning from https://github.com/Mirabis/nzbhydra.git

**Comment by theotherp** [comment]
Ah, ok. Thanks for the feedback.
