### ISSUE TITLE
Request: Add NZBFinder.ws to wiki

### ISSUE THREAD

**Issue by Fossil01** [theotherp/nzbhydra#176]
www.nzbfinder.ws is based on nZEDb and works with everything. You can basicly clone the nzbcat row for it.

**Comment by theotherp** [comment]
It's a wiki, you can add it yourself ;-)

But I will add it to the presets in the GUI.

**Comment by Fossil01** [comment]
I could not edit it yesterday but I see the button now.

**Comment by theotherp** [comment]
Ok, thanks. I'll reopen and commit the changes to the presets under this issue.
