### ISSUE TITLE
Ubuntu asking for newer version of python 2.7

### ISSUE THREAD

**Issue by blindpet** [theotherp/nzbhydra#181]
I have a few users saying they are getting this message when running NZBHydra for Ubuntu 14.x, it only has python 2.7.6 or something in the repo.

`When trying to execute nzbhydra.py it asks that I use Python 2.7.9+`

**Comment by theotherp** [comment]
I have Ubuntu 14.04 and hydra running. You need 2.7.9+

**Comment by blindpet** [comment]
How come it needs 2.7.9? How did you easily get Python 2.7.9+ on Ubuntu 14.04? (I told them to apt-get update and dist-upgrade, no luck they say)

**Comment by theotherp** [comment]
To be honest I'm not sure I just know that you get weird errors with a lower version. The check has been in there for a couple of weeks.

You can try http://serverfault.com/a/725064 or https://renoirboulanger.com/blog/2015/04/upgrade-python-2-7-9-ubuntu-14-04-lts-making-deb-package/ I'm not sure what I did, but I think I installed from source.

**Comment by blindpet** [comment]
Much appreciated, update the guide with the ppa which is probably the easiest.
