### ISSUE TITLE
Create a release once a reasonably stable point has been reached

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra#188]
Arch's AUR has nzbhydra-git, but it would be fantastic if a release were created from a point you consider stable so that an AUR nzbhydra package could also be created. Maybe there is a great stable point you know of in the past? Or maybe you're working towards one in the future? :)

**Comment by theotherp** [comment]
I'm kinda working towards the first "actual release" but it's missing a couple of features and has some bugs that prevent me. As I don't have enough time to fix that at the moment it will take some time.

But I have no idea what would need to be done for such an release in AUR...

**Comment by theotherp** [comment]
Alright, I guess this is a time as good as any to do a release.
