### ISSUE TITLE
Configuring nzbhydra on Sickrage/Couchpotato

### ISSUE THREAD

**Issue by hctancredi** [theotherp/nzbhydra#190]
Hello.

I was trying to configure nzbhydra on sickrage and couchpotato, but still no luck. 

How am I supposed to configure? Any tips?

Thanks

**Comment by theotherp** [comment]
What doesn't work? How did you configure it?

**Comment by hctancredi** [comment]
For Sickrage I configured the url as you posted.
But I end up with this error

2016-04-14 12:15:55 Thread-13 :: Error getting caps xml for [NZB Hydra]

**Comment by hctancredi** [comment]
I will test with CP later tonight and let you know, but I'm pretty sure that I used the same url.

**Comment by theotherp** [comment]
Try opening http://127.0.0.1:5075/api?t=caps&apikey=<YOURAPIKEY> and see if you get a valid XML back.

**Comment by hctancredi** [comment]
Got Sickrage to work. Apparently when I copied my API key it had an extra space. Sorry about that :(
About CP, I still need to test it properly.

**Comment by hctancredi** [comment]
CP is working for me. I had to use my IP and not localhost or 127.0.0.1. Thanks for helping me out.
