### ISSUE TITLE
Path to CSS incorrect in latest version

### ISSUE THREAD

**Issue by mescon** [theotherp/nzbhydra#193]
I have my.domain.com/nzbhydra/ as external URL because I serve this from behind a reverse proxy.
In the latest version the CSS points to my.domain.com/nzbhydra/static/css/ which gives me a 404 - if I speak with nzbhydra directly (i.e 192.168.1.2:5075/nzbhydra/static/css/) it gives a 404 as well.
If I try 192.168.1.2:5075/static/css/ it also gives a 404.
This is the result:

![image](https://cloud.githubusercontent.com/assets/5875228/14584213/b5ba64c2-043b-11e6-84f0-73e2ed357047.png)

**Comment by theotherp** [comment]
That's weird, it works on my machine (I think), is it only the CSS that cannot be loaded? Or the Javascript as well? What's the full URL of the CSS that tries to be loaded and what would you expect it to be?

**Comment by mescon** [comment]
You can see on the right hand side the full URL that fails. It tries to load ``https://my.domain.com/nzbhydra/static/css/`` which fails.

**Comment by theotherp** [comment]
Right, go to the config and select a theme and save. See if that helps.

**Comment by theotherp** [comment]
If not open settings.cfg and to the main section add 

"theme":"default",

**Comment by mescon** [comment]
It's already in there - theme is set to default - same problem.

**Comment by theotherp** [comment]
Can you please post the content of your index.html as shown by your browser.

**Comment by mescon** [comment]
I ended up removing it all together and re-installing it. Love the new dark theme.
