### ISSUE TITLE
Save Button not working when adding an indexer

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#194]
I just tried adding a new indexer for the first time in a while.  After I added it I went to click the Save button, but it wasn't lit up and I wasn't able to click it.  I thought maybe it was auto-saving somehow, but it wasn't listed on the index/search page under Indexers.  I was finally able to save it by clicking another tab within the Config page (Main in this case) after which the Save button lit up and I could then click it.  I've repeated this a couple of times, so I think it's reproducible.

Version: 0.0.1a89

**Comment by theotherp** [comment]
That's weird, it works fine for me. Haven't been able to reproduce that. I'll try to get an error summary working so that you can see what prevents the saving.

**Comment by theotherp** [comment]
Please make sure that all the other indexers' settings are complete. Disable all indexers except the new one and check if you can save then. In my case my omgwtf config was missing the username. When you load the indexer config and change any value for an existing indexer, can you save then?

**Comment by albino1** [comment]
Updated to `0.0.1a91` and have the same behavior.  In fact, it's even easier to test, if I just disable an indexer the save button doesn't light up, but if I then switch to another tab it lights up and gives me the option to save.  I'm not even really sure how to debug this, and obviously there's nothing in the log.

**Comment by theotherp** [comment]
Sorry, I haven't been able to get the error summary to work yet and I don't have too much time right now. Will try to get it working (or at least better feedback) somehow.

**Comment by albino1** [comment]
I don't know if this helps or not, but I made a little video demonstrating the problem.

I had to zip it because Github doesn't like mp4 files.

[NZBHydra-SaveButton.zip](https://github.com/theotherp/nzbhydra/files/243495/NZBHydra-SaveButton.zip)

**Comment by theotherp** [comment]
I'm afraid I won't be able to get the error summary implemented. I added some code that should make config fields with wrong or missing values more visible. Also the save button is now not disabled but shows an error message that the config is invalid. It will "touch" all fields to make sure that error messages are shown for required, empty fields even if they haven't been touched by the user yet (e.g. when adding a new indexer).

**Comment by albino1** [comment]
No problem.  When it gets pushed to Master and I can auto-update I'll run the test again to see if anything stands out.  Thanks.

**Comment by theotherp** [comment]
There seems to be a bug in the config library I use: https://github.com/formly-js/angular-formly/issues/677

It's not very actively maintained so I have to check what I can do about that. I ~~wasted~~ spent so much time on getting that library to work that I'm not eager to switch -.-

**Comment by theotherp** [comment]
Could you post a screenshot / screenshots of the whole indexers config page? Blur sensitive data, obviously. 

This is hard to debug as there's no other data that you can send me.

**Comment by albino1** [comment]
It's pretty big, but here you go...

![al-nzbh-configscreenshot](https://cloud.githubusercontent.com/assets/12164957/15033593/20d48e20-1221-11e6-97a8-855c4f5791eb.png)

Hope I removed everything :)

In doing this I thought maybe the reason might be because I accidentally had some duplicate indexer priorities, but I updated them and the problem hasn't gone away.  I also updated to 0.0.1a93, but that didn't help either.

**Comment by theotherp** [comment]
Your omg user is missing.

**Comment by albino1** [comment]
You're right... no wonder it never finds anything :)

And good news: problem solved.

I went through all of the NN indexers and double checked their settings after you first replied last week, but dismissed all the default top ones, totally forgetting that OMG was amongst them.

I'm not sure what we've learned here, other than I screwed up.  Maybe that there should be a warning of some sort saying that all the required fields haven't been filled in.

Thanks for the patience.

**Comment by theotherp** [comment]
Yeah that's the error summary I was talking about. My latest changes should've at least make the error more visible. Anyway, glad it's fixed now.

**Comment by albino1** [comment]
Yep, now when I remove my OMG username it lights up red and gives me an error.  Should be good moving forward.  I'll go ahead and close this, thanks.

**Comment by theotherp** [comment]
I completely redesigned the indexer configuration. An error like this shouldn't happen anymore (or not as easily).

**Comment by albino1** [comment]
Yeah, it looks really good, it's way less cluttered.

I might arrange it by Priority instead of Alphabetical, or at least put the priority number next to the icon.  Better yet, sort it by Priority and allow the user to change the priority by just dragging them up and down like a queue.

**Comment by theotherp** [comment]
Uhhhhh, fancy. I don't use the scores so I didn't think about that.

**Comment by theotherp** [comment]
See #210
