### ISSUE TITLE
Dark Theme: Indexer Preset Dropdown Font Color Wrong

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#195]
This is hardly worth making an Issue over, but I couldn't figure out where else to put it :)

In 0.0.1a89 using the Dark Theme the font color in the Indexer Preset dropdown menu is wrong.  It's dark grey instead of light grey and you can hardly read it:

![al-nzbhydra-presetsfontcolor](https://cloud.githubusercontent.com/assets/12164957/14759818/098e9fd4-08e5-11e6-8f54-05339d6bc2a4.jpg)

**Comment by theotherp** [comment]
That's alright, will fix it, thanks for the feedback.
