### ISSUE TITLE
couchpotato fails getting details

### ISSUE THREAD

**Issue by stalks** [theotherp/nzbhydra#196]
Couchpotato repeatedly fails to get this example URL from Hydra

`https://localhost:5075/api?apikey=xxx&t=details&id=%28indexer%3ASpotweb%2Cindexerguid%3A%27w7Z3np23x00QV4aVw9FXS%40spot.net%27%2Csearchid%3A106%2Ctitle%3A%27Risen+2016+HDRip+XviD+AC3-EVO%27%29`

The result in a browser shows: Unknown API request. Supported functions: search, tvsearch, movie, get, caps

Example CP log:
```
04-25 23:19:44 DEBUG [hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last):
HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: https://localhost:5075/api?apikey=xxx&t=details&id=%28indexer%3ASpotweb%2Cindexerguid%3A%27w7Z3np23x00QV4aVw9FXS%40spot.net%27%2Csearchid%3A106%2Ctitle%3A%27Risen+2016+HDRip+XviD+AC3-EVO%27%29

04-25 23:19:44 DEBUG [ase.providers.nzb.newznab] Error getting details of "Risen 2016 HDRip XviD AC3-EVO": Traceback (most recent call last):
  File "/usr/local/share/couchpotato/couchpotato/core/media/_base/providers/nzb/newznab.py", line 99, in _searchOnHost
    nzb_details = self.getRSSData(url, cache_timeout = 1800, headers = {'User-Agent': Env.getIdentifier()})[0]
IndexError: list index out of range
```

Usually CP will continue to fetch movies anyway, however if CP does too many of these "details" requests, it then marks the host as bad, and will start to say:
`Disabled calls to localhost:5075 for 15 minutes because so many failed requests.`

Hydra: 0.0.1a89 
CP: c4fad95c (24/02/2016, 14:05:59)

**Comment by theotherp** [comment]
Details and getnfo are currently not supported via API. It's on my list.

**Comment by theotherp** [comment]
Reopening for visibility.

**Comment by theotherp** [comment]
Please check if it works with a93.
