### ISSUE TITLE
omgwtf not working anymore

### ISSUE THREAD

**Issue by ghosted17** [theotherp/nzbhydra#203]
HI,

wtf stopped working and returns wrong credentials

they said they updated there api urls, a while back

direct down
https://api.omgwtfnzbs.org/nzb/?id={nzbid#}&user={username}&api={apikey}

get nfo
https://api.omgwtfnzbs.org/nfo/?id={NZBID}&user={username}&api={apikey}

Also maybe this is by design but when i search for a long specific term it comes up with thousands of unrelated items. Is there a way to search for an exact match

**Comment by theotherp** [comment]
Will take a look.

For the other issue please create a separate ticket and provide an example.

**Comment by theotherp** [comment]
Still works for me. Can anybody confirm this?

**Comment by judhat2** [comment]
Omgwtf is still working fine fir me.

**Comment by theotherp** [comment]
Thanks for the feedback, @judhat2 

@ghosted17 Please make sure that your settings are valid. I'll close this for now. If you're certain there's a bug in hydra please reopen.

**Comment by ghosted17** [comment]
theotherp

for some reason my settings were not saving, i tried again and it works now.

thanks and keep the the great work :)
