### ISSUE TITLE
Remove unused indexers from the stats page

### ISSUE THREAD

**Issue by mauirixxx** [theotherp/nzbhydra#208]
Title pretty sums it up. Basically the stats page shows the static, preconfigured indexers, as well as the dynamic, variable indexers I've entered.

**Comment by theotherp** [comment]
That's a tricky one. For some of the stats (access time, for example) I can't remove all unused / deactivated indexers because the stats would be wrong or not be able to be computed. I'll see what I can do.

**Comment by theotherp** [comment]
Disabled indexers are not shown. But they're still used for calculation. Can't do better for now.

**Comment by mauirixxx** [comment]
the end result is exactly what I wanted. thank you!
