### ISSUE TITLE
Duplicate Indexers on Main Search Page

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#209]
After my upgrade to NZBHydra 0.0.1a94 every one of my NN indexers is now shown twice on the Search page.  They only show up once on the Indexer Config page, it's only on the main index page that there's duplicates.  My guess would be something in https://github.com/theotherp/nzbhydra/commit/4bf131cc228d1ac564fbeb72e7fca427d911f329 has caused it.

**Comment by albino1** [comment]
I should add that I tried a restart, a full reload, and tried in a different browser.

**Comment by theotherp** [comment]
Oops.
