### ISSUE TITLE
DOGnzb - Results returned, but not displayed

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#21]
When I first added DOGnzb to NZBHyrda and ran a search it worked, however every subsequent search appears to connect and retrieve information, but no actual results are displayed.   Things I tried to fix it:

* Disabling and re-enabling it.
* Removing it and re-adding it.
* Moving it from `Newznab 1` to `Newznab 2`.

What finally solved it is changing the `Name` in the indexer configuration.

I'm attaching screenshots below.  First up is two shots of no results returned, and then a picture of results returned with a new name.

I was going to try reinstalling NZBHydra, but I thought maybe you'd want to debug before I changed anything.

![al-nzbhydra-dognzb-receivesresultsbutdoesntshowthem-01](https://cloud.githubusercontent.com/assets/12164957/11231709/399d528e-8d60-11e5-8eba-b01391a5a78c.jpg)
![al-nzbhydra-dognzb-receivesresultsbutdoesntshowthem-02](https://cloud.githubusercontent.com/assets/12164957/11231711/39a2dc86-8d60-11e5-8f82-f93492bc80b1.jpg)
![al-nzbhydra-dognzb-receivesresultsbutdoesntshowthem-03](https://cloud.githubusercontent.com/assets/12164957/11231710/39a07856-8d60-11e5-8830-9efcfa3b258c.jpg)

**Comment by theotherp** [comment]
It is possible that this is related to having updated from an earlier version to a newer one and using the same database. I changed some code how indexers are identified in the database and possibly broke something there. Renaming or using a new database file (just deleting the old one will remove all history and stats but no settings) should fix it as you already found out.

The db code is still somewhat iffy and needs to be improved.

**Comment by albino1** [comment]
Before I started my tests I deleted the whole install directory and did a fresh clone, so I don't think having a previous db version is the problem.  Unless maybe they're stored somewhere else and I didn't actually delete them?

**Comment by theotherp** [comment]
I'll change/improve the way the indexers are identified and do some tests.
