### ISSUE TITLE
Show indexer score in config and, if possible, allow dragging to change priority

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#210]
I don't use scores and I don't know how many do, but for those that do use it it would be nice to see their priority visually and ideally be able to change it by dragging them around.

Perhaps hide the scores if all are 0. Or sort by score and then alphabetically, that way it would be still ordered properly for those not using scores.

**Comment by theotherp** [comment]
Hm, now that I think about I'm not so sure about the dragging. Technically it wouldn't be too much of a problem. But what do you do when all your indexers have an initial score of 0? What if two have the same score? What I could try is an input box for the score with dialup/dialdown. It would show the score and allow the user to change it right there. Isn't as cool as dragging but probably more usable.

**Comment by albino1** [comment]
To be totally honest, I'm not even sure how the scores work.  I thought they worked by given priority in the listings to the higher ranked indexer when you included duplicates, but it never seems to shake out like that.  It mostly seems to show whichever indexer responded the fastest.

If I have PFM set to Priority 1, NZBGeek set to Priority 2, and NZBClub set to Priority 3, then when I do a search that has duplicates from all three shouldn't PFM be the one listed on the main page?  Instead it seems like it could be any one of those three, and I can only see PFM if I manually check Include Duplicates and then open up the row to reveal it.

Side question: is there a way to permanently check Include Duplicates?  I've looked in the config in the past, and tried again just now, but didn't find anything.

**Comment by theotherp** [comment]
No, it's actually the other way around. The result of the indexer with the highest score/priority *number* will be selected. I know that's a bit confusing because usually the highest priority is the one with the lowest number ("priority number one is...") but that would configuration harder. If you have 10 indexers and you want to prefer one you would need to change all the others' priorities. Of course you could go negative, but I find that even more confusing.

No, permanently selecting duplicates isn't possible right now, I'll add a ticket.

**Comment by albino1** [comment]
Okay... well that explains it.  No wonder it's never "worked correctly" for me :)

Rather than mess with all my priority settings right now I'll wait until the changes above get into the next update so I can test it out at the same time.

**Comment by albino1** [comment]
> But what do you do when all your indexers have an initial score of 0? What if two have the same score?

Regarding this, my thinking was that whatever order they were in would be the Priority Order regardless of whatever previous scores they might have had.  Is there any benefit to having all of your indexers set to 0, or several indexers all set to 5?  And looking at it the other way, are there disadvantages to setting a new priority based on sort for everybody's existing 0 indexers?  Could that break something, or would they never even know it happened?

**Comment by theotherp** [comment]
Oh, right. Nah, the value of the score doesn't matter at all, in the greater scheme of things. Every set of duplicates is sorted by their indexer's score. If they're the same it doesn't matter what the value is, it could be 0 or 99999 or -1.

My thinking was that I didn't want to impose a score on users that don't already use one. There is no reason to randomly prefer one indexer over the other because it will just mean that that indexer is gonna be used for any downloads with duplicates. And with automation most stuff you will search for will have duplicates. So if you have 5 reasonably fast indexers and you search for a show you will always download from one even if you have no reason to do so. I don't use any indexers with low download or API hit limits so I just leave the score as is. Mostly it's just the fastest indexer, as you said, but that's out of my control. So, bottom line, I wouldn't want (new) users to use scores if they don't actively choose so.

**Comment by theotherp** [comment]
Se #211 for the other topic.

**Comment by theotherp** [comment]
Hint: Use the cursor keys to increase or decrease the score. Not as fancy as dragging but basically the same.

**Comment by albino1** [comment]
The arrows thing is cool.  My only big suggestion would be to remove the ability to have duplicates, because right now if you just shift things down to the bottom you end up with everything as 2, or visa versa at the top.  Also, if you keep pressing up it just keeps going higher even though there's no reason to, so you could end up with your top indexer as 28 and the next one below it as 6.  That doesn't affect functionality, it just looks weird.

One other thing is that if you have a lot of indexers and your resolution isn't very high (I'm on my laptop right now) then when you're moving up or down the indexer ends up off screen and you have to stop and scroll to it before continuing to move it up or down.  I'm not sure how to fix that (make the window auto-scroll?) and it's not the end of the world, but I thought I would mention it.

As far as preferring indexers, I tend to rank higher the ones that are less likely to have fakes or passworded files.  I'm not sure how Sonarr/Sick Beard/etc work, but if they just request `TV Show S01E01` then I would prioritize indexers that have more high quality P2P encodes over Scene ones so I end up with the best possible version.

**Comment by albino1** [comment]
> Also, if you keep pressing up it just keeps going higher even though there's no reason to

Actually I found the easiest solution to the duplicates problem was just to put the top indexer up to like 25 and then shift the ones below it before sorting them all back out, so maybe that's a good thing.

**Comment by theotherp** [comment]
I'm not going to spend more time on this. If this was a feature that most users actually use and use it daily (instead of once and then be done with it) I might improve it, but I think for a configuration feature it's fine as it is now.

**Comment by albino1** [comment]
Totally understandable.  Thanks for making it more usable.
