### ISSUE TITLE
Layout issues in Indexers under Config

### ISSUE THREAD

**Issue by adam-long** [theotherp/nzbhydra#212]
There seems to be a spacing bug in the Indexers tab under Config if you reduce window size.  Layout is fine if the screen is maximized to typical 1080p, but if it's reduced, the following happens:  Seems to be a recent bug in 1a97. I've tested with Chrome and Firefox under Windows.

![image](https://cloud.githubusercontent.com/assets/18425580/15091618/e65768c4-141b-11e6-8001-b6f6bd289832.png)

**Comment by theotherp** [comment]
Oops. I fucking hate CSS. Thanks for the report.

**Comment by theotherp** [comment]
Still not ideal but better.
