### ISSUE TITLE
Error: API Hit limit not working?

### ISSUE THREAD

**Issue by sasha-koss** [theotherp/nzbhydra#213]
Settings:
API hit limit 
5

Timeout
120

API reset Time
23:59
or
01:00

```
2016-05-07 13:30:56,270 - ERROR - newznab - Indexer nzb.is returned unknown error code 500 with description: Request limit reached (6/5)
2016-05-07 13:30:56,270 - ERROR - search_module - nzb.is: Unable to access nzb.is: Unknown error while trying to access the indexer: Request limit reached (6/5)
```

**Comment by albino1** [comment]
> API reset Time
> 23:59
> or
> 01:00

Is that your guess as to the API reset time or the real one?  If you don't know the real one that nzb.is uses then going over the limit is probably going to happen.

If anybody is motivated enough to make a Wiki with reset times for each indexer then I think people would appreciate it.

**Comment by theotherp** [comment]
Please enable debug log level for the log file and do some searches (after the limit reset) and ideally reach the limit. Then post the log (using System / Bugreport)

**Comment by sasha-koss** [comment]
Disabled the Indexer for a few Days and it seems to be working fine now. Thanks!

> 2016-05-11 11:10:13,515 - INFO - search - Did not pick nzb.is because its API hit limit of 5 was reached. Will pick again after 22:59 tomorrow
