### ISSUE TITLE
Add torrent support

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#214]
Just a crazy idea.

[Jackett](https://github.com/Jackett/Jackett) supports searching private indexers via a newznab-like API. As a test I added it as an indexer to hydra and searching already works fine. Downloading doesn't work because I don't use the links provided in the search result but instead try to get it using the API call [t=get](http://newznab.readthedocs.io/en/latest/misc/api/#get) which isn't supported by Jackett (yet?).

Do get this done:

- Either 

- - I change the way of downloading NZBs. I would need to store the download link in the NZB ID (which already contains the indexer, indexer's guid, title and the search ID)

- - Jackett needs to support [t=get](http://newznab.readthedocs.io/en/latest/misc/api/#get). Currently it uses the indexer's torrent info page as GUID, so it would probably need to convert that or something like that. Don't know how much work that would be. I'll add a feature request.

- Jackett would be a new search module and when downloading a torrent Hydra needs to recognize that it should return a torrent and not an NZB.

- Downloader support would be nice, but even more low priority than supporting torrents at all. Most users will have a plugin for the browser to handle torrent files. I'd rather stick to usenet and keep this more as a bonus feature.

To alleviate the first problem: I had already thought about storing all found search results in the database linked to a unique ID. That way I can stop using the huge rison encoded IDs for NZBs. I could just store the download link, indexer, title and search ID in the database. That might mean storing huge amounts of (meta) data which could probably be deleted after week or so. Will need to check how much that could be.

**Comment by albino1** [comment]
This looks pretty great.  I only have one torrent site that supports API access and I couldn't get it to connect, so I couldn't really test it.  It's been having issues for ages so it might not be NZBH's fault.  For what it's worth, this was my error:

`Connection failed: 404 Client Error: Not Found for url: http://www.mytorrentsite.com/api?apikey=<APIKEY>&t=search&extended=1&offset=0&limit=100&q=search+terms`

If I go to the URL manually with my API key I get a 404 page.

Reading through the forums supposedly the API works with Sonarr just fine.  It's a fairly popular torrent site and there's an API documentation page I could send you privately if you're interested.

**Comment by theotherp** [comment]
See Jackett. You need to plug it between, it makes trackers available as newznab indexers m

**Comment by albino1** [comment]
Ohh, I see.  I didn't realize I needed to install Jackett separately, I thought you had included the Jackett functionality in NZBH.  I get it now.  Sorry about that.

**Comment by albino1** [comment]
It works, and it's awesome.  What a great feature.

My TV tracker returns perfect results.  The results are a little more iffy with my movie tracker, all the results are just listed under the Title even though they're all completely different releases, but that might be a Jackett thing and not a NZBH thing since it seems like it's parsing HTML instead of using an API for that one.

Anyway, really cool.

**Comment by theotherp** [comment]
Ah haha, I see how that could be misread. I'll change the wording.

I just use the title I get from jackett. It all went surprisingly well, half a day of work and I was done. 

I "only" have access to the big three and didn't test with any others, results may vary. But I guess for manual search it's more than enough.

**Comment by theotherp** [comment]
Checked again, I realize how the titles of the movie tracker results aren't very helpful. Don't think I can do anything about that.

**Comment by albino1** [comment]
Yeah, reading through their Github page it looks like that's just the way it is unless somebody wants to try and submit a fix themselves.

**Comment by theotherp** [comment]
Might freshen up my C sharp knowledge and give it a try. Sometime.

**Comment by theotherp** [comment]
Added a comment on the Jackett repository: https://github.com/Jackett/Jackett/pull/373#issuecomment-229471876 Will see what OP says. Fixing it would be quick and easy.
