### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#217]
For some reason today my NZBHydra install isn't prompting me to Update when I loaded the index page.  I tried a hard reload and switching browsers, but nothing.  So I went to the Updates page to just click the button and saw that my status is up to date even though I'm not:

![al-nzbh-update](https://cloud.githubusercontent.com/assets/12164957/15099346/a952aa1e-1507-11e6-9642-548d0a28b30c.jpg)

I was going to just manually pull the update, but I figured if it's a bug then I'd wait to test the fix.

**Comment by theotherp** [comment]
Yeah I know, my algorithm is buggy. I already jumped to 0.2.0 for that reason but the code is not yet ready for master. Until then everybody will stay on 0.0.9x.

To other people affected: EIther pull manually or change the version to "0.0.1a100" and go to the updates tab.

**Comment by albino1** [comment]
Never thought you'd make it into the triple digits, eh?  Congratulations ;)

**Comment by theotherp** [comment]
@albino1 You're one for experimenting, aren't you? Would you like to set your update branch to "develop" and try the update? There's some data migration involved and although my client and my server migrated just fine I'm a bit nervous about pushing to master :-D

**Comment by albino1** [comment]
I'm not scared, I'll give it a shot :)  How do I do it?

**Comment by theotherp** [comment]
Well, if you have a git install you can probably just shutdown hydra, do "git checkout develop and then start hydra again.

**Comment by albino1** [comment]
Everything seems to have migrated smoothly.  I looked through my config, and went through a few of the indexers, and all of the settings are correct.  I then did a search and added a file to SABnzbd successfully.  Anything else I should look for?

**Comment by theotherp** [comment]
Check the download history, do a search and try to download an NZB and send it to the downloader. Thanks.

**Comment by albino1** [comment]
Search history is there and clicking the search again button works.  Adding an NZB via the icon works, downloading directly via the NZB link works, clicking Details work.  However, the NFO seems to be broken.  I've tried multiple files that all have NFOs and NZBH is giving the error:

```
An error occured :
500: INTERNAL SERVER ERROR

searchresultid
```

**Comment by albino1** [comment]
I'm not sure if this was the case before, but when sorting by Age some of the results are `-1d` instead of `0d`.

**Comment by theotherp** [comment]
Awesome, that went better than expected :-) Thank you.

The age thing happens sometimes, even to regular indexers.

**Comment by albino1** [comment]
No problem :)

**Comment by theotherp** [comment]
Alright, I'd advise going back to master or you will get updates that crash even more than the ones on master...

Update should work now, closing this. Going to bed now and expecting bug reports during the night...
