### ISSUE TITLE
NOT NULL constraint failed searchresult.details

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#218]
May happen with 0.2.0.

**Comment by albino1** [comment]
For what it's worth I'm getting this error on Master even though I wasn't getting it during our previous test where I was on the Develop branch.

**Comment by theotherp** [comment]
That was pure luck..

**Comment by theotherp** [comment]
I seem to use indexers that behave better than many others, it's often that stuff works fine for me and not for others. I may need to invest in VIP for some other indexers... :-/

**Comment by theotherp** [comment]
Ok, actually it was me making a stupid mistake when I already should've been at sleep. Added a NULL constraint that was already there instead of dropping it.
