### ISSUE TITLE
error: Your local changes to the following files would be overwritten by merge

### ISSUE THREAD

**Issue by 88keyz** [theotherp/nzbhydra#219]
When I click update within the program now I get the following error.

```
error: Your local changes to the following files would be overwritten by merge:
	changelog.md
	nzbhydra/api.py
	nzbhydra/config.py
	nzbhydra/database.py
	nzbhydra/exceptions.py
	nzbhydra/indexers.py
	nzbhydra/search.py
	nzbhydra/stats.py
	nzbhydra/tests/playground.py
	nzbhydra/update.py
	nzbhydra/web.py
	static/html/directives/download-history.html
	static/html/directives/search-result-non-title-columns.html
	static/html/directives/search-result.html
	static/html/states/search-results.html
	static/js/nzbhydra.js
	static/js/nzbhydra.js.map
	templates/index.html
	ui-src/html/directives/download-history.html
	ui-src/html/directives/search-result-non-title-columns.html
	ui-src/html/directives/search-result.html
	ui-src/html/states/search-results.html
	ui-src/js/config-fields-service.js
	ui-src/js/directives/addable-nzb.js
	ui-src/js/directives/search-result-non-title-columns.js
	ui-src/js/nzb-download-service.js
	ui-src/js/nzbhydra.js
	ui-src/js/search-results-controller.js
	ui-src/js/search-service.js
	version.txt
Please, commit your changes or stash them before you can merge.
Aborting
```

If I update manually with **git reset --hard** then **git pull** and restart nzbhydra it works perfectly.  This just started happening, updates were working perfectly before.  Any chance you could add **git reset --hard** to the update process to eliminate this issue?

**Comment by theotherp** [comment]
I don't know why that would happen, but sure.

**Comment by After-Shock** [comment]
Looks like this error crept back into the latest update.  0.2.184 -> 0.2.186 in Docker using linuxserver Official image.  
Updating dd60aaf..5424ce0
2017-01-23 14:10:56,048 - ERROR - update - Thread-2407 - "git" pull origin master returned : From https://github.com/theotherp/nzbhydra
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
	changelog.md
	libs/arrow/__init__.py
	libs/arrow/api.py
	libs/arrow/arrow.py
	libs/arrow/factory.py
	libs/arrow/formatter.py
	libs/arrow/locales.py
	libs/arrow/parser.py
	libs/arrow/util.py
	nzbhydra/searchmodules/newznab.py
	static/js/nzbhydra.js
	static/js/nzbhydra.js.map
	ui-src/js/config-fields-service.js
	version.txt
Please, commit your changes or stash them before you can merge.
Aborting
