### ISSUE TITLE
Indexer Connection Test Displays in Wrong Location

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#22]
If you have more than one Newznab set up in NZBHyrdra then try to do a connection test that fails, the failed result is actually displayed next to the test button for the previous indexer.  Screenshots will probably illustrate this better, so see below.

![al-nzbhydra-indextestdisplaysinwronglocation-01](https://cloud.githubusercontent.com/assets/12164957/11231842/3e259ec8-8d61-11e5-8ba2-c9c3d5fcc4a4.jpg)
&nbsp;
----
&nbsp;
&nbsp;
![al-nzbhydra-indextestdisplaysinwronglocation-02](https://cloud.githubusercontent.com/assets/12164957/11231841/3e23231e-8d61-11e5-8f4a-790606e93dc8.jpg)

**Comment by theotherp** [comment]
That's weird. Will take a look.
