### ISSUE TITLE
Allow configuring indexer categories used for hydra categories

### ISSUE THREAD

**Issue by joshuader6** [theotherp/nzbhydra#222]
Currenty each indexer can be tested for "supported search types" 

![image](https://cloud.githubusercontent.com/assets/10895412/15105577/186ba868-15c3-11e6-8e67-6c96c053b8f3.png)

Included there is "Movies" 
Is there any way this can be manually Configured ? For example to add the Movies/Foregin category. Right now Couchpotato struggles at finding releases because Hydra only searches in the "main Movies" categorys.

**Comment by theotherp** [comment]
That's not what you think it is. That just says that the indexer allows searching for TV shows, movies, albums and ebooks using meta data like IMDB ID or TVRage ID and so on.

Please set the log level for the log file to debug, let CP search for some movies and post the log.
