### ISSUE TITLE
Single search result with API (Sonarr)

### ISSUE THREAD

**Issue by xawen** [theotherp/nzbhydra#223]
I upgraded from 0.0.1a99 to 0.2.2 this morning.  I have Sonarr configured to use only NZBHydra for searching.  Before the update Sonarr was seeing multiple results for manual searches (normal).  After the update, it only returns one result for a search.  

Hitting the API directly in a web browser appears to return multiple results, so I'm not sure if there's a formatting issue with the search result itself.  I checked this by using the same url that Sonarr submitted (grabbed from the logs on the reverse proxy web server).

**Comment by mobomelter** [comment]
I'm also seeing the same issue. This basically breaks Sonarr as you only get whatever seemingly random quality shows up with no way to get higher quality releases.

**Comment by theotherp** [comment]
Argh, somehow I managed to fuck everything up with my lates changes.

**Comment by theotherp** [comment]
Already know what's going on, will be quick to fix, at least.

**Comment by xawen** [comment]
Man, you're quick.  I was going to add more detail.  I'll test whatever you cook up and provide the extra info if you need it.

**Comment by theotherp** [comment]
Well, if I'm quick to break stuff I'm better quick to fix it, too ;-)

**Comment by xawen** [comment]
Working perfectly now.  Amazing work.

**Comment by mobomelter** [comment]
Seriously that's crazy fast.
