### ISSUE TITLE
No statistics being created on statistics page

### ISSUE THREAD

**Issue by mobomelter** [theotherp/nzbhydra#224]
Just was doing some testing and I noticed that nothing is being populated within the statistics page for Avg results share (%) and NZB Downloads Per Indexer. The other two fields Avg Response Time and Avg Indexer Access Success appear to be functioning properly. 

Some additional information

Using NZBGet
NZB Downloads tab is working properly (shows successful)
Config > Downloader is set to the following. Downloader : NZBGet, NZB access type: Proxy NZBs from indexer, NZB adding type : Send link.

Let me know if any additional information is helpful.

**Comment by theotherp** [comment]
Ok, thanks for the report.

**Comment by theotherp** [comment]
I can't repair the database entries that are incomplete but new ones should be added correctly.
