### ISSUE TITLE
Don't wipe search field at category selection 

### ISSUE THREAD

**Issue by Dimtar** [theotherp/nzbhydra#225]
I am not sure if this has been addressed but it would be nice if when you entered text into the search field it wasn't wiped if you then selected a category after entering said text.

**Comment by theotherp** [comment]
Main reason is the autocomplete function for movies and shows. If you choose those categories and have search terms left from the last query, would you want it to open? What if you do one search, download something, want to search something and need to delete the terms first. Either way has advantages and problems, this behavior was what I chose. But I can try if I can make it a better experience, perhaps check if the user already changed the terms or if they're just left from the last search.

**Comment by Dimtar** [comment]
Ok, all that makes sense. My user experience is that I often enter a name of something and then remember to pick the category so from that perspective its quite jarring thus me lodging the issue. I am happy to just get better at using the system, its great thanks!
