### ISSUE TITLE
Allow adding an indexer even when the connection test failed

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#226]
Hi,

I tried to add nzb.su today as one of my indexers but i can't save the information as hydra can't connect.
Used the ' Check Search types'  copied that link and nzb.su gives me 'Api hit limit reached' .

Profile still says 0/5000 keys hits... so probably rate limiting or outage on their side...

In either way, could we have the 'save'  go through - even if the indexer is currently down?

**Comment by theotherp** [comment]
I thought about it didn't think it would make sense. So much abouth that. Adding it to my list.

**Comment by Mirabis** [comment]
Yeah I can understand both ways ;p

Now I'd have to wait till the timeout/issue on their end is resolved before adding it - while it keeps people from adding wrongly configured indexers ;p

**Comment by theotherp** [comment]
Perhaps make the user pinky swear that they know what they're doing.
