### ISSUE TITLE
Missing URL_base on the getnzb? url

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#228]
My settings: 
```
URL base: /nzbhydra
External url: https://mydomain.com/nzbhydra/
Use SSL = off
Reverse proxy infront of it
```

A search on https://mydomain.com/nzbhydra/api?t= ..... gives correct results, **but: the actual enclosure url is wrong** : http://mydomain.com.nl/getnzb?apikey=.....

The http / https thing I understand as SSL is turned off, but that's already catched off at the proxy.

http://domain.com/getnzb? requires http://mydomain.com/nzbhydra/getnzb? to function properly.

As a workaround I've the proxy do a redirect on the url, which works now;p but just fyi

**Comment by theotherp** [comment]
I currently don't have a proper solution for this, the last time fiddled in this area I was close to jumping off a bridge.

As a workaround you can set the external URL to "https://yourdomain.com/nzbhydra/"

**Comment by theotherp** [comment]
Try to disable "Use local address in API results"

**Comment by Mirabis** [comment]
Ah that'll work, but stumbled upon another error - will create a separate post
