### ISSUE TITLE
FR: Only display NFO link if an NFO is actually available

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#23]
Since *most* results don't actually have an NFO it would be nice to only show the link when they do.  Or just grey the link out so that it doesn't break formatting.

This probably isn't possible, but if it is I thought I'd put in a feature request for it.

**Comment by theotherp** [comment]
Unfortunately NN+ API results don't provide infos on NFO availablity so we can only try if there's an NFO for a search result and then see what happens. The raw indexers (Binsearch, NZBIndex and NZBClub) do report NFO availability and for their results when the NFO link is shown that means there actually is one.

What I can do is to color NN+ NFO links in another color to mark them as "fuzzy", meaning you can try your luck.

**Comment by albino1** [comment]
Sounds like it should work.  Thanks.
