### ISSUE TITLE
Allow to better distinguish between downloader icons of the same type

### ISSUE THREAD

**Issue by mauirixxx** [theotherp/nzbhydra#231]
On the main search page, after getting the results of a search, I'm presented with 2 nzbget icons, but I don't know which icon is related to which server - I'm assuming the first icon on the left is representative of the first nzbget server I added?

In any case, when hovering the mouse over like: https://i.imgur.com/OoIYDCK.png would it be possible to add a small popup text with the name you assigned to the downloader?

**Comment by theotherp** [comment]
I could also let you select an icon for the downloader, for example a [glyphicon](http://getbootstrap.com/components/#glyphicons). It's not the best icon set, but it has some good ones.

**Comment by mauirixxx** [comment]
works perfect, thank you very much! :100:
