### ISSUE TITLE
Config has problems with downloader passwords containing certain special characters

### ISSUE THREAD

**Issue by mauirixxx** [theotherp/nzbhydra#232]
I already e-mailed you @theotherp with more detail, but essentially this is a bug report.

The password field for adding nzbget/sabnzbd doesn't like the question mark "?" symbol as part of a password, and while saving the downloader with the "?" symbol in there works (sort of), it breaks displaying the configured downloaders afterwards - the page shows you have none configured, but the config file clearly shows them entered, and even allows you to create duplicate entries.

**Comment by mauirixxx** [comment]
I'm still getting an error after upgrading to v0.2.9 - will e-mail you a screenshot of the error (it shows part of the password)

**Comment by theotherp** [comment]
Sorry about that. You could add 127.0.0.1 to your list of authorized IPs and delete the username and password in the hydra config.

**Comment by theotherp** [comment]
Or do you mean an error in the hydra GUI? I'll wait for your mail.

**Comment by mauirixxx** [comment]
error in the hydra gui. you should have my email by now with a screenshot of the error.

**Comment by theotherp** [comment]
Ah, sorry, I only just now read your mail with the password and the screenshot, that error is indeed different than I expected. I know what's going on, shouldn't be too hard to fix.

**Comment by mauirixxx** [comment]
Still a no go - the "?" symbol gets converted to %3F in the password string sent to nzbget:

`WARNING	Fri May 13 2016 10:55:20	Request received on port 6789 from 4x.xx.xx.xxx, but username or password invalid (mauirixxx:xxxxxx5L%3Feqxxxxxxx)`

I obfuscated the password, but the "5L" is part of it, as well as the "eq" - the "?" sits right between them.

I know I can simply make a password without the "?" symbol, and I'm sorry about being a pest about it, just trying to help make hydra even more awesome then it already is.

For what it's worth, the Headphones https://github.com/rembo10/headphones project has the same issue with "?" symbols in passwords as well - maybe it's just a python thing with strings and question marks?

**Comment by theotherp** [comment]
Ok, I'm walking from one problem into the next. I managed to use a ? in the password by setting the base64 encoded header myself but now I have errors when using certain other special characters like § because I cannot bas64 encode that. I currently have no solution for this.
