### ISSUE TITLE
Edit existing Indexer

### ISSUE THREAD

**Issue by siuside** [theotherp/nzbhydra#235]
Megasearch had at least this part nice and easy and I hope you could incorporate into NZBHydra which I have now managed to migrate in just a day :)

Currently there doesn't seem to be any way to edit an already added indexer. I tried fudging with the settings.cfg (after taking a backup of course) but I guess that there is some dependency on the nzbhydra.db as well. In my case during setup of NZBGeek, I guess somehow I hit save but the setup was not complete, but it saved it anyways. Then I entered valid NZBGeek info and saved but now there are 2 NZBGeek entries showing up in the webpage and settings.cfg Deleting the lines manually on settings.cfg causes NZBHydra to not start and settings.cfg file size becomes 0

Fortunately I had a backup to quickly restore and get back up and running in no time, but this could be tricky if users don't know about this. I am guessing manually editing just the basic things like say API may still work via settings.cfg but not sure if it gets entered into the db this way. 

All in all I would say the settings page must be very easy to edit IMO. Just simple and easy way to edit them like in megasearch. 

Great program though, I am loving the interface and most everything so far, but most of all your dedication and activity on the code. Thanks much !

**Comment by theotherp** [comment]
You just click the indexer button and change your data.

**Comment by siuside** [comment]
It is clear that is how it supposed to be changed. But it doesn't change the data, it just adds a new one. In the dropdown existing indexers with the existing don't show up for editing, just a blank template and that too the defaults, not the custom ones that I have added.

**Comment by Mirabis** [comment]
I was like... [gif on how to click!](https://gyazo.com/8d1e73de1d9f584d7bca2b8d0773a45b)..

But, @siuside  are you using a proxy infront of it? Cloudflares RocketLoader for instance can cause issues like that ;/

**Comment by siuside** [comment]
Wow, I don't see the same screens?? That would have made much more sense (in your gif).

I am sad puppy, take a look at my screens https://imgur.com/a/ESRZo

**Comment by theotherp** [comment]
Please check your browser console for errors. Post them.

**Comment by siuside** [comment]
http://pastebin.com/XdUxdeSX

**Comment by theotherp** [comment]
You have two indexers with the same name. You need to remove one of them or change the name manually in the settings.cfg. Then restart hydra.

**Comment by siuside** [comment]
Ok from my screenshot and the original post you can see I have NZBGeek x2 and now DrunkenSlug x2. Earlier I tried removing both NZBGeek and Hydra would not start resetting settings.cfg in the process. Let me try to remove only one entry (each of Geek and Slug) and do it that way. Will update shortly.

**Comment by siuside** [comment]
That did it. We can file this under "loser error" :)

**Comment by siuside** [comment]
@Mirabis 
Thanks for the gif btw. Good to know that I can see something similar now :) and btw didn't realize you had also migrated here from Mega ;)

**Comment by Mirabis** [comment]
@siuside I didn't really migrate xD but i stopped maintaining mega long ago and went to write a successor (nzbunify) , but @theotherp released first and I just started using his (saved me some time)

**Comment by siuside** [comment]
@Mirabis 
Wow good to know about nzbunify project ! Hopefully you could collaborate/contribute here with enhancements from your work. Either way it's all good. This is great tool for us usenet fans.

**Comment by theotherp** [comment]
Ooooh, you're the nzbm guy... 

Regarding your other project, I'd say competition is good but collaboration would be better ☺️

**Comment by theotherp** [comment]
Back to topic: I have an idea how I could prevent that from happening.
