### ISSUE TITLE
nZEDb Indexer Details link going to NFO

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#236]
It looks like with nZEDb the Details link in the results is going directly to the NFO on the site as opposed to the actual Details page.  It's definitely the case for NZBCat and NZBFinder, maybe others as well.

**Comment by theotherp** [comment]
Was that ever different? I use the details link provided by the indexers in their API search results.

**Comment by albino1** [comment]
Ah, I see.  Interesting that they would return the wrong link.  I've only noticed it with nZEDb indexers so far, does nZEDb not support a proper Details link out of the box?

**Comment by theotherp** [comment]
It does, it can be usually constructed easily, e.g. <host>/details/<guid>

I'll see if I can get around this.
