### ISSUE TITLE
Add option to allow auto update

### ISSUE THREAD

**Issue by ghosted17** [theotherp/nzbhydra#239]
?

**Comment by theotherp** [comment]
Uhm no, I'd rather have the user do it and check if it worked. At least for now where the update process might not be as smooth as it should be.

**Comment by theotherp** [comment]
I'm closing this for now. This will not be implemented for a long time. It's not I don't want that feature, hydra just doesn't have the proper backend for it. It's also always problematic doing an automatic update for programs on which other tools rely. If the update fails or hydra is just reloading in the time sonarr tries to reach it then the search will fail.
