### ISSUE TITLE
Details to setup reverse proxy

### ISSUE THREAD

**Issue by ghosted17** [theotherp/nzbhydra#240]
I noticed in your update you we should use a reverse proxy, Do you know of a simple way or service to do that?

**Comment by theotherp** [comment]
You can follow http://www.htpcguides.com/configure-sonarr-reverse-proxy-nginx-windows/ for the basics and then use the config excerpts in the wiki: https://github.com/theotherp/nzbhydra/wiki/Reverse-proxies-and-URLs

There're also a lot of posts on reddit in /r/usenet.

**Comment by ghosted17** [comment]
Thank you

**Comment by theotherp** [comment]
I'll close this. Please reopen if you have further questions.
