### ISSUE TITLE
Feature Request: Default Sort

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#241]
I've noticed that after I do a manual search the first thing I do after that is sort by size.  Maybe I'm alone in this, but if not, it would be nice to be able to change the default sort from Age.  Options might be Size, Alphabetical, and Category.  Not a major upgrade by any means, but a little more functionality.

**Comment by theotherp** [comment]
I take it as a good sign when minor requests like this instead of huge ones come in ;-)

**Comment by albino1** [comment]
Hah!  Everybody needs an easy win every now and then :)
