### ISSUE TITLE
Feature Request: Ignore Categories

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#242]
We have ignore words, but I find most of the junk comes from categories that are filled with tons of randomly named crap, like XXX or some of the Audio categories that are poorly moderated by indexer staff.  What do you think about adding ignored categories?  To be honest, I'm thinking most people would use it just to filter out XXX, but there might be more use cases.

**Comment by Mirabis** [comment]
Can't we already explicitly specify categories to search? / web interface / sonarr / on the indexers website?

**Comment by theotherp** [comment]
I rarely search without specifying a category, so I wouldn't need it. But I don't know why I couldn't add it, it might be helpful in some cases.

**Comment by albino1** [comment]
Interesting, I rarely search with a specified category.  My experience is that only a few of the indexers have the majority of their content properly sorted, so if you're looking for anything more obscure that the latest episode of a TV show, or a popular movie, then there's decent odds it's in the wrong category.  

For example, I just picked a random movie and searched for it and nzb.su has it listed under PC.  Just searched for another one and Usenet Crawler has a bunch of versions in Ebooks and a few more in TV.  For that same movie the category in NZBCat and NZBFinder shows up as N/A.  If you use Sonarr/CP and you only have those indexers then I would imagine they just report no versions available, even though they are.

FWIW, I only use NZBHydra for manual searches, and in my experience this is pretty common.

**Comment by theotherp** [comment]
It's always good to hear how other people use it, because developers tend to think that everybody works and thinks like they do. That's also a big source of bugs and features not implemented as many people would like.

I use it for API and manual searches, but API mainly because it's kind of an integration test to see myself how well it holds up. But I think many other people use it for API, considering the bug reports that come in when sonarr suddenly can't access hydra properly.

**Comment by albino1** [comment]
Yeah, I would imagine the majority of people use it for the API.  I use Dog's Watchlists for my upcoming shows and movies, so I really only use Hydra when I'm looking for archived content... which is still pretty much every day, but not nearly as much as the Sonarr/SR/SB/CP people :)

On the plus side, I interact with the actual interface more than they do, so that's probably why I post so many issues :)

**Comment by theotherp** [comment]
Which I'm thankful for.
