### ISSUE TITLE
Allow for OR boolean searches

### ISSUE THREAD

**Issue by rosarch** [theotherp/nzbhydra#244]
Bit of a strange edge case request.

I frequently like to download magazines, I have about 15 I routinely download, when I search for them I have to run one search at a time, I know I could use something like Lazy Librarian but tbh I don't like the App. 

It would be great if I could book mark a search that just does some thing like " magazine1 OR magazine2 OR magazine3" this will bring back results including any of the magazines, I can then just easily download the latest ones.

I'm open to any other ways of achieving what I am after..

**Comment by theotherp** [comment]
Try

> magazine1|magazine2|magazine3

Even
> "magazine 1"|"magazine"

will work although it will search for the phrases "magazine 1" or "magazine 2".

This will only work with newznab/nzedb indexers (so not binsearch, nzbclub, nzbindex, omgwtf).

**Comment by rosarch** [comment]
Perfect -  thanks :-)
