### ISSUE TITLE
Can't modify the indexers

### ISSUE THREAD

**Issue by rickytin** [theotherp/nzbhydra#245]
I have added some indexers but I cant modify, disable or delete.
Here two still to show you what I mean.
![capture1](https://cloud.githubusercontent.com/assets/4860538/15268944/983dc2b2-19bd-11e6-838c-fa31f02cb8d1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/4860538/15268945/9b45629e-19bd-11e6-8744-84f3c20a5da3.PNG)

**Comment by theotherp** [comment]
Pretty sure you added two indexers with the same name. Shutdown hydra, open your settings.cfg, rename the indexer(s) and start hydra again.

If that doesn't help post the log.

**Comment by rickytin** [comment]
Thanks theotherp it fix my problem.
