### ISSUE TITLE
Sending nzb link to SAB through SSL reverse proxy issue

### ISSUE THREAD

**Issue by Elfman72** [theotherp/nzbhydra#246]
I recently converted my apps to use reverse proxy on my Synology DS1815+.  It is using self signed cert and the external url is something like this:  https://hydra.myid.synologyddns.me:XXXX/hydra/(XXXX = my designated open port number).  Having Hydra attempt to send an NZB link to SAB errors out saying '**URL Fetching Failed; File not on server**'.

The URL it is attempting to use is reformatted as follows:

http://hydra.myid.synologyddns.me/getnzb?apikey=myapikey&searchrestuldid=###&downloader=SABnzbd

So you'll notice that the URL is not formatted properly (No SSL, no port number, no trailing /hydra after the port number.

Switching the downloader to 'Upload NZB' corrects the issue but just wondering if this is expected behavior for the 'Send Link' feature of Hydra.

Thanks!

**Comment by theotherp** [comment]
Try to set the external URL in the settings and maybe enable to use it for API search results.

**Comment by Elfman72** [comment]
So I thought I had that set.  Just updated to 0.2.93 tried it again and sending links seems to work now.  Much appreciated.
