### ISSUE TITLE
database is locked. search broken.

### ISSUE THREAD

**Issue by oppsig** [theotherp/nzbhydra#248]
Getting error "500: INTERNAL SERVER ERROR" while searching.
Not seeing any results anymore all of a sudden.

[logfile](http://termbin.com/9yvi)
I'm using the linuxserver/hydra docker container. Worked flawlessly until recently.

**Comment by theotherp** [comment]
This is a known but mysterious problem. No idea how this happens. Do you use a start script? Could you try running hydra in screen or tmux for a while to see if that fixes it?

**Comment by oppsig** [comment]
The docker container doesn't use a script but run it like this.
`/sbin/setuser abc python /config/hydra/nzbhydra.py --nobrowser`

**Comment by theotherp** [comment]
I have no idea what's going on here but I never had this problem on Windows or on "regular" Linux.

**Comment by theotherp** [comment]
Could you try running it outside of docker.

**Comment by enp2** [comment]
I have the same issue and also run in the linuxserver docker. I'd be happy to provide any logs/etc that might be helpful, but mostly just wanted to confirm it's affecting another.

**Comment by theotherp** [comment]
Thanks, logs won't help. I'll try if I can reproduce it using docker.

**Comment by Xploder** [comment]
I have the same issue after updating. 
Running NZBHydra straight up (no container) on my RPi 3.
Works if only searching with 1 indexer. 
I already removed the flask_session folder.

**Comment by theotherp** [comment]
Shit, I just saw that my server finally had the same problem but I have just restarted it and now it's gone :-(

**Comment by oppsig** [comment]
Prefer not to update my python with ppa. Could try another linux container though with init or systemd script. But I forgot to mention that api searching via nzbhydra is working fine, but manually not working.

**Comment by oppsig** [comment]
Just tested 2.9.4, havent gotten database locked yet :+1:

**Comment by theotherp** [comment]
Ok I now have a better understanding when it happens but not why. But it seems that I was able to get rid of it for the most part.

**Comment by theotherp** [comment]
I'll close this, please reopen if it comes up again.
