### ISSUE TITLE
Information retained when adding multiple indexers at once

### ISSUE THREAD

**Issue by wizzy99** [theotherp/nzbhydra#250]
0.2.91

Steps to reproduce.  Add new indexer (custom indexer).  Immediately add another custom indexer from same screen.  

Information entered for first indexer is prepopulated when adding second indexer.

Workaround - after adding indexer and saving, click on search tab at top and then come back to Config section.  Clicking onto another screen in config isn't enough to clear that retained information.

**Comment by siuside** [comment]
A workaround is to hit save after finishing up with the first custom indexer. Yes this is the one that got me a few days ago
