### ISSUE TITLE
Request for a login page vs the browser pop up? 

### ISSUE THREAD

**Issue by WilliamJBrown** [theotherp/nzbhydra#251]
Just wondering if it is possible to have a setting to choose what kind of login page you can have. Sadly password managers (Lastpass) doesn't work with pop up login style. Just wondering if it is something easy to include to have just a standard webpage to login with. I know this is a silly request but us password manager users would love this! I believe sonarr has a system like this were you can choose what style login you want. btw love the program and understand if its not to important in your developments.

**Comment by theotherp** [comment]
I'll see, this might be quite a lot of work..

Would anybody prefer HTTP auth? If I do this I'd rather switch completely (like CP) instead of making it configurable (like sonarr).

**Comment by enp2** [comment]
For what it's worth I'd prefer a switch. The popup is fine when I'm at my desktop, but on mobile it's kind of a nuisance.

**Comment by theotherp** [comment]
Yeah, I meant if anybody prefers basic HTTP auth.

**Comment by theotherp** [comment]
Doesn't matter, I'm 80% done with a solution where you can choose what you want to use.

**Comment by WilliamJBrown** [comment]
That's awesome to hear. Thanks for creating this as an option. I thank you for spending the time. Love the program! Use it all the time.

**Comment by theotherp** [comment]
Considering I spent the last 10 hours on this I sure hope so ;-)

**Comment by WilliamJBrown** [comment]
WOW Thanks. Again, thank you so much. Didn't expect you to turn around and get it done within a day. Awesome stuff. We as the community appreciate the hard work you put into this. You should be proud.

**Comment by theotherp** [comment]
Alright, @WilliamJBrown if you'd like to can do a beta test. Get the code from the develop branch and see if everything works.

**Comment by WilliamJBrown** [comment]
Awesome I'm on lunch now I will see if I can throw it together right now. Give me a bit.

**Comment by theotherp** [comment]
Uhm, just so you know you, I just found out that search results aren't shown anymore... But you can test everything else ;-) So don't hurry, I might solve it soon...

**Comment by WilliamJBrown** [comment]
Ok, I'll hold out till tonight. I don't think I can tap into my docker
installation from work either. They block all kinds of ports here. I'll
give it a shot tonight and let you know how it goes. Again I appreciate the
hard work :)

**Comment by theotherp** [comment]
Alright, fixed now.

**Comment by WilliamJBrown** [comment]
Sounds good. Will give you an update in like 6-7 hours ish.

**Comment by theotherp** [comment]
I noticed a flicker in the stats and some weird behavior. Nearly fixed but not in develop.

**Comment by WilliamJBrown** [comment]
Sadly cannot seem to update to the develop branch. I thought this was
possible but the docker container I am using doesn't seem to have a
functioning update branch selector. It seems I can root into my Synology
unit but I don't want to kill it. The docker container in question is:
https://hub.docker.com/r/mattsch/fedora-nzbhydra/

I can only map the config file to which I can access. I did rename the
branch to 'develop' but it doesn't seem to work without the git path which
is something I cannot find out. I tried editing the config file to the
develop URL which caused an error in the logs and I was just trying to see
if that worked but it didn't.

Sorry I cannot test this. I want to up hold my end of the work but cannot
even update to develop branch. I was so excited too.

**Comment by theotherp** [comment]
Weird, you should be able to set the branch in the config to develop, restart and update just fine, no matter the docker.

Anyway, I will need to do some more programing because I had to change a lot in the GUI and its routing. I'll add more automated tests to hopefully get this right. I'm moving in two weeks and won't have time to fix bugs for a bit so the next update should better be less bug ridden than the last.

**Comment by theotherp** [comment]
Alright, there you go.

**Comment by WilliamJBrown** [comment]
Just checked it out and it works a charm! I really appreciate it :)
