### ISSUE TITLE
Time Stamps in History are off 12 hours

### ISSUE THREAD

**Issue by imadunatic** [theotherp/nzbhydra#254]
I love that the history time stamps are now based on local time; however, my time stamps are 12 hours off of the 24 hour clock. "0" hour is noon, 12 is midnight, I don't see a handy way to adjust this? Am I missing it?

**Comment by theotherp** [comment]
That's weird. Where are you?

**Comment by albino1** [comment]
Is this related to what @mauirixxx reported in https://github.com/theotherp/nzbhydra/issues/237?

For what it's worth, my time is off by -6 hours.  Right now the history timestamp shows 15:38 and it should say 23:38.

**Comment by theotherp** [comment]
Apart from encoding stuff date/time stuff is the worst.

**Comment by albino1** [comment]
Actually, it's off worse than I thought it was, I didn't even look at the date.  It says:

2016-05-17 17:47

And the correct time should be:

2016-05-**16** **23**:47

So it's not -6 so much as +18 :)

**Comment by theotherp** [comment]
Well that's just fuuucked up.

Too hung over right now. will check it later.

**Comment by imadunatic** [comment]
> That's weird. Where are  you?

Eastern standard time 
Currently -4 GMT

**Comment by theotherp** [comment]
Got it. Fixed in 0.2.95.
