### ISSUE TITLE
See What's New is Blank

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#257]
Starting a few versions ago when you click the See What's New! button before upgrading it just shows a blank page:

![nzbh-seewhatsnew](https://cloud.githubusercontent.com/assets/12164957/15383085/fa7293c4-1d44-11e6-8ea2-6473c7edb5e1.jpg)

I'm not sure if you just stopped updating the changelog, or if it's a bug, but I thought I'd mention it.

**Comment by theotherp** [comment]
Should be fixed in .95, will display changes again for newer versions.

**Comment by albino1** [comment]
Great, thanks.

**Comment by theotherp** [comment]
Sorry, thought I had that fixed. Should be actually fixed in .96, changes should be shown when .97 is out.

**Comment by albino1** [comment]
I was just coming here to post about this :)

**Comment by theotherp** [comment]
Ok, now it showed too much...

**Comment by albino1** [comment]
Haha, yeah, whoops :)
