### ISSUE TITLE
Search Box Disappearing on Results Page

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#258]
NZBH: 0.2.95

After entering a search into the search box it disappears when the results are displayed:

![nzbh-missingsearchbox](https://cloud.githubusercontent.com/assets/12164957/15385784/a9704412-1d58-11e6-9f58-768b7472fb24.jpg)

I tested it in both FF and Chrome, restarted it, and did a hard reload.  So it would appear something got messed up between 0.2.94 and 0.2.95.

**Comment by theotherp** [comment]
Oops.
