### ISSUE TITLE
PSA: Development pause for a couple of weeks

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#259]
I'll be moving in two weeks, It's time for me to pack my stuff, paint my flat, etc. I won't be able to do much coding for three or four weeks or so.

I'll still be active here and on reddit and try to do some easy fixes, but no new features for a while.

**Comment by albino1** [comment]
Thanks @theotherp!  Good luck on the move :)

**Comment by mauirixxx** [comment]
enjoy the new place!

**Comment by theotherp** [comment]
Alright, settled in :-)

**Comment by judhat2** [comment]
Good to hear! It's nice to see a string of commits.  Thanks!
