### ISSUE TITLE
Return category in book search results (maybe other search results too?)

### ISSUE THREAD

**Issue by philborman** [theotherp/nzbhydra#263]
newznab searchers return the category as field 5 in result sets after pubDate. nzbhydra omits it. Can it be added please?  newznab results example:

    #    <item>
    #       <title>David Gemmell - Troy 03 - Fall of Kings</title>
    #       <guid isPermaLink="true">
    #          https://www.usenet-crawler.com/details/091c8c0e18ca34201899b91add52e8c0
    #       </guid>
    #       <link>
    #           https://www.usenet-crawler.com/getnzb/091c8c0e18ca34201899b91add52e8c0.nzb&i=155518&r=78c0509bc6bb91742ae0a0b6231e75e4
    #       </link>
    #       <comments>
    # https://www.usenet-crawler.com/details/091c8c0e18ca34201899b91add52e8c0#comments
    #       </comments>
    #       <pubDate>Fri, 11 Jan 2013 16:49:34 +0100</pubDate>
    #       <category>Books > Ebook</category>
    #       <description>David Gemmell - Troy 03 - Fall of Kings</description>
    #       <enclosure url="https://www.usenet-crawler.com/getnzb/091c8c0e18ca34201899b91add52e8c0.nzb&i=155518&r=78c0509bc6bb91742ae0a0b6231e75e4" length="4909563" type="application/x-nzb"/>
    #       <newznab:attr name="category" value="7000"/>
    #       <newznab:attr name="category" value="7020"/>
    #       <newznab:attr name="size" value="4909563"/>
    #       <newznab:attr name="guid" value="091c8c0e18ca34201899b91add52e8c0"/>
    #       </item>

**Comment by theotherp** [comment]
Will do so. Out of curiosity, what do you need this for? It's not standardized, indexers use all kind of different formats.

**Comment by philborman** [comment]
Not sure I do really now.  Lazylibrarian was missing the size of downloads
from nzbhydra because it used positional parameters, and without the
category field it tried to read size from the wrong field.  That's how i
noticed it. Seems all my usual downloaders provide it.  Fixed lazylibrarian
by making it check the field names.

However I'm just adding filtering options to downloads,  and might want to
allow the user to have the newsgroup/category the book was found in as a
filter.

Kind regards Phil

**Comment by theotherp** [comment]
Doesn't matter, adding it took about 5 minutes.
