### ISSUE TITLE
--logfile can move the log file correctly but the web ui won't pick it up

### ISSUE THREAD

**Issue by etomm** [theotherp/nzbhydra#264]
The web ui says there is no log file to show, but the log file is correctly logging

**Comment by theotherp** [comment]
Sorry for the delay. Could you provide more infos? Where is the log file located? On what OS do you run Hydra, do you use docker? Does it roll over (create .log.1, .log.2, etc). files?

**Comment by etomm** [comment]
I moved the --logfile in the command line in another folder, but when I looked inside Hydra Web ui the log was empty. Instead the file was getting written correctly. After this I changed the config setting for the log file to the same position that I specified in the command line and the web ui began to read it. 

I suppose that if someone specify --logfile in the commandline this should get a precedence over whichever setting I inserted in the web ui. In fact would be better to hide that setting completely.

**Comment by theotherp** [comment]
That's how I wanted it, too. If the command line doesn't take precedence it's a bug ;-)

**Comment by theotherp** [comment]
Alright, it actually uses the log file provided in the command line to log but shows the content of the configured log file in the GUI.

I'm not sure I agree that the setting should be hidden when the log file was given in the command line, though.

**Comment by etomm** [comment]
Ok, if not hidden, maybe a notification that the setting is overriden from the commandline in that moment.
