### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by Undeadhunter** [theotherp/nzbhydra#266]
Hi,

Suddenly I've gotten a password screen appearing when opening the main page, but for the love of  me I can't remember putting anything in.

What would be the easiest way to reset / set the password to something I do remember?

**Comment by theotherp** [comment]
Set the authentication type in the settings to "None".

**Comment by Undeadhunter** [comment]
Thanks, that did the trick! Hope other will be able to use this, couldn't find anything online.
