### ISSUE TITLE
Password challenged when searching

### ISSUE THREAD

**Issue by Cozza38** [theotherp/nzbhydra#267]
Good morning,

I'm having a strange problem where I'm being password challenged during a search. I believe my authorization configuration is correct. Help would be appreciated.

![Auth](http://i.imgur.com/UXdjodl.png)

![Challenge](http://i.imgur.com/syfjPZl.png)

I'm using hydra behind an Nginx reverse proxy.

**Comment by theotherp** [comment]
Please open the developer tools in your browser (F12) and go to the network tab. Do a new search and find the connection with status 401 (that's the one causing the password prompt). If possible, make a screenshot, remove sensitive data and post it.

**Comment by Cozza38** [comment]
Hi Mate,

Here's the request and the header with sensitive data removed>

```
GET /nzbhydra/internalapi/search?query=testies&indexers=DogNZB%7CNzbs2Go%7COZnzb%7CaltHUB%7Cnzb.su&category=All HTTP/1.1
Host: domain.com
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
MyApp-Handle-Errors-Generically: true
Referer: https://domain.com/nzbhydra/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: session=removed
```

```
HTTP/1.1 401 UNAUTHORIZED
Server: nginx/1.10.0
Date: Mon, 30 May 2016 06:31:29 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 90
Connection: keep-alive
WWW-Authenticate: Basic realm="Login Required"
Cache-Control: must-revalidate, no-cache, no-store, private, max-age=0
Expires: Mon, 30 May 2016 06:31:29 GMT
Set-Cookie: session=removed; Expires=Thu, 30-Jun-2016 06:31:29 GMT; HttpOnly; Path=/
```

**Comment by theotherp** [comment]
Yeah, that's weird. Could you please set the log level for the log file to debug, do another search and then post the relevant part of the log.

As soon as my computer is assembled I'll take a look ;-)

**Comment by Cozza38** [comment]
There doesn't seem to be anything useful in the log unfortunately.

``` 2016-05-30 22:23:47,312 - WARNING - web - IP 172.17.42.1 failed to authenticate. This was his first failed login attempt ```

**Comment by theotherp** [comment]
Post th the debug info from the system tab.

**Comment by theotherp** [comment]
Does the log even contain debug Infos? You might need to restart first for the change to take effect.

**Comment by Cozza38** [comment]
Log doesn't seem to look any different from usual. Debug is definitely enabled.

``` 2016-05-30 22:15:09,205 - INFO - nzbhydra - Started
2016-05-30 22:15:09,205 - INFO - nzbhydra - Loading database file nzbhydra.db
2016-05-30 22:15:09,240 - INFO - indexers - Activated indexer altHUB
2016-05-30 22:15:09,241 - INFO - indexers - Activated indexer nzb.su
2016-05-30 22:15:09,241 - INFO - indexers - Activated indexer OZnzb
2016-05-30 22:15:09,241 - INFO - indexers - Activated indexer Nzbs2Go
2016-05-30 22:15:09,242 - INFO - indexers - Activated indexer DogNZB
2016-05-30 22:15:09,242 - INFO - nzbhydra - Debug mode enabled
2016-05-30 22:15:09,242 - NOTICE - nzbhydra - Starting web app on 0.0.0.0:5075 ```

**Comment by Cozza38** [comment]
Ah I see, there's a log level and a debug mode. Had debug mode enabled but not log level changed.

**Comment by Cozza38** [comment]
Here's what I can see with debug enabled:

```
2016-05-30 23:00:19,149 - DEBUG - web - Sending index.html
2016-05-30 23:00:20,011 - DEBUG - web - Sending index.html
2016-05-30 23:00:20,023 - DEBUG - web - Get safe config request
2016-05-30 23:00:21,389 - WARNING - web - IP 172.17.42.1 failed to authenticate. This was his first failed login attempt
```

**Comment by theotherp** [comment]
Huh. As I said, it will take a couple of days before I can check this out.

In the meantime disable the debug mode, it's not secure. Thanks.

**Comment by theotherp** [comment]
I'm having some similar troubles myself... Hopefully I'll have time for this on thursday.

**Comment by Cozza38** [comment]
No worries matey potatey!

**Comment by Cozza38** [comment]
Nailed it! Thanks mate <3

**Comment by theotherp** [comment]
You're welcome. Was pretty easy, I just needed to sit down properly and take a look.
