### ISSUE TITLE
Display log in separate scrollable box

### ISSUE THREAD

**Issue by joshuader6** [theotherp/nzbhydra#268]
How about reversing the log output in the Web UI 
so that the newest messages are on top 
Additionally how about wrapping it in a seperate textbox so the website itself doesn't need to be scrolled.

**Comment by theotherp** [comment]
No to the first, yes to the second.

**Comment by theotherp** [comment]
The reason why I won't reverse the log output:

1. It's difficult to implement
2. I don't like it, it's hard to read for me.

**Comment by theotherp** [comment]
Best I can do.
