### ISSUE TITLE
Sabnzbd integration

### ISSUE THREAD

**Issue by soco11** [theotherp/nzbhydra#270]
Not sure if this is on purpose or not, but the only way to integrate sab is to have a username and password set up in your sab config. Otherwise you get an error. 
`An error occured :
500: INTERNAL SERVER ERROR

username`

**Comment by theotherp** [comment]
Nah, that's not on purpose.

In the future, please provide a bit more details, e.g. when this happens, and the log file (if it contains any errors).

**Comment by theotherp** [comment]
Any news on this? I'd like to close it, reopen when you have any more infos.
