### ISSUE TITLE
Default category not effective 

### ISSUE THREAD

**Issue by porkchop999** [theotherp/nzbhydra#271]
Default category set in dowloader (Nzbget r1716) but still prompts for category. Started happening after 0.2.95

**Comment by albino1** [comment]
I'm getting this as well, but when sending to SABnzbd.  Even if the listing has a category like Movies HD it still prompts you. 

![al-nzbh-category](https://cloud.githubusercontent.com/assets/12164957/15788175/084f21dc-297b-11e6-98c2-48bf80091327.jpg)
