### ISSUE TITLE
White list per category 

### ISSUE THREAD

**Issue by Metigoth** [theotherp/nzbhydra#273]
Could you please add category based white lists.
e.g. DON, EBp, CtrlHD, HiFi, D-Z0N3 for movies
NTB, VietHD, lol, and etc for TV

This would be a big help for couchpotato to only send white listed results. Right now it gets unknown groups, results with no groups, and groups of low quality with good. It would help making sure they only get quality releases.

Thank you

**Comment by theotherp** [comment]
Thinking about it, I might do a bigger change IRT the categories. Allowing required and forbidden words and allowing to map newznab categories to hydra categories.

**Comment by theotherp** [comment]
Can't you set these in the tools directly?

**Comment by Metigoth** [comment]
No, couchpotato has a preferred list and a blacklist, but no whitelist. So it pulls a lot of bad quality releases There are some that have no group.  
Sonarr is excellent for TV. 
LazyLibrarian only has reject list.
Headphones has required with OR so it may work.
Mylar didn't seem to have any filters.

**Comment by theotherp** [comment]
Alright, adding it to my list. It's not very complicated to implement but I'm still thinking about how to display it in the config.

**Comment by theotherp** [comment]
By the way, my CP has lists for Preferred, Ignored, Required in the categories section.

**Comment by Metigoth** [comment]
My couchpotato does also, but it will look for all those words in required.

**Comment by theotherp** [comment]
> Release should contain at least one set of words. Sets are separated by "," and each word within a set must be separated with "&"

**Comment by Metigoth** [comment]
If you put EBp, HiFi, DON, D-Z0N3, and etc it will look for all of them in release instead of a separate entries. Hopefully your new feature fixes that.

Thank you

**Comment by Metigoth** [comment]
It didn't work with CP.
I put in all the movie categories D-Z0N3, HiDt, TBB, SbR, HaB, CRiSC, NTb, Tayto, EbP, FoRM, DON, CtrlHD, VietHD, EA, decibel, HDMaNiAcS, Tree, ESiR

Couchpotato still found garbage releases it must not specify the movie newznab category numbers.
It worked perfectly in the nzbhydra internal search. Maybe if there was a separate api key for programs as an option that can be limited to certain category searches. CP api key X or Movie category api key x?

**Comment by theotherp** [comment]
Try with new version.

**Comment by Metigoth** [comment]
That fixed it.
Thank you very much!
