### ISSUE TITLE
Random naming issue when using with SABnzbd

### ISSUE THREAD

**Issue by danioj** [theotherp/nzbhydra#276]
Normally when an nzb is uploaded to SABnzbd, SABnzbd will display (in the first column) the name of the file or group of files being downloaded.

E.g. "Ubuntu 15.10"

Recently however I have noticed that in SABnzbd that the name in the download field is showing the url path to nzbhydra including the key.

E.g. "getnzb?apikey=xxxxxxxx&searchresultid=140212"

This seems to be intermittent and without any discernible pattern that I can see. The download itself,  downloads normally with no other issue that I can see.

Note, the nzbaccesstype = redirecttoindexer AND by in large the remaining settings are default. Also note that I only experience this issue when using nzbhydra and have only come across it recently.

nzbhydra version = 0.2.101
SABnzbd version = 1.0.0RC5 [97cfe94]
Indexer Types = newznab based and non newznab based
Date this issue was first noted: 2016-05-19 12:51:14

This seems like a bug to me, but I am not sure where. I am inclined to think this is with nzbhydra, hence why I am posting here, but in truth I don't know.

**Comment by theotherp** [comment]
I'm probably not providing the name when uploading the NZB. So yes, it's a bug.

**Comment by theotherp** [comment]
I cannot reproduce this. Could you describe in more detail what you're doing?

**Comment by albino1** [comment]
When you see `getnzb?apikey=xxxxxxxx&searchresultid=140212` do you also see a Retry countdown timer?  If you do, that means that SAB can't connect.  In my experience this is usually an SSL issue, but it could also be the method that you're using to send NZBs to SAB.  What are your NZBH settings for `NZB access type` and `NZB adding type`?

**Comment by theotherp** [comment]
Any news on this? Please reopen when you have more infos.
