### ISSUE TITLE
No multiple DLs anymore

### ISSUE THREAD

**Issue by BenoitMartin2** [theotherp/nzbhydra#277]
Hi, 

Since the last 2-3 upgrades (I'm 0.2.102) I can't DL multiple NZBs at once. 

Any idea? 
Thanks!

**Comment by theotherp** [comment]
Make sure at least one downloader is configured and enabled. You're also missing the direct download button to the right.

**Comment by BenoitMartin2** [comment]
Well, I use it with friends (we share a few paid APIs) so I didn't add any downloader. We only use it to get the .NZBs. BTW, a few builds earlier we could get x .NZBs at a time even without any CP/S/SR linked.

**Comment by theotherp** [comment]
What... I didn't know that was possible. It would just start separate downloads for every nzb in the browser?

**Comment by BenoitMartin2** [comment]
Yep.

**Comment by theotherp** [comment]
Funny, wasn't aware of that. Kinda in the middle of a big update right now, will take a look when I'm done.

**Comment by BenoitMartin2** [comment]
Thank you very much :)

**Comment by theotherp** [comment]
I'm sorry, I'm not sure I understand. Do you mean there was a button that would download all selected NZBs? Or do you mean that when you click multiple NZBs, one after the other, the downloads don't start?

**Comment by BenoitMartin2** [comment]
I mean there was a button "here" (see http://pix.toile-libre.org/upload/original/1465633018.png) to get all selected .NZBs. Aka "save as" using the browser (or directly added to SAB/NZBget using plugins BTW).

Actually if I want to get more than 1 .NZB forum NZBgydra I got to click on the right link "NZB" for each. A few updates ago (I mean ~2-3 weeks ago) I could just select all the .NZBs I wanted, click the "Download All" and get them all at once.

**Comment by theotherp** [comment]
Ok, sorry, kinda embarrassing but I don't remember ever having added (or removed) that.

**Comment by BenoitMartin2** [comment]
NP!  That was just easier :)  As I told you we use your work to share our paid APIs, that's good enough!
