### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by sanderjo** [theotherp/nzbhydra#279]
Hi,

I've written some code (about 25 lines) so that NZBhydra works via a SOCKS proxy.

Reason: I couldn't access binsearch directly anymore, but it worked via a proxy (in my case: a TOR proxy)

So, @theotherp are you interested in a pull request for this?

If so: SOCKS proxy config is now via the CLI:
```
  --socksproxy SOCKSPROXY, -s SOCKSPROXY
                        SOCKS proxy to use in format host:port, for example
                        127.0.0.1:9050
```
I'll check if I can make it a configurable item in the GUI (Config -> Main, I suppose?).

**Comment by theotherp** [comment]
Hey, why not, always good to have some features. I wouldn't be able to test it though (or not for a while). 

You could leave the GUI config to me, if you don't have gulp set up and know where to look it can be somewhat complicated though. Thanks!

**Comment by sanderjo** [comment]
Implemented
