### ISSUE TITLE
Can't view nzb details in CouchPotato when using the login form authorization type

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#280]
I am using the login form to authenticate nzbhydra.  When I try to click the details link within CouchPotato, a popup box asking for a username and password appears.  It rejects my credentials.  If I switch back to HTTP Basic authentication, then clicking the details link in CP works fine without asking for credentials.  The link goes to a url like this: 192.168.1.5:5075/details/nzbhydrasearchresult27541
```
2016-06-09 22:54:23,245 - DEBUG - web - Call to method get_details
2016-06-09 22:54:23,246 - DEBUG - web - Requiring auth for method get_details
2016-06-09 22:54:23,247 - WARNING - web - Missing token authorization header
2016-06-09 22:54:23,249 - WARNING - web - IP 192.168.1.110 failed to authenticate. This was his first failed login attempt
```

Here is what I am referring to in CouchPotato. The details link is the "i" button.
![image](https://cloud.githubusercontent.com/assets/3536802/15932412/8f778558-2e96-11e6-9160-e22690773e5b.png)

**Comment by theotherp** [comment]
Yeah, not sure how I could prevent that. I could either always ask for HTTP auth when using this or disable it at all. Will see If I can come up with a proper solution.

**Comment by judhat2** [comment]
Thanks!
