### ISSUE TITLE
Bug 0.2.103 Index

### ISSUE THREAD

**Issue by Metigoth** [theotherp/nzbhydra#281]
History & Stats, Config, System disappear until I hit logout.
Then they show and logout disappears.

BugReport broken also
An error occured while creating the debugging infos: 'ascii' codec can't decode byte 0xe2 in position 152584: ordinal not in range(128)

**Comment by theotherp** [comment]
I need more infos. Just send a screenshot of the auth config tab.

**Comment by Metigoth** [comment]
http://imgur.com/MkuWOPH

**Comment by theotherp** [comment]
Ooops. Lol, I tested every combination of auth type and users but never tested what happens with auth disabled. My bad.

**Comment by Metigoth** [comment]
I don't have it available outside LAN so didn't need it turned on. Don't need it on with reverse proxy since nginx will handle auth also.
