### ISSUE TITLE
original ignore words not showing up in the settings

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#283]
Just updated to the version 0.2.105.  Looking good!  I went to check out the new options for adding forbidden words, but I noticed that my old list was missing.  The text box in the Config->Searching page was empty.  I thought they had been erased, but they were still present in the settings.cfg and they work in the searches.  The old list just isn't located in the textbox so I can edit them. 

So, I added a word and saved it to see what it would do.  It looks like it added the new word in the settings.cfg like this: `"ignoreWords": "test",`. The old list is next to: `"forbiddenWords":`

[settings.txt](https://github.com/theotherp/nzbhydra/files/310326/settings.txt)

I went to the bug report page so I could post my config.cfg, but I got the pop up box asking for credentials. I am using the login form authentication, so I had to switch back to HTTP Basic auth momentarily to generate the bug report.  I'll create another issue for that.

**Comment by theotherp** [comment]
That should've been migrated, sorry.

**Comment by judhat2** [comment]
Thanks again!

**Comment by theotherp** [comment]
Thank you!
