### ISSUE TITLE
invalid literal for int() with base 10: ',' using with Sonarr

### ISSUE THREAD

**Issue by BenoitMartin2** [theotherp/nzbhydra#285]
Hi,

With HTTP it's ok, with SSL nope  (TLS1.2 only, https://i.imgur.com/tWQwWgS.png). When trying to use it with Sonarr it seems they can connect but there's this error.
Don't understand if it's on the Sonarrs side or NZBhydras one  :/

Sonarr log: http://pastebin.com/eCEnFWMh
NBZhydra one: http://pastebin.com/mHx4Acwv

**Comment by theotherp** [comment]
Mine :-(
