### ISSUE TITLE
Can't load link to show's website when using an rid ID key

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#287]
This happens on the 'History & Stats' -> 'Search History' page. Clicking this rid link in order to go to the TV show's website causes a popup to appear to ask for credentials.  I am using the login form authentication method, so it fails.  I think it only happens when it's an rid ID key and nzbhydra tries to convert it to a TVDB id.
![image](https://cloud.githubusercontent.com/assets/3536802/15986475/d40adbc6-3043-11e6-9a4f-51889948568c.png)

**Comment by theotherp** [comment]
Oh god what have I done...

Thanks for testing so much.

**Comment by theotherp** [comment]
Hm, works for me. Weird.

**Comment by judhat2** [comment]
It works for you? Huh. I cleared my cache and cookies and still got asked to enter a name and password. If I switch to HTTP Basic auth, then it works for me.

**Comment by judhat2** [comment]
My log says this:
```
2016-06-12 03:26:42,963 - DEBUG - web - Call to method internalapi_redirect_rid
2016-06-12 03:26:42,964 - DEBUG - web - Requiring auth for method internalapi_redirect_rid
2016-06-12 03:26:42,965 - WARNING - web - Missing token authorization header
2016-06-12 03:26:42,967 - WARNING - web - IP 192.168.1.110 failed to authenticate. This was his first failed login attempt
```

**Comment by theotherp** [comment]
Closed this by mistake.

**Comment by theotherp** [comment]
I'll check it tomorrow. I'll also rewrite my auth code so that it at least will accept username and password when entered into the basic HTTP auth window.

**Comment by theotherp** [comment]
Alright, with .208 you should be able to login with username and password. I'll consider switching to cookie based auth so that any calls to hydra from inside your browser work, not just the ones from the GUI.

**Comment by judhat2** [comment]
That works!
