### ISSUE TITLE
movie and tv searches aren't using the TVDB or IMDB id during a search

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#288]
When I try to use the TVDB or IMDB search feature, it doesn't seem to return the correct results.  It looks like it does a general query search in the tv or movies category. Like this:
/api?apikey=APIKEY&t=search&extended=1&offset=0&limit=100&cat=2000&password=0&q=Star+Wars
I have disabled generating queries for indexers which do not support ID based searches.
[nzbhydra-debuginfo.zip](https://github.com/theotherp/nzbhydra/files/310406/nzbhydra-debuginfo.zip)

**Comment by theotherp** [comment]
That's what I get for not having frontend tests.

**Comment by theotherp** [comment]
Should be fixed now.
