### ISSUE TITLE
URL Base ignored when submitting to SABnzbd

### ISSUE THREAD

**Issue by jangrewe** [theotherp/nzbhydra#291]
I'm running NZBHydra on the path /hydra of example.com and have set `/hydra` as the URL Base in the Config.
When i want to send a search result to SABnzbd, it complains that the NZB was empty. This happens because SABnzbd is told to get the NZB from `/getnzb` instead of `/hydra/getnzb`

**Comment by theotherp** [comment]
There are a couple of things you could try to prevent that, but I cannot test them right now. I'll check it later today, going kayaking now :-)

**Comment by jangrewe** [comment]
Hehe, enjoy that, i'll use "upload NZB" for now.

PS: do a barrel roll!

**Comment by theotherp** [comment]
Only unintentionally, I'm afraid...

**Comment by theotherp** [comment]
Please let me know if this works. I tested it locally and on my server, but with this kind of thing you never know.

**Comment by jangrewe** [comment]
Sorry for the late reply, it seems to be working now - thanks!
