### ISSUE TITLE
omgwtfnzbs not used when searching from api

### ISSUE THREAD

**Issue by paulg1981** [theotherp/nzbhydra#292]
Hello,
I just started using the software yesterday and I have about got it figured out but I ran into what I think is a bug.

When I search using the web all indexers return results as expected, when I search via the api by way of sonarr omgwtf never returns results. I can see this with the "history & stats" tab. 

I enabled info logging and found the following error which would seem to be the cause. Unfortunately I don't know squat about python or the like so I am posting it here for some help.

`2016-06-12 19:21:18,908 - INFO - web - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", limit "100" ]
2016-06-12 19:21:18,919 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/search.py", line 366, in start_search_futures
    results = f.result()
  File "/opt/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/opt/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 100, in search
    urls = self.get_showsearch_urls(search_request)
  File "/opt/nzbhydra/nzbhydra/searchmodules/omgwtf.py", line 204, in get_showsearch_urls
    return self.get_search_urls(search_request)
  File "/opt/nzbhydra/nzbhydra/searchmodules/omgwtf.py", line 170, in get_search_urls
    cats = map_category(search_request.category)
  File "/opt/nzbhydra/nzbhydra/searchmodules/omgwtf.py", line 114, in map_category
    return [newznab_to_omgwtf[x] for x in category.category.newznabCategories]
KeyError: 5040
2016-06-12 19:21:23,895 - INFO - search - Removed 144 duplicates from 453 results`

Any pointers or help would be most appreciated, thanks!

***Also is there anyway to change the limit of results? I am querying 5 indexers so I would like it to be higher than 100?

**Comment by theotherp** [comment]
My snarky response would be not using omgwtf... I have a bad time getting all my features to work with them because for some reason they decided to be a special flowflake using a completely custom API.

Anyway, it's not your fault, it's mine.

Regarding the limit, I'm pretty sure I tried that once and it didn't work, I think because indexers expect 100 results per default? I can take a look again.

**Comment by paulg1981** [comment]
Thanks for your reply, I haven't heard the word snarky in years 😂

I have gone ahead and disabled omgwtfnzbs for now. Not a huge deal by any means. 

In regards to the 100 article limit, thanks for checking it out. I poked around in Sonarr's settings and couldn't find anything related to a results or api limit. If it is on the clients end I understand but if we could adjust it on nzbhydra' send that would be awesome. 

Thanks again!

**Comment by paulg1981** [comment]
I think I found out about why just 100 results, from sonarr wiki:

> When searching, Sonarr will request the first 100 results, if more than 90 successful results are returned it will request the next 100 results from the indexer, to a maximum of 1000 results. If the indexer doesn't support paging, we make every effort to avoid requesting additional results.

**Comment by theotherp** [comment]
Hm no, I think it could work. When I have more time I'll test it with sonarr, CP and SB.
