### ISSUE TITLE
An error occured : 500: INTERNAL SERVER ERROR  iconCssClass

### ISSUE THREAD

**Issue by staticn0de** [theotherp/nzbhydra#293]
I'm seeing an error that appears when I add nzbget to nzbhydra. Below is from the log.

Formatting was bad. Paste bin here http://pastebin.com/zYgHHNmP

**Comment by theotherp** [comment]
Open your settings.cfg and in the downloader section add a new line
`"iconCssClass": "",`

That should've been migrated, sorry.

**Comment by staticn0de** [comment]
Awesome, thanks for that. Works like a charm now.

**Comment by switchpants** [comment]
Sorry about commenting on a closed bug...  but this is still happening with a fresh install of r743.00aa790

I start with an empty settings.cfg, add NZBGet as the downloader and receive the same iconCssClass error.  Adding the line to settings.cfg still fixes the issue, but it appears to still be broken for a newly-added downloader.

> 2016-06-14 08:42:05,736 - ERROR - web - iconCssClass
> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 354, in wrapped_function
>     return f(*args, **kwargs)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 1036, in internalapi_getsafeconfig
>     return jsonify(config.getSafeConfig())
>   File "/opt/nzbhydra/nzbhydra/config.py", line 735, in getSafeConfig
>     "downloaders": [{"enabled": x.enabled, "name": x.name, "type": x.type, "iconCssClass": x.iconCssClass, "defaultCategory": x.defaultCategory if hasattr(x, "defaultCategory") else None} for x in settings["downloaders"]],
>   File "/opt/nzbhydra/libs/bunch/__init__.py", line 121, in __getattr__
>     raise AttributeError(k)
> AttributeError: iconCssClass
>

**Comment by theotherp** [comment]
No worries, thanks for letting me know. No idea why that happens.
