### ISSUE TITLE
Select multiple entires with Shift+Click?

### ISSUE THREAD

**Issue by annetson** [theotherp/nzbhydra#294]
Not vital, but a usability change that would make selecting multiple search entries much easier? :) Something like this:

![selection](https://cloud.githubusercontent.com/assets/19753666/16047529/b7b83f0e-3250-11e6-939b-21a9e57eab9d.gif)

**Comment by theotherp** [comment]
I'd like that but was never able to get it to work. Will keep it in the backlog, who knows.

**Comment by annetson** [comment]
Good enough for me, thanks for replying :)

**Comment by theotherp** [comment]
It's a lot harder than you think it would be, at least with the way my table with the results is implemented. I'd also like to have a button to select all or inverse the selection, but that also didn't work out.

**Comment by theotherp** [comment]
Alright, got it.

**Comment by annetson** [comment]
You the man, this is a huge one for us downloading lots of tv series. Thank you so much! 👍
