### ISSUE TITLE
Details on NzbGeek

### ISSUE THREAD

**Issue by porkchop999** [theotherp/nzbhydra#296]
When clicking details for any nzbgeek link the following error in generated

Not Found
The requested URL /details/... was not found on this server.
Apache/2.4.7 (Ubuntu) Server at www.nzbgeek.info Port 443

other indexes seem to be #ok

**Comment by albino1** [comment]
Already fixed.  See: https://github.com/theotherp/nzbhydra/issues/295 and https://github.com/theotherp/nzbhydra/commit/d5aaaed8a3673f15f4504db8012643720e413a4e

**Comment by porkchop999** [comment]
Thanks all working
