### ISSUE TITLE
Why is Python 2.7.9 needed? Python 2.7.6 works for me

### ISSUE THREAD

**Issue by sanderjo** [theotherp/nzbhydra#298]
Why is Python 2.7.9 needed? Python 2.7.6 works for me on my Ubuntu 14.04 LTS.

So I changed the line
`if sys.version_info >= (3, 0) or sys.version_info < (2, 7, 9):`
to
`if sys.version_info >= (3, 0) or sys.version_info < (2, 7, 6):`

... which works, but is a bit annoying with git pull and pull requests.

So: can the requirement be lowered to 2.7.6? Or a CLI option to ignore the python check? If OK, I can send a PR for this.

**Comment by theotherp** [comment]
https://github.com/theotherp/nzbhydra/issues/181#issuecomment-204690224

**Comment by theotherp** [comment]
Entirely possible that it's not needed anymore. Why don't you just install 2.7.11, I'm running Ubuntu 14.04 as well.

**Comment by sanderjo** [comment]
OK, now on 2.7.11 with
`sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7`

Fingers crossed ... ;-)
