### ISSUE TITLE
typo in the help section in the searching config

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#300]
I didn't know how to name this issue...

I was just browsing through the "Help" part on the 'Config' -> 'Searching' page. At the bottom of the help, it says 
`Redirecting has the advantage that it causes the least load on Hydra but also the disadvantage that the requester might be forwarded to an indexer link that contains the indexer's API key. To prevent that select "Serve".`
However, I don't see any option on the page labeled "Serve".  There is an option that says "Proxy NZBs from Indexer". By no means does it affect functionality. It just seems like a typo of some sort.

I think this is the file: https://github.com/theotherp/nzbhydra/blob/master/onlinehelp/searching.md

**Comment by theotherp** [comment]
Well thank you for my 300th issue being a typo in the online help and not a serious bug :-D

**Comment by judhat2** [comment]
Haha, my pleasure!
