### ISSUE TITLE
weird search results from sonarr

### ISSUE THREAD

**Issue by mauirixxx** [theotherp/nzbhydra#302]
trying to figure out if this is a Sonarr issue or nzbhydra issue.I got a notification that an episode was pushed to my download client. When I eventually got to a computer, I saw that Sonarr never imported the video, so I did a manual search for the episode in question, and got the following results: 

I don't know if Sonarr performed a bad search, or if NZBhydra just dumped all results on Sonarr. I'm wondering if it's a combination of the two, since Sonarr isn't recognizing the very last result returned. 

And now when I do a manual search, I get 0 results ....... weird stuff. Not sure if I would classify this as a bug report? Could be a fluke, or something with Sonarr as well... I guess more of an FYI? I can provide the log file privately if wanted.

**Comment by theotherp** [comment]
Yes please send the hydra log with debug level enabled.

**Comment by judhat2** [comment]
Are all of the wrong results from the same indexer?  Run the mouse over each result and look at the url.  I had this problem with one indexer that didn't support the tvdbid search type.

**Comment by mauirixxx** [comment]
I think you might be on to something @judhat2 - all the erroneous results are coming from lulunzb. The one result that came back as correct (but wasn't recognized by Sonarr - that's their issue) came from dognzb.

I'll disable lulunzb and see what happens. Also, @theotherp I emailed you the log and settings file after enabling debug and restarting nzbhydra.

**Comment by mauirixxx** [comment]
OK, looks like the problem is with the lulunzb indexer and sonarr itself (in terms of parsing valid results). Close issue?

**Comment by theotherp** [comment]
Hydra should recognize that Lulu doesn't support that ID. If it still is used that might mean that Lulu says it supports the ID in its caps but actually doesn't support it.

I'll check it out later, caps pages should be available to me without API access.

**Comment by judhat2** [comment]
> If it still is used that might mean that Lulu says it supports the ID in its caps but actually doesn't support it.

That's what happened with the indexer drunkenslug. The caps reported it supported tvdbid, but it actually  didn't. The admin over there is aware of the error. I just disabled tvdbid support for it in the meantime.

**Comment by judhat2** [comment]
This is an issue with nZEDb. The issue here is that show has not been matched. That triggered a bug with nzedb where if no match is found then you get the latest releases..

https://github.com/nZEDb/nZEDb/issues/2181

**Comment by theotherp** [comment]
Interesting, thanks for the info.
