### ISSUE TITLE
0.2.113 breaks categories filter

### ISSUE THREAD

**Issue by Metigoth** [theotherp/nzbhydra#304]
Updated to 0.21.113 and the Categories filters are note filtering it shows the filter being empty. 
It was working in 0.2.112.

It is only certain searches where filters break.
Jack Reacher came back with unfiltered results

**Comment by theotherp** [comment]
That would be curious because I didn't change anything remotely in that area. Can you please provide more details.

**Comment by theotherp** [comment]
I'm doing a simple "Are any of the required words anywhere in the title". One of your required words is "ea" which is in your movie title, so it will be in most results.

I'll replace it with a proper word based comparison (split title into words and check if any of the required words match any of the words in the title). Don't know why I didn't do that in the first place.

**Comment by Metigoth** [comment]
Thanks that fixed it.
