### ISSUE TITLE
Anime Category

### ISSUE THREAD

**Issue by poplolnman** [theotherp/nzbhydra#305]
Might I suggest that you add an Anime Search category and allow the addition of https://anizb.org and animebytes to it?

**Comment by theotherp** [comment]
You might.

**Comment by theotherp** [comment]
Animebytes is closed. I can't support it without an account.

The aninzb API seems to work fine, implementing it shouldn't be too much work.

**Comment by poplolnman** [comment]
ty!

**Comment by OliRM** [comment]
Sorry for the absolute lack of any API info with anizb, but here is the basics if you end up implementing it (it's a pretty pathetic API).

The url is https://anizb.org/api/
The only parameters are:
`?q={title}`
and
`?limit={1-100}`

Multiple titles can be searched for by using "Title 1"|"Title 2"|"Title 3"
There isn't any limits to querying the API or dowloading NZBs either.

Hopefully that helps, and thanks if you do implement it.

**Comment by theotherp** [comment]
Thanks for the info, I tested searching using the _q_ parameter and it worked. Had assumed it would follow the other newznab standards, but good to know that it doesn't so I don't have to blindly test all the parameters.

@poplolnman Given that there doesn't seem to be a newznab category for anime and there's only two indexers for it, wouldn't it be easier just using them? What would be your typical use case?

**Comment by OliRM** [comment]
Is 5070 the newznab anime category?

**Comment by theotherp** [comment]
There's no "official" anime category. Dog and DS use 5070 for anime, nzbs.org 5070 for "TV BoxSD". Might be a nzedb/nn+ thing.

**Comment by OliRM** [comment]
Awesome, thanks for adding anizb. I'll make sure to fix any code that I might break when I improve the API.

**Comment by theotherp** [comment]
No worries, just shoot me a message beforehand and I'll change my code, so you don't have to crawl through it.
