### ISSUE TITLE
[Windows]  restart pc pauses because NZBHYDRA crashes

### ISSUE THREAD

**Issue by phairplay** [theotherp/nzbhydra#307]
Hi,

can you please help me. 
when I restart my pc it pauses because it says NZBHYDRA has crashed and give me a option to restart anyway or cancel. is there away to remove this?

**Comment by theotherp** [comment]
I need more infos. How are you running it? What windows? Send a screenshot of the message. Post the log from the debug info in the system tab.

**Comment by phairplay** [comment]
here is what I get 
http://imgur.com/2M5EqLE

I'm running windows 8 
through the system tray 

when I cancel the restart I see this message 
NZB Hydra exited with unkown error code 1073807364. do you want to restart Otherwise I'll just quit.
nothing is shown in the log

**Comment by theotherp** [comment]
I'll test it over the weekend.

**Comment by theotherp** [comment]
You know you got an obscure error if google has [1300 results for it](https://www.google.com/search?q="this+app+is+preventing+you+from+restarting")...

**Comment by theotherp** [comment]
When you click cancel you should see a message from hydra containing an exit code. Is that exit code 1073807364?

**Comment by theotherp** [comment]
Fixed (I think).
