### ISSUE TITLE
KeyError: u'categories'

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#308]
Just updated to 6e83577 at when I try to go hydra's homepage in Chrome, I get this error.  None of the web pages are accessible. 
```
2016-07-02 16:52:49,604 - DEBUG - web - Call to method internalapi_getsafeconfig
2016-07-02 16:52:49,605 - ERROR - web - u'categories'
Traceback (most recent call last):
  File "/root/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/nzbhydra/nzbhydra/web.py", line 355, in wrapped_function
    return f(*args, **kwargs)
  File "/root/nzbhydra/nzbhydra/web.py", line 1037, in internalapi_getsafeconfig
    return jsonify(config.getSafeConfig())
  File "/root/nzbhydra/nzbhydra/config.py", line 772, in getSafeConfig
    indexers = [{"name": x["name"], "preselect": x["preselect"], "enabled": x["enabled"],           "categories": x["categories"], "showOnSearch": x["showOnSearch"] and x["accessType"] != "external"} for x in settings["indexers"]]
KeyError: u'categories'
```

**Comment by theotherp** [comment]
Huh, the config migration should've added that. Did you check out manually or use the update function?

**Comment by judhat2** [comment]
I updated manually.  I'll try the update function.

**Comment by judhat2** [comment]
Hmmm, actually I can't access that page because of the error.  What should I do?

**Comment by theotherp** [comment]
Just pushed another update.

**Comment by judhat2** [comment]
That worked. Thanks!

**Comment by theotherp** [comment]
It's possible that you updated to an incomplete state where hydra asked for that setting that wasn't yet migrated.

**Comment by judhat2** [comment]
Yesterday, I went to the develop branch for a moment to check out the commit you made to change the stats page from #103, then changed back to master.  Since that made my version 0.2.118, the autoupdate didn't kick in with the new commits on the same version.  So I did it manually.  All of that must have confused it somehow.  Anyway, it's fixed now.
