### ISSUE TITLE
500: INTERNAL SERVER ERROR - categories

### ISSUE THREAD

**Issue by SubNoizey** [theotherp/nzbhydra#309]
> An error occured :
> 500: INTERNAL SERVER ERROR
> 
> categories

This came up straight after downloading 2.118. I even removed my config and tried reopening it to get the default. I then removed my entire folder and downloaded the zip. Still not working.

I'm using the windows version if that's any help.

The log shows the following

> 2016-07-02 20:23:17,062 - INFO - <string> - Opening browser to http://127.0.0.1:5075
> 2016-07-02 20:23:18,627 - ERROR - web - u'categories'
> Traceback (most recent call last):
>   File "site-packages\flask\app.py", line 1475, in full_dispatch_request
>   File "site-packages\flask\app.py", line 1461, in dispatch_request
>   File "nzbhydra\web.py", line 355, in wrapped_function
>   File "nzbhydra\web.py", line 1037, in internalapi_getsafeconfig
>   File "nzbhydra\config.py", line 772, in getSafeConfig
> KeyError: u'categories'
>

**Comment by theotherp** [comment]
Now?

**Comment by SubNoizey** [comment]
Boots fine now, everything seems to be working. I'll create a new issue if anything else is broken! thanks mate
