### ISSUE TITLE
Private Tracker addition to game catergories

### ISSUE THREAD

**Issue by poplolnman** [theotherp/nzbhydra#310]
Hi,

I see that private gaming trackers are not supported by jackett, but i was wondering if you might be able to support them for nzbhydra searches? ie unltimategamerclub, black cat, and gazelle?

Thanks!

**Comment by theotherp** [comment]
If they're not supported by Jackett I cannot do anything about that. Apart from that I would need accounts and I have only an account for one of those. You will need to create issues at jackett.
