### ISSUE TITLE
Sonnar reports Request Failed: Absolute URI is too short

### ISSUE THREAD

**Issue by jsbear** [theotherp/nzbhydra#311]
https://github.com/theotherp/nzbhydra/issues/301?_pjax=%23js-repo-pjax-container

**Comment by theotherp** [comment]
II'm having trouble reproducing this. My settings:

Host: 0.0.0.0
URL base: /nzbhydra
External URL not set

Adding http://192.168.1.103:5075/nzbhydra/ as indexer in sonarr works fine and it can download NZBs.

By the way, why do you have a base URL set when you don't use a reverse proxy? Just curious.

**Comment by theotherp** [comment]
Please reopen when you have more infos.
