### ISSUE TITLE
Can't add indexers after install (on Mac)

### ISSUE THREAD

**Issue by Big-Galloot** [theotherp/nzbhydra#313]
Hi,
The log shows:
2016-07-03 10:13:04,918 - ERROR - web - The client encountered the following error: http://127.0.0.1:5075/static/js/alllibs.js:9279:32
ngRepeatAction@http://127.0.0.1:5075/static/js/alllibs.js:37732:35
$watchCollectionAction@http://127.0.0.1:5075/static/js/alllibs.js:25738:21
$digest@http://127.0.0.1:5075/static/js/alllibs.js:25875:25
$apply@http://127.0.0.1:5075/static/js/alllibs.js:26139:31
http://127.0.0.1:5075/static/js/alllibs.js:33762:29
dispatch@http://127.0.0.1:5075/static/js/alllibs.js:4435:14
handle@http://127.0.0.1:5075/static/js/alllibs.js:4121:33. Caused by: No known cause
Please help

**Comment by theotherp** [comment]
Please post the debug info from the systam tab.

**Comment by theotherp** [comment]
Please reopen when you have more infos.
