### ISSUE TITLE
Support SABZNBD without a username or password

### ISSUE THREAD

**Issue by seertenedos** [theotherp/nzbhydra#314]
If you try to add SABNZBD as a download client and your sabnzbd instance does not have a username or password and instead just uses the API key you get an error adding it saying "the connection could not be tested" and then a popup with the following error. Note that i left username and password blank and that i have confirmed that my sabnzbd client does not need them.

```
An error occured :
500: INTERNAL SERVER ERROR

username
```

**Comment by theotherp** [comment]
Sorry it took so long.
