### ISSUE TITLE
Ignore the language ID at the end of nZEDb nzbs

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#316]
I am going to throw this out there and see if you think it's worth trying to figure out.

I have noticed that nZEDb indexers will add a language ID to the end of an nzb, if the language can be detected.  It only adds this extra information if a search is done via an ID, e.g. tvdb, imdb, etc. It won't add the language to the end of the nzb name if a general query search is executed.

Here is an example of what I am talking about. https://www.diffchecker.com/vup5nvbt

Do you think it's worth trying to ignore this language ID so that the nzb can be matched to the same nzb from the indexers (newznab) that don't add the audio language?

This is what I often see now.
![image](https://cloud.githubusercontent.com/assets/3536802/16589854/fe9c819e-430f-11e6-8c61-3d1f0cde9f02.png)

**Comment by theotherp** [comment]
Never seen that.

Could be worth a try.

**Comment by judhat2** [comment]
Great, I think it could result in a more accurate duplicate detection.

**Comment by judhat2** [comment]
If you can figure this out, perhaps you can add nzbgeek, too.  Nzbgeek will add -Obfuscated to nzbs that they deobfuscate causing the nzb not to be grouped with the identical nzb from other indexers.
![image](https://cloud.githubusercontent.com/assets/3536802/16714252/f0d5854c-46f7-11e6-9425-6a72bd1dd18c.png)

**Comment by theotherp** [comment]
I think the only nzedb indexer I have access to is NZB Finder. I didn't find any examples of this. Could you provide a couple more, perhaps with other languages? Is it always just <Release> <Language> where language is something like English,German,Dutch,Italian,etc.?

**Comment by judhat2** [comment]
Sure, here a few examples from nzb finder.  I'm sure I can find some more, if you need them.
French - https://www.diffchecker.com/cdm8xrvv
Italian - https://www.diffchecker.com/bomnufk4
German - https://www.diffchecker.com/xnncxeec

How many or which languages they use? I don't know.  I did find it in nZEDb's code, but I don't know which languages would be used. https://github.com/nZEDb/nZEDb/blob/105cca2259700ab9d695696e619bf45e4bae6627/nzedb/http/API.php#L61

**Comment by judhat2** [comment]
I've added this just under your commit to remove "-Obfuscated" and it seems to work fine for me.  It removes the language tag from nzedb's nzbs and groups it with the same nzb from newznab indexers.
```python
lang = [" English"," Korean"," Spanish"," French"," German"," Italian"," Danish"," Dutch"," Japanese"," Cantonese"," Mandarin"," Russian"," Polish"," Vietnamese"," Swedish"," Norwegian"," Finnish"," Turkish"," Portuguese"," Flemish"," Greek"," Hungarian"]
if entry.title.endswith(tuple(lang)):
    for word in lang:
        if word in entry.title:
            self.debug("Removing the language tag:%s from %s" % (word, entry.title))
            entry.title = entry.title.replace(word,"")
```

**Comment by theotherp** [comment]
Completely forgot about this, sorry. Will take a look.

**Comment by judhat2** [comment]
It looks like the update has an error.  It now shows "Remove API duplicate" twice, and the "Always show duplicates" option has disappeared. 

Other than that, it's working great. Thanks!

![image](https://cloud.githubusercontent.com/assets/3536802/17560649/d125c634-5f5d-11e6-9564-857713ab6b45.png)
