### ISSUE TITLE
Daily shows not properly supported

### ISSUE THREAD

**Issue by robnester** [theotherp/nzbhydra#318]
Steps to reproduce:
1) In Sonarr, configure a television show for "daily"
2) Perform a search for episode from show configured in step 1.

Expected results:
Successful search attempt

Actual results:
Traceback as follows:

From nzbhydra logs:
```
2016-07-06 09:51:46,389 - ERROR - web - invalid literal for long() with base 10: '07/05'
Traceback (most recent call last):
  File "/opt/nzbhydra/app/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/app/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/app/libs/webargs/core.py", line 368, in wrapper
    return func(*new_args, **kwargs)
  File "/opt/nzbhydra/app/nzbhydra/web.py", line 508, in api
    return api_search(args)
  File "/opt/nzbhydra/app/nzbhydra/web.py", line 564, in api_search
    search_request.episode = int(args["episode"]) if args["episode"] else None
  File "/opt/nzbhydra/app/libs/future/types/newint.py", line 76, in __new__
    return super(newint, cls).__new__(cls, val)
ValueError: invalid literal for long() with base 10: '07/05'
```

from Sonarr logs:
```
16-7-6 13:51:46.4|Warn|HttpClient|HTTP Error - Res: [GET] http://10.0.0.17:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=100&tvdbid=286373&rid=42474&season=2016&ep=07/05: 500.InternalServerError
invalid literal for long() with base 10: '07/05'
```

Current git revision: 4ecc8785292f5f53133a9bbac0f844bde1ee86c8

Additional notes:
This does not seem to occur with all shows configured as "Daily", as an episode from another show configured as "daily" was successfully downloaded immediately prior to this issue.

**Comment by theotherp** [comment]
Yeah, I don't watch any daily shows and didn't know they were handled differently. I never expected season or episode values to be anything but numbers.

**Comment by robnester** [comment]
Looking through the code, I gathered that. 
Is there any hard requirement for the values being integers? Or can you just handle them as strings?

**Comment by theotherp** [comment]
Cannot say for sure. Will take a look.

**Comment by theotherp** [comment]
Let me know if it works.
