### ISSUE TITLE
Add Option to Password Protect the Config Page Separately

### ISSUE THREAD

**Issue by Cozza38** [theotherp/nzbhydra#32]
Just a feature request to password protect the config page separately.

In some scenarios people would like to allow friends onto their meta search without giving away their indexer details :smile:

**Comment by McGriddle** [comment]
+1

**Comment by Cozza38** [comment]
In the meantime I've just stripped out the config link here: https://github.com/theotherp/nzbhydra/blob/master/ui-src/index.html#L23

and denied access to the page via the reverse proxy which hides the page on the public side but can still be accessed from the LAN.

``` location /config {
    deny  all;
} ```

**Comment by theotherp** [comment]
Cozza, ui-src is the folder where the actualy GUI files are copied / built from. You will need to edit https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/templates/index.html

**Comment by theotherp** [comment]
This may take some time. Note that currently on every page visit the complete configuration is retrieved from the server because it is needed to decide what to show on the search page. If your users want that data they can simply take a look in the browser development tools. To separate general and sensitive data would take some work. If you only share the page with friends and just want a minimum of security then hiding the link to the config page should be enough.

**Comment by Cozza38** [comment]
That's right, sorry, was writing from memory.

I found that blocking the page in nginx wasn't enough as users could still browse (Probably an AJAX thing?)

Hiding the link didn't show any obvious methods to get in.

**Comment by Cozza38** [comment]
Ahh wow, okay. Slapping /internalapi/getconfig onto the URL shows the entire config. That's a problem :(

**Comment by theotherp** [comment]
I wasn't expecting that anybody would open his instance to users he wouldn't trust with the config so I never paid attention regarding data separation.

I will do it but it will take some time as it will need some major changes in the auth system and frontend.

**Comment by theotherp** [comment]
Alright, was easier than expected. Added a separate admin user which can be enabled in the settings.

If neither user nor admin are enabled everybody can do anything.
If admin only is enabled you need to be admin to edit config.
If user only is enabled you need to be user to do anything.
If both user and admin are enabled you need to be user to do anything but change/see the config and be admin to do anything.

Replaced the config that is initially retrieved with a "safe config" that only contains the basic parts that are actually needed and which don't contain sensitive data like usernames, passwords and apikeys.

**Comment by theotherp** [comment]
Has some bugs. Please don't use yet.

**Comment by Cozza38** [comment]
Looks solid, thanks mate :)
