### ISSUE TITLE
Allow different usenetdate formats

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#325]
Apparently the latest nzedb uses a usenet date format like _2016-07-14 11:58:02_. Allow this and the regular pubdate format.

**Comment by judhat2** [comment]
This is fixed to conform back to newznab standards in the nZEDb dev branch.  It will be pushed to the master in the next update.
https://github.com/nZEDb/nZEDb/commit/dbf52fe5d122dfa52738bcbc6429ed49ee27e504

**Comment by theotherp** [comment]
Great, thanks for the info. Closing this.
