### ISSUE TITLE
Provide underlying nzb source for Couchpotato

### ISSUE THREAD

**Issue by sasha-koss** [theotherp/nzbhydra#326]
Would be nice to have the correct Provider displayed for the Couchpotato searches.
(Could be that Couch can't distinguish the source, but im not sure.)

http://i.imgur.com/kl5NruN.png

**Comment by theotherp** [comment]
I think CP shows that because Hydra is configured as a "Newznab" indexer in CP. I'm not sure I can influence that.

**Comment by sasha-koss** [comment]
Ok, thanks.
