### ISSUE TITLE
GETNFO function doesn't work with nZEDb indexers

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#329]
I noticed that the get nfo button wasn't working on some indexers. Turns out that nZEDb uses a different way of getting the .nfo.  

Newznab uses /api?t=**getnfo**
nZEDb uses /api?t=**info**
https://github.com/nZEDb/nZEDb/blob/0.x/docs/newznab_api_specification.txt#L585

I also noticed that nZEDb actually includes the link to the .nfo, if available, in the "info" attribute. https://github.com/nZEDb/nZEDb/blob/0.x/docs/newznab_api_specification.txt#L727

Newznab also started doing this a few months ago, according to their [WebSVN feed](http://newznab.com/plussvnrss.xml).  It will include a link to the .nfo in the "info" attribute.  It also includes an "nfo" attribute with a value of 0 or 1.
http://newznab.readthedocs.io/en/latest/misc/api/#list-of-attributes

All of the nZEDb indexers returned this information, but not all of the newznab indexers.  I guess either they have custom code or haven't updated.  

I was thinking that NZBhydra could search for this "info" attribute, so a manual .nfo check would not be needed.  In addition, what if both `<newznab:attr name="info" value="URL"/>` and `<newznab:attr name="nfo" value="0"/>` is absent, then could hydra still give the option to do the currently implemented manual check for the indexers that haven't updated or have custom code, such as nzbgeek.

Finally, Dognzb always gives the "info" attribute with a link to the nzb's details page.  Perhaps an exception could be made for this indexer, since it would result in false positives.  I made a post on their forum, and one of their staff said he was waiting for the admin to get back to him about it.

**Comment by theotherp** [comment]
Oh god, why can't they decide on one way of doing things, why do there have to be always two or three or who knows how many ways.

I can check if the attribute is given and then use that link. If not then it's probably a newznab indexer and should support t=info, right?

**Comment by judhat2** [comment]
Yeah, It would be a lot easier if they did things the same way on everything.
> If not then it's probably a newznab indexer and should support t=info, right?

Right, but newznab is t=getnfo :)

**Comment by theotherp** [comment]
Right.

**Comment by judhat2** [comment]
I'm not sure how far you want to go with this, but NZBgeek, which has custom code, does it a little different, too.  It looks like it ignores the raw=1 and returns another xml page.  The link to the .nfo is in the last 'description' attribute.  Here is an example.

https://api.nzbgeek.info/api?raw=1&apikey=xxxx&t=getnfo&o=xml&id=c0b3311e148fb8897f8c4c53271278af
will return:
```xml
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://nzbgeek.info/feeds/attributes/" version="2.0">
<channel>
  <atom:link href="https://api.nzbgeek.info/api?raw=1&apikey=xxxx&t=getnfo&o=xml&id=c0b3311e148fb8897f8c4c53271278af" rel="self" type="application/rss+xml"/>
  <title>api.nzbgeek.info</title>
  <description>NZBgeek API</description>
  <link>http://api.nzbgeek.info/</link>
  <language>en-gb</language>
  <webMaster>info@nzbgeek.info (NZBgeek)</webMaster>
  <category/>
  <image>
    <url>https://cdn.nzbgeek.info/covers/nzbgeek.png</url>
    <title>api.nzbgeek.info</title>
    <link>http://api.nzbgeek.info/</link>
    <description>NZBgeek</description>
  </image>
<item>
  <title>
    Movie Name
  </title>
  <guid isPermaLink="true">
    https://nzbgeek.info/geekseek.php?guid=c0b3311e148fb8897f8c4c53271278af
  </guid>
  <link>
    https://nzbgeek.info/geekseek.php?guid=c0b3311e148fb8897f8c4c53271278af
  </link>
  <pubDate>Tue, 02 Aug 2016 06:35:01 +0000</pubDate>
  <description>https://nzbgeek.info/geeknfo.php?nfoid=25212340</description>
</item>
</channel>
</rss>
```

**Comment by theotherp** [comment]
Thanks, not high prio now, will see when I find the time.

**Comment by judhat2** [comment]
Thanks for fixing this. It's working for a lot more indexers now.

Do you think it would be possible (or worthwhile) to make this like the comment icon where the .nfo icon is only shown if an .nfo exists.  The information is given in the api from indexers that have an up to date version of newznab, nZEDb, or nntmux. Omgwtfnzbs even shows a link if an .nfo is available.  I think the only indexers that wouldn't show this attribute is nzbgeek and dognzb (custom code) and indexers with old versions of their engine software.  Perhaps those two indexers, since they are popular, could still be checked for an available .nfo.  

Just a thought. :)

**Comment by theotherp** [comment]
Hm, no idea why I didn't implement that.

I only have a couple of indexers to test, most seem to work wekk, Dog doesn't report it as you said and NzbFinder sometimes claims to have an NFO and even provides a link but then the link says there's no NFO attached.

**Comment by albino1** [comment]
I've noticed that quite often if you click on NFO nothing is returned, but if you go the actual indexer details page you can see there really is an NFO on there.  Anybody else notice this?

I know you both have a DOGnzb account, so we'll use that as an example.  Try this search:

`The.Hamiltons.2006.1080p.BluRay.x264-PSYCHD`

It returns two results on DOGnzb, both of which don't seem to return NFO files, but if you click the Details links you'll see that both actually do have NFOs.  It does seem to be random though, I ran the search a bunch of times and once I swear I got an NFO, though I might have clicked on a different indexer by mistake.

Here's another example where NZBGeek returns no NFO, even though it has one:

`The.Grift.2008.1080p.BluRay.x264-THUGLiNE`

Final example:

`Boogeyman.3.2008.1080p.BluRay.x264-aAF`

2 versions on DOG, 2 on Geek, all 4 return no NFOs, but all 4 actually have NFOs on their respective sites.

**Comment by theotherp** [comment]
@albino1 I'll do some tests.

**Comment by theotherp** [comment]
@albino1 Yeah, that seems to be Dog's fault. https://api.dognzb.cr/api?apikey=APIKEY&t=getnfo&id=ed4f16e09332214dadc330798e4ad399 doesn't return anything but https://dognzb.cr/details/ed4f16e09332214dadc330798e4ad399 contains an NFO.

You might want to create a thread on their forum.

**Comment by judhat2** [comment]
Yeah, I mentioned it a few months ago on dognzb's forum, but it never got fixed.

With nzbgeek, I mentioned that a few post above. https://github.com/theotherp/nzbhydra/issues/329#issuecomment-236992546 Looks like it would require some special attention.

**Comment by albino1** [comment]
I forgot all about that thread by @judhat2.  What's weird is it sometimes returns an NFO and sometimes doesn't.  So the call works in theory, but I have no idea why it only works a third of the time.
