### ISSUE TITLE
Unable to search for "daily" TV shows.

### ISSUE THREAD

**Issue by claym** [theotherp/nzbhydra#330]
Tried Last Week Tonight on 7/31/2016, and the logs showed an error for

ERROR - web - invalid literal for long() with base 10: '07/31'

**Comment by claym** [comment]
Sorry, just noticed this was a dupe of https://github.com/theotherp/nzbhydra/issues/318

Would really love for a fix on this one, it's going to prevent me from using the app.

**Comment by theotherp** [comment]
I've got a lot going on, will try to find some time for it.
