### ISSUE TITLE
CasstormNZB doesn't support https

### ISSUE THREAD

**Issue by switchpants** [theotherp/nzbhydra#334]
Hey there.

I created an account at CasstormNZB just to see what it was like after I noticed it was one of the presets in nzbhydra.  Anyway, the preset uses https, but it appears that CasstormNZB only supports http.  I thought I'd mention it so you can change the preset to "http" for a future release.

Thanks for nzbhydra -- its good stuff!  😁

**Comment by theotherp** [comment]
Will change the preset. But I don't recommend using an indexer without
https. Thanks for the info.

**Comment by switchpants** [comment]
I agree about the https vs http...  might be worth just removing the Casstorm preset.

Anyway, thank you again.  Your efforts are much appreciated.

**Comment by theotherp** [comment]
I'll remove it, the certificate is issued to and by "www.soccer-tipser.com". Not worth being supported I think.
