### ISSUE TITLE
Error with Drunkenslug

### ISSUE THREAD

**Issue by jason-ellis** [theotherp/nzbhydra#335]
I've done a lot of searching on this issue but cannot figure out where to go from here.

When I first started using NZBHydra, all was well. I specifically saw some NZBs coming from Drunkenslug. At a certain point, I was trying to add Headphones to my setup and it won't work at all with Hydra (but that's not what this issue is about). When I went to look at the Hydra logs, I noticed that it constantly throws up errors for Drunkenslug. Below is the entry in NZBHydra for why it failed. I replaced some info with X's. When I plug in the URL with my API token it returns valid XML with the correct search results in the browser. This is a TV request from Sonarr. When I just add the same Drunken Slug info to Headphones or Sonarr it works fine. I have other indexers that work fine. 

When I added DS originally I used the default settings. After is stopped working I switched to the https://api.drunkenslug.com URL because that's what is the default in Sonarr. Neither work in Hydra.

Thoughts?

Connection failed: HTTPSConnectionPool(host='api.drunkenslug.com', port=443): Max retries exceeded with url: /api?apikey=<APIKEY>&t=tvsearch&extended=1&offset=0&limit=100&cat=5030,5040&rid=XXXXX&ep=4&season=4 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f27f6911950>: Failed to establish a new connection: [Errno 115] Operation now in progress',))

I'm running everything on a Synology diskstation in docker containers from linuxserver.io. Please let me know what additional information I can provide.

**Comment by theotherp** [comment]
No idea, please contact the DS admin.

**Comment by jason-ellis** [comment]
Resolved. Total bonehead issue. I don't remember ever changing this, but it appears the problem was that the Drunken Slug indexer settings had the timeout set to 0. I deleted that so it would use the default search value of 20 and issue appears resolved.

Thank you for looking into this for me, and sorry to waste your time!

**Comment by theotherp** [comment]
Hehe, thanks for the update. I'll add a restriction to the field so it cannot be set to 0.
