### ISSUE TITLE
Error parsing nzb-file

### ISSUE THREAD

**Issue by hermy65** [theotherp/nzbhydra#336]
I have been using Hydra for about a week now without issues and then tonight all of a sudden everything that an application finds and tries to add to NZBGet fails. This is what i see in the NZBGet log

ERROR	Sun Aug 07 2016 21:47:21	Error parsing nzb-file linux-iso.nzb
ERROR	Sun Aug 07 2016 21:47:21	Error parsing nzb-file: Extra content at the end of the document
ERROR	Sun Aug 07 2016 21:47:21	Error parsing nzb-file: SYSTEM or PUBLIC, the URI is missing
ERROR	Sun Aug 07 2016 21:47:21	Error parsing nzb-file: SystemLiteral " or ' expected
ERROR	Sun Aug 07 2016 21:47:21	Error parsing nzb-file: Space required after the Public Identifier

If i go to the download history and click the nzbget button it loads the nzb without any issue. Any suggestions?

Edit: It looks like its only affecting downloads from Sonarr as others seem to be working.

**Comment by airbillion** [comment]
I am having the same issue with sonarr and Hydra...with both SAB and nzbget...

**Comment by theotherp** [comment]
Can you do an API call with Hydra and try to download an NZB from the result? Check if it contains XML or something else.

For example do http://127.0.0.1:5075/api?apikey=YOURAPIKEY&t=tvsearch in your browser and click one of the links. Download the file and open it with a text editor.

**Comment by airbillion** [comment]
Downloaded nzb and I think it looks OK...updated to 0.2.131 and tried to grab and episode from sonarr and push to sab...sab errors out withj " Empty NZB file....." still...not sure what happened.  It was working fine up until soemtime this weekend.

**Comment by theotherp** [comment]
Do a search in hydra and push NZBs from at least two different indexers to your downloader. Does that work?

**Comment by hermy65** [comment]
Doing an API call in Hydra i am able to download a valid nzb and i am able to do a search in Hydra and push nzb's to NZBGet without issue, i pushed from 3 different indexers and they all load up without issue.

I did also just update to 0.2.131 to see if that had any affect but it did not.

**Comment by airbillion** [comment]
Search and push directly from Hydra is working fine for me...only when sonarr makes the request does it not work...tested from couchpotato successfully too...something is not working between sonarr and hydra it would seem.  Sonarr works if I remove hydra and use my indexers directly though...

**Comment by theotherp** [comment]
Do you use "Proxy NZBs from indexer" or "Redirect to the indexer"? 

Check the download tab in the history and check if the NZBs are all from the same indexer.

**Comment by hermy65** [comment]
I have tried both options and have manually pushed from multiple indexers using hydra

**Comment by theotherp** [comment]
I still don't know what indexer(s) is/are affected.

**Comment by hermy65** [comment]
These are the indexers i have setup in Hydra:

NZBs.org
DogNZB
NZBgeek
AltHub
NZBIndex
Binsearch
NZBClub

When Sonarr requests something and Hydra finds it NZBGet fails to load NZBs from all of the above except Binsearch and NZBIndex as those have not had any hits yet. I have gone through the search history and all of the above have tried sending nzbs but they fail. If i manually push them through hydra they work without issue so i dont think its indexer related but more so Hydra/Sonarr related.

**Comment by theotherp** [comment]
Yeah, no idea. Sonarr hasn't had any updates lately and I didn't change anything. Both have been running without issues for me. Set the log level to debug for both. Reproduce the error and send me the logs.

**Comment by hermy65** [comment]
Where would you like me to send them to?

**Comment by theotherp** [comment]
I'm sorry, I'm out of ideas.

**Comment by WilliamJBrown** [comment]
I am also seeing this issue. Have tried every setting involved to see if I can not get this error. Is it something to do with that latest update? I can put NZBCat into Sonarr directly and that will send to NZBGet. But if I put NZBCat in Hydra and get Sonarr to pull from Hydra it instantly sends it to the failed section of NZBGet.

**Comment by WilliamJBrown** [comment]
You have a IRC or a instant communication channel to work on this together? May it be something to do with the update of nzbget 17.0? Let me know, willing to help all I can.

**Comment by theotherp** [comment]
I'm running the latest Hydra with NZBGet 17.0 on Ubuntu 14.04 and haven't had any problems. Also @airbillion wrote that it doesn't work with sabnzbd either.

I'm having friends visit over the next week and won't have much time to analyze this.

I noticed the warning from sonarr about redirects in @hermy65 's logs. Do you other guys see those warnings as well? I don't have them in my log.

**Comment by theotherp** [comment]
[This](https://www.reddit.com/r/usenet/comments/4x63mf/status_check_sonarr_nzbhydra_nzbget/d6d0zce) seems to fix this problem.

**Comment by theotherp** [comment]
Any news on this?

@WilliamJBrown I have a little bit more time now, would just need to find a day and time when we're both free.

**Comment by WilliamJBrown** [comment]
That did fix the problem which you posted above. I'm just trying to battle this docker container to update on its own. It an issue on my end I'm sure.

**Comment by theotherp** [comment]
Nope, never have used docker in my life. Can't help you there, sorry.
