### ISSUE TITLE
Reverse proxy nginx with not showing webpage

### ISSUE THREAD

**Issue by nuddyd** [theotherp/nzbhydra#338]
Hi,

I am having a very wired issue - looks like my reverse proxy redirects the request. However NZBhydra is not loading the complete page.

I am only getting "Yay, there's an update available. Your version: . Latest version: . " and two buttons
"See whats new" and "upgrade". Other than that all is blank.

Any idea?
My ngynix config below.

`server {
listen 80;
server_name xxxx  20.20.20.6;
return 301 https://$server_name$request_uri;  # enforce https

}

server {
        server_name xxxx  20.20.20.6;
        listen 443 ssl;
        ssl_certificate xxxxx;
        ssl_certificate_key xxxxxx;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "xxxxxxxxxxx";
        ssl_session_cache shared:SSL:10m;

location /nzbhydra {
    proxy_pass http://127.0.0.1:5075/nzbhydra/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}`

**Comment by theotherp** [comment]
Do you open http://127.0.0.1:5075/nzbhydra/ ? Note the trailing slash.

**Comment by nuddyd** [comment]
nope still not working.
I am typing my domain name "xxxx.com/nzbhydra/ still not working...
But the question is why it is showing ony two buttons and not whole page.

However when I use the link 127.0.0.1:5075 it works

**Comment by nuddyd** [comment]
got it working - basically i loaded the webpage first locally i.e. 127.0.0.1:5075
and then there is setting where you have to add the "URL base" - I added /nzbhydra/ and it worked.

Thanks
