### ISSUE TITLE
No query results when using API

### ISSUE THREAD

**Issue by whitebird** [theotherp/nzbhydra#340]
When I use CouchPotato, SickBeard or Sonarr to search for a show it doesn't return any results:

> 2016-08-11 19:52:59,571 - INFO - web - API search request: SearchRequest [ type "tv", query "The.Simpsons", forbiddenWords "[]", requiredWords "[]", season "1", episode "13", offset "0", limit "100"

When doing the same query manually, it shows several results.

**Comment by that0n3guy** [comment]
I'm having a similar issue.   I'm trying to add nzbhydra as an indexer in sonarr.   Sonarr says `Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.`

In hydra the logs show: 
```
2016-08-12 16:33:21,142 - INFO - web - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", limit "100" ]
2016-08-12 16:33:21,256 - INFO - search - Removed 0 duplicates from 0 results
```

This is the api query url from sonarr:
```
http://hydra:5075/api?t=tvsearch&cat=5030,5040&extended=1&apikey=5mwv9w325ksgo4s40koo3&offset=0&limit=100
```

If I navigate to that url via web browser I get:
```
<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>NZB Hydra</title>
<description>NZB Hydra - the meta search</description>
<link>https://github.com/theotherp/nzbhydra</link>
<language>en-gb</language>
<webMaster>TheOtherP@gmx.de (TheOtherP)</webMaster>
</channel>
</rss>
```

**Comment by theotherp** [comment]
I added a function that logs a warning if no indexers were selected for searching. Update to the newest version, try again and check your log.

**Comment by whitebird** [comment]
Updated to newest version, log didn't contain anything new.

**Comment by theotherp** [comment]
I've still not seen a log with debug level.

**Comment by whitebird** [comment]
Indeed, forgot to set debug level. Full log: https://gist.github.com/whitebird/51569f4d970997576c66ca3224f920c0

**Comment by theotherp** [comment]
You should add at least one "proper" indexer like Dog, Monkey, DrunkenSlug, whatever.

**Comment by whitebird** [comment]
Confirmed, fixed when adding DrunkenSlug indexer. Any idea why this happens with the others?

**Comment by theotherp** [comment]
Aha, there was a bug in the womble support where it wouldn't call any URLs at all.

Sonarr basically just asks for the latest releases in a given category. Binsearch, NZBClub and NZBIndex don't support "queryless" searches, so they're not picked for that. Because Womble was buggy it was picked but not actually searched. For DrunkenSlug another code part is used.
