### ISSUE TITLE
500: INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by Yaff1e** [theotherp/nzbhydra#342]
For the last several updates I've been unable to search from the GUI. 99% of the time I get:-

![image](https://cloud.githubusercontent.com/assets/11681244/17703009/144952aa-63c8-11e6-8213-633a64b40c7e.png)

Occasionally I do get a valid result but most of the time not. API search is working fine.  The relevant part of the log seems to be:-

> 2016-08-16 14:19:18,279 - ERROR - search - Error while calling search module
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/search.py", line 401, in start_search_futures
    results = f.result()
  File "/opt/nzbhydra/libs/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/opt/nzbhydra/libs/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 140, in search
    queries_execution_result = self.execute_queries(urls, search_request)
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 405, in execute_queries
    self.handle_indexer_failure(reason="Access failed")
  File "/opt/nzbhydra/nzbhydra/search_module.py", line 298, in handle_indexer_failure
    indexer_status.save()
  File "/opt/nzbhydra/libs/peewee.py", line 4915, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/opt/nzbhydra/libs/peewee.py", line 3244, in execute
    return self.database.rows_affected(self._execute())
  File "/opt/nzbhydra/libs/peewee.py", line 2774, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/nzbhydra/libs/peewee.py", line 3645, in execute_sql
    self.commit()
  File "/opt/nzbhydra/libs/peewee.py", line 3466, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/opt/nzbhydra/libs/peewee.py", line 3638, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: database is locked
2016-08-16 14:19:18,313 - DEBUG - search - Retrieved 3 of 13 calls from executor <

I can occasionally get a single search to work by deselecting all indexers and then selecting one only but it only works for 1 search.

I've done some searching and have seen plenty of references to the same problem and have tried some of the suggested fixes with no joy.

Any suggestions on anything I can try?

**Comment by theotherp** [comment]
Yeah, no. This seems to affect very few people and I don't know why. Is this a docker container? Is it possible multiple instances are running? You can also try to disable the threaded server in the config. The downside of that is that only one program can access the instance at any time, so when you do a manual search and sonarr does a request at the same time then that request may time out.

**Comment by Yaff1e** [comment]
It's just a bog-standard Ubuntu Server install using init.d. It has been working for a while but just seems to come up with this error now. I've tried disabling threaded server already which didn't seem to make any difference. As far as I know there's only one instance running.  When I get chance I'll have to have a proper play around with it to see if I can get it working again.

**Comment by theotherp** [comment]
Try reducing the amount of active indexers. 13 is really high.

**Comment by Yaff1e** [comment]
Okay, I'll give that a go thanks. Is there a sensible limit? Most of them are limited free accounts anyway so not a problem.

**Comment by theotherp** [comment]
No idea, it's just a theory, reducing the amount of parallel threads could solve the issue.

**Comment by Yaff1e** [comment]
I've just dropped it down to 4 to start with and it worked okay so I started re-enabling one at a time until the error occurred again. Typically it didn't occur until the last one was enabled. I then tried removing 1 at a time and got the error every time until I was back down to a low number of indexers. I'll keep playing and see if I can find a stable number for my machine.

Thanks.

**Comment by theotherp** [comment]
Please reopen when you know more. Sorry, can't help with this at the moment.
