### ISSUE TITLE
(De)select all indexers on the search page

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra#343]
Any chance for a button to (de)select all indexers on the search page, maybe invert the selection? I have six rows of indexers there now, and this would make selecting only a specific one much easier. There's already an issue where somebody asks for something similar with search results, and it doesn't seem so easy there, but maybe it's less difficult here.

Thanks for NZB Hydra in general, which I find hugely useful - even if I have to make some more clicks every now and then :-)

**Comment by albino1** [comment]
+1 

Would love this.
