### ISSUE TITLE
Results in NZB360 android app sent to nzbget hang at "Fetching" status

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra#345]
My setup:
Ubuntu 16.04
nzbhydra v0.2.136
nzbget v17.0
nzb360 v9.5.4

Expected behavior is to be able to perform a search within the nzb360 app (both on localhost or remotely depending on environment) and send that search to nzbget so it can download it. First error is that some searches show up as "Error getting search results" even though I know there are some available on my indexer while others do not; the second error (and the one in which this bug report covers) is that whenever a successful search occurs and I select to send it to nzbget it just hangs in nzbget with a Status of "Fetching". If I click to open the name of that search from withing nzbget and copy/paste the the url link inside that within my browser, I am prompted to download/save the appropriate nzb file to my local hard drive. The download eventually times out with a status message of "Fetch: Failure". It seems nzbget is unable to upload the specified nzb file sent from nzbhydra via nzb360.
I've search for this problem and most similar issues seem to surround the external URL and reverse proxies. I do not have a reverse proxy setup though. I'm just using IPaddress:port# in the External URL field on the Main settings page on nzbhydra. A proper Apache reverse proxy may solve this issue but I've ran into independent problems going that route and would like to investigate this problem for others that may be running this same setup.

This problem occurs regardless of Config -> Searching -> NZB access type -> (Redirect or Proxy) or Config -> Downloaders -> nzbget -> NZB access type (Redirect or Proxy) -> NZB adding type (Send link or Upload NZB). I've tried everything combination of the preceding sentence with restarts of nzbhydra between each setting change but the same problem always occurs. Relevant sections of nzbhydra and nzbget log files are attached. NZB360 does not provide debug files but have provided relevant information to it's developer which he says he is debugging on his end. I will post any information he may be able to provide here if and when he gets back to me.

I've tried everything I know to do on my end. Please let me know what other information I may be able to provide or any further troubleshooting steps I can attempt.

[nzbget_error.txt](https://github.com/theotherp/nzbhydra/files/423377/nzbget_error.txt)
[nzbhydra_logfile.txt](https://github.com/theotherp/nzbhydra/files/423375/nzbhydra_logfile.txt)
[nzbhydra_settings.txt](https://github.com/theotherp/nzbhydra/files/423376/nzbhydra_settings.txt)
![nzbget_error](https://cloud.githubusercontent.com/assets/6394767/17749015/a4df5580-6481-11e6-94ba-6cd505e648e8.png)
![nzbget_error2](https://cloud.githubusercontent.com/assets/6394767/17749016/a4e11fe6-6481-11e6-8352-0ffafe93b202.png)

**Comment by theotherp** [comment]
I'll try and do some tests tomorrow.

**Comment by theotherp** [comment]
I just tried about every combination possible and in all cases it worked - but I know how to configure it and might not think of something that you misunderstand.

Please send me your settings.cfg via [mail](mailto:theotherp@gmx.de) Delete the API keys if you want but please leave everything else as it is.

**Comment by theotherp** [comment]
NZBGet does not include the port in the displayed name but as you can see on your second screenshot the link does still include the port.

Your NZBGet log looks like this:

```
Wed Aug 17 12:26:32 2016        INFO    Queue IPaddress/getnzb?apikey=<APIKEY>&searchresultid=598788
Wed Aug 17 12:27:32 2016        ERROR   Connection to IPaddress failed: ErrNo 110, Connection timed out
```

While mine looks like this:
```
Sat Aug 20 19:14:26 2016	INFO	Queue 192.168.1.103/getnzb?apikey=apikey&searchresultid=1850
Sat Aug 20 19:14:26 2016	DETAIL	Downloading 192.168.1.103/getnzb?apikey=apikey&searchresultid=1850
Sat Aug 20 19:14:27 2016	DETAIL	URL http://192.168.1.103:5075/getnzb?apikey=apikey&searchresultid=1850 redirected to https://dognzb.cr/fetch/foo/bar
Sat Aug 20 19:14:27 2016	DETAIL	Downloading 192.168.1.103/getnzb?apikey=apikey&searchresultid=1850
```

When you do a manual Hydra search and add an NZB to NZBGet, does that work? It should be the same as when using NZB 360: A link is sent to NZBGet which then tries to download the NZB from Hydra. 

Do you run Hydra and/or NZBGet in a container or something like that which would explain why the latter is unable to communicate with the former? Apparently it's only the two that cannot communicate with each other, NZB 360 can talk to NZBGet and Hydra and when using your browser you can access Hydra as well. Perhaps your firewall is configured strangely so that NZBGet cannot access your local network?

It seems like to redacted your IP address in nzbget_error.log. Is that your local IP address (like 192.168.0.1)?

I'm just guessing here, but this doesn't seem to be a problem with Hydra but rather with NZBGet

**Comment by theotherp** [comment]
Could it be something like [this](https://www.reddit.com/r/usenet/comments/2ju99h/cannot_connect_using_public_ip_while_on_internal/clfafjo)?

**Comment by theotherp** [comment]
What happens when you disable "Use local address in API results"? NZBGet should try to download from "http://dynamic.domain.com:5075".

**Comment by jaywk** [comment]
> When you do a manual Hydra search and add an NZB to NZBGet, does that work?

Yes.

> Do you run Hydra and/or NZBGet in a container or something like that which would explain why the latter is unable to communicate with the former?

No.

> Perhaps your firewall is configured strangely so that NZBGet cannot access your local network?

I've completely disabled my firewall for testing purposes and it made no difference.

> It seems like to redacted your IP address in nzbget_error.log. Is that your local IP address (like 192.168.0.1)?

No, that was my WAN IP.

> Could it be something like this?

This option was already disabled in my router settings


> What happens when you disable "Use local address in API results"?

Results still show up within NZB 360 but they never show up in nzbget whenever click "Send to nzbget".


> You could also try setting "0.0.0.0" as host.

This made no difference then having it set to the IP address of the machine that both nzbhydra and nzbget are running on.

**Comment by jaywk** [comment]
> Perhaps your firewall is configured strangely
> Could it be something like this?

So, it is working for me now. These two lines of thought got me thinking about DNS and router settings. I made a few changes on my router (actually reset everything in the router and started configuring it from the ground up) and now everything seems to be working as expected.

Thank you for taking the time to help me. In the end, it had nothing at all to do with nzbhydra, but I never would have looked at my router settings without the suggestions you put forth in your last replies here. Thanks again for your help, creating such an awesome program, and being so active in developing it.

**Comment by theotherp** [comment]
That's great, thanks for the info. I was suspecting something like that. But it's great to have it confirmed.
