### ISSUE TITLE
[REQ] Per category ignore wanted list words?

### ISSUE THREAD

**Issue by schumi2004** [theotherp/nzbhydra#348]
## How to request a new feature
* What do you want to happen?
I would like to see a feature having a per category ignore/wanted list words configuration.

* Why do you want it?
For example, for video files (movies/tv) i would like certain words to be ignored or wanted but not for music.

* Do you think it's something only you need or something that might me popular?
I can't answer this question i can only say this would be usefull for me.

* If need be explain the use case.
When external apps like couchpotato or sonarr do api requests they send category to search in. In this case having ignore words for movies/tv would be a must for me.
When headphones (music app) does a api request it does it in music catgory, in this case i don't need any ignore/words or only a minimal set since ignore word WEB (i have configured) is wanted in this case but NOT for movies/series.

* Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
It's a nice to have function not a must.

My idea about implementing such is to assign categorys to ignore/wanted words it should be applied to and ignored for others like for example All categories when doing a manual search

**Comment by judhat2** [comment]
Uh, isn't this already available? Look in http://127.0.0.1:5075/config/categories

**Comment by theotherp** [comment]
Yeah, I think so, too..

**Comment by schumi2004** [comment]
Oops, my bad. You are right.
