### ISSUE TITLE
FR: Refine Results within the GUI for Manual Searches

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#349]
**What do you want to happen?**
I'd like to be able to refine my search results within the GUI when doing manual searches without having to run the entire search again.

**Why do you want it?**
I think it would speed up the process of weeding through large amounts of results to fractions of a second.

**Do you think it's something only you need or something that might me popular?**
I'll freely admit that the number of people that use the NZBH GUI for manual searching is probably a small part of the overall userbase, but I think for those that do search manually that this functionality would be very helpful and save a lot of time.

**If need be explain the use case.**
If you have hundreds of results and want to quickly add a size or date filter, or add a keyword like 1080p to your search, you currently have to run the entire thing again and query every indexer.  Since all of the results for those searches already exist in the NZBH database it seems like you could almost instantaneously whittle it down by just typing 1080p into a separate smaller search box above the results, or by adding a size/date filter, without having to re-query all of the indexers.

I think you could maybe disable/enable this in the config if people might want to always force a full search again, and maybe if you choose to enable it then add an option to force a full search anyway.

**Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.**
Definitely not a must have, but it would indeed be nice.

**Comment by judhat2** [comment]
+1 This would be cool!

**Comment by theotherp** [comment]
When designing the results table I had already planned something like that.

Currently only the first 100 results are retrieved and displayed because showing and filtering them needs a lot of resources (due to the framework I use and I haven't found a way and the patience to improve that). I could try again.

If this were done using extra input buttons I don't think there would be need for an option to disable this. You would just not use it.

I'll play around and see what I can come up with.

**Comment by albino1** [comment]
Sounds good, thanks for looking into it!

**Comment by theotherp** [comment]
Funny, a couple of months ago I thought Hydra would be feature complete and there wasn't anything I could add.

**Comment by albino1** [comment]
Took me a minute to figure out that it was even working because I just kept hitting enter to filter, not realizing it was happening as I typed :) 

I'm having a problem where when, after doing an initial search, I try to do a new search from the box and  it just shows the previous search even after I hit enter.

I'm also having an issue where sometimes even when I'm on the index page my search doesn't go through and instead it returns every thing from every indexer, so like 30 million results:

`Loaded 2142 of 30259697 results`

Also, any chance you could add the ability to remove words as well?  For example if you searched for `Breaking Bad S01E01 720p` but then wanted to do something like `--German`.

**Comment by albino1** [comment]
Turns out the issue for both problems is just hitting enter too fast after you finish typing.  If you pause a second after you finish and *then* hit enter the search is successful every time, but if you're a fast typer and slap enter immediately after typing your last letter then it's still doing the sorting and ends up with the previous search terms.. which in the case of the index page is no search terms at all.

**Comment by theotherp** [comment]
Oops, yes. It's because I "debounce" the entering so that it waits 500ms until it does the filtering, but that also means that pressing return faster than that uses a shorter query than entered. Will remove the debounce for now and think of something.

**Comment by albino1** [comment]
Well, I think a partial solution is just to definitely turn it off when you're on the index page, because there's no results to refine in the first place :)

If it was me (and it's not, hah!), I think I would just put a smaller search box in like the top right corner just above the results that's clearly marked as "refine results".  And maybe leave the date/size boxes where they are on the index, but move them on the results page to the middle attached to the results table as well -- just make a whole mini-header row at the top for refining results.  That would also have the added benefit of bringing the overall results up higher on the page and not burying them at the bottom.  Anyway, something like that :)

**Comment by theotherp** [comment]
I experimented with filter boxes in the table headers but that was ugly. Perhaps I add a smaller version of the search box (query, size, ages) just above the table and make it expandable so it's hidden by default.

I felt using the already shown search box was quite an elegant solution. But it comes with some problems and my resolution might be bigger than that of most others.

**Comment by albino1** [comment]
On my PC the resolution is never a problem, but on my laptop it can sometimes be an issue.  Though it doesn't help that I use multi-row tabs, so I lose a bit of screen real estate vertically.
