### ISSUE TITLE
Enable for Specific Categories Not Working

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#353]
I have an indexer (PFM) set to only search the Movie and TV categories, but instead it returns results from all of the categories.  Here's how I have my settings:

![nzbh-pfm-categories1](https://cloud.githubusercontent.com/assets/12164957/17990692/defdf05c-6aec-11e6-9340-60a1595e1ed1.jpg)

Then here's a search for the term `example` with only that indexer enabled:

![nzbh-pfm-categories2](https://cloud.githubusercontent.com/assets/12164957/17990701/e795cb54-6aec-11e6-8b04-9e10e083412c.jpg)

As you can see there's a bunch of categories being searched instead of just Movies/TV.

**Comment by theotherp** [comment]
Ah. Well, I see why you think that's a bug but that's actually not what you think it means.

"Enable for... <categories>" means that the indexer will be used when you do a search in any of those categories and will be hidden from the selection box when you do a search in any of the other (not enabled) categories.

So it doesn't mean "Ignore results from ...". I guess there're two ways of interpreting this. I might add a button "Ignore results from other categories" below the selection box. If enabled then results from any of the not-selected categories would be remove.

Or I just do it that way without checkbox, apparently users interpret that function differently than I do.

**Comment by albino1** [comment]
Ohh, okay, yeah, I definitely thought it was something else related to a discussion previously about the ability to ignore specific categories.

I always search under the All drop down, because results are frequently in the wrong categories, but PFM in particular returns a lot of random results if your query isn't specific enough, mostly in XXX and Audio FLAC.   So I was thinking I could mitigate that by constraining it to only the Movies and TV categories.

It's not a big deal, and clearly not a bug, so I'll go ahead and close this :)

**Comment by albino1** [comment]
Actually, now that I'm thinking about it, couldn't it just do both?

Scenario: Set an indexer to only be enabled for Movies.

* Current Expectation: That indexer is disabled/unchecked, but if you manually select one of the movie categories from the drop down then that indexer becomes enabled/checked.
* Additional Enhancement: That indexer is enabled/checked for `Any` by default, then it will search all of the categories for every indexer, but *only* the movie categories for the one that's been restricted.  If you then switch the drop down to a different non-Movies category then it becomes auto-disabled and unchecked.

Maybe it's just late and I'm tired, but it seems like they don't have to be mutually exclusive.  I might also be over complicating it for very little gain :)

**Comment by theotherp** [comment]
Yes, that's what I meant.

Only thing is that not searching in a category is pretty hard. You cannot exclude categories in a search, only include all the others. But as "all the others" is different for every indexer that's not what I do. I just search in all categories and then remove results from the unwanted categories. That's not ideal but I can't change that without a lot of additional work.

But yes, I will change it so that indexers are only displayed categories which are selected in the "Enable for..." box and will remove any results not in any of those categories.

**Comment by albino1** [comment]
I probably just gave you a lot of work for very little payoff :)  Thanks though!

**Comment by theotherp** [comment]
I've decided against explicitly enabling indexers for which preselect is disabled.
