### ISSUE TITLE
Search Types: Audio never detected with indexers?

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#354]
I've noticed when I add an indexer that NZBHydra almost NEVER detects audio as a capability despite it being capable. 

Also, is there a way to simply remove the MP3 category to make sure it searches all audio instead of just MP3? I've noticed that a lot of indexers don't necessarily split the two up. 

Am I missing something or is this by design?

Thanks,

**Comment by albino1** [comment]
> I've noticed when I add an indexer that NZBHydra almost NEVER detects audio as a capability

The "detected capabilities" are so you can have it search by IDs for IMDb, TVDB and TVRage.  There's no equivalent thing for music that the indexers support, because music on Usenet is a totally unorganized disaster with just random badly named posts here and there.

> Also, is there a way to simply remove the MP3 category to make sure it searches all audio instead of just MP3?

Under the Search drop down (which is set to `All` by default) you can switch it to `Audio` when you want to search all of the audio categories.

**Comment by seanvree** [comment]
Ahhh, okay, got it @albino1 , thanks.

So is there a way to have it search all audio when doing an API search?

**Comment by albino1** [comment]
Hmm, I don't know, perhaps omeone else does though.  I assume you're using Headphones?  Maybe ask the dev that revived that project, I've never used it.

**Comment by seanvree** [comment]
Yeah, using headphones. When the command is sent to Hydra, it searches as MP3 only.  But, if I do a manual search for the same term using audio, I find a lot more.

**Comment by theotherp** [comment]
Check the log for the search that headphones does. I guess it only searches in category 3010 which is MP3. Hydra uses the categories requested by the API call so there's nothing I can do about that. I guess I could implement an option to override categories but I don't think that's used often and I already have a lot of really specialized stuff that rarely is needed (feature creep).

I'm going to close this.

**Comment by seanvree** [comment]
So could I add the "audio" category to MP3 to try and trick it?  Does that make sense?

**Comment by theotherp** [comment]
No, I thought about that but Hydra doesn't override the category selection of indexers. I might implement that at some point, but currently it's not possible. I'm sure you can configure headphones to search in all audio categories.

**Comment by seanvree** [comment]
@theotherp , unfortunately not, there is no setting for that.
