### ISSUE TITLE
Old search results are added as new ones

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#355]
In the process of trying to improve the speed of saving search results to the database I introduced a bug where search results are always added as new results. That explains why the database access is so fast again... But that also means that every new search claims to have new results with new GUIDs. 

Thanks to David G. for the bug report.

**Comment by theotherp** [comment]
I kinda regret introducing the whole database thing...

**Comment by theotherp** [comment]
Yeah, this is embarrassing... The database indexes were never created. 

![Picard](http://i.imgur.com/iWKad22.jpg)

**Comment by albino1** [comment]
No wonder it was so fast :)

**Comment by theotherp** [comment]
Conversely, no wonder it was slow before...

Am 28.08.2016 10:33 vorm. schrieb "albino1" <notifications@github.com>:
