### ISSUE TITLE
Add ebook category

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#36]
If properly supported by newznab. Perhaps use "pdf","epub", "mobi", "ebook" as suffix in raw indexers.

**Comment by albino1** [comment]
FWIW, in Newznab the ebooks category is `7020`.

**Comment by Mirabis** [comment]
The regexes used in PyNab might be useful for ur search suggestion functions:
https://github.com/Murodese/pynab/search?utf8=%E2%9C%93&q=ebook

**Comment by theotherp** [comment]
nzbs.org uses 4050 which is usually PC games.

I would probably do a search in "all" with mobi, pdf and epub as suffixes. A quick test shows that most newznab indexers should support OR based queries with the API like "q=ebooktitle+epub|mobi|ebook|pdf" which would save accesses. I would probably do a search in all categories and use OR or multiple searches for raw indexers where possible.
