### ISSUE TITLE
RFE: use POST instead of GET.

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#363]
sometimes I have a tab open with nzbhydra, and if I kill and restart firefox (as one has to do somewhat regularly) then when I reselect that tab, because of using http GET, it redoes the previous search, instead of letting go ahead and search for something else without a wait.

certainly not a must have, but i think it might be a nice touch.

**Comment by theotherp** [comment]
I like it this way because you can bookmark and share search URLs.

By the way, I never have to kill my firefox...
