### ISSUE TITLE
Indexer statuses box doesn't remember state

### ISSUE THREAD

**Issue by diamaunt** [theotherp/nzbhydra#365]
version 0.2.147 and for a while now.
I noticed that the indexer statuses box is always coming up expanded on searches, instead of minimized.  
would prefer it be minimized.

**Comment by theotherp** [comment]
It should remember the last state but that's buggy. I noticed a couple of weeks but was too lazy to fix it...

**Comment by albino1** [comment]
Yeah, sometimes I get into a loop where I can't get it to stay closed after opening.  Eventually it seems to solve itself, though I have no idea how.
