### ISSUE TITLE
Development pause

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#368]
Part of my appartment building has burned downed and I won't have power for an indeterminate time. As development is kinda hard to do without a running computer I won't be able to do any updates for who knows how long. Could be days, could be weeks. I will still try to provide support.

**Comment by albino1** [comment]
Wow, that's awful.  Sorry to hear that.

**Comment by theotherp** [comment]
Thanks guys, it was less dramatic than it seemed at first. I was kinda lucky and could move back in on monday. Since yesterday I even have power and hot water, yay! No damages to my apartment or its contents. On the plus side, my neighbors were less lucky and haven't moved yet in, so now I can turn my music up :-D
