### ISSUE TITLE
Allow manual upload/install of previously created backups.  Save list of previous backups somewhere.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#374]
I would like to request the ability to upload the previously made backups to the server and have them "install".   

Additionally perhaps the previously made backups could be stored in either the settings or the database so when you restore one it still lists the previous ones made?  As it is I manually restored a backup and my "previous backups" screen is now blank.

**Comment by theotherp** [comment]
Hydra just lists all the found backup files. It would probably be possible to store their names to the database but if the files aren't available anymore why would you want to have them listed?

I already considered with an option to upload backups but never got around to implementing it. I'll give it a try when I have time but currently I'm too swamped to start developing any new features.

**Comment by famewolf** [comment]
Define "found".  I had to restore my settings and database because trying to pull in the develop branch hosed things....now my "previous backups" shows blank even through I have 2 stored locally.

**Comment by theotherp** [comment]
Perhaps it's not as stable as it could be ;-)

**Comment by famewolf** [comment]
Did you get the restore working on windows?  I thought I saw something saying that was still broken?

**Comment by theotherp** [comment]
Yeah, I thought I had. I just tested it and it doesn't work. WTH.

**Comment by theotherp** [comment]
Yes, works.
