### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by schumi2004** [theotherp/nzbhydra#377]
I played a bit with a local dns server on my nas but reverted back to isp dns servers but now nzbhydra seems to have issues resolving things. 

I already rebooted router and nas, dns settings are good but still nzbhydra fails. 
Is there a file/dir I can clear to have resolving fixed?

**Comment by theotherp** [comment]
No idea. You might need to flush the DNS cache on your NAS.

**Comment by schumi2004** [comment]
If I remove database then I need to start from scratch right? 
I'm going to give that an attempt since fetching search categories from indexes works fine except search release isn't.

**Comment by theotherp** [comment]
That would make no sense, but no, you only lose your stats. All the settings are saved in settings.cfg (catchy file name).

**Comment by theotherp** [comment]
I'm gonna close this, this has nothing to do with hydra.
