### ISSUE TITLE
Fix stats for Womble / Rework search results shares

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#378]
Doesn't show any results shares.

Possibly also rework the whole calculation of search results shares as it's pretty pointless currently.

**Comment by albino1** [comment]
I literally have no idea how to even interpret the shared results stats or what it's even supposed to mean.  Is it good to share results or bad?  Does it mean how often it has the same results as other indexers?  Is lower better, because that means more unique results?  Or is that skewed by indexers that constantly return junk that doesn't match your search query?

**Comment by theotherp** [comment]
qed ;-)

When you do a search which then searches two indexers which return 75 and 25 results, respectively, the first has a result share of 75% and the second of 25%. It was supposed to give an impression on how big the index of a certain indexer is. Unfortunately the numbers get diluted mainly by update queries, i.e. searches without a particular query (as sonarr does it to check newest releases in a certain category). Each API search result returns a "total" number of results. Some indexers return the actual number of results here, some return something like 100 (always) and some return something like 12000. At that point the numbers become useless.

I'm thinking about adding two new stats:

- Of all processed results (which are stored in the database and were either shown on screen or returned for an API query) calculate how many were return by each indexer. So if indexers A and B return a "total" of 300 results their share will be 50% each. If they return 75 and 25 results their share will be 75% and 25%. It's not perfect but should provide better insight. If possible I might also only include results from actual queries because usually you wanna know if one indexer is better for searching than the other. Having 100 results in a given category isn't hard.

- This might be tricky but if possible I want to calculate the number of unique results for each indexer and search. Or something like that. This will be probably be really high for all the raw search engines but I can filter them out.

Will do some experiments to see what works,

**Comment by theotherp** [comment]
Hah, turns out I already only include searches with specific query or ID. That's why Womble doesn't show any stats, it only supports query-less requests.

**Comment by theotherp** [comment]
Well, this kinda got out of hand but now we got [fancy graphs](http://i.imgur.com/Xc6URSc.png).

**Comment by albino1** [comment]
Haha, looks amazing!

**Comment by albino1** [comment]
FWIW, I noticed that the hour of the day stats aren't localized.  I'm not using the API, I only use the GUI, and the peak of my listed downloads is shown as 5am local time, during which I'm almost certainly asleep and not downloading anything :)

**Comment by theotherp** [comment]
One day I'll implement a function related to datetime and think of that stuff.

**Comment by albino1** [comment]
Yeah, no biggie.  Things like hourly stats are just a bonus anyway, I doubt anybody cares other than as a curiosity :)
