### ISSUE TITLE
Fix Graphical Stat issues

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#379]
The recent graphical stats look great other than some cosmetic issues.

They are as follows:  

Avg. response times:  the first two characters of "usenet-crawler.com" are truncated off the screen.  
Average results  and average unique results:  the last two characters of the last indexer are truncated off 
the screen.

Suggested solution:  Use a more condensed font like Roboto or smaller font size.  Remove .com, .org etc from filenames.

NZB downloads per indexer:  Names like "usernet-crawlet.com" and "drunkenslug.com" go completely out of the pie chart.  Names are hard to read especially for smaller pie slices.

Suggestions to resolve these issues:  remove all the .com, .org etc extensions and just go with root name.  Change the font of text to white like the other charts instead of black.   Add a number to each indexers listed above and use either only the number or include it.  This will help identify indexers that have similar colors and are to small to read the names due to being on top of each other.

Searches per day of week and NZB downloads per day of week:
"Days of the week" has no space between it and "Wednesday".

Suggested solution:  Change the days of the week to "Mon, Tue, Wed, Thu, Fri, Sat, Sun

**Comment by theotherp** [comment]
I changed the day names to short names.

But as there's no limit to the length of indexer names changing the font wouldn't be a solution. I can shorten the names as you described, but they could be still too long.

Thanks for the feedback, but I won't waste much more time on this. I was just curious to see if I could add charts and thought it looked cool. I'd rather spend time on other features.
