### ISSUE TITLE
Request: SABConnect++ chrome extension compatibility

### ISSUE THREAD

**Issue by phit42** [theotherp/nzbhydra#380]
Would it be possible to represent the search results in such a way that the chrome extension SABConnect++ recognizes the nzb's and provides 1-click downloading for them, just like it does for so many newznab providers?

**Comment by theotherp** [comment]
Why do I even add that template if nobody uses it... You don't have to follow it word by word but... 

Anyway, I'm not sure what requirements must be met for the extension to work. It could be that my NZB links don't end with ".nzb". I'll add that and if it works, alright. If it doesn't then you'll need to find out what would need to be done on my part for it to work.

**Comment by theotherp** [comment]
Ok, doesn't work out of the box. You'll need to ask the extension developer what to do here.

But why don't you just configure sab in hydra?

**Comment by phit42** [comment]
Primarily because I didn't get sab with hydra to work (stuck in "trying to retrieve nzb from ...", and use sabconnect++ anywhere else w/ nzb's. 
I will ask the extension developer.

Template?

**Comment by theotherp** [comment]
Template: The text that was put in the comment field above that you had to delete before you could enter your request.
