### ISSUE TITLE
Add feature to check commit status and self update similar to CP, headphones etc.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#385]
All the apps I use have checks that alert you when new commits have become available and give you the option to update from within the app.   This code is present in headphones, lazylibrarian, sabnzbd, couch potato (python based like nzbhydra), sickrage etc.

Please add a similar feature as an enhancement as time allows.

![commit](https://cloud.githubusercontent.com/assets/4558832/19281620/10bdbe6a-8fb9-11e6-8dbe-437eec32515c.png)

**Comment by theotherp** [comment]
Already implemented.

**Comment by famewolf** [comment]
Is it specific to the master branch only or can you update within develop as well?  I have a "recipe" running on zapier.com that tells me when commits get applies to the develop branch so I can know when to update.

**Comment by theotherp** [comment]
That's what the "branch" setting in the config is for. I strongly recommend you to not use the debug branch. I told you to check it out to test the fix to the database problem. The develop branch has often broken code which is not for the public and buggy (even more than the master branch). Check the master branch in your recipe, usually every commit to the master branch is a bump in the version which triggers the upload dialog.

**Comment by theotherp** [comment]
I mean, you can use the develop branch and give feedback, you're welcome to, but don't expect stable code. When you do an update and start hydra and your hard drive explodes it's not my fault, you were warned... ;-)

**Comment by famewolf** [comment]
I plan to go back to master when you push the new release but the last
commit to master was august 29th and you've fixed ALOT of stuff since then.

**Comment by theotherp** [comment]
Usually I do rather small updates and push to master whenever a bug or feature is complete. Because I changed to much in critical areas I wanted to be sure not o make things worse.
