### ISSUE TITLE
Config>Searching>Result Processing>Remove API Duplicates - Toggle Halfway On and Off

### ISSUE THREAD

**Issue by terrelsa13** [theotherp/nzbhydra#386]
Release notes indicate this option was removed. I assume the UI just needs to be updated to not show this toggle.

> Changed: Removed option that decided if duplicates should be removed for API calls, this is now always enabled.

* What do you expect to happen?

-Remove API Duplicates - toggle to be hidden. Or...

-Remove API Duplicates - toggle always On.

* What does happen? 

-Remove API Duplicates - toggle shows half On and Off

* Have you searched for this problem? 

-Yes.

* Can the problem be reproduced?

-Yes

* How can the problem be reproduced

-1a:Updated to version 0.2.148 using the GUI

-1b:Started via command line `sudo service nzbhydra start`

-1c:After starting hydra via the cmd line Remove API Duplicates - toggle halfway On and Off

-2a:Restart via GUI

-2b:After restarting hydra via the GUI Remove API Duplicates - toggle halfway On and Off

-3a:Restarted via command line `sudo service nzbhydra restart`

-3b:After restarting hydra via the cmd line Remove API Duplicates - toggle halfway On and Off

-4a:Turn Off/On linux machine

-4b:After restarting linux machine GUI Remove API Duplicates - toggle halfway On and Of

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

-Done.

-Log.
[nzbhydra-debuginfo-2016-10-11-20-34.zip](https://github.com/theotherp/nzbhydra/files/523311/nzbhydra-debuginfo-2016-10-11-20-34.zip)

-Screenshot.
![screenshot from 2016-10-11 20 12 39](https://cloud.githubusercontent.com/assets/16886488/19294436/448bf278-8ff2-11e6-8738-2d85bb449a31.png)

**Comment by theotherp** [comment]
Thanks for the detailed description. Is fixed in next version.

**Comment by terrelsa13** [comment]
Np! Thank you for these new awesome charts and graphs in the version 0.2.149. Really makes reading the data more fun!
