### ISSUE TITLE
`sudo service nzbhydra restart` has to be run twice to "restart"

### ISSUE THREAD

**Issue by terrelsa13** [theotherp/nzbhydra#387]
- What does happen? 

-When reporting [issue#386](https://github.com/theotherp/nzbhydra/issues/386) I noticed the first time I run the `sudo service nzbhydra restart` command it only stops hydra. Running it a second time actually restarts hydra.
- What do you expect to happen?

-Running `sudo service nzbhydra restart` once stops and then starts hydra
- Have you searched for this problem? 

-Yes.
- Can the problem be reproduced?

-Yes.
- How is the problem reproduced?

-On Linux Mint 17.3 run command `sudo service nzbhydra restart`. Notice hydra is only stopped.

-Run `sudo service nzbhydra restart` a 2nd time. Notice hydra is started.
- Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.

-Done.

-Log.
[nzbhydra-debuginfo-2016-10-11-20-47.zip](https://github.com/theotherp/nzbhydra/files/523339/nzbhydra-debuginfo-2016-10-11-20-47.zip)

-Screenshot.
![screenshot from 2016-10-11 20 26 50](https://cloud.githubusercontent.com/assets/16886488/19294640/0ec66360-8ff4-11e6-87de-6b57d70df48d.png)

**Comment by theotherp** [comment]
I didn't write the script so I can't help you with that. Hopefully somebody else here has an idea.

**Comment by terrelsa13** [comment]
Nbd, hopefully this will help clear up any confusion for someone in the future expecting to only have to run it once.

I'll just keep in mind to explicitly use `sudo service nzbhydra stop` followed by `sudo service nzbhydra start`
