### ISSUE TITLE
Why do I have a lot of blank query entries in history?

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#388]
[nzbhydra-debuginfo-2016-10-12-14-24.zip](https://github.com/theotherp/nzbhydra/files/525338/nzbhydra-debuginfo-2016-10-12-14-24.zip)
In browsing the history I notice line after line showing no search terms.  Is this normal?  Is it bumping up the # of times the api is hit on my indexers?  Some only allow a fixed number per day.

![nzbhydra](https://cloud.githubusercontent.com/assets/4558832/19322381/c82176be-9086-11e6-8ebf-2eb82c6c11f2.png)

**Comment by theotherp** [comment]
Those are update queries by your automation tools looking for the latest releases.

**Comment by famewolf** [comment]
Thank you.  Shouldn't it show something such as the show title..or season or episode?  Many do..just confused by the api hits that show no information at all.

**Comment by theotherp** [comment]
There is no title or season or episode to show.

**Comment by famewolf** [comment]
I updated to your latest commit this morning and just physically went to the local file and verified that the line to assign "Update Query" was present yet I'm still seeing blank lines.  See screenshot.  I note one example from the log:

2016-10-13 05:34:43,109 - INFO - web - Thread-1069 - API search request: SearchRequest [ type "ebook", title "The Ministry of Necessity", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ]

That query shows BLANK in the attached screenshot.
![nzbhydra1](https://cloud.githubusercontent.com/assets/4558832/19348856/fa7cae0c-911d-11e6-9777-2d8064b06c93.png)
[nzbhydra-debuginfo-2016-10-13-08-17.zip](https://github.com/theotherp/nzbhydra/files/527038/nzbhydra-debuginfo-2016-10-13-08-17.zip)

**Comment by famewolf** [comment]
@theotherp  Did you see this is still a valid, non update query problem?

**Comment by theotherp** [comment]
YEEEES. ffs, I get an email for every new issue and comment. Just because I don't respond doesn't mean I didn't read it.

**Comment by famewolf** [comment]
Well I didn't know if you still got it once the issue had been CLOSED.  *shrug*  I was gonna re-open a new one if you preferred.

**Comment by theotherp** [comment]
This isn't even an issue, there ARE NO VALUES TO SHOW. It's blank because there isn't anything. I just added it because .... argh forget it, I will try to fix it when I can.

**Comment by famewolf** [comment]
I pasted an example. It has a TITLE.  "The Ministry of Necessity"  That title is showing BLANK.  How is that not an issue?  It's NOT an update query.

**Comment by theotherp** [comment]
Sorry having a bad day. Will take a look whenever.

**Comment by theotherp** [comment]
Title is not a value that is stored for the search value so I can not display it.

**Comment by famewolf** [comment]
When you have music you have Artist and Album Name.  When you have Ebook's you have Author and Book Title.   Can it not be mapped to whatever field is being displayed if that field is blank?   I'm just thinking for the general public it's going to make a lot more sense than a bunch of blank lines.   If it can't be mapped then perhaps an option to supress blank lines would help.

In any case thanks for looking at it.

**Comment by famewolf** [comment]
I'm still confused.  Here's the same list of books except here it's author AND title including a couple of variations on "The Ministry of Necessity"...and both show up fine...but when it's JUST title you are saying you can't save it?  How are you saving it when author is with it?

![nzbhydra2](https://cloud.githubusercontent.com/assets/4558832/19406248/a02ae804-9250-11e6-8057-bb3846a226bf.png)

**Comment by theotherp** [comment]
Can't say but I guess the title is converted to a query?

When starting to develop Hydra I didn't think of tools like LL, Mylar and Headphones because they're rarely used and Usenet sucks for books and audio anyway. Also I buy my books and use Spotify so I may have made the typical mistake of assuming all users were like me.

Later on I added ebook support but never really tested it or cared about (and neither seem many others). Looking at the code it seems that in some scenarios where the indexer does not support ebook search then a query is built using the author and the title. In those cases that query is what you see in the stats. 

I may extend the database to properly include title and author and reflect that in the history. Personally I think it's not worth the work and I don't care about the history but after including it I might as well make it complete.

**Comment by famewolf** [comment]
I initially started only with couchpotato and sickrage (freenas has to run alot more to run mono and sonarr is inherently more unstable but I like the interface ALOT more) but I eventually dabled in headphones because once it scans your music library, something I already had, it would automatically download new albums by artists you already own....additionally it would give you options to try and grab lossless copies of music you only had mp3's of.........that led me to lazylibrarian where I give it a list of authors I like or series within an author..and it auto grabs their new books, drops it into a folder that gets auto synced with my kindle via email...   It just became really convenient.  I do however also see blank entries for "TV HD" so it seems to be beyond just LL and Headphones.  I don't use mylar so can't speak for it.

**Comment by theotherp** [comment]
I forgot to commit the changes in the HTML. Fixed in fde18589b6bb43a640fe079e43f122e68a70e586

**Comment by theotherp** [comment]
See #396
