### ISSUE TITLE
Add own category?

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#390]
When I look at config/categories I see predefined categories. Is it possible to add my own category?

Ie: I use 'tv sickrage' for all my tv-downloads, and I don't really want to change this.

This is off course a nice to have. ;-)

Btw: maybe I misunderstood, but I want to use those categories so SABnzbd will recognize the download

**Comment by theotherp** [comment]
Allowing to add custom categories would be really complicated, I think. Still not sure I understand why you need them. Perhaps you could describe in more detail what you want to happen and why.

**Comment by famewolf** [comment]
@pven   Just about all the clients pass a category to sabnzbd when they submit a download.  Lazylibrarian sends "ebook", headphones sends "music", couchpotato sends "movie" or you can change those to whatever you want.   THOSE are the categories sabnzbd will see and sort.  By default "ebook", "movie", "tv", "music" and other people add categories like porn or xxx etc...when you manually submit a nzb to sabnzbd via nzbhydra that's where it's getting it's list from.   When you go into sickrage if you go to settings, search settings, nzb search you can change the default category from "tv" to "tv-sickrage" if that's what you want to use and it will get passed to sabnzbd that way.

The "categories" in nzbhydra are to map newsnab category codes to a "generic category name" within nzbhydra where you can apply size qualifications.  For example if you are downloading an ebook  and it's 4GB something is more than likely wrong...nzbhydra won't download ebooks larger than 100mb by default although this can be changed.  It's easier to remember "ebook" then it is newsnab categories 7020 and 8010. 

![ebook](https://cloud.githubusercontent.com/assets/4558832/19391811/213f7fe0-91fc-11e6-83c9-7d3723a95996.png)

**Comment by theotherp** [comment]
Trying to add a thumbs up but can't with my android app it seems.

**Comment by pven** [comment]
Thanks for the answers!

Too bad it is not possible in NZBhydra itself. But when I try to use SABnzbd for it (config / categories / groups/index tags) I am not able to remap anything. What can I fill in so SABnzbd is able to match it?

**Comment by famewolf** [comment]
https://sabnzbd.org/wiki/configuration/1.1/categories

For more info you'll need to post your questions on the sabnzbd forum.

**Comment by pven** [comment]
Thanks!
