### ISSUE TITLE
Add Rss reading support for nzb's from sites like NZB-RSS.com.

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#391]
There are several sites apparently where you can get fed an rss feed of the latest available nzb's...one example is NZB-RSS.com.    Both lazylibrarian and headphones have rss reading built in so the logic may be easy to snag.

*enhancement*

**Comment by theotherp** [comment]
I can only add those of which I know. So add any that you can find.

**Comment by famewolf** [comment]
Rss is pretty well defined...why not parse it in a generic manner and let the user add entries of the actual urls similar to how you do with indexers?

For example from LazyLibrarian:

![ll1](https://cloud.githubusercontent.com/assets/4558832/19445901/47063f2e-9464-11e6-9618-f6b3c7fcc62e.png)

**Comment by famewolf** [comment]
I saw one of the requests was for nzbking..not sure if it has rss...doesn't look like it on first glance.

**Comment by theotherp** [comment]
That site doesn't seem to provide any general RSS but instead for shows and series. How would that make sense to be integrated into Hydra?

**Comment by famewolf** [comment]
When doing searches on tv and movie you can't use https://www.nzb-rss.com/latest ?

**Comment by theotherp** [comment]
I don't think it would make sense to use the latest 30 or so releases for a specific query, how likely is it that the searched stuff is in there? Without any categories I wouldn't even be able to use it for update queries.

Womble kinda works that way and I use it for TV update queries and a lot of my downloads come from there, so there's a place for indexers like that, but I just don't see it here.
