### ISSUE TITLE
Make periodic backups in the background

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#394]
Hydra doesn't have background tasks (yet) but the backup could be done when a search is executed, it would only take a couple of seconds and be done perhaps once a week.

**Comment by famewolf** [comment]
You might consider an auto backup right before applying a commit/update so if it trashes the database or something similar they can recover when it's fixed(we know this happened recently with one commit when the database was upgraded)..or if the app had a "rollback" feature for failed commits they could do that.

**Comment by theotherp** [comment]
That's already supposed to happen ;-)

Am 21.10.2016 05:46 schrieb "famewolf" <notifications@github.com>:

**Comment by theotherp** [comment]
Implemented in v2 which will be released soon.
