### ISSUE TITLE
trouble with macOS Sierra with versions after 0.2.147

### ISSUE THREAD

**Issue by Alrescha-git** [theotherp/nzbhydra#398]
I'm not sure what OSes are expected to work, so this might be just an FYI, but previous versions of hydra worked fine in Sierra (python v2.7.10) by downloading, unzipping, and running nzbhydra.py in Terminal.  This worked up to and including 0.2.147.

Releases after that work for a query or three, then fail with various problems.  I have seen:

"the database is malformed"
"file is encrypted or not a database"

as well as python blowing up with various exceptions.  All the other log messages would indicate things working normally up to the point of failure.  I have tried upgrading by using the internal updater, updating by unzipping on top of the existing installation, upgrading by restoring a backup, and finally a completely clean install just using the included indexers.  No joy.

If I go back to 0.2.147, everything is fine.

**Comment by theotherp** [comment]
Please try and update your sqlite3. No idea how this is done on mac but my windows DLL was severely outdated.

**Comment by theotherp** [comment]
By the way, please try with 0.2.151, I added a fix in that or the version before that which hopefully fixed some part of the database migration.

**Comment by Alrescha-git** [comment]
Thanks for the reply.  I was using sqlite3 v3.14.1, so I also tried the version included with macOS (v3.14.0) and your latest 0.2.151.  No change.  There was a unicode decode error logged from web.py for the next to last query (with error 500 to the browser), and the last query resulted in 'file is encrypted or not a database'.

The latest sqlite that I see mentioned is .2, so I will try to hunt that down.

**Comment by theotherp** [comment]
No, I don't think that would help.

Would you be willing to send me your database file? I can check if the schema is correct and if not add a fix to the code to prevent this happens to others or fixes it for them.

**Comment by Alrescha-git** [comment]
This happens with a clean install of the software, no configuration, no previous database.  Three or four queries and it's toast.  You are welcome to any part of the corpse if it is useful to you.

**Comment by Alrescha-git** [comment]
As you predicted, no improvement with sqlite3 version 3.15.0.

**Comment by theotherp** [comment]
Please send me your nzbhydra.db via mail.

**Comment by theotherp** [comment]
May take a couple of days, sorry.

**Comment by Alrescha-git** [comment]
No worries.  I'm perfectly fine with 0.2.147.  Let me know if you need any more tests or files.

**Comment by theotherp** [comment]
No idea why that's happening. I cannot reproduce it on any system. I also didn't find out what exactly why your db is corrupted. I changed a bit of code in 0.2.153 but don't really expect it to help. Will do some mor research on the weekend.

**Comment by Alrescha-git** [comment]
At the risk of being premature, that seems to have fixed it.

I tested with a clean install and could not get it to fail in ~10 searches.  I then cleaned/reinstalled and copied in my db and settings.  No failures yet, thank you.

**Comment by theotherp** [comment]
Whadaya know. I'll take it ;-)
