### ISSUE TITLE
Feature to minimize to tray in windows

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#40]
Not sure if possible in pure python or packaging as an exe would be needed. That would complicate things.

**Comment by Corrupta** [comment]
I would also like to hide the console, completely if possible like you can with mega

**Comment by theotherp** [comment]
Until then just rename nzbhydra.py to nzbhydra.pw and open it with pythonw.exe. Every other solution requires me to build it and publish it and considering how often I currently release new alphas it would be too much overhead. Will do it when it's more stable.

**Comment by Corrupta** [comment]
cool i'll try the work around

**Comment by albino1** [comment]
You can also start it as a service in Windows, which is what I do.  Then it's always running in the background and I can just access it from my browser when I want to use it.  See the section called "Create NZBMegaSearch Windows System Service" in this tutorial for the basic idea:

http://www.htpcguides.com/install-nzbmegasearch-windows-from-source/

**Comment by Corrupta** [comment]
albino that's what i ended up doing and it's running well

**Comment by albino1** [comment]
Yeah, it's a good solution.  Ideally though once NZBHydra is out of beta it would be nice to have a full fledged Windows version to help gain traction and support.  NZBM had that, but it never got updated and became worthless, which is why that tutorial above even exists in the first place.

@theotherp, when you feel comfortable that it's pretty much working as you want then you should get @blindpet involved again to make a tutorial explaining how to install and use NZBHydra.

**Comment by blindpet** [comment]
I will definitely be making a guide for this over the weekend. If you provide a donation link I'll send you some money to get a logo and some css from fiverr.com. You can PM me on reddit to exchange details.

**Comment by TBhimdi** [comment]
Instead of calling "python.exe", call "pythonw.exe" (should be in the same directory as your python.exe). No renaming required or Windows service and no console pop-up. Works great here.

**Comment by TBhimdi** [comment]
Looks like "pythonw.exe" isn't going to work anymore. I believe it's because a recent commit to "log.py" added "sys.stdout" and is causing "pythonw.exe" to fail. More info here:

http://stackoverflow.com/questions/24835155/pyw-and-pythonw-does-not-run-under-windows-7

**Comment by theotherp** [comment]
There are just too many ways for me to break anything ;-)

Please try with the latest changes, it should only use console logging when not being run with pythonw.exe. Thanks for the hint.

**Comment by TBhimdi** [comment]
Thanks for the very quick fix! Works perfectly again.

**Comment by theotherp** [comment]
Expect this to be implemented in the first beta (ETA unknown). It all works, I'm just not yet ready to release an actual build.

**Comment by theotherp** [comment]
Implemented in windows releases. Stay tuned.

**Comment by blindpet** [comment]
@theotherp posted guides for Windows for you to add to Wiki http://www.htpcguides.com/install-nzbhydra-windows-for-universal-usenet-searching/

Ubuntu too http://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/
