### ISSUE TITLE
Errors When Updating, Failed to Automatically Restart

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#400]
* What do you expect to happen? What does happen? 

Expected a normal Update followed by Restart, but the restart failed.  Killing the process and restarting it manually allowed Hydra to become accessible again.  It says it's currently updated to 0.2.152, so it appears it was eventually successful.

* Can the problem be reproduced? How?

I don't think so, not without replacing NZBH from backups and then trying again.

* Describe the problem succinctly, don't just copy and paste the error message.

There were several errors.  I was running from the command line, and updating remotely by clicking the button at the bottom of the index page.  First, here's the Bug Report log file:

[nzbhydra-debuginfo-2016-10-18-15-23.zip](https://github.com/theotherp/nzbhydra/files/537505/nzbhydra-debuginfo-2016-10-18-15-23.zip)

And then there looks like some additional information from the command line:

[nzbhydra-command-line-errors.txt](https://github.com/theotherp/nzbhydra/files/537500/nzbhydra-command-line-errors.txt)

The highlights being:

`Exception: Error, database not properly initialized before opening connection`

`ResultTimeout: results not ready, timed out.`

**Comment by theotherp** [comment]
I don't know. This whole database shit sucks. No idea why I ever thought it would be a good idea to use that.

**Comment by albino1** [comment]
Hah, I feel ya.  Well, it might just have been me, there's been no other posts about it, so maybe I'll just close this and you can cross your fingers :)
