### ISSUE TITLE
API not sending correct URL to download NZBs using reverse proxy.

### ISSUE THREAD

**Issue by Doonga** [theotherp/nzbhydra#403]
## How to do a bug report

* What do you expect to happen? What does happen? 
My server is available on https://nzbhydra.hostname.com/. I use a reverse proxy, even internally so that I don't have port numbers all over the place. The URLs that are being returned from the API contain invalid links, not sure if I have something set wrong or if there's an actual issue here. Here's a sample from the API

```
<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>NZB Hydra</title>
<description>NZB Hydra - the meta search</description>
<link>https://github.com/theotherp/nzbhydra</link>
<language>en-gb</language>
<webMaster>TheOtherP@gmx.de (TheOtherP)</webMaster>
<newznab:response offset="0" total="26"/>
<item>
<title>Some title.</title>
<guid isPermaLink="false">nzbhydrasearchresult2884</guid>
<link>
http://nzbhydra.hostname.com:5075/getnzb?apikey=XXX&searchresultid=2884
</link>

```
The value in the link field is incorrect, it should be https://nzbhydra.hostname.com/. I did set the external hostname field in the UI but that didn't seem to help.

* Have you searched for this problem? 
Yes, searched for "api link" "api url" no luck.

* Can the problem be reproduced? How?
Hit the API with a search and look at the results, I can give you access to my server if needed.

* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
Hopefully the title is clear, it's probably a corner case.

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**
Attached.
[nzbhydra-debuginfo-2016-10-21-15-57.zip](https://github.com/theotherp/nzbhydra/files/545101/nzbhydra-debuginfo-2016-10-21-15-57.zip)

The more information you provide up front the higher the chance that I can help you.

If you need any other information please let me know and I'll do my best to help.

**Comment by theotherp** [comment]
Set "Use local address in API results" to "false" in the main settings.

**Comment by theotherp** [comment]
I should probably switch that logic and rename it to "Use external URL in API results".

**Comment by Doonga** [comment]
Oops! I skimmed right over that option. Thanks
