### ISSUE TITLE
RSS support request

### ISSUE THREAD

**Issue by leram84** [theotherp/nzbhydra#405]
I have a list of items that i think will be released one day, so i keep checking back every few days to see if hydra finds it. It would be really cool if there was a way to get an rss feed for a query. You do a search, and then hit the rss button, and it gives you a link for that search. So whenever anything new gets added, it will show in your feed. Im not sure if there's a more intelligent way to do this, but a dumb method would be to have hydra perform that same search once a day and add anything with a 0d age to the feed. 

Is this possible?

**Comment by theotherp** [comment]
You can use any API call as RSS query, e.g. http://127.0.0.1:5075/api?apikey=YOURAPIKEY&t=search&q=newstuff

But of course that will mean that for every refresh a search is executed, so you should reduce the refresh interval in your RSS reader.

**Comment by leram84** [comment]
sorry, im not quite following. How do i generate an api call? If i want to get a feed url for an rss reader how would i get that url from hydra?

**Comment by theotherp** [comment]
I just told you. Call that URL above but insert your API key and what you want to search. But it will only allow to search for one thing at a time, so you'll need a new URL for every release you're waiting for.

**Comment by judhat2** [comment]
> How do i generate an api call? If i want to get a feed url for an rss reader how would i get that url from hydra?

Check out https://newznab.readthedocs.io/en/latest/misc/api/#search.
NZBhydra accepts most of those commands.

**Comment by theotherp** [comment]
Examples:

http://127.0.0.1:5075/api?apikey=YOURAPIKEY&t=search&q=Finding+Doozy+1080p+Bluray
http://127.0.0.1:5075/api?apikey=YOURAPIKEY&t=search&q=Watch+Cats+2+CPY
etc.
