### ISSUE TITLE
OMG address change

### ISSUE THREAD

**Issue by Servrpro** [theotherp/nzbhydra#408]
omgwtfnzbs is under new management. They have changed the domain name from omgwtfnzbs.org to omgwtfnzbs.me, in a month .org will cease.  I would believe the preset for OMG in NZBHydra will not function.

**Comment by albino1** [comment]
FYI the address has been updated, but the "name" in NZBHydra is still .org instead of .me both on the Indexer Config page and on the main Search page.  Here's an example:

https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/config.py#L678

**Comment by theotherp** [comment]
As @albino1 said it's already in there and working. I've added coded to properly rename it to prevent misconceptions.
