### ISSUE TITLE
Cardigann issue with size element

### ISSUE THREAD

**Issue by manderss99** [theotherp/nzbhydra#410]
Thanks for implementing this. I have tested on several indexers and it seems fine except
for the size column. For all indexers it displays as 'NaN'.
The size is present in the feed from cardigan:

      <torznab:attr name="size" value="849700000"></torznab:attr>

I am testing using the hydra web ui.

**Comment by theotherp** [comment]
Huh, worked for me.

**Comment by theotherp** [comment]
You're right, fixed now.
