### ISSUE TITLE
maxage attribute isn't respected via an api call

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#412]
* What do you expect to happen? What does happen? 

If I use nzbget's rss feature and use the url `http://192.168.1.105/api?apikey=xxxx&t=search&cat=5000&limit=100&q=ufc+720p&maxage=2`, then I expect to only revieve results younger than 2 days. However, all results are returned. In the log `u'maxage': 2` is, however, listed in the api details.

* Can the problem be reproduced? How?

I can put the url in my browser and reproduce it.

* Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section]

[logfile.txt](https://github.com/theotherp/nzbhydra/files/556384/logfile.txt)

Testing this out, I noticed something about the maxage attribute.  If I do a query search, then `&maxage=2` is added to the indexer search url that is sent to the indexer. However, if I do a search in the TV or movie category, the maxage is not added to the search url.  Perhaps, if it's added to the search url, then it could remove some work that nzbhydra has to do. I could open another issue for this if you prefer.

**Comment by judhat2** [comment]
Thanks, that seemed to have fixed it.

**Comment by theotherp** [comment]
I hope so ;-)
