### ISSUE TITLE
Replace omgwtf specific implementation with newznab

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#416]
Do some tests and when all is working fine:
- remove old implementation (back- and frontend)
- add preset for newznab
- add migration for settings and history & stats

**Comment by theotherp** [comment]
Big props to their staff, the server is much faster than the old one, they're actively working on the newznab endpoint and support me as a developer.

**Comment by judhat2** [comment]
I saw that every nzb has the same poster. Will that affect finding duplicates?
`<newznab:attr name="poster" value="omgwtfnzbs"/>`

**Comment by theotherp** [comment]
Hm, that might be a bug on their side. It certainly makes no sense to include it.

It's not worse than no providing the poster, results from the same indexer are never considered duplicates, but of course it would be better to actually include the poster, provided they store that in their database.

**Comment by judhat2** [comment]
Yeah, maybe they can fix it in their api. I am not sure how Hydra what priority the poster's name has when it tries to detect duplicates from multiple indexers.  Just wondering if it would cause omgwtfnzbs to have 100% unique results.

**Comment by theotherp** [comment]
They provide the group. Combined with size and age that's usually enough, a couple of false negatives here or there, but not too many.

**Comment by judhat2** [comment]
Ah, ok.

**Comment by theotherp** [comment]
@judhat2 Attribute was removed.
