### ISSUE TITLE
Provide more info how many results where rejected and why

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#417]
When a search result is rejected store the reason and count each rejection. Log accordingly and show in the search results.

**Comment by judhat2** [comment]
When you say "show in the search results", are you thinking you will give an option to show rejected releases in the browser interface, such as an option with a checkbox similar to "Include duplicates"?

**Comment by theotherp** [comment]
Hm, interesting idea. Not what I meant but could be worth it.
