### ISSUE TITLE
API / Searching broken on Windows 

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#418]
Running NZBHydra as a Service on Windows 10:

Current NZBH version: 0.2.163

Started happening after the latest update:

API calls time out (From Sonaarr)

Unable to search manually:

Logs:

http://pastebin.com/GYQ0WTHv

**Comment by judhat2** [comment]
Just updated to 0.2.164. I don't use Binsearch or NZBIndex, but I am getting this error, too.
[logfile.txt](https://github.com/theotherp/nzbhydra/files/573154/logfile.txt)

**Comment by theotherp** [comment]
Hmm...

**Comment by theotherp** [comment]
Results come in, exception comes out, can't explain that.

**Comment by judhat2** [comment]
Do you need anymore information or any more test I can do to pinpoint the problem?

**Comment by theotherp** [comment]
Thanks, but there's nothing I can think of right now.

**Comment by theotherp** [comment]
Hah, got it.

**Comment by judhat2** [comment]
Yup, that fixed it. Thanks!
