### ISSUE TITLE
NZBH won't update on Windows

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#419]
So, the latest version won't update. 

On version : 0.2.164 
Trying to update to Latest version: 0.2.165 

I'm on Windows., NZBH is running as a Service

Settings:
https://drive.google.com/file/d/0B7OujkYtbxFNd3FiUmhoYUtuTzQ/view?usp=sharing

Logs:
https://drive.google.com/file/d/0B7OujkYtbxFNYXAwckxreWNRTTQ/view?usp=sharing

**Comment by seanvree** [comment]
Humm.  I had to overwrite the local repository from the master repository and then restart the service, so I'm on the latest now, but the update function from the GUI didn't work as expected.

**Comment by theotherp** [comment]
Well the log says update went fine, so what's the problem?

Am 05.11.2016 22:21 schrieb "seanvree" <notifications@github.com>:

**Comment by seanvree** [comment]
@theotherp .... not sure buddy, I'm no noob.  It wasn't updating via the WEBGUI. 

All good, you're welcome to close if you'd like.

**Comment by Mobrockers** [comment]
I had the same issue. NZBHydra seemed to have sorta crashed in the background. Sonarr could no longer reach it and nothing at all was being written to the log. Updating was also not doing anything from the WEBGUI. Once I force ended the process and restarted NZBHydra, the log was once again being written and I could update from the WEBGUI. Sonarr can also now reach NZBHydra again.
