### ISSUE TITLE
Excluded words don't work with omgwtf

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#421]
I contacted the staff, just putting it here for information.

**Comment by judhat2** [comment]
Spotweb also does not support excluded words in the api. 

In addition, nzbgeek has a bug in which the api search will fail when the query exceeds 12 variables in either the inclusion or exclusion words.  The admin is aware, but will probably not fix it anytime soon.

**Comment by theotherp** [comment]
I had hoped I wouldn't need any more special handling for omgwtf. Oh well...

**Comment by judhat2** [comment]
I asked them about it a week or two ago, and they said adding the ability was on their to-do list but didn't have an ETA.

**Comment by theotherp** [comment]
Seems to work now using "!". Will update the code when I have time.
