### ISSUE TITLE
failed to update

### ISSUE THREAD

**Issue by aberrix** [theotherp/nzbhydra#422]
Current version: 0.2.162 
Latest version: 0.2.165 

I tried to update and it failed

log:
016-11-08 07:39:07,714 - INFO - web - Thread-1057 - Starting update
2016-11-08 07:39:14,888 - INFO - backup_debug - Thread-1057 - Successfully backed up database and settings to /opt/nzbhydra/backup/nzbhydra-backup-2016-11-08-07-39.zip
2016-11-08 07:39:16,271 - INFO - update - Thread-1057 - git output: HEAD is now at ac5126e Delete nzbhydra.log.1
2016-11-08 07:39:18,087 - INFO - update - Thread-1057 - git output: From https://github.com/theotherp/nzbhydra
 * branch            master     -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <nzbhydra@hydra.(none)>) not allowed
2016-11-08 07:39:18,089 - ERROR - update - Thread-1057 - "git" pull origin master returned : From https://github.com/theotherp/nzbhydra
 * branch            master     -> FETCH_HEAD

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <nzbhydra@hydra.(none)>) not allowed

**Comment by theotherp** [comment]
Yeah, no idea. The last person just deleted everything except settings and database, cloned again and put settings and db back.

Will do some tests.

**Comment by theotherp** [comment]
I guess this is because I deleted the file nzbhydra.log.1 but only later added it to git ignore. Sorry, no idea how to solve this, I'm not a git pro. It's probably easiest if you start again and restore your settings.

**Comment by TBhimdi** [comment]
Same issue, just re-cloned and copied over the old settings.cfg file. Everything looks good so far.

Didn't copy over the db from the old installation. Does it hold anything important and/or necessary?

**Comment by theotherp** [comment]
Your search and download history and stats. Nothing functional.

Am 09.11.2016 02:12 schrieb "TBhimdi" <notifications@github.com>:

**Comment by theotherp** [comment]
Guess it's fixed.
