### ISSUE TITLE
nZEDb shows no results anymore

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#425]
i can´t search on my nZEDb indexer anymore. nzbHydra is up to date, `Check capabilities` works and gives me an ok. I am 100% sure, that a certain release exists on the indexer. Just nzbHydra doesn´t give any result or error-message. Happens on TV-series and movies.

**Comment by theotherp** [comment]
I don't have a VIP account for any nZEDb indexer and no API hits left forday.

If you wanna help set the log settings to debug, to a search and post your debug infos (which would've been a good idea anyway).

**Comment by theotherp** [comment]
Or donate bitcoin...

**Comment by Hobbabobba** [comment]
noticed something very strange: the IP of my nZEDb-Indexer is `192.168.0.125` (internal). The log file from nzbHydra show´s that hydra is searching on `192.168.0.58`
All the config-files and GUI-settings say `192.168.0.125 `

**Comment by Hobbabobba** [comment]
ok, i tested it with another (dockerized) nzbHydra instance. Works. I think my Hydra-installation just broke down.
