### ISSUE TITLE
Please add OMGWTF indexer support

### ISSUE THREAD

**Issue by Corrupta** [theotherp/nzbhydra#43]
Please add OMGWTF indexer support

**Comment by theotherp** [comment]
I don't have an account and am not willing to donate to get one.

**Comment by Corrupta** [comment]
fair enough i think there api details are available online if you'd like for us to test it out for you, if or when you decide to try to integrate it. also mega has it so that maybe another way to integrate it

**Comment by theotherp** [comment]
Yeah I know I can find the implementation but without being able to test it myself it would be complicated. I'll look into it.

**Comment by Corrupta** [comment]
I'd be happy to do the testing for you, that's the only thing stopping me from getting rid of mega

**Comment by Corrupta** [comment]
Wow dude, I woke up this morning to this, I was thinking dude you fixed all the problems i needed fixed in like 2 days the rest of the stuff for me can wait.

I hate to say it but it doesn't work:

 2015-12-12 13:00:30,582 - INFO - omgwtf - Testing connection for omgwtfnzbs
2015-12-12 13:00:30,586 - INFO - omgwtf - Unable to connect to indexer using URL
 /api.omgwtfnzbs.org/xml?apikey=<APIKEY>&user=DEBUGTEST: Invalid URL '/api.omgwt
fnzbs.org/xml?apikey=<APIKEY>&user=DEBUGTEST': No schema supplied. Perhaps you m
eant http:///api.omgwtfnzbs.org/xml?apikey=<APIKEY>&user=DEBUGTEST?


I just changed the username for your debug but error is exactly the same with real details.

I haven't done programming in years so i can't really help you but if this info can help you:

Maybe you can save this info and I'll delete the comment

""""""""""""""""""""
These notes relate to v2.0 of our API

You should use the HTTPS GET method for sending queries to the sever. POST method is not supported.


JSON Search API
url to use:

https://api.omgwtfnzbs.org/json/?search={some search term}&user={username}&api={apikey}

variables:

* ?search=something = No terms no search!
* &user={username} = Your account username.
* &api={apikey} = Your API Key.
* &catid=1,2,3 ect = Optional, search multiple categorys.
* &retention={days} = Optional, limit the search to X amount of days ago.
* &eng=1 = Optional, return only english/unknown posts.

example api Call:

https://api.omgwtfnzbs.org/json/?search=bones.s08&user=you&api=apikeyfoundinyraccount&catid=19,20&retention=500
this would search for bones.s08 in tvsd,tvhd with a max age of 500 days.

sample output:

[
{
nzbid: "100677",
release: "Some.Movie.Title-GRP",
group: "alt.binaries.moovee",
sizebytes: "1601590891",
usenetage: "1317286337",
categoryid: "15",
cattext: "movies.sd",
language: "11",
weblink: "http://example.com/",
details: "https://omgwtfnzbs.org/details.php?id={nzbid}",
getnzb: "https://api.omgwtfnzbs.org/sn.php?id={nzbid}&user={username}&api={apikey}"
}
]
If your request was successful you will get upto 500 results listed in JSON format


other responses:

* {"notice":"applying some updates please try again later."} = Applying some updates to the code
* {"notice":"no search no results"} = Search term is required
* {"notice":"0 results matched your terms"} = No results for your query were found
* {"notice":"search to short"} = min term must be 3 characters or more ([a-Z0-9]) any other characters will be ignored
* {"notice":"your user or api information is incorrect.. check and try again"} = Bad/Incorrect api auth details


XML Search API: (updated 9th March 2013)
url to use:
https://api.omgwtfnzbs.org/xml/?search={some search term}&user={username}&api={apikey}

variables:
* ?search=something = string to search for (also see special features)
* &username={username} = Your account username.
* &api={apikey} = Your API Key.
* &catid=1,2,3 ect = Optional, search multiple categorys.
* &eng=1 = Optional, return only english/unknown posts.
* &retention={days} = Optional, limit the search to X amount of days ago.
* &page={#} = go to the next page of results if there is any.

If your request was successful you will get upto 500 results per page listed in xml format

special features:
* ?search= Sending a request with a blank search term will return results from the last 7 days &retention= will have no effect on your query
* ?search=tt1234567 = Search using the IMDB id. (if included at time of index)

sample output:

<xml version="1.0" encoding="ISO-8859-1">

<info>
<results>100</results>
<pages>2</pages>
<current_page>1</current_page>
<published>server time request was published</published
</info>

<search_req>

<post>
<release>Some.FLAC.Release.Name-INFO</release>
<group>alt.binaries.sounds.flac</group>
<sizebytes>286396335</sizebytes>
<usenetage>1338679302</usenetage>
<categoryid>22</categoryid>
<cattext>music.flac</cattext>
<language>0</language>
<imglink>https://if-added.jpg</imglink>
<weblink>http://weblink.net</weblink>
<details>https://omgwtfnzbs.org/details.php?id={nzbid}</details>
<getnfo>https://api.omgwtfnzbs.org/nfo/?id={nzbid}&user={username}&api={apikey}/getnfo>
<getnzb>https://api.omgwtfnzbs.org/sn.php?id={nzbid}&user={username}&api={apikey}</getnzb>
</post>

</search_req>
</xml>
Notice:
All requests are cached for 10 minutes to reduce the load on the server.


other responses:

* {no search no xml} = Search term is required
* {invalid search terms} = Invalid search term
* {0 results found} = No results for your query were found
* {search to short} = min term must be 3 characters or more.
* {your user/api information is incorrect.. check and try again} = Bad/Incorrect api auth details


Direct Download API: (updated 7th October 2014)
No HTML output is generated and the NZB is sent directly to your software/browser etc.

url to use:
https://api.omgwtfnzbs.org/nzb/?id={nzbid#}&user={username}&api={apikey}

variables:
* ?id={nzbid#} = taken from omgwtfnzbs.org
* &user={username} = Your account username.
* &api={apikey} = Your API Key.

output results:
If your request was successful the NZB will be sent directly to your browser/software.

If there was a problem with your request one the following responses will be output.

* {"notice":"applying some updates please try again later."} = Applying some updates to the code
* {"notice":"you have made too many nzb-api requests recently. nzb-api requests are limited to once every 15 seconds."}
* {"notice":"your user or api information is incorrect.. check and try again"} = Bad/Incorrect api auth details
* {"notice":"NZB has been removed from our index (cached result)"} = Just what it says
* {"notice":"no nzb found"} = Found the info but cant make the nzb
* {"notice":"bad nzbid#"} = Invalid nzbid#.

notes:
Only full posts can be retrieved, there is no support for partial posts.
Only one post can be downloaded per request.


GET NFO API: (updated 7th October 2014)
url to use:
https://api.omgwtfnzbs.org/nfo/?id={NZBID}&user={username}&api={apikey}

variables:
* ?id={nzbid#} = taken from omgwtfnzbs.org
* &user={username} = Your account username.
* &api={apikey} = Your API Key.
* &send=1 = No HTML output is generated and the NFO is sent directly to your software/browser etc.

output results:
If your request was successful the NFO will be displayed in your browser/software.

If there was a problem with your request one the following responses will be output.

* {"notice":"applying some updates please try again later."} = Applying some updates to the code
* {"notice":"you have made too many nfo-api requests recently. nfo-api requests are limited to once every 15 seconds."}
* {"notice":"your user or api information is incorrect.. check and try again"} = Bad/Incorrect api auth details
* {"notice":"nfo unavailable/removed"}

notes:
Only one NFO can be viewed per request.

"""""""""""""""""""""

**Comment by theotherp** [comment]
Oops. Open your settings.cfg and replace "https:/api.omgwtfnzbs.org" with "https://api.omgwtfnzbs.org". Restart and it should work. I hope :-)

**Comment by theotherp** [comment]
Note to self: Add (omgwtfnzbs) username to data to be cleared from log.

**Comment by Corrupta** [comment]
It's working now, good stuff :)

only other indexer that's not working is https://nzb.is

It's really not a priority for me, so whenever you get around to it. 

I know not much to work with in the log


 2015-12-12 17:56:50,822 - INFO - newznab - Unable to log in to indexer https://n
zb.is. Unknown error Unknown error while trying to access the indexer..
