### ISSUE TITLE
Socks5 w/Auth?

### ISSUE THREAD

**Issue by SCRPD** [theotherp/nzbhydra#430]
Is this possible with the the current socks proxy text box? Any special url format for auth that it needs? Or is it just not supported?

* What do you want to happen?
Socks5 with auth support.

* Why do you want it?
Private internet access socks5 proxy. Extra protection.

* Do you think it's something only you need or something that might me popular?
A lot of people have PIA, should be useful.

* If need be explain the use case.
Extra protection.

* Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
It would be nice to have, but not needed.

Thanks!

**Comment by theotherp** [comment]
Can be done. Perhaps tomorrow.

**Comment by SCRPD** [comment]
Sweet! Thank you very much! 
Love the program!

**Comment by theotherp** [comment]
More complicated than I thought and I have a lot going on right now, will have to wait some more.
