### ISSUE TITLE
Innaccurate stats

### ISSUE THREAD

**Issue by lukyjay** [theotherp/nzbhydra#431]
The stats page should allow me to only see data from the last 30 days. At the moment it appears to show data since the beginning of time.

This is unhelpful for two reasons:
1. I may have added a new indexer. This is going to have less data than the older indexers.
2. An indexer may have technical issues which were resolved recently.

Can we please have the stats delete after 30 days?

**Comment by theotherp** [comment]
I'll add options in the GUI to show the stats for a certain period, like All, last 30 days, last 7 days.

**Comment by lukyjay** [comment]
That would be fantastic! Thank you

**Comment by theotherp** [comment]
Oops.
