### ISSUE TITLE
Couch Potato Read Timeout Error when searching

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#432]
NZH version: 
CP Version:  40577904 

Platform:  Windows

I noticed CP wasn't snatching any files from NZBH the past few days. Here is the error within CP:
Errror from CP:
11-21 03:18:44 INFO
[hpotato.core.plugins.base] Opening url: get http://192.168.1.20:5075/api?imdbid=0083855&apikey=xxx&t=movie&extended=1&movies, data: []
11-21 03:19:14 ERROR
[hpotato.core.plugins.base] Failed opening url in Newznab: http://192.168.1.20:5075/api?imdbid=0083855&apikey=xxx&t=movie&extended=1&movies Traceback (most recent call last): ReadTimeout: HTTPConnectionPool(host='192.168.1.20', port=5075): Read timed out. (read timeout=30)

LOGFILE:

https://drive.google.com/file/d/0B7OujkYtbxFNYXAwckxreWNRTTQ/view?usp=sharing

**Comment by theotherp** [comment]
Can you open that URL on your machine?

**Comment by seanvree** [comment]
@theotherp , this is the error I get:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>NZB Hydra</title>
<description>NZB Hydra - the meta search</description>
<link>https://github.com/theotherp/nzbhydra</link>
<language>en-gb</language>
<webMaster>TheOtherP@gmx.de (TheOtherP)</webMaster>
</channel>
</rss>

**Comment by theotherp** [comment]
Seems to work. No idea why CP would be unable to open that URL, especially under windows. Although I think I remember something like that being on reddit, perhaps you can search the posts there.

**Comment by seanvree** [comment]
@theotherp , yeah wierd.  question - is this error saying that CP timed out, or NZBH?  I have my timeout set in NZBH to 30, and i have A LOT of indexers, should I push that timeout up??

THX

**Comment by theotherp** [comment]
Open that URL in your browser and time how long it takes. If it's more than 30 seconds you will need to increase the timeout in CP, not Hydra. The error above means that CP contacted Hydra and didn't get a response in less than 30 seconds. That is actually high, but not impossible.

**Comment by theotherp** [comment]
Any news?

**Comment by seanvree** [comment]
It's really hard to pinpoint @theotherp ....  I think it just might be those indexers are down?  I'll keep watching brother.

**Comment by seanvree** [comment]
Seems to be resolved.

**Comment by seanvree** [comment]
SO this issue is back, alghough I'm pretty certain it's a problem on the CP side:

**Comment by seanvree** [comment]
So I figured out a temp workaround to get NZBH working. This will get you some fakes if you don't have ETA enabled as well as good "exclusion terms" and ensure you're on good private trackers. 

\CouchPotato\couchpotato\core\media\_base\providers\nzb\newznab.py

Comment out this line:

line 115:    # 'age': self.calculateAge(int(time.mktime(parse(date).timetuple()))),

It's a temp workaround, but as soon as I did that, all the errors in CP stopped appearing and CP started snatching right away.

**Comment by seanvree** [comment]
@theotherp  - so after the check caps issue was fixed CP was working, but now they are back!! ARRHHH:


[ couchpotato.core.event] Error in event "provider.search.nzb.movie", that wasn't caught: Traceback (most recent call last): File "C:\CouchPotato\couchpotato\core\event.py", line 15, in runHandler return handler(*args, **kwargs) File "C:\CouchPotato\couchpotato\core\media\_base\providers\nzb\newznab.py", line 41, in search self._searchOnHost(host, media, quality, results) File "C:\CouchPotato\couchpotato\core\media\_base\providers\nzb\newznab.py", line 115, in _searchOnHost 'age': self.calculateAge(int(time.mktime(parse(date).timetuple()))), File "C:\CouchPotato\libs\dateutil\parser.py", line 718, in parse return DEFAULTPARSER.parse(timestr, **kwargs) File "C:\CouchPotato\libs\dateutil\parser.py", line 308, in parse raise ValueError("unknown string format") ValueError: unknown string format encoding=cp1252 debug=False args=['--data_dir=C:\\couchpotato'] app_dir=C:\CouchPotato data_dir=C:\couchpotato desktop=None options=Namespace(config_file='C:\\couchpotato\\settings.conf', console_log=False, daemon=False, data_dir='C:\\couchpotato', debug=False, pid_file='C:\\couchpotato\\couchpotato.pid', quiet=False)

**Comment by seanvree** [comment]
I've migrated to another movie search.  

Good luck!
