### ISSUE TITLE
New logfile-location is not activated

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#435]
Fist I installed nzbhydra manually on my Synology. But after I found there is a package for it, I installed that package, updated it and copied the db-files and settings.cfg from the original location. In the past I changed the logfile-location to /volume1/log/nzbhydra.log , that worked fine for the manual installation. But the package-installation does not pick up this change. It keeps pointing to /volume1/@appstore/nzbhydra/var/nzbhydra.log (which is the same as /usr/local/nzbhydra/var/nzbhydra.log), even though settings.cfg and the config-screen shows /volume1/log/nzbhydra.log. Off course I restarted several times, but nothing helps.

What is going on?
[nzbhydra-debuginfo-2016-11-22-10-54.zip](https://github.com/theotherp/nzbhydra/files/605997/nzbhydra-debuginfo-2016-11-22-10-54.zip)

**Comment by theotherp** [comment]
Not sure I can help you with that, you might want to contact the package container. Is it possible that the process is started with arguments pointing to the wrong location?

**Comment by pven** [comment]
Hm, I am afraid it is hardcoded in the package.

When I check the cmd in /proc I see:
```
/usr/local/nzbhydra/env/bin/python /usr/local/nzbhydra/share/nzbhydra/nzbhydra.py --daemon --nobrowser --database /usr/local/nzbhydra/var/nzbhydra.db --config /usr/local/nzbhydra/var/settings.cfg --logfile /usr/local/nzbhydra/var/nzbhydra.log --pidfile /usr/local/nzbhydra/var/nzbhydra.pid
```

Sorry for bothering you! I think I am going to fix it by using a symbolic link.
