### ISSUE TITLE
' RSS-only'  option per Indexer

### ISSUE THREAD

**Issue by Mirabis** [theotherp/nzbhydra#437]
## Feature Request in pre-formated style.
* What do you want to happen?
I'd like to have an additional dropdown option to select specific indexers which should only be used with the rss option (e.g. with Sonarr). 

* Why do you want it?
Besides my VIP indexers, I have some free accounts which are API limited and i'd only like to use them for RSS (more efficient use of hits available).

* Do you think it's something only you need or something that might me popular?
Assuming there are a lot of people with free indexers, I think this is universally beneficial if possible. 

* If need be explain the use case.
Users with indexers that have a low api limit, may still efficiently use RSS functionality.

* Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
Nice to have.

**Comment by theotherp** [comment]
I don't use any RSS and neither does Sonarr. What Sonarr calls "RSS" is actually a regular API call without specific query, i.e. getting the latest TV releases.

So for this to have any effect would mean that I'd need to implement RSS calls to indexers first. I'll keep it in mind.

**Comment by Mirabis** [comment]
Ah okay, no problem. Thought it was a different api call (not search) because toggling RSS on (my) sonarr has never worked with NzbHydra yet. 

Will look into it ; )

**Comment by theotherp** [comment]
It shouldn't make a difference. One of the Sonarr devs confirmed in the reddit thread that they don't actually use "RSS".

**Comment by Mirabis** [comment]
Okay, thanks for the information :)

Request is unnecessary then.
