### ISSUE TITLE
indexers showing up multiple times under indexer status?

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#438]
Noticed under indexer status that dognzb is showing up 3 times and nzbstars is showing up twice...I verified I don't have them listed multiple times.   Logs and screenshot attached.
![nzb](https://cloud.githubusercontent.com/assets/4558832/20549994/4b6499a0-b0ff-11e6-9f9a-4d830604c5b2.png)
[nzbhydra-debuginfo-2016-11-22-21-56.zip](https://github.com/theotherp/nzbhydra/files/608037/nzbhydra-debuginfo-2016-11-22-21-56.zip)

**Comment by theotherp** [comment]
See #431. No idea why that happens.

**Comment by theotherp** [comment]
Yeah, that was already reported once, don't know why I closed it or why it happens in the first place.
