### ISSUE TITLE
/details/nzbhydrasearchresult#### does not utilize a derefer service but should

### ISSUE THREAD

**Issue by pironic** [theotherp/nzbhydra#439]
### What do you want to happen? 
when hitting the more information from couchpotato or sonarr it derefers before forwarded to my nzbhydra instance but not from my nzbhydra instead to the indexer that originally pulled the information. I should be able to disable the derefer from couch to sonarr and it still derefer to the indexer.

specifically the 302 header that is provided is currently sending the browser directly to the indexer... rather than forwarding through a derefer url.
### Why do you want it?
current functionality is that the hit via api from nzbhydra to the indexer is completely tracked. they can see where it was refered from. they can see the incoming traffic.

### Do you think it's something only you need or something that might me popular?
everyone should want this. those that dont, dont understand what they dont want.
### If need be explain the use case.
even if you want to keep the derefer between couchpotato and nzbhydra that's fine, but we should also provide the derefer url to the indexer via the api hit for more information on an api returned result. 
### Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
i would argue must have. as long as there is an option for a derefer srevice in the options, we should use it.

**Comment by theotherp** [comment]
Well, I personally don't give two shits about that deferrer thing but I agree that if it's there it should be utilized properly.

**Comment by pironic** [comment]
thanks very much @theotherp!
