### ISSUE TITLE
Support special characters in downloader password

### ISSUE THREAD

**Issue by sachse** [theotherp/nzbhydra#440]
I had trouble getting NZB Hydra to connect to my NZBGet instance. It turns out that it was because my NZBGet password contained special characters - any chance this could be supported? I assume it's just an issue of escaping the string.

**Comment by theotherp** [comment]
Anything related to encoding is way more complicated than it should be (or I'm just too dumb). Will see.

**Comment by theotherp** [comment]
I played around a bit. I can increase the number of characters that work (like "ä","&","ß", etc.) but some will still cause problems ("/","\","@").

**Comment by theotherp** [comment]
I noticed that nzbget itself doesn't like a lot of characters. With a password like "öäü" I can't log in using the web interface. I'd recommend sticking to a long alphanumeric password.

**Comment by sachse** [comment]
>I'd recommend sticking to a long alphanumeric password.

That's what I'm using now and it's all good. Although I'd prefer not being limited to certain types of passwords it's not a big deal, especially since the issue exists with NZBGet as well. However, it might be a good idea to make a note of it somewhere.
