### ISSUE TITLE
Devel:  No module named requests?

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#441]
I just sync'd my source to the current changes from today and upon restart got:

Starting nzbhydra.
Traceback (most recent call last):
  File "/usr/local/www/nginx/nzbhydra/nzbhydra.py", line 6, in <module>
    from nzbhydra import webaccess
  File "/usr/local/www/nginx-dist/nzbhydra-develop/nzbhydra/webaccess.py", line 3, in <module>
    import requests
ImportError: No module named requests
/usr/local/etc/rc.d/nzbhydra: WARNING: failed to start nzbhydra

**Comment by theotherp** [comment]
Already fixed, just don't use the develop branch...

**Comment by theotherp** [comment]
On the other hand it's good to get feedback before I push stuff to master. I don't know. Any way, it's fixed.

**Comment by famewolf** [comment]
Well I have both setup.   I figured you wanted feedback. ;)

**Comment by famewolf** [comment]
As an fyi nzb.cat has open invites and is doing $5 Lifetime VIP.   I figure you already have but just in case.

**Comment by judhat2** [comment]
The link to the invites is https://nzb.cat/invites :)
