### ISSUE TITLE
Performance after mem upgrade really slow

### ISSUE THREAD

**Issue by phit42** [theotherp/nzbhydra#444]
I am running hydra on a synology nas, not the newest but usually a fast one (ds712+), with the synocommunity package. Recently I upgraded the memory from 1GB to 4GB which overall improved speed very noticably, particularly with web apps (eg couchpotato). Only Hydra has been getting really slow ever since, for example switching from a search to config takes 45 seconds with the blue bar running.
I don't know where to start looking to fix this?

**Comment by theotherp** [comment]
Uhm no idea. Just switching the pages takes so long? That's weird.

**Comment by phit42** [comment]
I've also checked the logs, and even in debug mode it shows nothing out of the ordinary. Only that the single log entries are obviously time stamped and show the delay. What could I test to narrow down the problem?

**Comment by theotherp** [comment]
Have you tried a new installation? Don't know how easy that is with NAS.

**Comment by phit42** [comment]
Hi, I have no idea how unfortunately, but this is fixed. Maybe I received a python update for my synology nas in the meanwhile (synocommunity package is now on v2.7.13-16) but not sure about the release dates anymore.
Thank you nonetheless.
