### ISSUE TITLE
Devel: Duplicate indexers under status

### ISSUE THREAD

**Issue by famewolf** [theotherp/nzbhydra#445]
The previous bug report was closed and I think I saw recent commit that talked about this but if so the problem still occurs.  Now however the duplicates don't show any info including a time/date stamp where before I believe they did.

![nzb1](https://cloud.githubusercontent.com/assets/4558832/20649896/84c5ea00-b497-11e6-8fc5-a034ff3ffc30.png)

**Comment by theotherp** [comment]
Then your database is whack. There can only be one indexer status for every indexer, which means there must be multiple indexers with the same name, for some reason. Perhaps you renamed some.

**Comment by theotherp** [comment]
Nevermind, found something.

**Comment by theotherp** [comment]
Yeah, this is embarrassing... The database migration code actually made the problem worse. Should be better now.

**Comment by famewolf** [comment]
Looks good now!
