### ISSUE TITLE
Indexers Disabled permanently?

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#447]
Windows 10 (Service)
version: Latest version: 0.2.174 

I've noticed that some indexers are "disabled permanently" with no reason?

Indexers like NZBGeek, OMGWTF, DOGNZB

I've deleted them, then re-added them and they connect fine, but they still say "disabled permanently". 

I"m not sure when this started as I haven't looked at the status page in awhile

Logfile: https://drive.google.com/file/d/0B7OujkYtbxFNYXAwckxreWNRTTQ/view?usp=sharing

Settings: https://drive.google.com/file/d/0B7OujkYtbxFNd3FiUmhoYUtuTzQ/view?usp=sharing

Thanks for the hard work @theotherp !!!

**Comment by theotherp** [comment]
That should only be displayed when the indexer encountered an error which "won't go away", e.g. an authentication error. If the API key is wrong there's no point in trying again.

It's probably just a display issue.

**Comment by seanvree** [comment]
@theotherp ... Right, I've double checked the API keys they are good. Like I said, I test them fine.  

Thanks buddy
