### ISSUE TITLE
IP address in log file when incorrect password entered

### ISSUE THREAD

**Issue by Yaff1e** [theotherp/nzbhydra#448]
I've previously had my NZBHydra install limited to my internal network but have just opened it up to external access. I've just been looking at the log file to find out what errors are generated on an unsuccessful login so that I can set up a Fail2Ban jail. If I enter an incorrect username and password the error has the IP address in. If I enter the correct user name but incorrect password it only has 'Login attempt with user karl and invalid password' but no IP address. I was just wondering if it's possible to include the IP address on those messages please?

**Comment by theotherp** [comment]
I wanted to do some changes to the code anyway. Will include this when I have time to do that.

**Comment by theotherp** [comment]
Sorry this took so long.
