### ISSUE TITLE
Second Download App

### ISSUE THREAD

**Issue by morchel** [theotherp/nzbhydra#45]
Hi,

could you add the option to configure a second download application?
I use sab at home and have a gigabit vserver with sab to share some downloads with friends, since my home network is too slow.

**Comment by theotherp** [comment]
So you would want two buttons in the results and when adding multiple results you would want to choose to which downloader to send it?

Will look into it, but not high priority right now because I don't think this applies to many people.

**Comment by morchel** [comment]
yes that would be cool. Thank you.

**Comment by mauirixxx** [comment]
I guess I'm the 2nd vote for this feature - only instead of 2 configured downloaders, why not allow an unlimited amount, maybe add a button similar to the "Add new newznab indexer" button, only on the downloader page?

**Comment by theotherp** [comment]
Took a while but there you go.
