### ISSUE TITLE
Invalid formated json/xml results

### ISSUE THREAD

**Issue by Andy2244** [theotherp/nzbhydra#450]
Going by the documentation on [newznab](http://newznab.readthedocs.io/en/latest/misc/api/) the individual results should be under 'item', yet i see them under 'items'?

It also seem there are 3 versions of encoding attributes and nzb.cat seems to add '_' to all attribute keys and to the enclosure array keys.

**Official newznab RSS:**
```
  <!-- Additional attributes -->
  <newznab:attr name="category" value="2000"/>
  <newznab:attr name="category" value="2030"/>
  <newznab:attr name="size"     value="4294967295"/>
```
**Hydra json:**
```
"items": [
      {
        "attr": [
          {
            "@attributes": {
              "name": "category", 
              "value": "5040"
            }
          }, 
```
**pfmonkey/dognzb json:**
```
"item": [
      {
        "attr": [
          {
            "@attributes": {
              "name": "category", 
              "value": "5040"
            }
          }, 
```
**cat.nzb using 'nZEDb' as generator in json:**
```
"item": [
        {
            "newznab:attr": [
                {
                    "_name": "category",
                    "_value": "5040"
                },
            ],
            "title": "The title",
            "enclosure": {
                "_url": "",
                "_length": "1357053171",
                "_type": "application/x-nzb"
            }
```

So from my point of view, none is a "correct" implementation of whats officially documented. It seems cat.nzb would be correct, if they remove the '_' from the keys. So whats going on?

At least i would like to have hydra use the pfmonkey/dognzb version with 'item'. Why the attributes are double wrapped in a "@attributes" instead of a single 'newznab:attr' array is also strange, similar to why cat.nzb adds underscores to some fields?

**Comment by theotherp** [comment]
If you expect indexers to follow that spefication completely you'll have a bad time. I can rename "items" to "item" but indexers' JSON and XML formattings are all over the place. nzedb even uses somewhat different formats for excluded words or getting NFOs.

I can't speak for any of the other indexers.

**Comment by Andy2244** [comment]
I understand i just try to get a slight reduction on variants going for projects that are on github and are willing to adapt one of the more common variants. I'm already adding like 5 variants to my code, which should cover most indexers. In the worst case they can always use hydra, since i will always make sure that's properly supported. 

So yeah i will leave the crazy parsing to you, since it seems hydra converts all to the newznab V2 version.

thx
Andy
