### ISSUE TITLE
APPCRASH in Windows Server 2012

### ISSUE THREAD

**Issue by ak47uk** [theotherp/nzbhydra#453]
I am having an intermittent issue where I am connected to the web interface over my LAN, send a search query and hydra starts searching but freezes on the searching process. The blue search bar moves across the machine but doesn't complete, when this happens any API requests also seem to fail. If I connect to the machine hosting hydra I have an APPCRASH message (below), once I select to close I can see nzbhydra is still running in taskman but the tray app is not. If I quit hydra and then launch the tray app it returns to normal. 

I have attached logs from Hydra, it contains more info than required but this last happened this morning (30th Nov) around approx 9am. I hope this is enough info.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	NZBHydraTray.exe
  Application Version:	1.0.0.0
  Application Timestamp:	577779fe
  Fault Module Name:	RichEd20.DLL
  Fault Module Version:	5.31.23.1231
  Fault Module Timestamp:	545049ea
  Exception Code:	c0000005
  Exception Offset:	0005ef25
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	2057
  Additional Information 1:	4c0d
  Additional Information 2:	4c0d3d1124626f82bbca335142b4acec
  Additional Information 3:	af59
  Additional Information 4:	af59c41c119ec45a0617de0a0db00a60

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	NZBHydraTray.exe
  Application Version:	1.0.0.0
  Application Timestamp:	577779fe
  Fault Module Name:	RichEd20.DLL
  Fault Module Version:	5.31.23.1231
  Fault Module Timestamp:	545049ea
  Exception Code:	c000041d
  Exception Offset:	0005ef25
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	2057
  Additional Information 1:	1ee8
  Additional Information 2:	1ee88d0555b2bfe0b0748b2261ae0af5
  Additional Information 3:	5954
  Additional Information 4:	59542bba35e6912ac9bcc62830a22a52

[nzbhydra-debuginfo-2016-11-30-09-18.zip](https://github.com/theotherp/nzbhydra/files/621376/nzbhydra-debuginfo-2016-11-30-09-18.zip)

**Comment by theotherp** [comment]
Hmm, I think that's a bug in my tray tool. Will do some tests.

**Comment by Crowley007** [comment]
I can confirm problems with the tray app. It vanishes from tray, but shows in task manager (along with nzbhydra.exe). After that has happened, neither search nor API access will work but webui does work. Now running only nzbhydra.exe and testing how it goes.

**Comment by theotherp** [comment]
Should be fixed with next update.

**Comment by ak47uk** [comment]
I'll look forward to that then, thanks for all the hard work!

**Comment by theotherp** [comment]
Fixed?

**Comment by ak47uk** [comment]
I haven't had a crash since so seems to be sorted, thanks again :)

**Comment by Crowley007** [comment]
I can confirm, it has been very stable.
