### ISSUE TITLE
Enhancement request - button to re-enable disabled indexers

### ISSUE THREAD

**Issue by philborman** [theotherp/nzbhydra#454]
My internet link went down, vpn connection lost, so all indexers were disabled either "connection failed" or "connection timed out".  I know they will automatically get re-enabled in a few hours, but would be useful to have a button to re-enable them on demand, either individually, or en-masse.

**Comment by philborman** [comment]
Forget it. Just noticed the little green tick next to the time does _exactly_ what I want. Didn't realise it was clickable.

**Comment by theotherp** [comment]
Could probably be more intuitive.
