### ISSUE TITLE
Add indexer infos and priority to API search results

### ISSUE THREAD

**Issue by Andy2244** [theotherp/nzbhydra#455]
I have a small feature request, it would be nice to get the hydra indexer priority, indexer name and host url per search result in the 'item' list. This way extra sorting can take place for the results based on those fields.

Something like this maybe?
```
{
  "@attributes": {
    "version": "2.0"
  }, 
  "channel": {
    "category": {}, 
    "description": "NZB Hydra - the meta search", 
    "items": [
      {
        "hydra_name": "pfmonkey indexer", 
        "hydra_host": "https://pfmonkey.com", 
        "hydra_priority": 9, 

        "category": "TV HD", 
        "comments": "https://pfmonkey.com/details/80eec58c3c60bc1db3fef8f041062111", 
        "link": "http://127.0.0.1:5075/getnzb?apikey=&searchresultid=509f6eac7bb3fbbca570cbef006638d18c1096e5", 
        "pubDate": "Sun, 27 Nov 2016 12:23:43 -0500", 
        "title": "Westworld.S01E08.Trace.Decay.720p.HBO.WEBRip.DD5.1.H.264-monkee"
      }, 

```
or
```
    "items": [
      {
        "hydra":[
              'name": "pfmonkey indexer", 
              "host": "https://pfmonkey.com", 
              "priority": 9,
         ]
```

thx
Andy

PS: Are feature request fine to post here?

**Comment by theotherp** [comment]
To be clear, you want this in the API results, not in the GUI? I guess I can do that.

Yes, feature requests are perfectly fine.

**Comment by Andy2244** [comment]
Yes for the api aka json/xml, so i can use this to my new flexget newsnab plugin. This than allows advanced sorting by those fields to filter the search results. Still need to add a weighted sort plugin, but than in flexget you could do weighted sort by priority, size, grabs and date.

thx
andy

**Comment by Andy2244** [comment]
Thx works great in my new flexget weighted sort plugin!

**Comment by theotherp** [comment]
Whatever that is.. M

**Comment by Andy2244** [comment]
http://flexget.com :)
