### ISSUE TITLE
Changelog not appearing anymore

### ISSUE THREAD

**Issue by notexe** [theotherp/nzbhydra#457]
**What do you expect to happen? What does happen?**
The changelog on system/updates is no longer appearing anymore ever since the latest update 0.2.176.

**Have you searched for this problem?**
Yes.

```
2016-12-03 10:11:14,268 - ERROR - update - Thread-122 - Unable to read local changelog
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra/update.py", line 101, in getVersionHistory
    return getChangesSince(changelog, oldVersion=oldVersion, sinceLastVersion=sinceLastVersion)
  File "/opt/nzbhydra/nzbhydra/update.py", line 122, in getChangesSince
    return markdown.markdown(changelog, output_format="html", extensions=['markdown.extensions.nl2br'])
  File "/opt/nzbhydra/libs/markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "/opt/nzbhydra/libs/markdown/__init__.py", line 359, in convert
    source = util.text_type(source)
```

**Comment by theotherp** [comment]
Huh, still? That should've already been fixed yesterday. You might've been one of a few unlucky ones which did the update before I could change the changelog. It should automatically fix itself with the next update.

**Comment by notexe** [comment]
I opened the changelog.md file and it seems to be up to date with the current one on GitHub.

**Comment by theotherp** [comment]
Does it contain a "€" sign?

**Comment by notexe** [comment]
Yeah

**Comment by theotherp** [comment]
That's my guess. Although it works fine on my developer windows machine and linux dedicated server.

Anyway, I didn't notice my git push failed, so the file wasn't replaced, but should be now.

**Comment by notexe** [comment]
I forced an update and now the changelog works fine. Maybe it depends on what locale you are using. I'm using en_US which may have been the reason it wasn't working.

**Comment by theotherp** [comment]
Alright, seems that the force update option was a good idea. I'd like to keep this open for other users for might experience the same problem.
