### ISSUE TITLE
Manual searching produces no results

### ISSUE THREAD

**Issue by Cozza38** [theotherp/nzbhydra#46]
It appears when a manual search is performed, either when pressing enter or the "GO" button every indexer becomes unchecked and no results are returned. I can retrieve the results by using the history.

I've made a gif for you to show the issue: https://i.imgur.com/WLI5YyX.gifv

**Comment by theotherp** [comment]
That's weird. Do you have a log?

**Comment by theotherp** [comment]
Should be fixed now. If not please reopen.

**Comment by Cozza38** [comment]
Just tested, worked perfectly. Thanks :)
