### ISSUE TITLE
[Feature Request] display more accurate nzb ages

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#460]
* What do you want to happen?
Is it possible to show a more accurate age rather than "0d" on the browser interface? I thought about it when I saw that Sonarr shows the age in minutes if under an hour and in hours if under a day old.
<img width="178" alt="snip_20161203191532" src="https://cloud.githubusercontent.com/assets/3536802/20858636/ec13d8c6-b98c-11e6-86c5-ade0c88c5639.png">

* Why do you want it?
I just think it would look a little better.

* Do you think it's something only you need or something that might me popular?
Definitely not needed. It might just be me and my fastidiousness that wants it. :)

* Is it nice to have or a must have? I might disagree but it's still good for me to know what you think.
Just nice to have.

**Comment by theotherp** [comment]
Shouldn't be too much work. Currently busy playing Watch

**Comment by theotherp** [comment]
Ooops.

... Dogs 2.

**Comment by judhat2** [comment]
Thanks!
