### ISSUE TITLE
Duplicate size threshold config doesn't seem to be working

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#463]
* What do you expect to happen? What does happen? 

I came across 2 nzbs that nzbhydra returned as unique, but upon further inspection, they are the same.  Turns out that have the same group, time, poster, and files. Only the size is different. Some indexers say it's 4.74 GB and others say it's 4.59 GB, which is bigger than the 1% difference that hydra looks for.  So, I increased the "Duplicate size threshold" in the settings to 4%. I got the same results. Increased it to 10% and still no change.  

I looked into the code some and found a mention of the size threshold here. https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/search.py#L535. It looks like the setting from the config is being overwritten.  I changed the `size_threshold` to a value of 4 at line 537, and finally nzbhydra saw them as duplicates.

Am I reading this wrong or is the duplicate size threshold and age threshold settings being overwritten?

**Comment by theotherp** [comment]
I'll look into it. Entirely possible.

**Comment by judhat2** [comment]
Thanks AGAIN! Working now.
