### ISSUE TITLE
[Feature request] Option to prefer obfuscated NZBs over non-obfuscated

### ISSUE THREAD

**Issue by strafer** [theotherp/nzbhydra#466]
Certain files from certain networks fail frequently if they're not recent releases. However, the obfuscated versions of these files, often from NZBGeek, usually download successfully. 

It would be nice to have an option for NZB Hydra to prefer obfuscated NZBs over non-obfuscated versions, if there are both types available. Or would this be more of a Sonarr/SickRage feature?

**Comment by theotherp** [comment]
Unfortunately that won't work. Indexers don't provide any information on what posts are obfuscated and what not. You could do a feature request on nzedb and nntmux and possibly newznab.

Sonarr/CP could not do that either.
