### ISSUE TITLE
Create occasional releases

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra#469]
I added the non-git Arch AUR package for [nzbhydra](https://aur.archlinux.org/packages/nzbhydra/) after finding you had a release. There is also a [nzbhydra-git](https://aur.archlinux.org/packages/nzbhydra-git/) version to cover master. It'd be really super if you could do occasional point releases, when they make sense.

As much as a built in updater is awesome, some people still stick to packages. :)

**Comment by theotherp** [comment]
I already automatically make releases for the Windows binaries every time I push a new version, I could do the same for the main repo, no problem.

**Comment by theotherp** [comment]
Alright, I changed my build file to make github releases on every release.
