### ISSUE TITLE
Custom categories

### ISSUE THREAD

**Issue by securos** [theotherp/nzbhydra#471]
Hello

Is it possible to allow for custom categories? While I watch my series and movies in english, my friends prefer to watch them in their native german. I like to occasionally download series and movies for them via manual search and share them via plex. 

It would be great if I could simply choose a category like "Movies HD German" which would then have some required keywords like "german, deutsch" or something like that.

Not sure how popular that feature would be. It's more of a luxury request since I can simply add those key words to my search. But it would be nice to have those custom categories :)

Anyway, NZBHydra is great! Thanks for all your hard work!

**Comment by theotherp** [comment]
That's a great idea but would need some work. I'll look into it, but don't expect it for a while.

**Comment by pven** [comment]
I would also love this!

Take your time. ;)

**Comment by Firemad03** [comment]
+1 because I need French and English (I'm from Canada). I have 2 x Sonarr I prefer the regex in nzbhydra.

**Comment by theotherp** [comment]
Implemented in v2 which will be released soon.
