### ISSUE TITLE
API hits vs download limits

### ISSUE THREAD

**Issue by lukyjay** [theotherp/nzbhydra#472]
Hi

Please tag as feature request or enhancement.

In configuration we have API hit limits, which most indexers provide. However they also provide download limits and they are normally a lot less than the API hit limits.

With one of my indexers as an example, I have an API hit limit of 5,000, and a download limit of 1,000. Once I exceed my download limit, it still lets me search and download NZB files, but those files have no content.

Can we please have an option to limit by download count?

Thanks
Jay

P.S Have completed your survey 👍

**Comment by theotherp** [comment]
See #247

**Comment by lukyjay** [comment]
Sorry - That's exactly what I was looking for. Maybe we should close this as a duplicate?
