### ISSUE TITLE
Timeout for stats

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#474]
My Synology DS410is not really that fast. So when I look at stats, sometimes a timeout occurs. Is it possible to set a custom timeout for stats?

![2016-12-07 13_31_53-nzb hydra - config indexers](https://cloud.githubusercontent.com/assets/671621/20967867/b1e3f77e-bc81-11e6-9526-494885267208.jpg)

**Comment by theotherp** [comment]
That's a known database problem. You'll need to live with it.
