### ISSUE TITLE
500: INTERNAL SERVER ERROR - categories

### ISSUE THREAD

**Issue by rebelbase** [theotherp/nzbhydra#475]
Hi,
   Just updated to the latest version from and everytime I start up I get the following error:

An error occured :
500: INTERNAL SERVER ERROR
categories

and the traceback:

2016-12-08 06:53:08,475 - ERROR - web - Thread-24 - categories
Traceback (most recent call last):
  File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/nzbhydra/nzbhydra/web.py", line 341, in wrapped_function
    return f(*args, **kwargs)
  File "/opt/nzbhydra/nzbhydra/web.py", line 1057, in internalapi_getsafeconfig
    return jsonify(config.getSafeConfig())
  File "/opt/nzbhydra/nzbhydra/config.py", line 927, in getSafeConfig
    "categories": categories.getCategories(),
  File "/opt/nzbhydra/nzbhydra/categories.py", line 115, in getCategories
    for k, v in config.settings.categories.categories.items():
  File "/opt/nzbhydra/libs/bunch/__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: categories

Great tool by the way, thanks for the effort and the great work!

**Comment by theotherp** [comment]
Please post your settings.cfg with all sensitive data removed (API keys, usernames, passwords).

**Comment by rebelbase** [comment]
{
    "auth": {
        "authType": "none", 
        "restrictAdmin": false, 
        "restrictSearch": false, 
        "restrictStats": false, 
        "users": []
    }, 
    "categories": {
        "categories": {
            "anime": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 15000, 
                "min": 50, 
                "newznabCategories": [
                    5070
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "audio": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 2000, 
                "min": 1, 
                "newznabCategories": [
                    3000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "audiobook": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 1000, 
                "min": 50, 
                "newznabCategories": [
                    3030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "comic": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 250, 
                "min": 1, 
                "newznabCategories": [
                    7030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "console": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 40000, 
                "min": 100, 
                "newznabCategories": [
                    1000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "ebook": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 100, 
                "min": null, 
                "newznabCategories": [
                    7020, 
                    8010
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "flac": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 2000, 
                "min": 10, 
                "newznabCategories": [
                    3040
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "movies": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 20000, 
                "min": 500, 
                "newznabCategories": [
                    2000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "movieshd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 20000, 
                "min": 3000, 
                "newznabCategories": [
                    2040, 
                    2050, 
                    2060
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "moviessd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 3000, 
                "min": 500, 
                "newznabCategories": [
                    2030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "mp3": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 500, 
                "min": 1, 
                "newznabCategories": [
                    3010
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "pc": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 50000, 
                "min": 100, 
                "newznabCategories": [
                    4000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tv": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 5000, 
                "min": 50, 
                "newznabCategories": [
                    5000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tvhd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 4500, 
                "min": 300, 
                "newznabCategories": [
                    5040
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "tvsd": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "never", 
                "max": 1000, 
                "min": 50, 
                "newznabCategories": [
                    5030
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }, 
            "xxx": {
                "applyRestrictions": "both", 
                "forbiddenRegex": null, 
                "forbiddenWords": [], 
                "ignoreResults": "both", 
                "max": 10000, 
                "min": 100, 
                "newznabCategories": [
                    6000
                ], 
                "requiredRegex": null, 
                "requiredWords": null
            }
        }, 
        "enableCategorySizes": true
    }, 
    "downloaders": [
        {
            "apikey": "****************", 
            "downloadType": "nzb", 
            "enabled": true, 
            "iconCssClass": "", 
            "name": "SABnzbd", 
            "nzbAddingType": "link", 
            "nzbaccesstype": "redirect", 
            "password": null, 
            "type": "sabnzbd", 
            "url": "http://localhost:***", 
            "username": null
        }
    ], 
    "indexers": [
        {
            "accessType": "both", 
            "categories": [
                "anime"
            ], 
            "enabled": true, 
            "generate_queries": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://anizb.org", 
            "name": "anizb", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "anizb", 
            "username": null
        }, 
        {
            "accessType": "internal", 
            "categories": [], 
            "enabled": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://binsearch.info", 
            "name": "Binsearch", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "binsearch", 
            "username": null
        }, 
        {
            "accessType": "internal", 
            "categories": [], 
            "enabled": true, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://www.nzbclub.com", 
            "name": "NZBClub", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "nzbclub", 
            "username": null
        }, 
        {
            "accessType": "internal", 
            "categories": [], 
            "enabled": true, 
            "generalMinSize": 1, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://nzbindex.com", 
            "name": "NZBIndex", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "nzbindex", 
            "username": null
        }, 
        {
            "accessType": "external", 
            "categories": [
                "tv", 
                "tvhd", 
                "tvsd"
            ], 
            "enabled": true, 
            "generate_queries": false, 
            "hitLimit": 0, 
            "hitLimitResetTime": null, 
            "host": "https://newshost.co.za", 
            "name": "Womble", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": false, 
            "timeout": null, 
            "type": "womble", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "animeCategory": "5070", 
            "apikey": "****************", 
            "audiobookCategory": "3030", 
            "backend": "newznab", 
            "categories": [
                "movies", 
                "movieshd", 
                "moviessd", 
                "tv", 
                "tvhd", 
                "tvsd", 
                "audio", 
                "flac", 
                "mp3", 
                "xxx", 
                "console", 
                "pc", 
                "anime", 
                "comic", 
                "audiobook"
            ], 
            "comicCategory": "7030", 
            "ebookCategory": null, 
            "enabled": true, 
            "hitLimit": null, 
            "hitLimitResetTime": 0, 
            "host": "https://drunkenslug.com", 
            "magazineCategory": "7010", 
            "name": "drunkenslug", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [
                "movie", 
                "tvsearch"
            ], 
            "search_ids": [
                "imdbid", 
                "rid", 
                "tmdbid", 
                "traktid", 
                "tvdbid", 
                "tvmazeid"
            ], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "newznab", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "animeCategory": "5070", 
            "apikey": "****************", 
            "audiobookCategory": "3030", 
            "backend": "newznab", 
            "categories": [
                "movies", 
                "movieshd", 
                "moviessd", 
                "tv", 
                "tvhd", 
                "tvsd", 
                "audio", 
                "flac", 
                "mp3", 
                "xxx", 
                "console", 
                "pc", 
                "anime", 
                "audiobook"
            ], 
            "comicCategory": null, 
            "ebookCategory": null, 
            "enabled": true, 
            "hitLimit": null, 
            "hitLimitResetTime": 0, 
            "host": "http://nzb.is", 
            "magazineCategory": null, 
            "name": "nzb.is", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "searchTypes": [
                "movie", 
                "tvsearch"
            ], 
            "search_ids": [
                "imdbid", 
                "rid", 
                "tmdbid", 
                "traktid", 
                "tvdbid", 
                "tvmazeid"
            ], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "newznab", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "animeCategory": null, 
            "apikey": "****************", 
            "audiobookCategory": null, 
            "backend": "newznab", 
            "categories": [], 
            "comicCategory": null, 
            "ebookCategory": null, 
            "enabled": false, 
            "hitLimit": null, 
            "hitLimitResetTime": 0, 
            "host": "https://api.oznzb.com", 
            "magazineCategory": null, 
            "name": "oznzb.com", 
            "password": null, 
            "preselect": true, 
            "score": 0, 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "newznab", 
            "username": null
        }, 
        {
            "accessType": "both", 
            "animeCategory": null, 
            "apikey": "****************", 
            "audiobookCategory": null, 
            "backend": "newznab", 
            "categories": [
                "tv", 
                "tvhd", 
                "tvsd", 
                "movieshd", 
                "moviessd", 
                "movies"
            ], 
            "comicCategory": null, 
            "ebookCategory": null, 
            "enabled": true, 
            "hitLimit": null, 
            "hitLimitResetTime": 0, 
            "host": "http://localhost/spotweb", 
            "magazineCategory": null, 
            "name": "spotweb", 
            "password": null, 
            "preselect": true, 
            "score": 1, 
            "searchTypes": [], 
            "search_ids": [], 
            "showOnSearch": true, 
            "timeout": null, 
            "type": "newznab", 
            "username": null
        }
    ], 
    "main": {
        "apikey": "****************", 
        "branch": "master", 
        "configVersion": 31, 
        "debug": false, 
        "dereferer": "http://www.dereferer.org/?$s", 
        "externalUrl": null, 
        "firstStart": ****************, 
        "flaskReloader": false, 
        "gitPath": null, 
        "host": "0.0.0.0", 
        "httpProxy": null, 
        "httpsProxy": null, 
        "keepSearchResultsForDays": 7, 
        "logging": {
            "consolelevel": "INFO", 
            "logIpAddresses": true, 
            "logfilelevel": "INFO", 
            "logfilename": "nzbhydra.log"
        }, 
        "pollShown": 0, 
        "port": 8787, 
        "repositoryBase": "https://github.com/theotherp", 
        "runThreaded": true, 
        "secret": "****************", 
        "shutdownForRestart": false, 
        "socksProxy": null, 
        "ssl": false, 
        "sslcert": null, 
        "sslkey": null, 
        "startupBrowser": true, 
        "theme": "bright", 
        "urlBase": null, 
        "useLocalUrlForApiAccess": true
    }, 
    "searching": {
        "alwaysShowDuplicates": false, 
        "applyRestrictions": "both", 
        "duplicateAgeThreshold": 8, 
        "duplicateSizeThresholdInPercent": 1, 
        "forbiddenRegex": null, 
        "forbiddenWords": "", 
        "generate_queries": [
            "internal"
        ], 
        "htmlParser": "html.parser", 
        "ignorePassworded": false, 
        "ignoreTemporarilyDisabled": false, 
        "maxAge": "", 
        "nzbAccessType": "redirect", 
        "removeLanguage": true, 
        "requiredRegex": null, 
        "requiredWords": "", 
        "timeout": 20, 
        "userAgent": "NZBHydra"
    }
}

**Comment by theotherp** [comment]
Your settings work fine with my code. There's nothing there that would explain that error.

Check your backup folder for your latest backup ZIP. Copy it somewhere else, delete the folder, install it new and restore your backup.

**Comment by rebelbase** [comment]
I'll try another  fresh reinstall without my config file to see if that works then I'll put it back in and see what happens.

Thanks

**Comment by theotherp** [comment]
Alright. Good luck.

**Comment by rebelbase** [comment]
The fresh install worked, I just pulled the API keys from by backup .cfg and it is now working again.

Thanks

**Comment by theotherp** [comment]
Great. No idea what caused the problem but at least it's fixed.
