### ISSUE TITLE
Feature Request: Indexer Filtering by check/uncheck

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#476]
**What do you want to happen?**

I love the instantaneous filtering, and in addition to filtering by search box or through the various time/size options, I'd like to also be able to filter by unchecking the indexer and having the items from that one removed from the results.

**If not clear, why do you want it?**

A lot of times indexers return a lot of junk results and it would be handy to just quickly clear those out by dropping the results from the whole indexer.  In particular, if you do a search that returns a large amount of results from an open indexer, like Binsearch, it would be nice to quickly eliminate those from the listings.  Right now in order to do this you have to actually uncheck them and then run the search a second time.

**Do you think it's something only you need or something that might be popular?**

I think anybody that uses the GUI and doesn't use very specific searches with lots of include/ignore words would benefit, but in all honesty that's probably a very small subset of the actual NZBHydra user base.

I think it would be nice to have, but by no means do I think it's important.  If it's difficult, cumbersome or confusing, then I completely understand if you don't want to implement it.  Just something I thought might be useful :)

**Comment by judhat2** [comment]
I think the feature you want is already implemented. Have you tried unchecking the box next to the indexer name in the "Indexer statuses / Rejected results" dropdown? I use this feature often. I just happen to find this feature one day. I haven't seen it mentioned in any of the docs.

**Comment by theotherp** [comment]
It might not be that intuitive, being hidden in the indexer statuses box. When I added that feature the box was always shown and named differently.

**Comment by albino1** [comment]
Thanks @judhat2!  Yeah, I had no idea that was there.  It never even occurred to me that those checkboxes might serve a purpose other than indicating that those indexers were selected when making the initial search.

That more or less solves my feature request, so I'll go ahead and close this.  Thanks guys :)
