### ISSUE TITLE
extend forbidden words functionality

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra#478]
It would be nice if the list of forbidden words worked across all additional attributes of the nzb file. I may be mistaken but it seems that the list of forbidden words only work against the title of an nzb file or title of a post but it would be beneficial if it worked for other attributes; specifically 'poster' or 'group'.

Recently I have been flooded with spam nzbs and they all come from one poster in particular (not sure if I should mention the name here but can and will if needed) and usually posted to the same group. They always fail due to either being encrypted (which is somehow not recognized on the front end of hydra's search results) but usually due to a health failure with no (0) par files in the original upload.

This would help everyone that uses hydra out tremendously as you could then set hydra to essentially blacklist all post from known spam posters or spam groups and not have to rely on individual indexers' site admin to implement the blacklist on their end. It would also just be another option for the user to have to further refine unwanted search results.

**Comment by judhat2** [comment]
+1 for being able to block certain posters.  There's one that has been uploading tons of junk.  Some indexers are good at blocking it, but some do not. It would be nice if hydra could fix that problem.
