### ISSUE TITLE
allow filtering within History & Stats tab

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra#479]
If would be nice to be able to have a find-as-you-type type filtering/clicking within the history & stats tab. This would add functionality to further refine your stats. For example, say I'm interested in seeing which nzb files came from a certain indexer. On the Download History tab I could type the name of an indexer and it would filter out all results that didn't match that indexer. The same could be done for the title of an nzb. Another option would be to filter by time, maybe like you way you currently can on the Stats tab, to only show nzbs downloaded during a certain time frame.

Another option could be a click to filter setting. If you're on the Stats tab you could click the name of an indexer in your pie chart and it would find all results from said indexer. Maybe load those results in a popup or take you to the Download History tab with that indexer's results showing.

Obviously, this isn't actually needed in order to make hydra function but could be another neat way to extend and view the search results stats and data from your indexers.

**Comment by theotherp** [comment]
Not all of that will be possible, but some of it. Working on it.
