### ISSUE TITLE
How to delete default indexers?

### ISSUE THREAD

**Issue by rfgamaral** [theotherp/nzbhydra#480]
I might be missing the obvious here but how do I delete all the default indexers after a clean installation? I don't need those and just want to use my own. Yes, I can disable them but it's not the same thing because they still show up under "indexer statuses" and I'd like to hide that because I simply don't use them.

Is this possible somehow?

**Comment by theotherp** [comment]
Currently not possible.

**Comment by rfgamaral** [comment]
Not even editing some files or something?

NZBHydra is a really nice idea and I don't know why I haven't installed this before... But it doesn't really make much sense to have default indexers without the ability to remove them. My 2 cents. Thanks.

**Comment by theotherp** [comment]
I'm not saying it doesn't make sense, just that it's not possible.

**Comment by rfgamaral** [comment]
Ok, thanks.

Should this remain open as a feature suggestion?

**Comment by YipYup** [comment]
So long as removing them means there is also a way to "reset" and un-ignore the provided templates again, should one change their mind and wish to show them again in the indexer provisioning.
