### ISSUE TITLE
[Enhancement] Per-Indexer User-Agent string overwrite

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#482]
You don't have to follow this template by the letter, just think about what you're trying to achieve ;-) 

* ## What do you want to happen?
Allow **per-indexer** User-Agent overwrites / customization (that are used for the http requests)
* ## If not clear, why do you want it?
Some Indexers expect specific user agents, filtering requests based on if they include the expected user agent or not. Others utilize third party front-end security proxies that additionally filter requests coming in based on the user agent string. 
* ## Do you think it's something only you need or something that might be popular?
I think this is needed amongst a subset of indexers.
* ## If need be explain the use case.
Being able to customize this on a per-indexer basis, without changing it system wide is what is desired here.

**Comment by theotherp** [comment]
What indexers?

**Comment by YipYup** [comment]
Headphones (CodeShy)

**Comment by Fossil01** [comment]
Sounds like a shady way to go by unnoticed in some indexers logs...

**Comment by theotherp** [comment]
I've never seen any indexer demand which user agent a tool should use or not use.
