### ISSUE TITLE
new nZEDb indexer: indexers capabilities test fails

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#485]
i checked the capabilities of my new (private) nZEDb indexer. The indexer works perfectly with Sickrage and Couchpotato (search and nzb-download).
when i press the "test" button, it shows activity, but nothing happens. No error-message, nothing.
I set the log-level for debugging - no errormessage. any idea?
What i tried:
- delete indexer-entry and try again
- tried docker-version of nzbhydra
- tried fresh install of nzbhydra on a fresh Ubuntu install

**Comment by theotherp** [comment]
Duplicate of #477 I think.
