### ISSUE TITLE
Indexer: Usenet-Crawler - Connection Failed, Aborted, Bad Status Line

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#486]
* ## What do you expect to happen? What does happen?
API Connectivity to https://www.usenet-crawler.com is failing, being aborted.

* ## Can the problem be reproduced? How?
URL for API:  https://www.usenet-crawler.com
API Query Limits / 24 Hrs: 50,000
API Key Required & Configured?: Yes

* ## Log file:
Emailed to your listed address.

**Comment by albino1** [comment]
Did you try and visit the site?  It's down right now with a 404 error.

> It's not just you! https://www.usenet-crawler.com looks down from here.

FWIW, they recently underwent a management change, so hopefully the downtime and errors are because they're working on improvements.

**Comment by YipYup** [comment]
@albino1 Thanks. I missed the obvious :)
