### ISSUE TITLE
Log file location won't change

### ISSUE THREAD

**Issue by bradmurray** [theotherp/nzbhydra#487]
I am trying to set the log to /var/log/nzbhydra.log, but when I do it still just logs to the application root/nbzhydra.log. If logging has to happen in the application folder the UI should mention that.

**Comment by theotherp** [comment]
Running from source or some kind of package or docker or something?

**Comment by bradmurray** [comment]
source

**Comment by theotherp** [comment]
Are you using a script to startup hydra which sets the log file location via command line?
