### ISSUE TITLE
Search Provider Visual Progress Testing

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#490]
Enhancement Request

## What do you want to happen?
Visual feedback of Server Capabilities Testing / Server Status Testing when adding a new search provider OR confirming/reconfirming an existing provider.

1.  Show HTTP responses of , Code & Human Readable definition of HTTP code (ie 403 access denied, 500 service unavailable, 200 Ok)
2.  Show visual one or two row table (additional row including column headers) of what features the tracker supports, and specifics of the testing.

Show what features are confirmed to be supported, not supported, or were undetermined, as progress happens. Visual output in a one row table could include { Supported, Not supported, Unable to Determine, Null (Untested / Not yet checked) }

* Site requires API Key {Yes Required, Not Required, Not Applicable/Key Not Supported }
* API Key Provided is Correct {Yes, No, Not Applicable }
* RSS Recent Feed Supported {Yes {XML,JSON, Internally Scraped}, No} {Per-Category,Basic Site-Wide Recent Only, Not Supported, }
* Search IDs Supported {Trakt, IMDB, TVDB, etc }
* Search Supported {Yes {XML Get, JSON, Internally Scraped}, No}
* etc

## If not clear, why do you want it?
Show current progress of test, rather than simply leave it to a spinning progress icon. Let the user see it as it happens, rather than wondering if there is a problem or not.

## Do you think it's something only you need or something that might be popular?
I think this would be very useful for anyone adding an indexer to help them know if they put in the right URL, see if the API key is correct, and see what abilities the indexer supports right off the bat.

**Comment by theotherp** [comment]
It's a bug that it stays spinning. It should fill in the details and show feedback.

**Comment by theotherp** [comment]
Should be fixed now. Found supported IDs are added and if the indexer could not be accessed the connection check should already fail with an appropriate message.
