### ISSUE TITLE
Error updating to 0.2.180 - Help needed

### ISSUE THREAD

**Issue by g13ryj** [theotherp/nzbhydra#492]
I am currently on 0.2.153 and trying to update to 0.2.180

The updates fails and in the log I see:

> 2016-12-30 12:58:27,098 - ERROR - update - Thread-39 - "git" pull origin master returned : From https://github.com/theotherp/nzbhydra
>  * branch            master     -> FETCH_HEAD
> error: Your local changes to the following files would be overwritten by merge:
> 	.gitignore
> 	ISSUE_TEMPLATE.md
> 	README.md
> 	changelog.md
> 	contrib/nzbhydra.service
> 	gulpfile.js
> 	libs/bs4/__init__.py
> 	libs/bs4/builder/__init__.py
> 	libs/bs4/builder/_html5lib.py
> 	libs/bs4/builder/_htmlparser.py
> 	libs/bs4/builder/_lxml.py
> 	libs/bs4/dammit.py
> 	libs/bs4/diagnose.py
> 	libs/bs4/element.py
> 	libs/bs4/testing.py
> 	libs/peewee.py
> 	libs/playhouse/_speedups.pyx
> 	libs/playhouse/sqlite_ext.py
> 	libs/playhouse/sqliteq.py
> 	libs/requests/__init__.py
> 	libs/requests/adapters.py
> 	libs/requests/api.py
> 	libs/requests/auth.py
> 	libs/requests/cacert.pem
> 	libs/requests/certs.py
> 	libs/requests/compat.py
> 	libs/requests/cookies.py
> 	libs/requests/exceptions.py
> 	libs/requests/hooks.py
> 	libs/requests/models.py
> 	libs/requests/packages/__init__.py
> 	libs/requests/packages/urllib3/__init__.py
> 	libs/requests/packages/urllib3/_collections.py
> 	libs/requests/packages/urllib3/connection.py
> 	libs/requests/packages/urllib3/connectionpool.py
> 	libs/requests/packages/urllib3/contrib/appengine.py
> 	libs/requests/packages/urllib3/contrib/ntlmpool.py
> 	libs/requests/packages/urllib3/contrib/pyopenssl.py
> 	libs/requests/packages/urllib3/exceptions.py
> 	libs/requests/packages/urllib3/fields.py
> 	libs/requests/packages/urllib3/filepost.py
> 	libs/requests/packages/urllib3/packages/six.py
> 	libs/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
> 	libs/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py
> 	libs/requests/packages/urllib3/poolmanager.py
> 	libs/requests/packages/urllib3/request.py
> 	libs/requests/packages/urllib3/response.py
> 	libs/requests/packages/urllib3/util/__init__.py
> 	libs/requests/packages/urllib3/util/connection.py
> 	libs/requests/packages/urllib3/util/response.py
> 	libs/requests/packages/urllib3/util/retry.py
> 	libs/requests/packages/urllib3/util/ssl_.py
> 	libs/requests/packages/urllib3/util/timeout.py
> 	libs/requests/packages/urllib3/util/url.py
> 	libs/requests/sessions.py
> 	libs/requests/status_codes.py
> 	libs/requests/structures.py
> 	libs/requests/utils.py
> 	libs/socks.py
> 	nzbhydra/api.py
> 	nzbhydra/categories.py
> 	nzbhydra/config.py
> 	nzbhydra/database.py
> 	nzbhydra/downloader.py
> 	nzbhydra/indexers.py
> 	nzbhydra/infos.py
> 	nzbhydra/log.py
> 	nzbhydra/search.py
> 	nzbhydra/search_module.py
> 	nzbhydra/searchmodules/anizb.py
> 	nzbhydra/searchmodules/binsearch.py
> 	nzbhydra/searchmodules/jackett.py
> 	nzbhydra/searchmodules/newznab.py
> 	nzbhydra/searchmodules/nzbclub.py
> 	nzbhydra/searchmodules/nzbindex.py
> 	nzbhydra/searchmodules/omgwtf.py
> 	nzbhydra/searchmodules/womble.py
> 	nzbhydra/stats.py
> 	nzbhydra/tests/db_prepare.py
> 	nzbhydra/tests/mock/omgwtf_search.xml
> 	nzbhydra/tests/mockbuilder.py
> 	nzbhydra/tests/playground.py
> 	nzbhydra/tests/playground2.py
> 	nzbhydra/tests/test_Config.py
> 	nzbhydra/tests/test_DuplicateDetection.py
> 	nzbhydra/tests/test_IntegrationTestsSearch.py
> 	nzbhydra/tests/test_Newznab.py
> 	nzbhydra/tests/test_OmgWtf.py
> 	nzbhydra/tests/test_Search.py
> 	nzbhydra/tests/test_SearchModule.py
> 	nzbhydra/tests/test_SearchPerformance.py
> 	nzbhydra/tests/testsettings.cfg.orig
> 	nzbhydra/update.py
> 	nzbhydra/web.py
> 	py2exesetup.py
> 	reproducePeeweeDbFile.py
> 	static/css/dark.css
> 	static/css/dark.css.map
> 	static/css/default.css
> 	static/css/default.css.map
> 	static/html/about.html
> 	static/html/directives/addable-nzb.html
> 	static/html/directives/duplicate-group.html
> 	static/html/directives/search-result-non-title-columns.html
> 	static/html/directives/updates.html
> 	static/html/modal.html
> 	static/html/states/config.html
> 	static/html/states/indexer-statuses.html
> 	static/html/states/main-stats.html
> 	static/html/states/search-results.html
> 	static/html/states/system.html
> 	static/js/nzbhydra.js
> 	static/js/nzbhydra.js.map
> 	ui-src/html/about.html
> 	ui-src/html/directives/addable-nzb.html
> 	ui-src/html/directives/duplicate-group.html
> 	ui-src/html/directives/search-result-non-title-columns.html
> 	ui-src/html/directives/updates.html
> 	ui-src/html/modal.html
> 	ui-src/html/states/config.html
> 	ui-src/html/states/indexer-statuses.html
> 	ui-src/html/states/main-stats.html
> 	ui-src/html/states/search-r
> Aborting
> Updating 6288ecf..f521391

Any ideas what I am doing wrong?

Thanks in advance.

**Comment by theotherp** [comment]
Wow, that's an old one. It's probably easiest if you backup your nzbhydra.db* and settings.cfg, delete everything, install anew and put them back.

**Comment by g13ryj** [comment]
Thanks for the reply.

My install was in docker on Synology DS415.

I deleted all the config files, restarted the container and it pulled in the latest version and restored the backup I did.  Worked a treat.

Thanks!
