### ISSUE TITLE
Internal Server Error 500 for URL

### ISSUE THREAD

**Issue by rjsears** [theotherp/nzbhydra#493]
Just installed and configured NZBHydra. I have four indexers three of which work just fine. My forth indexer (NZBgeek) keeps failing with this internal server error. It works in Sonarr, etc.. just not nzbhydra.

I deleted the indexer and retried putting it in again with the exact same result. I have verified the API and it is correct and it has no password on it, just the API key. 

Thanks!

## DEBUG LOG

2016-12-30 17:15:58,762 - DEBUG - search_module - Thread-29 - NZBGeek: Requesting https://api.nzbgeek.info/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=West+World--dxva+--hdscr+--hdrip+--bdrip+--brrip+--webrip+--screener+--dvdscreener+--german+--dutch+--french+--danish+--swedish+--dubbed+--swesub+--korsub+--hsbs with timeout 20
2016-12-30 17:16:04,737 - ERROR - search_module - Thread-29 - NZBGeek: Error while connecting to URL https://api.nzbgeek.info/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=West+World--dxva+--hdscr+--hdrip+--bdrip+--brrip+--webrip+--screener+--dvdscreener+--german+--dutch+--french+--danish+--swedish+--dubbed+--swesub+--korsub+--hsbs: 500 Server Error: Internal Server Error for url: https://api.nzbgeek.info/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=West+World--dxva+--hdscr+--hdrip+--bdrip+--brrip+--webrip+--screener+--dvdscreener+--german+--dutch+--french+--danish+--swedish+--dubbed+--swesub+--korsub+--hsbs
2016-12-30 17:16:04,740 - INFO - search_module - Thread-29 - NZBGeek: Disabling indexer temporarily due to access problems. Will be reenabled in 14 minutes

**Comment by judhat2** [comment]
Nzbgeek has custom code and does things a little bit different.  

First, I notice that there is an error to how nzbhydra is using ignore words with nzbgeek.  It should be `q=query--ignorewords` with the ignore words separated by spaces, without the double dash before each one.  I thought this was already fixed here: https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/searchmodules/newznab.py#L330. Maybe @theotherp can say why that isn't working.  

Second, nzbgeek has a bug with their code that causes the api to fail with more than 12 variables in either inclusion or exclusion. https://nzbgeek.info/showthread.php?tid=6790.

Unless theotherp modifies the code to fix geek's variable limit, you can reduce the amount of ignore words you use, move the ignore words to the category forbidden words, which doesn't get added to query searches, or you can manually edit the code.  If you want to do the latter, try replacing https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/searchmodules/newznab.py#L331 to `query = query` and restart nzbhydra.

**Comment by theotherp** [comment]
@judhat2 I don't understand what it should look like correctly.

**Comment by judhat2** [comment]
Nzbgeek wants it to be like this `&q=West+World--dxva+hdscr+hdrip+bdrip+brrip` with only one double-dash separating the wanted words and the forbidden words.

**Comment by theotherp** [comment]
I don't have access to that forum, is the limit something they can fix and are working on or will that stay?

**Comment by judhat2** [comment]
The admin said in August that it's on the development list to be looked at, but he doesn't know when that will occur.  So, no telling when it will be fixed or if it ever will.

I have many words in my forbidden word list, and I just modify nzbhydra's code after each update in order to skip adding ignore words to nzbgeek.

**Comment by theotherp** [comment]
This solution isn't ideal but it will work for now.

**Comment by judhat2** [comment]
That solution is working well for me.

**Comment by rjsears** [comment]
Thanks @theotherp 

Do I just reinstall to get the changes?

**Comment by rjsears** [comment]
@theotherp is there something else I need to do besides a git pull to get this fixed? I did a git pull, now showing 0.2.181but I still get the error when I try to search via nzbgeek:

### NZBGEEK ERRORS
Connection failed: 500 Server Error: Internal Server Error for url: https://api.nzbgeek.info/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&password=<PASSWORD>&q=West+World--dxva+hdscr+hdrip+bdrip+brrip+webrip+screener+dvdscreener+german

**Comment by rjsears** [comment]
I did verify that the problem is still related to the forbidden words. When I remove then, searching via nzbgeek works just fine, but whatever update you made did not seem to fix the problem for me.

Thanks

**Comment by theotherp** [comment]
I don't have an account for nzbgeek so I can't test it. Don't know what's going on.

**Comment by judhat2** [comment]
I passed this error onto nzbgeek's admin again.  He's looking into it once more.  I'll let you know if it gets fixed, so you can change the code accordingly.
