### ISSUE TITLE
nginx Reverse Proxy using subdomain instead of folder

### ISSUE THREAD

**Issue by microSCOPED** [theotherp/nzbhydra#494]
I am trying to setup a reverse proxy. I use subdomains instead of folders:

nzbhydra.domain.com instead of domain.com/nzbhydra

I can not seem to get it to work, the page just loads a white background and 2 buttons [about checking for updates].

My nginx config looks like:

server {
    listen       <IP>:80;
    server_name  nzbhydra.domain.com;

    ## send request back to sab ##
location / {
     proxy_pass  http://127.0.0.1:5075/nzbhydra/;
     proxy_redirect off;
     proxy_buffering off;
     proxy_set_header        Host            $host;
     proxy_set_header        X-Real-IP       $remote_addr;
     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   }

}

If I set the location to "/nzbhydra/" and set that in the config for the URL base the page loads, but I have to use "search.domain.com/nzbhydra/" - I dont want to use the folder.

What am I missing? Thanks.

**Comment by theotherp** [comment]
Hm, never tested that. Will have to set up a test environment and get back to you.

**Comment by microSCOPED** [comment]
Thanks theotherp. I appreciate it.

**Comment by Torawk** [comment]
I have it setup with apache doing the reverseproxy.  I'm not 100% familiar with nginx, but I'd try changing proxy_pass to just be:

proxy_pass http://127.0.0.1:5075/

then in nzbhydra change the settings so the urlbase is empty.  I'm just getting nzbhydra setup so I haven't tried using any nzbs but I suspect the "External URL" in nzbhydra should be the proxied url (ie: nzbhydra.domain.com).

**Comment by microSCOPED** [comment]
So, I made the following changes:

```
## Start search.domain.com ##
server {
    listen       <IP>:80;
    server_name  search.domain.com;

    access_log  /var/log/nginx/log/search.domain.com.access.log  combined;
    error_log   /var/log/nginx/log/search..domain.com.error.log;

    ## send request back to nzbhydra ##
location / {
     proxy_pass  http://127.0.0.1:5075/;
     proxy_redirect off;
     proxy_buffering off;
     proxy_set_header        Host            $host;
     proxy_set_header        X-Real-IP       $remote_addr;
     proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
   }

}
```
I changed the "URL base"setting to <BLANK>, and the external URL to search.domain.com

when I go to _search.domain.com_ I get the "Welcome to nginx" page BUT if I go to _search.domain.com/nzbhydra_ then it comes up fine. BUT If I click on the "System" tab it loads _search.domain.com/search_ - removes the nzbhydra!
