### ISSUE TITLE
Indexers which don't give the poster cause an error when checking for forbidden posters

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#495]
* What do you expect to happen? What does happen? 

I am getting this error when using a forbidden poster.
```
2016-12-31 15:17:48,368 - ERROR - search_module - Thread-19 - omgwtfnzbs: Error while processing search results from indexer omgwtfnzbs
Traceback (most recent call last):
  File "/nzbhydra/nzbhydra/search_module.py", line 425, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/nzbhydra/nzbhydra/searchmodules/newznab.py", line 475, in process_query_result
    accepted, reason, ri = self.accept_result(entry, searchRequest, self.supportedFilters)
  File "/nzbhydra/nzbhydra/search_module.py", line 251, in accept_result
    if forbiddenPoster in nzbSearchResult.poster:
TypeError: argument of type 'NoneType' is not iterable
```
It shows this error for all of the Jackett torrent trackers and for the indexers that don't give a poster name (omgwtfnzbs and dognzb). Because of this, none of their results are returned in the results. 

I would assume that the same error would appear when using forbidden groups with indexers that don't give a group, like nzb.su.

Here is my log: [logfile.txt](https://github.com/theotherp/nzbhydra/files/679494/logfile.txt)

**Comment by theotherp** [comment]
Argh...

I have fixed it on master without releasing a new version, you'll need to do force pull. I'm having some problems with my git.

**Comment by judhat2** [comment]
Thanks! That fixed it.
