### ISSUE TITLE
System > Log  - Jump to most recent

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#497]
## What do you want to happen?
* Provide a javascript function and button that jumps to the bottom of the log (the most recent) on the Logs page. This is an independent request of #498 , that wether or not the user has the other requested active-refresh enabled,  there would be this GUI button to quickly jump to the bottom of the text field where the logs are displayed.

## If not clear, why do you want it?
* It is time consuming to scroll through the log text field to get to the bottom.

## Do you think it's something only you need or something that might be popular?
* Anyone working to troubleshoot and debug NZBHydra would appreciate this I suspect.

**Comment by albino1** [comment]
Just a thought:

CTRL+End
CTRL+Home

**Comment by YipYup** [comment]
Thanks, but not all keyboards have those buttons :( 
 I'm definitely still looking forward to the web UI button(s).
