### ISSUE TITLE
System > Log - Active Refresh aka Tailing of Log in Web UI.

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#498]
## What do you want to happen?
* Provide a javascript function and button that tails the log display, auto refreshing and auto-jumping to the most recent (bottom of the text field with the most recent entries) when the option is enabled.

## If not clear, why do you want it?
* After refreshing the page to get the latest log output, It is time consuming to scroll through the log text field to get to the bottom.

## Do you think it's something only you need or something that might be popular?
* Anyone working to troubleshoot and debug NZBHydra would appreciate this I suspect.

**Comment by theotherp** [comment]
The last three lines will not be visible when scrolling down. I don't know why.
