### ISSUE TITLE
Adding DogNZB causes NoneType exception

### ISSUE THREAD

**Issue by OmgImAlexis** [theotherp/nzbhydra#500]
I've just used the docker container provided by linuxserverio to setup Hydra, I haven't touched any settings apart from changing the debug log to "on" and setting the theme to "dark".

I went to the indexer page, chose DogNZB, added my API key, my API limit and hit the check capabilities button.

```
2017-01-07 17:11:25,678 - ERROR - newznab - Thread-62 - Error getting or parsing caps XML. Error message: 'NoneType' object has no attribute 'findall'
2017-01-07 17:11:31,510 - INFO - newznab - Thread-63 - Testing connection for host https://api.dognzb.cr
2017-01-07 17:11:36,019 - INFO - newznab - Thread-63 - Unable to log in to indexer https://api.dognzb.cr. Unknown error .
```

[logfile.txt](https://github.com/theotherp/nzbhydra/files/691602/logfile.txt)
[settings.txt](https://github.com/theotherp/nzbhydra/files/691603/settings.txt)

**Comment by theotherp** [comment]
Their API seems to be down or inactive or something. Try again later.

**Comment by OmgImAlexis** [comment]
Seems to be fine via CURL and Medusa(sickrage fork).

Even tried in my browser.
`https://api.dognzb.cr/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxx`

**Comment by theotherp** [comment]
Still?

**Comment by OmgImAlexis** [comment]
I'll have to check as I don't have the container up anymore.

**Comment by mellowpimp** [comment]
i too have this issue with dog.

**Comment by theotherp** [comment]
Yeah, dog sucks ass when combined with Hydra. I don't know why.

See #426

**Comment by dmwyatt** [comment]
Can we get some way to override the fact that Hydra won't do Dognzb id-based searches?  I can hit https://api.dognzb.cr/api?t=caps all day long in my browser and get the caps, but hydra won't do id searches on dognzb because it can't get the caps.

**Comment by Mirabis** [comment]
@dmwyatt can't you manually toggle the id's?

**Comment by dmwyatt** [comment]
@Mirabis well yes I can!  I didn't put two and two together when API searches told me that they wouldn't use dognzb that I had to go in and toggle those search ids...but your comment got me on the right track.

**Comment by preacher65** [comment]
@dmwyatt @Mirabis Apologies for hijacking this but would you mind explaining a little more what you mean by toggle the ids? I've had a look at https://api.dognzb.cr/api?t=caps and on the basis of what it shows I've set these as follows:
![image](https://cloud.githubusercontent.com/assets/11784530/22906779/010c23ac-f23e-11e6-946e-28cc311b8841.png)
Is this (more or less) what you're referring to?
