### ISSUE TITLE
[Maintenance Req] Womble Indexer shut down; Please remove support

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#501]
A little more than a week ago Womble Indexer's homepage displayed an announcement declaring he was shutting down his indexer service as he was not able to keep up with the constant changes required for anti-spam. As of now the host is down completely. He left the message up for just a few days before taking it offline indefinitely.

* It has since been delisted from the Usenet Indexers wiki page on Reddit
https://www.reddit.com/r/usenet/wiki/indexers

* Reddit user thread where a community member first spotted the announcement.
https://www.reddit.com/r/usenet/comments/5l6soy/farewell_wombles_nzb_index/

**Comment by theotherp** [comment]
Yeah, I noticed, haven't gotten to it.
