### ISSUE TITLE
Add small notification for new updates

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra#504]
I just realized that I was many versions behind because I hadn't known there were any new updates. Perhaps add a small notification somewhere on all pages to let the user know when a new update is available? Maybe a little badge over the "System" tab link (similar to how Sonarr does it).

(If this feature was added between 0.2.150 and now, please ignore).

**Comment by theotherp** [comment]
Should've been available a lot longer that that. Upon loading the view there should be a footer with an update notification.

**Comment by whispy** [comment]
I hadn't seen it before, but I will keep an eye out. If it's not persistent, that may be why.

**Comment by theotherp** [comment]
It's possible that your version was affected by a bug. I haven't had any complaints that the feature doesn't work.

If you experience this bug again please let me know. Development is a bit slow at the moment but there should be a new version at least every couple of weeks.
