### ISSUE TITLE
Add Tooltips on Hover of Icons

### ISSUE THREAD

**Issue by whispy** [theotherp/nzbhydra#506]
Add in tooltips that show when hovering over icons with details of what the icons do. Icons are not always sensible to everyone, so this will help with usability and accessibility.

**Comment by whispy** [comment]
Additionally, the icons are very tightly packed. Adding in a few pixels of padding between them would allow them to breathe a bit more.

**Comment by theotherp** [comment]
Which icons?

Am 12.01.2017 4:25 nachm. schrieb "Dan Berkowitz" <notifications@github.com

**Comment by whispy** [comment]
@theotherp, compare (top is with padding added, bottom is as the icons are currently): https://vgy.me/32MDnb.png

**Comment by theotherp** [comment]
Yes I see it.

**Comment by whispy** [comment]
The tooltips all look great! There's a slight bug with the NFO icon's tooltip. See: https://gfycat.com/FrayedImpoliteCockatoo

If the mouse is in the bottom left of the icon, then the tooltip appears steadily. If the mouse is placed elsewhere on the NFO icon, then the tooltip flashes on and off rapidly.

**Comment by theotherp** [comment]
Yeah I know. To fix that I'd need to update a JS library but newer versions break a lot of my code and I already tried once to get it to work and gave up. So currently I'm stuck with it and have no (easy) way of fixing that :-(

**Comment by whispy** [comment]
It looks like the issue is that the tooltip is placed too low over the NFO icon, causing it to intercept the mouseover event which fires the tooltip in the first place. Since we already know what size the NFO icon will be, would it be possible to add a vertical offset based on the icon's height to its tooltip? Maybe something in the tooltip's CSS?

I'm not sure what JS library you're using, so it could be impossible to do with it.
