### ISSUE TITLE
Reverse Proxy, Error reading from remote server

### ISSUE THREAD

**Issue by Vanguard382** [theotherp/nzbhydra#507]
Hello!

Not sure if truly a bug but wasn't sure where too turn to to find out.

I've in the past successfully access and search my nzbhydra setup via my site.server.com/nzbhydra
Not sure if I've done something to break my setup but lately when trying to search via site.server.com/nzbhyra I receive the following error 

Proxy Error
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request GET /nzbhydra/internalapi/search.
Reason: Error reading from remote server

I've tried to confirm my apache setting as well but everything so far appears correct.
I am able to access all other functionality of nzbhydra via my site.server.com/nzbhydra just not searching.
My search results are shown find though if I navigate to site.server.com:port/nzbhydra 

Let me know what logs I can provide or any other setting that I have that are relevant.

Thanks for such a fantastic piece of software!!
Really is great.

**Comment by theotherp** [comment]
Just to be sure, do you call `site.server.com/nzbhydra/`? Note the trailing slash.

**Comment by Vanguard382** [comment]
Thanks for getting back to me and apologizes for bothering you with this on the weekend.

Only receive the error when searching, searches do work properly when started from http://127.0.0.1:port/nzbhydra/

Grabbed the two relevant lines from my Apache config as it appears to be something with my trailing slash

ProxyPassReverse /nzbhydra http://site.server.com:port/nzbhydra/
ProxyPass /nzbhydra http://site.server.com:port/nzbhydra/

I had also tried alerting these to include a slash following "ProxyPassReverse /nzbhydra/" but same result.
Reverse proxy is one of the new things I've begun to play with so sincerely appreciate any/all the feedback/assistance.

**Comment by Vanguard382** [comment]
Help if I read the button more carefully before I clicked too...

**Comment by theotherp** [comment]
`site.server.com/nzbhyra` gives an error when searching but `site.server.com:port/nzbhyra` does not?

**Comment by theotherp** [comment]
Try adding  `retry=1 acquire=3000 timeout=600 Keepalive=On` in your ProxyPass line like so:

```
ProxyPass /nzbhydra/ http://127.0.0.1/nzbhydra/ retry=1 acquire=3000 timeout=600 Keepalive=On
ProxyPassReverse /nzbhydra/ http://127.0.0.1/nzbhydra/
```

**Comment by Vanguard382** [comment]
awesome that line seems to have done that trick!
thanks so much for the time and assistance!
