### ISSUE TITLE
Update fail: "Please, commit your changes or stash them before you can merge."

### ISSUE THREAD

**Issue by jcchristian** [theotherp/nzbhydra#510]
Tried running `git reset --hard` and `git pull` but still doesn't work.

> 2017-01-17 22:37:56,507 - ERROR - update - Thread-444 - "git" pull origin master returned : From https://github.com/theotherp/nzbhydra
>  * branch            master     -> FETCH_HEAD
> error: Your local changes to the following files would be overwritten by merge:
> 	bower.json
> 	changelog.md
> 	nzbhydra/config.py
> 	nzbhydra/indexers.py
> 	nzbhydra/log.py
> 	nzbhydra/searchmodules/anizb.py
> 	nzbhydra/searchmodules/newznab.py
> 	nzbhydra/searchmodules/womble.py
> 	nzbhydra/stats.py
> 	nzbhydra/tests/test_Womble.py
> 	nzbhydra/web.py
> 	static/css/bright.css
> 	static/css/bright.css.map
> 	static/css/dark.css
> 	static/css/dark.css.map
> 	static/css/grey.css
> 	static/css/grey.css.map
> 	static/html/directives/download-history.html
> 	static/html/directives/duplicate-group-row.html
> 	static/html/directives/duplicate-row.html
> 	static/html/directives/indexer-statuses.html
> 	static/html/directives/search-history.html
> 	static/html/directives/search-result.html
> 	static/html/directives/title-row.html
> 	static/html/download-history.html
> 	static/html/indexer-statuses.html
> 	static/html/search-history.html
> 	static/html/states/search-history.html
> 	static/js/alllibs.js
> 	static/js/alllibs.js.map
> 	static/js/nzbhydra.js
> 	static/js/nzbhydra.js.map
> 	ui-src/html/states/search-history.html
> 	ui-src/js/config-fields-service.js
> 	ui-src/js/directives/log.js
> 	ui-src/js/nzbhydra.js
> 	ui-src/js/search-history-controller.js
> 	ui-src/js/stats-service.js
> 	ui-src/less/nzbhydra.less
> 	version.txt
> Please, commit your changes or stash them before you can merge.
> Aborting
> Updating 3633687..2723b7d

**Comment by judhat2** [comment]
try to stash them `git stash` first then do the `git pull`

**Comment by jcchristian** [comment]
When I do a `git stash` it returns:

> root@nzbhydra:/config/hydra# git stash                                                                                                         
>                                                                                                                                                
> *** Please tell me who you are.                                                                                                                
>                                                                                                                                                
> Run                                                                                                                                            
>                                                                                                                                                
>   git config --global user.email "you@example.com"                                                                                             
>   git config --global user.name "Your Name"                                                                                                    
>                                                                                                                                                
> to set your account's default identity.                                                                                                        
> Omit --global to set the identity only in this repository.                                                                                     
>                                                                                                                                                
> fatal: unable to auto-detect email address (got 'root@nzbhydra.(none)')                                                                        
> Cannot save the current index state

What am I supposed to do now?

**Comment by theotherp** [comment]
Most straight forward solution is to backup your data, install again and restore. Or just delete your .git folder. It will do a ZIP based update.

**Comment by jcchristian** [comment]
I renamed my `.git` to `.git_bak` and tried updating and got an error:

> 2017-01-18 19:01:32,775 - ERROR - update - Thread-1852 - "git" pull origin master returned : fatal: Not a git repository (or any parent up to mount point /config)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by dancarroll** [comment]
I'm seeing the same issue, and have also had no luck with any of the workarounds.  The updater is not falling back to a ZIP based update.

**Comment by jcchristian** [comment]
I don't know why, I didn't do anything new, just had the `.git_bak` folder sitting there for the night. Today, I tried updating using the web gui (server:5075/system/updates) and it worked, I'm on 0.2.184 right now!
