### ISSUE TITLE
Time format error from DogNZB

### ISSUE THREAD

**Issue by mattsch** [theotherp/nzbhydra#512]
Started noticing issues today when searching Dog.  Did some digging and noticed this error:

```
2017-01-19 14:18:30,744 - ERROR - search_module - Thread-7 - DogNZB: Error while processing search results from indexer DogNZB
Traceback (most recent call last):
  File "/opt/nzbhydra/app/nzbhydra/search_module.py", line 425, in execute_queries
    parsed_results = self.process_query_result(request.content, searchRequest)
  File "/opt/nzbhydra/app/nzbhydra/searchmodules/newznab.py", line 476, in process_query_result
    entries, total, offset = self.parseXml(xml_response, maxResults)
  File "/opt/nzbhydra/app/nzbhydra/searchmodules/newznab.py", line 501, in parseXml
    entry = self.parseItem(item)
  File "/opt/nzbhydra/app/nzbhydra/searchmodules/newznab.py", line 595, in parseItem
    usenetdate = arrow.get(entry.pubDate, 'ddd, DD MMM YYYY HH:mm:ss Z')
  File "/opt/nzbhydra/app/libs/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/opt/nzbhydra/app/libs/arrow/factory.py", line 195, in get
    dt = parser.DateTimeParser(locale).parse(args[0], args[1])
  File "/opt/nzbhydra/app/libs/arrow/parser.py", line 137, in parse
    raise ParserError('Failed to match token \'{0}\' when parsing \'{1}\''.format(token, original_string))
ParserError: Failed to match token 'Z' when parsing 'Thu, 19 Jan 2017 12:54 PM -0600'
```

Not sure why that changed or if it's an error on their end.

**Comment by dancarroll** [comment]
Noticed this as well.  Manually fetching the API URL works fine, it just seems like they are now sending back a different format in the pubDate element.

Example:
`<pubDate>Thu, 19 Jan 2017 02:27 PM -0600</pubDate>`

**Comment by dancarroll** [comment]
Just submitted a pull request with one potential fix.

If you're looking for a temporary workaround, you can manually edit nzbhydra/searchmodules/newznab.py on your server.  Go to line 595 and change:
`usenetdate = arrow.get(entry.pubDate, 'ddd, DD MMM YYYY HH:mm:ss Z')`
to
`usenetdate = arrow.get(entry.pubDate, ['ddd, DD MMM YYYY HH:mm:ss Z', 'ddd, DD MMM YYYY HH:mm A Z'])`

This change attempts to parse the publish date with two formats -- one being the original, and the second format matching what Dog is currently returning.  I'm running with the change locally, and confirmed that I see results from Dog again.

**Comment by dancarroll** [comment]
Lol, now Dog is just messing with me.  Getting failures again, since they're now using yet another datetime string format (dropped the AM/PM this iteration):

`ParserError: Could not match input to any of [u'ddd, DD MMM YYYY HH:mm:ss Z', u'ddd, DD MMM YYYY HH:mm A Z'] on 'Thu, 19 Jan 2017 20:54 -0600'`

Just updated my pull request with a third format option:
```
            usenetdate = arrow.get(entry.pubDate,
                                   ['ddd, DD MMM YYYY HH:mm:ss Z',
                                    'ddd, DD MMM YYYY HH:mm A Z',
                                    'ddd, DD MMM YYYY HH:mm Z'])
```

**Comment by mattsch** [comment]
Interesting, I'm getting mine in 24-hour format:
`Thu, 12 Jan 2017 13:31 -0600`

Adding that to the list fixed it for me:
`ddd, DD MMM YYYY HH:mm Z`

**Comment by mattsch** [comment]
Heh, yea, Dog is screwing with all of us apparently...

**Comment by dancarroll** [comment]
@mattsch Definitely!  I remember seeing lots of chatter online about issues with Dog + NZBHydra, but not with other applications.  This is probably one of the sources of that problem.

Out of curiousity, I dug in Sonarr's code a bit, since it never seems to have a problem parsing the same results.  Sonarr is written in C# and takes advantage of .NET's [DateTime.Parse](https://msdn.microsoft.com/en-us/library/1k1skd40(v=vs.110).aspx) method, which handily attempts to parse a datetime string with many different format options.  Unfortunately, the Arrow library that NZBHydra is using doesn't seem to have the same flexibility.

**Comment by theotherp** [comment]
I'll get to it this evening.

The problems with Hydra and Dog are usually of a more general nature; connections would time out or something like that, although I've never encountered that. No idea why they would suddenly change their date format.

**Comment by theotherp** [comment]
If you're affected you can do a "Force update" in the system tab or do it manually with Git. I'll increment the version later.

**Comment by judhat2** [comment]
GingaDADDY uses this format 'Fri, 20 Jan 2017 14:01:17 MST'. Is there a way to convert the 'MST'?  As of now, all of their results get discarded, because Hydra can't match MST to Z.

**Comment by dancarroll** [comment]
Here's the documentation for Arrow's datetime parsing: http://crsmithdev.com/arrow/#tokens

Would need to use token 'ZZZ' to match that timezone format.

**Comment by judhat2** [comment]
Thanks, I just noticed that GingaDADDY put their nzb's 'usenetdate' in the api's 'description' attribute, like where dognzb used to put their 'group' attribute (which they don't include anymore).  It's a mess.  I'll see if their admins can update their api.

**Comment by theotherp** [comment]
Dog's API returns empty pages for me. Their server has been getting shittier and shittier. I haven't even extended my VIP because it doesn't work so often.

**Comment by theotherp** [comment]
Fixed for everybody? If not please reopen.
