### ISSUE TITLE
Cannot add new indexer

### ISSUE THREAD

**Issue by anonvoy** [theotherp/nzbhydra#514]
I'm on 0.2.185. On the Config/Indexers page, pressing the "Add new indexer" button used to call up a form where you could input the data for your new indexer and then proceed to test it, add it etc.

Now, pressing that button accomplishes absolutely nothing, no form appears. There is now a drop-down menu to the right with lots of preconfigured indexers, and if I click on one of those, a pre-filled (and pre-named) form for that particular indexer comes up. But I don't want to add one of those preconfigured indexers, I want to add a different one. How do I accomplish that now that pressing said button apparently does not work? I've tested this with three different browsers (Firefox, Chrome, Vivaldi), same results. There is nothing about this in the logs.

**Comment by theotherp** [comment]
You're right, that's a bug. For now just select one of the presets and change the settings accordingly.
