### ISSUE TITLE
[Enhancement] Quick re-search

### ISSUE THREAD

**Issue by leram84** [theotherp/nzbhydra#515]
First of all, am I missing something? The search history tab used to have a magnifying glass button next to each item so you could quickly re search old queries. Since it's gone now, i'm wondering if something else has already been added. Regardless of that, i was going to request a way to add this to the home search page anyway. I OFTEN attempt to search for terms i've already tried, for various reasons. It would be really convenient to have some kind of a drop down, or pop up so we can access that list of old searches in one click from the main page, and select an item to search it again.

**Comment by theotherp** [comment]
No, that's just missing due to the changed search history and I haven't gotten around to add it again.

**Comment by leram84** [comment]
ok, cool... any chance of adding (at least maybe the most recent 20) to some kind of a popup on the home screen? It gets used so much it would be easier if it wasn't buried in the history bar.

**Comment by leram84** [comment]
Nice!

**Comment by theotherp** [comment]
There you go.

**Comment by leram84** [comment]
hahahaha! WHAT?!?!? This is amazing! That was the fastest feature request turnaround i've ever seen! lmfao. THANK YOU!

**Comment by leram84** [comment]
OH! one thing. It's not a big deal, so its really not important to do this if its a lot of work, but if it is an easy fix, it would be better (for the quick search option) to remove duplicates. Since it provides no use, i can't imagine anyone missing it, and it would be better if all 20 were unique queries.

I tend to search the same thing a lot, so like half my quick search list would be the same query.

**Comment by theotherp** [comment]
It's not as straight forward as I thought because it would always hide all but the earliest encounter of a query.

Say your searches are for a, a, b, c, d, a, in that order You would expect the history box to contain "a,d,c,b" (top to bottom). What actually happens (with a simple implementation) is that you get "d,c,b,a" so the latest query would be shown as the last in the history box.

I'll take a look on the weekend, perhaps I can think of a way to get this done quickly.

**Comment by theotherp** [comment]
Got it.

**Comment by leram84** [comment]
HAHA!! wtf dude!! lol works perfectly!

btw... this has been a pretty magical experience. Between running hydra through my domain via nginx, your awesome 1 click upgrade setup, and these ridiculously fast updates, it's a pretty amazing, real time collaboration process. lol. Thanks again!

**Comment by leram84** [comment]
ok, lol, i have one more idea if you're interested. But it's not for me. I personally wouldn't use this, since i automate everything, but i know a lot of people use hydra for everything. If i was still doing everything manually, this would be a really desirable feature: the ability to "pin" searches (or "favorite"). Basically a second list that wouldn't ever change. Just a thought.

**Comment by sumofatguy** [comment]
Would it be possible to have this as a 'per user' history or the ability to disable it all together? I don't want every user to see the last 20 searches from all users

Thanks!

**Comment by leram84** [comment]
huh... yeah, i didn't think of that either. guess it would be a problem if ur sharing sharing hydra
