### ISSUE TITLE
After Loading Backup.zip Getting '500 Internal Server Error'

### ISSUE THREAD

**Issue by terrelsa13** [theotherp/nzbhydra#516]
**After Loading Backup.zip Getting '500 Internal Server Error'**

* What do you expect to happen?
Hydra webpage to load.

* What does happen? 
I get the "500 Internal Server Error"
![screenshot from 2017-01-24 20-37-35](https://cloud.githubusercontent.com/assets/16886488/22276150/50ccef10-e277-11e6-8452-4316534c7629.png)

* Have you searched for this problem?
Yes. Looks like this has happened in the past. But none of the solutions seemed to work.

* You don't have to answer, just make sure.
I suspect after updating there is something wrong/not expected with my settings.

* Can the problem be reproduced?
Yes.

* How?
Fresh install of Hydra loads the webpage. As soon as I restore my previous settings (nzbhydra-backup-2017-01-22-11-09.zip) I get the "500 Internal Server Error"

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**
Can't get to system/bugreport thru the GUI. Is this just the log file /opt/nzbhydra/nzbhyrda.log?

[nzbhydra.log.txt](https://github.com/theotherp/nzbhydra/files/728524/nzbhydra.log.txt)

**Comment by terrelsa13** [comment]
Not a bid deal anymore. I ended up reentering all my indexers manually.

**Comment by theotherp** [comment]
Apparently the old instance was still running. It looks like the actual restoration of the backup had been successful.
