### ISSUE TITLE
Problems with MacOS Sierra - 500: internal server error

### ISSUE THREAD

**Issue by heidundranes** [theotherp/nzbhydra#518]
Hey

I'm having trouble with MacOS Sierra. I did a search but couldn't find a solution. On a fresh install, starting a search yields:

```
500: INTERNAL SERVER ERROR
cannot commit transaction - SQL statements in progress
```

I've tested the available releases and 0.0.1a90 works fine.

It would be great if you could help me out :)

I've attached the log: [log.txt](https://github.com/theotherp/nzbhydra/files/730927/log.txt)

edit: the debug branch version 0.2.142 also works.

**Comment by theotherp** [comment]
Did you try to shutdown Hydra and start again and do another search? Does this happen all the time or just this once?

**Comment by heidundranes** [comment]
On a fresh install it might happen on the first, second or third search. After that it doesn't seem to work, also after restarting.

**Comment by theotherp** [comment]
Hm, that's weird. Sorry, no idea what's going on. I haven't had any reports like that so far. 

If you could do a regression test and narrow down which version started misbehaving that would help a lot. Sorry for the trouble.

**Comment by heidundranes** [comment]
I've tried the releases available on github, and only the first (0.0.1a90) seems to work, as well as the debug version I mentioned. I found this [https://github.com/theotherp/nzbhydra/issues/398](url) report stating that 0.2.147 and 0.2.153 work. Are these and others still available for download?

**Comment by heidundranes** [comment]
/u/eteitaxiv of reddit provided a solution: use homebrew's python instead of the default macOS one.

**Comment by theotherp** [comment]
Great, thanks for proving a solution to your problem.

**Comment by Alrescha-git** [comment]
I have done some testing, it looks like .170 is the last one that works with Sierra's python.

A.
