### ISSUE TITLE
[Enhancement] Add anizb.org index for Anime NZB searching

### ISSUE THREAD

**Issue by EZarnosky** [theotherp/nzbhydra#520]
I recently discovered anizb.org and it has been fairly helpful in my search for anime titles. I can't see anything regarding a API nor a way to contact the site owner but it would be even more useful if it was included in HydraNZB searches.

**Comment by theotherp** [comment]
It's already in there. You can add it as an indexer, click the dropdown next to "Add new indexer" and check the bottom of the list.

**Comment by EZarnosky** [comment]
Dang, sorry about that.

**Comment by theotherp** [comment]
No worries.
