### ISSUE TITLE
[Enhancement] Strip or Replace String from Result(s)

### ISSUE THREAD

**Issue by YipYup** [theotherp/nzbhydra#521]
## What do you want to happen?
Add ability to strip keywords from search results before being sent back downstream in the API to the requesting agent.

## If not clear, why do you want it?
Often times my downstream applications misinterpret a particular release group name, as a release language. For example:

- Some.Public.Access.TV.Show.S05E11.720p.HDTV.x264-NLSubs
- Some.Public.Access.TV.Show.S05E11.720p.HDTV.x264-NL-Subs
- Some.Public.Access.TV.Show.S05E11.720p.HDTV.x264-NL.Sub
- Some.Public.Access.TV.Show.S05E11.720p.HDTV.x264-NLSubs
- Some.Public.Access.TV.Show.S05E11.720p.HDTV.x264-NLSubs

Contrary to the implied name of the release group, the content is neither subtitled, nor is the audio foreign. It is in fact native English audio. However because of the general regex matches used by the downstream search parsers, they are mistakenly ignored due to the perceived language.

## Do you think it's something only you need or something that might be popular?

I believe anytime someone is using Sonarr, SickRage, Sickbeard, or any other variant or fork of the two, that it is common behavior for this poorly named release group to have its releases misinterpreted as indicating a specific language. I've found lots of content is identified improperly due to this.

## If need be explain the use case.

The use case is that without a way to filter out and or replace specific strings, content would never be picked up unless manually identified in the downstream client, which is very tedious.

**Comment by theotherp** [comment]
I wonder if this might cause some issues with the external tools when the downloaded NZB has a different name than the found result.

Example: Sonarr searches for "Show.s01e01.xyz.abc" and you want to remove "abc". Hydra reports a result with the name "Show.s01e01.xyz." and Sonar downloads it. Hydra redirects to your indexer. "Show.s01e01.xyz.abc" is downloaded but Sonarr is looking for ""Show.s01e01.xyz." and won't find it.

Some downloaders provide a unique ID for an NZB and some tools use that, but I guess at least some will be unable to find the downloaded NZB.

Sure, I could rename the NZB when it's proxied, but as that is not the default I'm worried that this would cause a lot of trouble.

How about opening issues for the other tools and ask for special handling of this group?

**Comment by YipYup** [comment]
Let me see if the Sonarr group is willing to address this first, as I generally agree with your logic.
