### ISSUE TITLE
Version 0.2.189: no more question for password?

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#522]
since the update to 0.2.189 i don´t need to login with my  username and password to enter the stats and admin area.
even after logout and rebooting my debian system, there is still no question for password/username. cleaned my browser cache, too. no effect.

**Comment by theotherp** [comment]
Try opening in a private browser window, it should ask you then. You're authenticated with a cookie.

**Comment by theotherp** [comment]
POST YOUR DEBUG INFOS FFS.

**Comment by Hobbabobba** [comment]
when i tried to login this morning to change the settings for a debugfile, i noticed to things:
1. now hydra asks for my password 👍 
2. i can´t login with my password (copy & paste from my password manager, no typo)

when i reinstall hydra and restore from yesterdays backup i should be fine, right?

**Comment by Hobbabobba** [comment]
did a manual update to the new version. can access hydra with my login, but still get 404s when  i try to logout. my debug infos are here https://paste.ee/p/vtlOe and here https://paste.ee/p/ppmmT

**Comment by theotherp** [comment]
You have enabled "Restrict searching" and "Restrict stats" but disabled "Restrict admin". That does not make any sense.

**Comment by theotherp** [comment]
When enabling "Restrict admin" everything works as expected for me.

**Comment by Hobbabobba** [comment]
gotcha - now it works! Thanks!
One last stupid question: if i restore the settings from a backup, will the API key restore from backup, too? Or will nzbhydra generate a new key anyway?

**Comment by theotherp** [comment]
That's the reason I ask for the debugging infos, I could've answered this a lot faster.

The API key is stored in the settings which are also restored, so it should be the same. A restored Hydra instance should be identical to the backed up one, apart from the log files.
