### ISSUE TITLE
Can't login to nzbhydra via reverse proxy since updating to 0.2.189 & 0.2.190

### ISSUE THREAD

**Issue by Githubtordl** [theotherp/nzbhydra#523]
* What do you expect to happen? What does happen? 
 I've been using nzbhydra with my current nginx config for quite sometime now, since upgrading to v0.2.189 and 0.2.190, I can't seem to login when tried to access nzbhydra via reverse proxy, I get the "login failed" message, when I try to log in

 I can login fine when I try to access via the local url

If I **downgrade** to v0.2.188,  I can login via reverse proxy and locally.

* Can the problem be reproduced? How?
Yes, when I upgrade to v0.2.189 or 0.2.190, I can't login to nzbhydra when accessed via reverse proxy (using nginx)

This problem is fixed when downgraded to v0.2.188

Log files:
- Settings: https://paste.ee/p/kZT8s
- Logfile:  https://paste.ee/p/rmr79

The nzbhydra location block in my nginx config:

	location /nzbhydra/ {                             
						proxy_pass http://192.168.0.16:5075/nzbhydra/;
                                               	proxy_set_header Host $host;
                				proxy_set_header X-Real-IP $remote_addr;
                				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
					 } 

**UPDATE:**

I had auth type as 'login form' on nzbhydra, I just tried changing it to 'HTTP basic auth' and it worked! I can login via reverse proxy and locally now. 

Could you please look into this issue? I would like to switch back to 'login form' auth

**Comment by theotherp** [comment]
Works fine on my machine with Apache, will set up nginx and test that.
