### ISSUE TITLE
Categories - Duplicate newznad categories 

### ISSUE THREAD

**Issue by Firemad03** [theotherp/nzbhydra#525]
## Categories - Duplicate newznad categories 

I will try to explain it.

If I put the same newznab categories to the categories Movies for example (7000) and in TV (7000) nzbhydra always check for the categories Movies because both have the same newznab categories.

Sometime the newznab categories others or misc have some releases in it for foreign language.

I checked the Search History and I'm always able to replicate it.

Side question: Do we have a ways to tag Sonarr to a specific category ? Like SABnzbd do ? It can be a workaround ;)

**Comment by theotherp** [comment]
There's no way around that. It's just a matter of which category is shown anyway.

Side answer: no.
