### ISSUE TITLE
Drunken Slug API Host/Link Update

### ISSUE THREAD

**Issue by terrelsa13** [theotherp/nzbhydra#526]
Not really an issue.
Looks like the indexer Drunken Slug has a updated their API host/link.

**Old Drunken Slug link:** https://drunkenslug.com
**New Drunken Slug link:** https://api.drunkenslug.com

![dsapiupd](https://cloud.githubusercontent.com/assets/16886488/22407098/5fb3ed6a-e625-11e6-8392-8df98777e34d.png)

**Comment by theotherp** [comment]
Thanks for the info.
