### ISSUE TITLE
Connection to binsearch.info timed out

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#529]
When looking for something like 'buurman en buurman' binsearch is not returning anything. I am quite sure this worked before.

Is something changed in one of the recent updates?

[nzbhydra-debuginfo-2017-01-30-13-31.zip](https://github.com/theotherp/nzbhydra/files/738891/nzbhydra-debuginfo-2017-01-30-13-31.zip)

**Comment by pven** [comment]
Never mind, binsearch looks down ...

**Comment by theotherp** [comment]
:-)
