### ISSUE TITLE
After getting a windows 10 update, NZBHydra shows paused state

### ISSUE THREAD

**Issue by DarthChowder** [theotherp/nzbhydra#530]
I added NZBHydra as an NSSM service that auto starts with windows. When I log in it should be running and when I got the browser it just works.

ever since I updated window 10 last night, it will not run. When I check the service from task manager is says "paused" in the status field.

I did a quick google of this and couldn't find others reporting this same issue...

I stopped the service and started the service and still same result. I even checked to make sure that the service was setup correctly in NSSM. It seemed to be good.

Any ideas?

**Comment by theotherp** [comment]
Unfortunately I don't have much experience with NSSM. Have you checked the windows log for any entries. Apparently NSSM logs there.

Does running nzbhydra.exe manually work.

**Comment by DarthChowder** [comment]
I figured out for some reason the python wasn't running, I have it working for the moment but have to have that open. I liked it in the background. I'll see about setting all that up again maybe.

**Comment by theotherp** [comment]
You can use the tray tool to keep Hydra in the system tray.

**Comment by Adrian-Rasmussen** [comment]
I also have this issue, having followed the instructions to install as a Windows Service 

> See the WindowsService folder in your NZB Hydra directory. It contains batch scripts to install and uninstall Hydra as a service. Run installService.cmd with administrator rights.) 

Error message that pops up when I try to restart/resume from Windows Services is:

> Windows could not start the NzbHydra service on Local Computer. The service did not return an error. This could be an internal Windows error or an internal service error.

I can open nzbhydra.exe manually.

It looks like it may be the same issue as this: https://github.com/SickRage/SickRage/issues/3070

I'm on Windows 10 Pro, Version 1703 Build 15063.11. I was in the Insider Programme, but have reverted back to release builds recently.

**Comment by theotherp** [comment]
Hey guys, I got a mail from a user who kinda analyzed this. I found a mention of this bug on the nssm website. Could you please uninstall the service and install it again with the bat file in the attached zip? Extract it to the "WindowsService" folder, overwrite the old one. See if you can start the service,

[installService.zip](https://github.com/theotherp/nzbhydra/files/907274/installService.zip)

**Comment by stephbairey** [comment]
I'm having this issue now, after my first reboot in a few weeks. Service remains paused. I can't run nzbhydra.exe manually - I get a cmd screen that closes before any text appears. Running from python itself  this message: 
`PS C:\Program Files (Other)\NZBHydra> c:\python279\python279.exe "c:\Program Files (Other)\NZBHydra\NZBHydra.exe" -d
  File "c:\Program Files (Other)\NZBHydra\NZBHydra.exe", line 1
SyntaxError: Non-ASCII character '\x90' in file c:\Program Files (Other)\NZBHydra\NZBHydra.exe on line 1, but no encodin
g declared; see http://python.org/dev/peps/pep-0263/ for details`

Same without -d. What can I provide to help figure this out? Flowers?

**Comment by theotherp** [comment]
Try changing the install batch file in the Windows service folder as
described here https://nssm.cc/download this was fixed in a current version
of hydra but I had to revert to an older version because of another more
severe problem. I'm currently on vacation and can't provide a proper fix.

**Comment by stephbairey** [comment]
I'm in no rush, but here's my results: nope. I've removed the nssm and replaces with the older version at that link, uninstalled the service then reinstalled with the new version, same error. I set the noappconsole=1, same error. 

Trying to run from command line also doesn't work. Using powershell as administrator, I get:

```
> C:\Program Files (Other)\nzbhydra> c:\python27\python27.exe "c:\Program Files (Other)\NZBHydra\NZBHydra.exe"
>   File "c:\Program Files (Other)\NZBHydra\NZBHydra.exe", line 1
> SyntaxError: Non-ASCII character '\x90' in file c:\Program Files (Other)\NZBHydra\NZBHydra.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by theotherp** [comment]
You cannot start an exe file with Hydra. Just call `c:\Program Files (Other)\NZBHydra\NZBHydra.exe`

**Comment by stephbairey** [comment]
Long delay, sorry.. that is how you run a specific version of python in windows. I run different things written for different versions (would prefer python 3 for instance, but nzbhydra only runs on 2.7) so I have to specify which instance to use.

https://stackoverflow.com/questions/4583367/how-to-run-multiple-python-versions-on-windows
