### ISSUE TITLE
Auto redirect when reverse proxy http_root is set

### ISSUE THREAD

**Issue by supmagc** [theotherp/nzbhydra#531]
I'm using nzbhydra as a plugin for FreeNAS. As such I approach it by hostname on my local network, and throuh a reverse proxy from outside my LAN. Since I don't want to remember the port, I set it to 80, and enabled the http_root for the reverse proxy.

But now I always have to browse to http://host/nzbhydra/ instead of http://host/.

##What do I want to happen?
When enabling the http_root for the reverse proxy, forward all request not using the prefix to the correct url.

##Why do I want it?
I like the reverse proxy feature, but don't want the hassle when approaching nzbhydra directly. I could keep nzbhydra on it's default port, and install nginx next to it, enable the redirect on http://host:80/ to http://host:80/nzbhydra, and have http://host:80/nzhdyra enable a reverse proxy to http://127.0.0.1:5075/nzhdyra, but I'd rather not install another service.

##Would it be a popular feature?
Not entirely sure. It's a very specific usecase. However, some other plugins implement it as well (ex: couchpotato, transmission, ...)

Anyways,
thanks for creating this tool, and your continued effort to improve it!

**Comment by theotherp** [comment]
Unfortunately, this is as good as it gets. I've spent days on the reverse proxy thing to work reasonably well. 

I'm afraid you'll have to go the extra mile and enter 10 characters more.
