### ISSUE TITLE
Empty Query on CP search

### ISSUE THREAD

**Issue by duczz** [theotherp/nzbhydra#532]
You don't have to follow this template by the letter, just think about what you're trying to achieve ;-) 

## How to do a bug report

* What do you expect to happen? What does happen? 
When i search via CP i see a empty Query in the Hydra history, when i search it manuall over the search button on history same problem Requered Word missing - when i search it manual i found files.
The Traceback Error when runs the debug Mode is strange too
[nzbhydra.txt](https://github.com/theotherp/nzbhydra/files/744086/nzbhydra.txt)

* Have you searched for this problem? You don't have to answer, just make sure.
yes
* Can the problem be reproduced? How?
See Step 1
I can show you via TeamViewer if you want
* Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.
Done

**Comment by theotherp** [comment]
**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/system/bugreport).**

**Comment by duczz** [comment]
I get this Error when i wanna use "Log and settings"
An error occured : -1:

**Comment by theotherp** [comment]
In that case open the settings.cfg and remove all your API keys. Post the settings.cfg.

When you searched for "dragonball+battle+of+gods" 10 results were found.

**Comment by theotherp** [comment]
Perhaps you should search for a more known movie to test if it works in general.

**Comment by duczz** [comment]
the problem are not the founded releases, same issue when i search for an other with many results
[settings - Kopie.txt](https://github.com/theotherp/nzbhydra/files/744255/settings.-.Kopie.txt)

**Comment by theotherp** [comment]
Wenn du willst können wir am Wochenende mal chatten, das ist vielleicht einfacher. Ich raff nicht so ganz was das Problem ist ;-)

**Comment by duczz** [comment]
Hehe glaub ich dir, mein english sit nicht so gut um es dir ganz detailiert zu erklären ^^
Gerne ich kanns dir auch via TeamViewer zeigen, gerne auch gleich, jenachdem wie du zeit hast.

**Comment by theotherp** [comment]
Ok, ich sag nochmal Bescheid, wahrscheinlich Sonntag irgendwann.

**Comment by duczz** [comment]
Super, Danke

**Comment by duczz** [comment]
Klappts heute?

**Comment by theotherp** [comment]
Sorry, bin immer noch verkatert. Morgen abend vielleicht.

**Comment by theotherp** [comment]
Hast du Discord?

**Comment by duczz** [comment]
jup

**Comment by theotherp** [comment]
Melde mich heute abend mal, ich weiß meine ID nicht auswendig, vielleicht hab ich zwischen Arbeit und Fußball ne halbe Stunde Zeit.

**Comment by theotherp** [comment]
eQAowlDiz0oFt9xqOyqasXMbqdrtU45b#7269

**Comment by duczz** [comment]
Sorry war die letzten Tage nicht Zuhause, hättest du heute Zeit?
