### ISSUE TITLE
[Suggestion] Search ability should be deactivated when search string is empty

### ISSUE THREAD

**Issue by Antioch18** [theotherp/nzbhydra#533]
## How to request a new feature
* What do you want to happen?

I don't want to mistakenly be able to start a search when the search box is empty.

* If not clear, why do you want it?

Mistaken searches for "" wastes API access and returns a lot of results.

* Do you think it's something only you need or something that might be popular?

Popular

**Comment by theotherp** [comment]
Well, you can use it to get a list of the latest releases...

**Comment by Antioch18** [comment]
Indeed, that is true, but I have never used nzbhydra for browsing, but always as a search engine.

**Comment by theotherp** [comment]
Yeah, I was only half serious. Sure, I can add that.
