### ISSUE TITLE
Updating Hydra, times out every time

### ISSUE THREAD

**Issue by Crowley007** [theotherp/nzbhydra#536]
I'm currently using Hydra as a windows service. Every time I try to update, It times out. Force update is the same. When I manually restart it afterwards, the update gets installed. Not a big deal, but having it restart automatically would save some time and trouble.

These show up in the log: `2017-02-01 18:49:28,944 - ERROR - update - Thread-258 - Error while trying to update: [Error 5] Access is denied: 'C:\\Apps\\nzbhydra\\WindowsService\\nssm.exe'
2017-02-01 18:50:45,789 - ERROR - update - Thread-268 - Error while trying to update: [Errno 13] Permission denied: 'lxml.etree.pyd.updated'`

**Comment by muok** [comment]
I have the exact same issue.

**Comment by theotherp** [comment]
I actually never tested updating when run as a windows service. Entirely possible that it doesn't work at all. I'll do some tests on the weekend.

**Comment by theotherp** [comment]
Alright, the solution is a bit hacky. See the changelog. Shutdown the service and update the files manually. Change the service so that it runs with your windows user. This will allow Hydra to change its own files. The next update after this should hopefully work.

**Comment by Crowley007** [comment]
It sort of works now. It still throws time out errors, but after a couple of refreshes it is running the newer version.
