### ISSUE TITLE
[Feature Request] Name-Based Fallback Query Option

### ISSUE THREAD

**Issue by Alamei** [theotherp/nzbhydra#540]
While running a battery of tests, I discovered that Sonarr would often return a significant number of results for less popular series when I had it query indexers directly, yet those same results would fail to show up when I had it run the query against Hydra. At first I assumed it was just one of my filtering settings that was stripping the records out, but when I checked Hydra's logs, I saw that it wasn't getting any results from most of the indexers in the first place. Curious as to how Sonarr was managing to pull records that Hydra wasn't, I looked into Sonarr's logs, and I discovered that Sonarr appears to have a sort of fallback routine in place for its queries: Specifically, if an indexer returns zero records for an episode based on an ID pull, it re-sends the query to that indexer using the series name instead of the IDs (one query per alias if the series has multiple names). This functionality works nicely when you have all the individual indexers returning results separately, but obviously falters if you're merging results, since even one indexer returning one file will make the request appear fulfilled.

Given that Hydra already has the ability to generate name-based queries from IDs, would it be possible to add an option to use that functionality to perform fallback queries, resubmitting a search using the names/aliases if no results are returned from an ID-based query? It makes a huge difference with less popular series that apparently aren't mapped to IDs on most indexers. The name-based queries would obviously increase the number of API calls and lower accuracy to some extent, so the option should probably be turned off by default, but it could be a real boon for users that understand the implications and are comfortable making the trade-off.

**Comment by theotherp** [comment]
That's an interesting analysis and feature proposal, thanks for that.

I also noticed that Sonarr would sometimes do queries with series names using the newznab "tvsearch" action (which I previously didn't know even worked) but never made a connection.

I don't think this would be too complicated to implement, everything I need is already there.

**Comment by Alamei** [comment]
Commit e0091a9554e0e1f38a13288357a23e0a47caf518 helps with instances where none of the indexers have an ID mapped, but the fallback still won't trigger in the more common instance where one or more indexers have the ID mapped and the rest don't. 

As an example, let's say you have five theoretical indexers, A-E. If Hydra queries all five with an ID and receives 0 results from indexers A, B, C and E, but receives 1 result from indexer D, Hydra currently considers the whole request successfully fulfilled. To allow for varying levels of mapping accuracy among indexers, the fulfillment status would have to be determined at a more granular level. E.g., the request would be considered fulfilled _from indexer D_ because of its non-zero result set, but the request is reformatted and re-sent to A, B, C and E due to their null return sets.

**Comment by theotherp** [comment]
I'm aware of the limitations but chose this way because the other would be vastly more complicated.

**Comment by theotherp** [comment]
Hm maybe not that complicated. I'll think about it.

**Comment by Alamei** [comment]
I completely understand if it's too much hassle to implement the granular fallback on your end. Since I may be one of the few users that would rely on this feature, I'll see if I can find some time to build and integrate it and send a pull request.

**Comment by theotherp** [comment]
Good luck understanding that code :-)

I'll push a small patch in a couple of minutes for this feature.

**Comment by Alamei** [comment]
Your code is just fine to read. I'm used to working with single-owner projects where there aren't a lot of comments; it just requires a little looking about.

#557 gets the fall-back title queries running properly and allows per-indexer triggering.

While running comparisons between Hydra and other apps to test the changes, I realized that most of the other apps I use actually send all of the available IDs with the query, to allow matches on any of them (e.g., if Rage, TVDB and TVMaze IDs are available, it just sends them all with the the same query string, which newznab apparently treats as a non-exclusive OR search). It might make sense to have Hydra try to do the same as a mechanism to improve the chance of getting results before even needing to fall back to title searches.
