### ISSUE TITLE
Request: Add API grab limit

### ISSUE THREAD

**Issue by creoden** [theotherp/nzbhydra#541]
I appreciate the api hit limit, but is there a way to add an API Grab limit? So the indexer is shut off for X minutes/hours till it resets.

I have 2 indexers who allow 10 times more hits than grabs per day, and a few times now, when sickrage has done it's quality baklog it will hit the max grabs causing everything to error out, and since it keeps hitting the indexer, the max grabs never has a chance to reset.

**Comment by theotherp** [comment]
See #247
