### ISSUE TITLE
nzbhydra and reverse proxy

### ISSUE THREAD

**Issue by janipewter** [theotherp/nzbhydra#546]
My apache web and reverse proxy server is at 192.168.10.21

I have all of my usenet related services set up across two servers (192.168.10.22 and 192.168.10.23) and the reverse proxy has entries for all of them. I am using SSL certificates from Lets Encrypt. The proxy server is the only one visible to the outside internet and it is hidden behind cloudflare as I do not wish to reveal the origin server public IP.

The services are each accessed using a subdomain of my main domain; all of these subdomains resolve externally (through cloudflare) and internally (through local IP DNS entries in my firewall) to the proxy server.

I want to have nzbhydra at https://search.mydomain.com and not have to use a subdirectory but I am running into some issues which it creates between nzbhydra and nzbget.

Originally I was running the reverse proxy on the same machine which ran nzbhydra and nzbget (192.168.10.22) but I have now offloaded the proxying to a separate machine for other reasons. It worked perfectly when the proxy was on the same machine as hydra and nzbget.

The apache configuration is like this (unnecessary stuff removed):

```
<VirtualHost *:443>
ServerName search.mydomain.com
DocumentRoot /var/www/html
ProxyPreserveHost On
# setup the proxy
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>
ProxyPass / http://192.168.10.22:5075/
ProxyPassReverse / http://192.168.10.22:5075/
</VirtualHost>

```

I can access hydra fine using https://search.mydomain.com which is what I want and expect. The search works fine but if I try to send a file to nzbget, it sits in nzbget as "Fetching" and the messages screen fills up with "Connection to search.mydomain.com failed: ErrNo 111, Connection refused"

Now I assume nzbget is somehow trying to directly communicate with hydra BUT it will not work this way because that url (search.mydomain.com) resolves to the proxy server NOT the server running hydra. There is nowhere in the nzbget configuration where that hostname is entered so it must be getting it through the API calls from hydra I guess. If I access hydra directly like at 192.168.10.22:5075 and try downloads, it works fine with nzbget.

Now I saw the options in hydra about reverse proxy and I tried various configurations and couldn't get the results I wanted. At first I tried setting the URL base to just / and the External URL to https://search.mydomain.com/ but this didn't work. When I tried to access it I just had the update button and a link to the changelog and nothing else. So then I found some other post saying to set the URL base to /nzbhydra/ and the External URL to https://search.mydomain.com/nzbhydra but then I could only access it by going to https://search.mydomain.com/nzbhydra which I do not want. Regardless, it still had the same issue with nzbget. I tried setting the ProxyPass and ProxyPassReverse to http://192.168.10.22:5075/nzbhydra but this also didn't work.

No combination of configuration would work for me the way I want it to so at the moment I am stuck with accessing hydra directly with the IP. This is fine for home use (albeit annoying as I always forget the port) but obviously I cannot access it from the outside internet like this.

I appreciate any help you can offer, thanks

**Comment by theotherp** [comment]
Try setting the "NZB adding type" in the downloader section to "Upload NZB".

**Comment by janipewter** [comment]
That worked. Thanks!
