### ISSUE TITLE
Download all NZB's with one click

### ISSUE THREAD

**Issue by pven** [theotherp/nzbhydra#550]
Hi,

Sometimes I want to spread some NZB's. When I search and I have multiple hits, I need to download them one-by-one. I would really like some kind of 'download all nzb-files'-button.

Thanks!

**Comment by theotherp** [comment]
I considered that when I started NZBHyda and disregarded it as too complex. But the software is already so much bigger and more complicated that I've every dreamed so why not. I'll see what I can do.

**Comment by pven** [comment]
Thanks for the update!
