### ISSUE TITLE
Category min and max sizes not effective for API calls

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#551]
* What do you expect to happen? What does happen? 

 I have set my "Movies HD" category sizes to 3000 min and 20000 max. When an api call is sent to NZBHydra from Radarr, Hydra returns results that go beyond the min and max size requirements. Following this url in my browser also shows those unwanted sizes. 
http://127.0.0.1:5075/api?t=movie&cat=2000,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0468569

Are those size requirements only for internal searches?  Does anyone else experience this?

Here is my debug info: [logfile.txt](https://github.com/theotherp/nzbhydra/files/780751/logfile.txt) [settings.txt](https://github.com/theotherp/nzbhydra/files/780752/settings.txt)

I also noticed in the log that it list the attributes that the api call gives. Such as `API request: {u'minsize': None, u'raw': 0,...}`.  So, I added `&minsize=5000000000000` to the api call to see if it would affect it.  It changed in the log to `API request: {u'minsize': 5000000000000, u'raw': 0,...}`, but it didn't limit the results.  I don't know if that is supposed to work or not.

Edit: It looks like the category size restrictions aren't working for me for through the web interface either.

**Comment by theotherp** [comment]
It says "Size preset" because it's the value that's prefilled in the boxes when the category is selected. They're not meant to be restrictions for API calls in that category. I could change that but it might need some work.

The newznab API standard does not support providing min or max size so that's why setting it doesn't change anything beyond the log output.

**Comment by theotherp** [comment]
I'll add min/max age/size support to API calls in case some tools run specifically against Hydra so they can use it.

**Comment by judhat2** [comment]
ah, ok.  I didn't comprehend that it was only a preset for when searching tha category in the web interface.  It makes sense now. 

I don't know of any tools that use that, but I would be able to add it as an additional parameter in Radarr's indexer config, if you decide to implement it. It could be handy filtering some results. Thanks!

**Comment by judhat2** [comment]
Just tried this in Radarr, and it's working as expected!

**Comment by theotherp** [comment]
Great. Closing this.
