### ISSUE TITLE
NZBHydra won't start, logger TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by weirdcrap** [theotherp/nzbhydra#559]
I have NZBHydra running on Ubuntu 16.04LTS behind an NGINX reverse proxy with Python 2.7.12.

I updated NZBHydra today from 0.2.182 to 0.2.205 using the built in updater and now I can't get the web interface to come back up at all. This is the relevant piece of the log:

2017-02-18 14:05:35,361 - ERROR - nzbhydra - MainThread - Fatal error occurred
Traceback (most recent call last):
  File "/opt/nzbhydra/nzbhydra.py", line 190, in run
    logger.notice("Starting web app on %s:%d" % (f.host, f.port))
TypeError: %d format: a number is required, not NoneType
2017-02-18 14:05:35,361 - INFO - nzbhydra - Dummy-3 - Exit registered. Shutting down database...
2017-02-18 14:05:35,362 - INFO - nzbhydra - Dummy-3 - Database shut down

I attempted to download a new copy and restore from backup and I receive the same error.

It sounds like something about my logging options has broken Hydra?

These are my logging settings if they help at all:
"logging": {
            "consolelevel": "INFO",
            "keepLogFiles": 10,
            "logIpAddresses": true,
            "logMaxSize": 1000,
            "logRotateAfterDays": null,
            "logfilelevel": "INFO",
            "logfilename": "nzbhydra.log",
            "rolloverAtStart": false
        },

**Comment by weirdcrap** [comment]
I managed to get it up and working by changing:
logger.notice("Starting web app on %s:%d" % (f.host, f.port))

To:
logger.notice("Starting web app on %s" % (f.host))

**Comment by theotherp** [comment]
Hope it's fixed now, sorry about that.

**Comment by weirdcrap** [comment]
Thanks for the quick fix! Everything appears to be working with the new update.
