### ISSUE TITLE
Reverse proxy not working with subdirectory

### ISSUE THREAD

**Issue by usntanon** [theotherp/nzbhydra#56]
Hello,

Reverse proxy seems to be working fine when using a dedicated subdomain, but when trying to use a subdirectory things begin to break.  I have all my usenet apps under the same subdomain like:
nzb.example.com/sabnzbd
nzb.example.com/sickbeard
so i was hoping to have /hydra, but that leads to the page looking like:
![screenshot from 2015-12-17 08 47 39](https://cloud.githubusercontent.com/assets/16337273/11871080/f41f0282-a49a-11e5-8889-734edcbf47a8.png)
because it assumes all the links are located at /
I tried setting the baseurl to nzb.example.com/hydra, but everything after the slash appears to be stripped out.  Would it be possible to also add a basedir configuration option?

**Comment by theotherp** [comment]
There is a setting in the main category for exactly this usecase.

**Comment by usntanon** [comment]
Sorry about missing that.  What is it labelled as?

**Comment by theotherp** [comment]
No, sorry, I misread. That base URL setting is the only one and it looks like mine.
Try adding a trailing backslash in apache (for ProxyPass and ProxyPassReverse).

**Comment by theotherp** [comment]
My apache conf:

```
 SSLProxyEngine On
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerExpire off
      SSLEngine on
       SSLCertificateFile /etc/apache2/ssl/server.crt
       SSLCertificateKeyFile /etc/apache2/ssl/server.key
       SSLProtocol all -SSLv2 -SSLv3
       SSLHonorCipherOrder On
SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 \
EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 \
EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS"

    ProxyPass /nzbhydra/ http://localhost:5060/nzbhydra/
    ProxyPassReverse /nzbhydra/ http://localhost:5060/nzbhydra/
```

Well look at that, I don't even use ProxyPreserveHost...

**Comment by usntanon** [comment]
Ah, so there's the issue, it works fine as long as you use nzbhydra as the subdirectory.
![screenshot from 2015-12-18 10 23 37](https://cloud.githubusercontent.com/assets/16337273/11900070/70235d7a-a571-11e5-900e-d56d57f9e190.png)
I can live with the subdirectory being nzbhydra, but this might still be a bug if you want to allow different ones.

**Comment by theotherp** [comment]
Uhm that's weird. No idea why. Will try to fix that.

**Comment by theotherp** [comment]
Please try the web.py from d490cc6bf4cb64d0056241261451449fc7964c46
It works fine for me with /nzbhydra/ and /hydra/

Thanks.

**Comment by usntanon** [comment]
Works great, only issue is that it requires a trailing slash when visiting the root (search) page.  Otherwise you end up with:
![screenshot from 2015-12-18 11 31 31](https://cloud.githubusercontent.com/assets/16337273/11901697/f37be2d8-a57a-11e5-8ecb-559f38bc8857.png)
megasearch also had this issue, but it can be worked around using:
```
RewriteCond %{REQUEST_URI} !^/mega/
RewriteRule ^(.*)$ /mega/ [R=301,L]
```
in the Apache proxy directive.

**Comment by usntanon** [comment]
Applying d490cc6 to the changes made in 81144af seems to fix this.

**Comment by theotherp** [comment]
That error was probably a result of an inconsistent code due to changes in master that weren't included in develop or vice versa.

Closing this but will work on the trailing slash thing.
