### ISSUE TITLE
login failed 

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#561]
Using username pass from settings.cfg

after restarting i only get this msg 
`maySeeDetailsDl`

Log 

> 2017-02-19 16:11:32,035 - ERROR - web - Thread-16 - u'maySeeDetailsDl'
> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
>     return f(*args, **kwargs)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 459, in base
>     bootstrapped = getUserInfos(user)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 177, in getUserInfos
>     maySeeDetailsDl = user["maySeeDetailsDl"] or not detailsDlRestricted
> KeyError: u'maySeeDetailsDl'

**Comment by theotherp** [comment]
Did you create a new user with one of the latest versions?

**Comment by theotherp** [comment]
Anyway, you can fix it by adding the line
`"maySeeDetailsDl": true,`
and, if missing,
`"showIndexerSelection": true,`
to all users in your settings.cfg

**Comment by ajkis** [comment]
Thanks thats fixed the problem.
