### ISSUE TITLE
Ubuntu 16.04 service file fails to start: nzbhydra.service: Start request repeated too quickly.

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#564]
Error when starting service:  nzbhydra.service: Start request repeated too quickly.

If i start it in terminal (with same path/params) it works:

> /usr/bin/python2.7 /opt/nzbhydra/nzbhydra.py --daemon --nobrowser --pidfile /opt/nzbhydra/nzbhydra.pid
> 2017-02-20 12:39:08,511 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.206
> 2017-02-20 12:39:08,511 - NOTICE - nzbhydra - MainThread - Base path is /opt/nzbhydra
> 2017-02-20 12:39:08,512 - NOTICE - nzbhydra - MainThread - Loading settings from /opt/nzbhydra/settings.cfg
> 2017-02-20 12:39:08,515 - INFO - log - MainThread - None
> 2017-02-20 12:39:08,515 - INFO - nzbhydra - MainThread - Started
> 2017-02-20 12:39:08,516 - INFO - nzbhydra - MainThread - Daemonizing...
> 

Service file 

> [Unit]
> Description=NZBHydra Daemon
> Documentation=https://github.com/theotherp/nzbhydra
> After=network.target
> 
> [Service]
> User=plex
> Group=plexe
> Type=forking
> 
> ExecStart=/usr/bin/python2.7 /opt/nzbhydra/nzbhydra.py --daemon --nobrowser --pidfile /opt/nzbhydra/nzbhydra.pid
> PIDFile=/opt/nzbhydra/nzbhydra.pid
> KillMode=process
> Restart=always
> SuccessExitStatus=6
> RestartPreventExitStatus=6
> 
> [Install]
> WantedBy=multi-user.target

**ERROR**
> sudo systemctl start nzbhydra.service
> Job for nzbhydra.service failed because the control process exited with error code. See "systemctl status nzbhydra.service" and "journalctl -xe" for details.
> systemctl status nzbhydra.service
>  nzbhydra.service - NZBHydra Daemon
>    Loaded: loaded (/etc/systemd/system/nzbhydra.service; enabled; vendor preset: enabled)
>    Active: inactive (dead) (Result: exit-code) since Mon 2017-02-20 12:38:26 CET; 4s ago
>      Docs: https://github.com/theotherp/nzbhydra
>   Process: 16012 ExecStart=/usr/bin/python2.7 /opt/nzbhydra/nzbhydra.py --daemon --nobrowser --pidfile /opt/nzbhydra/nzbhydra.pid (code=exited, status=216/GROUP)
>  Main PID: 9497 (code=exited, status=216/GROUP)
> Feb 20 12:38:25 flix systemd[1]: Failed to start NZBHydra Daemon.
> Feb 20 12:38:25 flix systemd[1]: nzbhydra.service: Unit entered failed state.
> Feb 20 12:38:25 flix systemd[1]: nzbhydra.service: Failed with result 'exit-code'.
> Feb 20 12:38:26 flix systemd[1]: nzbhydra.service: Service hold-off time over, scheduling restart.
> Feb 20 12:38:26 flix systemd[1]: Stopped NZBHydra Daemon.
> Feb 20 12:38:26 flix systemd[1]: nzbhydra.service: Start request repeated too quickly.
> Feb 20 12:38:26 flix systemd[1]: Failed to start NZBHydra Daemon.
> plex@flix /opt/Radarr $ < 12:38:30 > journalctl -xe
> -- Subject: Process /usr/bin/python2.7 could not be executed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- The process /usr/bin/python2.7 could not be executed and failed.
> --
> -- The error number returned by this process is 3.
> Feb 20 12:38:25 flix systemd[1]: Starting NZBHydra Daemon...
> -- Subject: Unit nzbhydra.service has begun start-up
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit nzbhydra.service has begun starting up.
> Feb 20 12:38:25 flix systemd[1]: nzbhydra.service: Control process exited, code=exited status=216
> Feb 20 12:38:25 flix systemd[1]: Failed to start NZBHydra Daemon.
> -- Subject: Unit nzbhydra.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit nzbhydra.service has failed.
> --
> -- The result is failed.
> Feb 20 12:38:25 flix systemd[1]: nzbhydra.service: Unit entered failed state.
> Feb 20 12:38:25 flix systemd[1]: nzbhydra.service: Failed with result 'exit-code'.
> Feb 20 12:38:26 flix systemd[1]: nzbhydra.service: Service hold-off time over, scheduling restart.
> Feb 20 12:38:26 flix systemd[1]: Stopped NZBHydra Daemon.
> -- Subject: Unit nzbhydra.service has finished shutting down
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit nzbhydra.service has finished shutting down.
> Feb 20 12:38:26 flix systemd[1]: nzbhydra.service: Start request repeated too quickly.
> Feb 20 12:38:26 flix systemd[1]: Failed to start NZBHydra Daemon.
> -- Subject: Unit nzbhydra.service has failed
> -- Defined-By: systemd
> -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
> --
> -- Unit nzbhydra.service has failed.
> --
> -- The result is failed.

**Comment by theotherp** [comment]
Try removing `--daemon`

**Comment by ajkis** [comment]
Same error.

**Comment by judhat2** [comment]
Can you start it via the command line?  Try it and see if you get any error starting it that way.  
`/usr/bin/python2.7 /opt/nzbhydra/nzbhydra.py --nobrowser --pidfile /opt/nzbhydra/nzbhydra.pid`

Also, your group name in your service file is "plexe". Is that right or is it supposed to be plex?

**Comment by theotherp** [comment]
No idea, sorry.

Thanks for jumping in, @judhat2

**Comment by ajkis** [comment]
Fixed, there were some typos in service files.
