### ISSUE TITLE
on search : An error occured : 500: INTERNAL SERVER ERROR  Error binding parameter 0 - probably unsupported type.

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#565]
I added couple of indexers ( tests passed ), updated today to latest verion. 

This is the error in log I get on search 

> 2017-02-20 13:15:55,280 - DEBUG - web - Thread-257 - Call to method internalapi_search_requestsforsearching
> 2017-02-20 13:15:55,280 - DEBUG - web - Thread-257 - Requiring auth for method internalapi_search_requestsforsearching
> 2017-02-20 13:15:55,283 - ERROR - web - Thread-257 - Error binding parameter 0 - probably unsupported type.
> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 407, in wrapped_function
>     return f(*args, **kwargs)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 1126, in internalapi_search_requestsforsearching
>     return jsonify(get_search_requests(1, 20, sortModel=None, filterModel=filterModel, distinct=True, onlyUser=limitToUser))
>   File "/opt/nzbhydra/nzbhydra/stats.py", line 393, in get_search_requests
>     total_requests = query.count()
>   File "/opt/nzbhydra/libs/peewee.py", line 3074, in count
>     return self.wrapped_count(clear_limit=clear_limit)
>   File "/opt/nzbhydra/libs/peewee.py", line 3087, in wrapped_count
>     return rq.scalar() or 0
>   File "/opt/nzbhydra/libs/peewee.py", line 2842, in scalar
>     row = self._execute().fetchone()
>   File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
>     self._wait()
>   File "/opt/nzbhydra/libs/playhouse/sqliteq.py", line 53, in _wait
>     raise self._exc
> InterfaceError: Error binding parameter 0 - probably unsupported type.
> 2017-02-20 13:16:44,681 - DEBUG - web - Thread-259 - Call to method internalapi_askAdmin
> 2017-02-20 13:16:44,682 - DEBUG - web - Thread-259 - Requiring auth for method internalapi_askAdmin
> 2017-02-20 13:16:44,683 - DEBUG - web - Thread-259 - Get askadmin request
> 2017-02-20 13:16:46,201 - DEBUG - web - Thread-261 - Call to method internalapi_getlogs
> 2017-02-20 13:16:46,201 - DEBUG - web - Thread-261 - Requiring auth for method internalapi_getlogs
> 2017-02-20 13:16:46,201 - DEBUG - log - Thread-261 - Reading log file nzbhydra.log
>

**Comment by theotherp** [comment]
No idea what's causing that and I can't reproduce.

**Comment by ajkis** [comment]
Me neither it was during that lost records in DB; now its working as it should. 

p.s. Is there some special setting as Radarr now searchs for movies but on download it does not send request to nzbget ( in logs is sending but nzbget never receive anything )

**Comment by theotherp** [comment]
Nothing special there. See the download history if the download was requested and the radarr log for errors.
