### ISSUE TITLE
Adding to Sonarr/Radarr ( No results were returned from your indexer, please check your settings.)

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#566]
Cant add Nzbhydra to indexers 
URL: IP:port
API key:  xxx ( Copy pasted from Main -> Security )

I changed my default port ( not firewall is running ) and Sonarr/Radarr are installed on same server Ubuntu 16.04.

**Comment by theotherp** [comment]
That's a horrible description. What do you mean that you can't add it? What error do you get? Do applications' logs show anything?

**Comment by ajkis** [comment]
My bad, sonarr log: HTTP Error - Res: [GET] http://xxx/api?t=caps&apikey=(removed) 401.Unauthorized

**Comment by theotherp** [comment]
Can you call that from your browser?

**Comment by ajkis** [comment]
No, what is URL for nzbhydra since its now answering on /api? ...

**Comment by theotherp** [comment]
What? Enter  http://xxx/api?t=caps&apikey=(removed) with your actual domain/ip, port and apikey in your browser's address bar...

**Comment by ajkis** [comment]
That was my first try. 
Sonarr error log
> 	Invalid request Validation failed: 
>  -- No results were returned from your indexer, please check your settings.

But if i visit it in browser i get proper XML 

> <caps>
> <server appversion="0.0.1" version="0.1" title="NZBHydra" email="theotherp@gmx.de" url="https://github.com/theotherp/nzbhydra"/>
> <limits max="100" default="100"/>
> <retention days="2500"/>
> <searching>
> <search available="yes" supportedParams="q"/>
> <tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep"/>
> <movie-search available="yes" supportedParams="q,imdbid"/>
> <audio-search available="no"/>
> <book-search available="yes"/>
> </searching>
> <categories>
> <category id="1000" name="Gaming">
> <subcat id="1010" name="NDS"/>
> <subcat id="1020" name="PSP"/>
> <subcat id="1030" name="Wii"/>
> <subcat id="1050" name="Xbox 360"/>
> <subcat id="1080" name="Playstation 3"/>
> <subcat id="4050" name="PC"/>
> </category>
> <category id="2000" name="Movies">
> <subcat id="2010" name="Foreign"/>
> <subcat id="2020" name="Other"/>
> <subcat id="2030" name="SD"/>
> <subcat id="2040" name="HD"/>
> <subcat id="2050" name="BluRay"/>
> <subcat id="2060" name="3D"/>
> <subcat id="2070" name="Mobile"/>
> </category>
> <category id="3000" name="Audio">
...

**Comment by theotherp** [comment]
>  -- No results were returned from your indexer, please check your settings.

is a different error. You probably haven't configured any proper indexers in Hydra or haven't enabled query generation.

**Comment by ajkis** [comment]
Well i have indexers and they passed test when adding them. 
( except dognzb.cr so its disabled )

As for query generation where do I add that ?

**Comment by theotherp** [comment]
Does  http://xxx/api?t=tvsearch&apikey=(removed) (with proper parameters) return anything?

**Comment by ajkis** [comment]
Sec I just noticed that after restarting hydra ( when i was trying to start it with systemd ) deleted all my indexers. adding them again.

**Comment by ajkis** [comment]
Yea after readding all indexers the problem is fixed, not sure how they disapeared but it happend when i shut it down and try to run it in service file without --daeamon.
