### ISSUE TITLE
Can't download from sonarr/radarr: "request Failed: Invalid URI: The URI is empty"

### ISSUE THREAD

**Issue by seanvree** [theotherp/nzbhydra#569]
OS:  Windows 10E
webserver:  IIS 10
NZBHydra Ver: 0.2.207 (Running as SYSTEM service)

Issue:

When I do a manual search for a release, sonarr/radarr finds a release, but when I click to download form NZBhydra, I get the error: "Request Failed: Invalid URI: The URI is empty"

This started when I was trying to configure the Reverse Proxy function.  Reverse proxy IS working for NZBHydra. However, Sonarr and Radarr are accessing NZBH via LAN (They are on the same box)

Both work for downloading directly from any nzb indexer.

Settings:
Sonarr/Radarr: Indexer: Newznab:
URL: http://192.168.1.20:5075/nzbhydra/
API Key: REDACTED

Settings: NZBHydra:
Host: 192.168.1.20
URL Base:  /nzbhydra/
Port: 5075
ExternalURL:  HTTPS://DOMAINNAME.com/Nzbhydra/ (Works) (SSL Enabled on webserver)
Use local address in API Results: ON (however have tried both)
SSL:  OFF

SETTINGS:
HTML parser: LXML
NZB Access type:  Proxy NZBs from Indexer (however, have tried both)

Logs;

No logs appear in NZBHydra. However, here are the logs from Sonarr/Radarr:

Here's my log:
sytstem.UriFormatException: Invalid URI: The URI is empty. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) at System.Uri..ctor(String uriString) at NzbDrone.Common.Http.HttpClient.PrepareRequestCookies(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 121 at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 68 at NzbDrone.Common.Http.HttpClient.Get(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 193 at NzbDrone.Core.Download.UsenetClientBase1.Download(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\UsenetClientBase.cs:line 43 at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\DownloadService.cs:line 66 at NzbDrone.Api.Queue.QueueActionModule.Grab() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:line 108 at NzbDrone.Api.Queue.QueueActionModule.<.ctor>b__7_2(Object x) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Api\Queue\QueueActionModule.cs:line 41 at CallSite.Target(Closure , CallSite , Func2 , Object ) at Nancy.Routing.Route.<>cDisplayClass4.<Wrap>b3(Object parameters, CancellationToken context

**Comment by theotherp** [comment]
http://192.168.1.20:5075/nzbhydra/api?t=tvsearch&apikey=<apikey)

What do the links look like?

**Comment by seanvree** [comment]
@theotherp I was a little confused how to find the exact link, but if I right click and hit copy link address, this is what I get:

Just one example

https://api.nzbplanet.net/details/a6ae8715de59b3a38b30b314c01fbe2c

**Comment by theotherp** [comment]
Uhm no, the links should look like  http://192.168.1.20:5075/nzbhydra/getnzb?apikey=apikey&searchresultid=<some-alphanumeric>

Right click, select "Show page source" (or something like that) and post one of the "item" elements. Remove the API key.

It should look a bit like this:

```
<item>
                <title>Pandemien.Die.Menschheit.in.Gefahr.DL.German.DOKU.720p.HDTV.x264-UTOPiA</title>
                <guid isPermaLink="false">ID</guid>
                <link>http://192.168.1.20:5075/nzbhydra/getnzb?apikey=APIKEY&amp;searchresultid=ID</link>
                <comments>https://nzbs.org/details/ID</comments>
                <pubDate>Sun, 26 Feb 2017 12:09:29 +0000</pubDate>
                <category>TV</category>
                <description>Pandemien.Die.Menschheit.in.Gefahr.DL.German.DOKU.720p.HDTV.x264-UTOPiA - NZBs.org</description>
                <enclosure url="http://192.168.1.20:5075/nzbhydra/getnzb?apikey=APIKEY&amp;searchresultid=ID" length="1462142353" type="application/x-nzb"/>

                
                    <newznab:attr name="hydraIndexerScore" value="0"/>
                    <newznab:attr name="info" value="https://nzbs.org/api?t=getnfo&amp;id=ID&amp;raw=1&amp;apikey=APIKEY"/>
                    <newznab:attr name="rageid" value=""/>
                    <newznab:attr name="hydraIndexerHost" value="https://nzbs.org"/>
                    <newznab:attr name="hydraIndexerName" value="NZBs.org"/>
                    <newznab:attr name="tvdbid" value=""/>
                    <newznab:attr name="category" value="5080"/>
                    <newznab:attr name="completion" value="100"/>
                    <newznab:attr name="nfo" value="1"/>
                    <newznab:attr name="poster" value="&#34;www.the-evil-news.info&#34; &lt;the-evil-news.info@web.de&gt;"/>
                    <newznab:attr name="grabs" value="0"/>
                    <newznab:attr name="usenetdate" value="Sun, 26 Feb 2017 12:09:29 +0000"/>
                    <newznab:attr name="comments" value="0"/>
                    <newznab:attr name="password" value="0"/>
                    <newznab:attr name="details" value="https://nzbs.org/api?t=d&amp;id=ID&amp;apikey=>APIKEY"/>
                    <newznab:attr name="group" value="alt.binaries.comp"/>
                    <newznab:attr name="guid" value="ID"/>
                    <newznab:attr name="tvmazeid" value=""/>
                    <newznab:attr name="files" value="20"/>
                    <newznab:attr name="size" value="1462142353"/>
                    <newznab:attr name="category" value="5000"/>
            </item>
```

**Comment by seanvree** [comment]
@theotherp  - Yeah, I knew I was doing it wrong, 


This is what I got when I right click on "View page source"  I'm using Chrome on Windows.  
I also tried INSPECT to bring up the developer console, but I can't seem to find any text in any of the source that you had above:


<!doctype html>
<html>
<head>
    <title>Radarr</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>

    <meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>

    <link href="/Content/bootstrap.css?h=wcqjGP+NXU6zQB710jaZYA" rel='stylesheet' type='text/css'/>
    <link href="/Content/bootstrap.toggle-switch.css?h=zOaXXVYFa3wIaWmeJ2sr4g" rel='stylesheet' type='text/css'/>
    <link href="/Content/Messenger/messenger.css?h=qO6BkYDBjiMimxVChpoknA" rel='stylesheet' type='text/css'/>
    <link href="/Content/Messenger/messenger.flat.css?h=uXfH5hwpPgS6GV/TDVEpRw" rel='stylesheet' type='text/css'/>
    <link href="/Content/fullcalendar.css?h=+N47qDNHLCzhq6d1OTdepw" rel='stylesheet' type='text/css'>
    <link href="/Content/theme.css?h=8Dg5AfHNEs6gDhpcRo1FlA" rel='stylesheet' type='text/css'/>
    <link href="/Content/cells.css?h=3NtW5vRM2uvNma94lvVz2Q" rel='stylesheet' type='text/css'>
    <link href="/Content/series.css?h=IU/N0gS+iRHOd9kvKvimYw" rel='stylesheet' type='text/css'/>
        <link href="/Content/movies.css?h=hp2eU9aNOyy9TN1+eUZm6w" rel='stylesheet' type='text/css'/>
    <link href="/Content/activity.css?h=qGb/lr8wlOFjP6ojdT/Fkg" rel='stylesheet' type='text/css'/>
    <link href="/Content/logs.css?h=DHA5Xdi32cMm+arZUwDTsQ" rel='stylesheet' type='text/css'/>
    <link href="/Content/settings.css?h=JIM57hMFwRTqhaL6G1tQcg" rel='stylesheet' type='text/css'/>
    <link href="/Content/addSeries.css?h=MZh65ykhNcJhLqVkNSWvjQ" rel='stylesheet' type='text/css'/>
        <link href="/Content/addMovies.css?h=H/voc+yRwvoytE6a9GnP3w" rel='stylesheet' type='text/css'/>
    <link href="/Content/calendar.css?h=dBIvmQH/ui0JNcPXVN1XjQ" rel='stylesheet' type='text/css'/>
    <link href="/Content/update.css?h=y1X/Ux4RQDePx6ayJkGoIQ" rel='stylesheet' type='text/css'/>
    <link href="/Content/overrides.css?h=otCHWxvtUl/dtV42bX5a/w" rel='stylesheet' type='text/css'/>
    <link href="/Content/info.css?h=jf+rPHdtcdGib5t0QUZUIQ" rel='stylesheet' type='text/css'/>

    
    <meta name="msapplication-navbutton-color" content="#272727"/>

    
    <link rel="apple-touch-icon" sizes="180x180" href="/Content/Images/favicon/apple-touch-icon.png?h=UBN3ftVMb44yAaIXbvl3XA">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-32x32.png?h=WAUYkXE4zzTaYFI97G4qUQ" sizes="32x32">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-194x194.png?h=DW9FfrgNnOhP+lc14KRIsQ" sizes="194x194">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/android-chrome-192x192.png?h=k6xV1Mb8yK20z8DwcIroYg" sizes="192x192">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-16x16.png?h=ajRBz7COoQNatEJFxcfQ8A" sizes="16x16">
    <link rel="manifest" href="/Content/Images/favicon/manifest.json">
    <link rel="mask-icon" href="/Content/Images/favicon/safari-pinned-tab.svg" color="#ffc230">
    <link rel="shortcut icon" href="/Content/Images/favicon/favicon.ico?h=5rhS3DvgQdQTAys3GmDWXw">
    <meta name="apple-mobile-web-app-title" content="Radarr">
    <meta name="application-name" content="Radarr">
    <meta name="msapplication-TileColor" content="#272727">
    <meta name="msapplication-TileImage" content="/Content/Images/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="/Content/Images/favicon/browserconfig.xml">
    <meta name="theme-color" content="#272727">

    <link rel="alternate" type="text/calendar" title="iCalendar feed for Radarr" href="/feed/calendar/Radarr.ics"/>
</head>
<body>
<div class="container">
    <div id="nav-region"></div>
</div>
<div id="page">
    <div class="page-container">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12" id="notification-region"></div>
            </div>
            <div class="container-fluid main-region" id="main-region">
                <div id="followingBalls">
                    <div id="ball-1" class="ball"></div>
                    <div id="ball-2" class="ball"></div>
                    <div id="ball-3" class="ball"></div>
                    <div id="ball-4" class="ball"></div>
                </div>
            </div>
            <div id="modal-region"></div>
            <div id="modal-region2"></div>
        </div>
    </div>
    <div id="scroll-up">
        <i class="icon-sonarr-back-to-top visible-lg-inline" title="Back to the top!"></i>
    </div>
</div>
<div class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div id="footer-region">
                    Radarr Ver.
                    <span class="version"></span>
                    <div class="branch"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="control-panel-region" class="control-panel"></div>
<div id="errors"></div>
</body>
<script type="text/javascript">
    window.NzbDrone = {
        ApiRoot    : '/api',
        ApiKey     : '42c058f6107f45fca337d2861600e149',
        Version    : '0.2.0.375',
        Branch     : 'develop',
        Analytics  : false,
        UrlBase    : '',
        Production : true
    };
</script>

<script src="/polyfills.js?h=lNPw50dpfmIeXiK2IfrqdQ"></script>
<script src="/handlebars.runtime.js?h=VR1gUKhkPyiPuEfway9bag"></script>
<script src="/templates.js?h=63Cn1GwlQio7EcfFFGZ2tA"></script>
<script src="/vendor.js?h=D9I/BkyjGfvXSFCnkcq/eQ"></script>
<script src="/main.js?h=Ms9vbS12ta28qnS+yf5ryw"></script>
</html>

**Comment by theotherp** [comment]
No, you're doing it on the Radarr page. Open http://192.168.1.20:5075/nzbhydra/api?t=tvsearch&apikey=<apikey> and check its source code.

**Comment by seanvree** [comment]
@theotherp  - ha, holy crap, I'm sorry man!  

Here we go:

<item>
<title>Taboo.UK.S01E06.1080p.HDTV.x264-MORiTZ</title>
<guid isPermaLink="false">1574f7559d83024b0d3d2fe06897843edb154689</guid>
<link>
http://192.168.1.20:5075/nzbhydra//getnzb?apikey=REDACTED&searchresultid=1574f7559d83024b0d3d2fe06897843edb154689
</link>
<comments>
https://www.tabula-rasa.pw/details/c63d4d190624c3b52535a87ab0d73cef98fc2f65
</comments>
<pubDate>Mon, 27 Feb 2017 00:48:53 +0100</pubDate>
<category>TV HD</category>
<description>
Taboo.UK.S01E06.1080p.HDTV.x264-MORiTZ - Tabula-Rasa
</description>
<enclosure url="http://192.168.1.20:5075/nzbhydra//getnzb?apikey=REDACTED&searchresultid=1574f7559d83024b0d3d2fe06897843edb154689" length="2783090614" type="application/x-nzb"/>
<newznab:attr name="tvrageid" value="41814"/>
<newznab:attr name="grabs" value="0"/>
<newznab:attr name="prematch" value="1"/>
<newznab:attr name="guid" value="1574f7559d83024b0d3d2fe06897843edb154689"/>
<newznab:attr name="usenetdate" value="Mon, 27 Feb 2017 00:48:53 +0100"/>
<newznab:attr name="size" value="2783090614"/>
<newznab:attr name="hydraIndexerScore" value="90"/>
<newznab:attr name="hydraIndexerName" value="Tabula-Rasa"/>
<newznab:attr name="title" value="Episode 6"/>
<newznab:attr name="imdbid" value="3647998"/>
<newznab:attr name="comments" value="0"/>
<newznab:attr name="tvairdate" value="2017-02-18"/>
<newznab:attr name="season" value="1"/>
<newznab:attr name="files" value="34"/>
<newznab:attr name="category" value="5040"/>
<newznab:attr name="hydraIndexerHost" value="https://www.tabula-rasa.pw"/>
<newznab:attr name="poster" value="mmmq@meh.com"/>
<newznab:attr name="tmdbid" value="65708"/>
<newznab:attr name="group" value="alt.binaries.tatu"/>
<newznab:attr name="password" value="0"/>
<newznab:attr name="rageid" value="41814"/>
<newznab:attr name="episode" value="6"/>
<newznab:attr name="tvdbid" value="292157"/>
<newznab:attr name="category" value="5040"/>

**Comment by theotherp** [comment]
Remove the trailing slash from the URL base. A validator should prevent that from having been set but apparently it failed to do so. I'll add a note.

**Comment by seanvree** [comment]
@theotherp  - YUP! That was it!

Danke!
