### ISSUE TITLE
Search history is blank

### ISSUE THREAD

**Issue by sumofatguy** [theotherp/nzbhydra#574]
I am on windows version 0.2.209. Since the last (2?) update(s), my search history is blank (signed in as an admin, restarted server etc). The 'download history' and 'stats' both work, but there is no search history (although download history shows all usernames blank). I can't see any errors in the log (set to debug). 

Perhaps this is just a config error, although the search history has worked fine in the past for me. Thanks!

**Comment by jaywk** [comment]
Seeing the same thing here on 0.2.209 on linux.

**Comment by fovert** [comment]
Same here on FreeBSD @ 0.2.209
I can manually inspect the database and entries are still being inserted, so this does look like it's just a display issue.

**Comment by sumofatguy** [comment]
yes, manually inspecting the database and entries works ok, they are just not displayed in the web interface
