### ISSUE TITLE
Ability to specify umask of log files

### ISSUE THREAD

**Issue by dimaj** [theotherp/nzbhydra#579]
It would be nice if users could specify the umask of the logfiles created. This could prove useful when using scripts to process those logs as another system user that is part of the same group as nzbhydra.

With the current setup, log files are created with umask `0x177` (`rw- --- ---`)
After searching online, I was able to find some code that allows for that to happen. Here's the code that I added to the `log.py`:
```
# add custom logging handlers
class GroupWriteRotatingFileHandler(logging.handlers.RotatingFileHandler):
    def _open(self):
        prevumask = os.umask(0o117)
        rtv = logging.handlers.RotatingFileHandler._open(self)
        os.umask(prevumask)
        return rtv

class GroupWriteTimedRotatingFileHandler(logging.handlers.TimedRotatingFileHandler):
    def _open(self):
        prevumask = os.umask(0o117)
        rtv = logging.handlers.TimedRotatingFileHandler._open(self)
        os.umask(prevumask)
        return rtv

logging.handlers.GroupWriteRotatingFileHandler = GroupWriteRotatingFileHandler
logging.handlers.GroupWriteTimedRotatingFileHandler = GroupWriteTimedRotatingFileHandler

....
    if rotateAfterDays is None:
        file_logger = GroupWriteRotatingFileHandler(filename=logfilename, maxBytes=maxBytes, backupCount=backupCount)
    else:
        file_logger = GroupWriteTimedRotatingFileHandler(filename=logfilename, when="d", interval=rotateAfterDays, backupCount=backupCount)
```
This code was found here: http://stackoverflow.com/questions/1407474/does-python-logging-handlers-rotatingfilehandler-allow-creation-of-a-group-writa

I was also trying to add an option to the config section of the web UI, but I had a lot of problems building and running it locally. As a result, I'm filing an enhancement issue instead of a PR

**Comment by theotherp** [comment]
Sorry this took so long...

**Comment by dimaj** [comment]
no worries! Thanks!

**Comment by theotherp** [comment]
Lemme know if it works, I tested it on my VM and server but I have only limited unix experience, who the hell knows what I could've forgotten.

**Comment by dimaj** [comment]
Confirming that it works!

Thanks again.


Regards,

dimaj <http://blog.dimaj.net>
