### ISSUE TITLE
Add rTorrent to Downloader 

### ISSUE THREAD

**Issue by STX2k** [theotherp/nzbhydra#580]
I know NZB Hydra already some time but have it the days the first time tried. I'm excited. 

Also with jacket integration works problem-free. As Downloader there are already NZBGet and Sabnzbd, but I'm missing a possibility for torrents. Is it planned to integrate ruTrorrent Support (etc.)?

I already searched in the tickets for * Torrent *. But nothing found on the subject.

Greets STX2k

**Comment by theotherp** [comment]
Not impossible but unlikely. Very few people actually use this and it would take a lot of work. I'll keep it open, who knows. I've already implemented a lot of stuff I hadn't thought would ever be done.

**Comment by theotherp** [comment]
Will not be implemented. V2 will be released soon and has an option to download torrent files to a given folder, that should do the trick.

**Comment by STX2k** [comment]
You are the best ✌️
