### ISSUE TITLE
Add indexer selection option buttons on search page

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra#581]
* What do you want to happen?
Add functionality to the Invert Selection button on the main search page. Add button to 'Select All Indexers', 'Select API indexers only', 'Select Manual Search Only'. Could even be extended to select by Priority type (i.e Priority > 50; Priority < 50, etc.)

* If not clear, why do you want it?
Allows for a way to select a certain type of indexer quickly and easily. 

* Do you think it's something only you need or something that might be popular?
I'd like to think that others would appreciate a way to quickly select/deselect certain indexers on the fly.

**Comment by theotherp** [comment]
> 'Select API indexers only', 'Select Manual Search Only'
Wouldn't make any sense because the first group isn't even shown on the search page in the first place.

**Comment by jaywk** [comment]
Yes, you are correct about the 'Select API indexers only'; momentary lapse in thinking, but the other options would still be beneficial. What I should have and meant to write was:

'Select All' - (when 'Internal and API searches' are selected in the indexer's config page); could temporarily override the Preselect option if set to off in the indexer's config page; also probably the default selection for most users.
'Select Internal Only' - (when 'Internal searches only' are selected in the indexer's config page); would deselect all indexers that have 'Internal and API searches' selected on the config page.

**Comment by theotherp** [comment]
Implemented in v2 which will be released soon.
