### ISSUE TITLE
Send nzb to downloader: wrong URL

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#582]
[logfile.txt](https://github.com/theotherp/nzbhydra/files/842271/logfile.txt)
[settings.txt](https://github.com/theotherp/nzbhydra/files/842272/settings.txt)

when i find a release and send it to the downloader, the downloader will receive a wrong URL.
Should be: https://www.mydomain.com/nzbhydra/getnzb?apikey=xxxyyy&searchresultid=56f90c004c0e2699996eb92fa5d742959f2cf89a&downloader=DS415%2B
Is: http://www.mydomain.com:5075/nzbhydra/getnzb?apikey=xxxyyy&searchresultid=56f90c004c0e2699996eb92fa5d742959f2cf89a&downloader=DS415%2B

I didn´t change settings and i did no update. noticed just today. Last night it was still working.
strange: i have this problem with just one indexer. Test for this indexer in hydra is ok.

**Comment by theotherp** [comment]
Huh. With just one indexer? And it changed randomly? To be honest, no idea... Try again tomorrow ;-)

**Comment by Hobbabobba** [comment]
found my mistake: didn´t switch off local URL for the API :)
