### ISSUE TITLE
Hydra not filtering "to small" releases?

### ISSUE THREAD

**Issue by weirdcrap** [theotherp/nzbhydra#587]
Using the latest Hydra and Radarr development build. When I search for the movie "Hacker (2015)" as an example I noticed a large number of extremely small releases that are clearly not video files.
![screenshot 2017-03-23 07 13 33](https://cloud.githubusercontent.com/assets/22824785/24247388/877ac92a-0f99-11e7-9fe6-c417e5135733.png)

 I assumed these would be filtered out by Hydra's category limits, is this not the correct expected behavior?
These are my categories, nothing special (SD is 300MB lower cutoff):
![movies](https://cloud.githubusercontent.com/assets/22824785/24247475/d1fbec72-0f99-11e7-98db-e27b886a9d73.PNG)
![movies-hd](https://cloud.githubusercontent.com/assets/22824785/24247478/d479dc98-0f99-11e7-9e9f-fd9f2f2ba310.PNG)

I can reproduce easily, I will post debug logs here in a bit. 

EDIT: Github keeps telling me the .zip file from hydra is not supported, try uploading it in .zip format. lol
I can just e-mail the debug zip to you if that works.

**Comment by theotherp** [comment]
See #551

**Comment by weirdcrap** [comment]
Ah, didn't see that. Thanks for the quick response.
