### ISSUE TITLE
Stats page not working correctly

### ISSUE THREAD

**Issue by Crowley007** [theotherp/nzbhydra#588]
It seems the stats page percentages aren't working, they add to more than 100%.

Pictures attached.

![capture](https://cloud.githubusercontent.com/assets/23026322/24336155/cc6509dc-1292-11e7-94ec-a9b2c2143512.PNG)
![capture2](https://cloud.githubusercontent.com/assets/23026322/24336156/cc697620-1292-11e7-9298-25c746f6f747.PNG)

**Comment by theotherp** [comment]
No, that's correct. Althub's results made up 85.85% of the results in searches *where it was used*. 

Say you start one search and select only 6box. It's results share will be 100%. Then you select 6box and Cat and both find 50 results. Their results share is 50%. Now Cat has a total result share of 50% and 6box has one of 75%. Something like that.

It's not completely intuitive, but it wouldn't make sense to calculate the share over all searches. For example if there's one indexer that you only enabled for ebook searches and which continously finds a lot of results but which you never select for the other searches, it would have a very low results share.

**Comment by Crowley007** [comment]
Ok, I still don't quite get it, the stat measures number of downloads per indexer, so If "Indexer 1" has 7 downloads and "Indexer 2"  had 3, my mind says percentages should be 70% and 30% etc. It just seems odd to me that the pie chart adds to more than 100 percent. 

I have everything enabled for everything and just want to see which indexer gets used most, which should be the one that gets releases fastest since everything also has the same priority. 

But it seems it's working as intended, just not the way I would expect. Thanks.

**Comment by theotherp** [comment]
I'm currently at work and can't take a proper look. To be honest I need to check the source code to see how exactly the stats are calculated, it might be a bug, I don't know.

**Comment by jaywk** [comment]
Can confirm. Seems to have been this way for several past releases now. 
![stats](https://cloud.githubusercontent.com/assets/6394767/24580370/f630e092-16d4-11e7-9a57-06e39b182a2f.png)

**Comment by theotherp** [comment]
Yeah that doesn't look right...

**Comment by Crowley007** [comment]
So it seems this is a legit bug? Still happening with the latest release updated today
![capture](https://cloud.githubusercontent.com/assets/23026322/24887245/086142da-1e63-11e7-887d-1d114e34ddd0.PNG)

**Comment by theotherp** [comment]
Yes, this is a bug. But I have too much stuff to do to fix a bug which I consider relatively minor.

**Comment by theotherp** [comment]
Please let me know if it's actually fixed ;-)

**Comment by fryfrog** [comment]
My chart no longer has entries that are > 100%, mission accomplished. :)

**Comment by Crowley007** [comment]
Yeah, seems to be fixed :)
