### ISSUE TITLE
Failed Download Stats

### ISSUE THREAD

**Issue by jknight2014** [theotherp/nzbhydra#589]
* What do you want to happen?
Add a stat of how many of a Indexers downloads fail. As a percentage. 

* If not clear, why do you want it?
This would give a little more insight into the worthyness of an indexer. 

* Do you think it's something only you need or something that might be popular?
I think many people who are looking to save money would be interested to know how well their indexers are doing. For example if my most used indexer has 50% failure rate and the second best is only 10% less downloads but only a 10% failure rate its actually the better indexer but without knowing the failure rate the pie chart can be misleading. I know failures are not related to the indexer, but if my highest paid indexer is returning failing downloads but another is always succeeding it would make it worth my while to switch primary indexers. 

This would require linking an indexer download with SABnzbd's queue via the API

**Comment by mattmac24** [comment]
This is a great idea that I also had. Although I think it would be better if nzbhydra was able to use Sonarr/Radarr's blacklist. I think this would work better and for people who use other downloaders. Also I use the option to remove completed downloads from my downloader which would probably break this feature as described above. Perhaps Nzbhydra could check a download against the blacklist after 24 hours? This would allow the blacklist to be manually cleared later down the line without issue.

This way it would also allow nzbhydra to mark a download as failed even if it succeeded in nzbget/sabnzbd but Sonarr/Radarr rejected it in the case of mislabelled files or something similiar. At the end of the day we only really care if Sonarr/Radarr is able to pull the file successfully .

I hope this happens for the exact same well explained reasons jknight2014 has listed above.

**Comment by theotherp** [comment]
This would require a web hook / user script for the downloader to inform hydra about the actual result of the downloading. This is currently not supported. I'll add it to the todo list but don't expect it for some time.

**Comment by mattmac24** [comment]
Thanks for the reply. This feature could help me save some $'s so I'm looking forward to the day this is supported :)

**Comment by theotherp** [comment]
This feature is available in https://github.com/theotherp/nzbhydra2/
