### ISSUE TITLE
Sending nzbs to SAB with different internal and external ports

### ISSUE THREAD

**Issue by mrowlinson** [theotherp/nzbhydra#590]
I use use port fordwarding to redirect an external port to the internal port NZBHydra uses. This works out fine when I'm accessing NZBHydra from within my network and sending nzbs to SAB. However, when I access it remotely it tries to send the nzb to SAB using my external address but the internal port so obviously it doesn't work. Maybe I'm overlooking it but is there not some way to send the nzb to SAB using the internal address/port only, and even when you're accessing NZBHydra remotely?

**Comment by theotherp** [comment]
Sorry, I don't understand. Please provide an example.
