### ISSUE TITLE
Sonarr/Radarr not working with nzbhydra with Jackett only

### ISSUE THREAD

**Issue by kdizzay** [theotherp/nzbhydra#593]
I am using nzbhydra in conjunction with Jackett for torrent indexers and am running into issues with Sonarr and Radarr when I add nzbhydra as a custom newznab indexer. In Sonarr, I am getting the error "No results were returned from your indexer,please check your settings"
1) Added Jackett indexers to nzbhydra and am able to do manual searches in nzbhydra just fine, getting results.
2) Am using IP:port and the API key from NzbHydra as the input for the indexer in Sonarr/Radarr.
3) Everything is on the same local machine so no reachability issue.
4) Am not using any usenet indexers in Nzbhydra, the goal for this was to use Jackett (torrent indexers) and set priorities for each of the indexers.
Thanks.

NzbHydra debug log: 

2017-04-04 19:09:19,836 - INFO - web - Thread-227 - API search request: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ] 

2017-04-04 19:09:19,836 - INFO - search - Thread-227 - Starting new search: SearchRequest [ type "tv", forbiddenWords "[]", requiredWords "[]", offset "0", loadAll "False", limit "100" ] 2017-04-04 19:09:19,852 - INFO - search - Thread-227 - Some indexers were not selected for this search:

Disabled for API searches: *MYTRACKERHERE* 2017-04-04 19:09:19,884 - INFO - search - Thread-227 - All indexers exhausted 2017-04-04 19:09:19,884 - INFO - search - Thread-227 - Returning 0 results 2017-04-04 19:09:19,884 - INFO - web - Thread-227 - API search request completed in 47 ms

I see that 'Disabled for API searches: *MYTRACKERHERE*' , I believe this is the issue. When I do an internal search it's fine, but when Sonarr tries to do through API it is seeing that my tracker is disabled for API searches. Let me know if you need anything else.

**Comment by theotherp** [comment]
You cannot use torrent trackers for API calls, i.e. with tools like radarr.

**Comment by kdizzay** [comment]
Ah shucks. I was hoping I could prioritize my torrent indexers in nzbhydra and radarr because radarr doesn't allow the ability to prioritize torrent trackers, looks like that's a feature request I'll have to make. Thanks anyway.
