### ISSUE TITLE
nzbhydra broke itself overnight (500 Internal Server Error)

### ISSUE THREAD

**Issue by janipewter** [theotherp/nzbhydra#595]
Realised a couple of days ago after not having any new download notifications for a week from sonarr or radarr that my nzbhydra install has broken itself.

I get some crazy error 500's when I try to access it.

https://imgur.com/a/TjoKP

Tried manually updating with Git, everything is up to date. Restarted hydra, restarted the whole VPS, but nothing helps. Nothing whatsoever in the logs to suggest a problem and server reports status as running as normal:

> media@vps:~$ service nzbhydra status
> nzbhydra.service - NZBHydra Daemon
>   Loaded: loaded (/etc/systemd/system/nzbhydra.service; enabled; vendor preset: enabled)
>   Active: active (running) since Wed 2017-04-05 11:15:41 UTC; 1 day 23h ago

OS: Ubuntu 16.04 x64

It worked absolutely fine before it broke, seemingly at random.

**Comment by theotherp** [comment]
Uhm, no idea. Try a new installation and import your old settings. You can also just copy over your settings.cfg and old database files before starting. See if that helps.

**Comment by theotherp** [comment]
Shutdown Hydra, open nzbhydra.py in the main folder and search for
`web.run(host, port, basepath)`
Replace that with
`web.run(host, port, basepath, debug=True)`

Start Hydra, try again and see if you get a better error message.

**Comment by janipewter** [comment]
If I do that, it doesn't start at all.

>Apr 07 11:49:31 vps systemd[1]: nzbhydra.service: Service hold-off time over, scheduling restart.
>Apr 07 11:49:31 vps systemd[1]: Stopped NZBHydra Daemon.
>Apr 07 11:49:31 vps systemd[1]: nzbhydra.service: Start request repeated too quickly.
>Apr 07 11:49:31 vps systemd[1]: Failed to start NZBHydra Daemon.

**Comment by theotherp** [comment]
Try and start it in the console instead of relying on the daemon. You might get some insightful console output.

**Comment by theotherp** [comment]
Sorry, my bad. In settings.cfg look for the setting "debug". Set it to "true" and (re)start Hydra.

**Comment by janipewter** [comment]
OK, debug now on. It seems to start fine:

> media@vps:/opt/nzbhydra$ sudo python nzbhydra.py
> 2017-04-09 08:34:55,327 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.212
> 2017-04-09 08:34:55,328 - NOTICE - nzbhydra - MainThread - Base path is /opt/nzbhydra
> 2017-04-09 08:34:55,329 - NOTICE - nzbhydra - MainThread - Loading settings from /opt/nzbhydra/settings.cfg
> 2017-04-09 08:34:55,339 - INFO - log - MainThread - None
> 2017-04-09 08:34:55,340 - INFO - nzbhydra - MainThread - Started
> 2017-04-09 08:34:55,340 - INFO - nzbhydra - MainThread - Loading database file /opt/nzbhydra/nzbhydra.db
> 2017-04-09 08:34:55,346 - INFO - nzbhydra - MainThread - Starting db
> 2017-04-09 08:34:55,350 - INFO - indexers - MainThread - Activated indexer Binsearch
> 2017-04-09 08:34:55,353 - INFO - indexers - MainThread - Activated indexer NZBClub
> 2017-04-09 08:34:55,355 - INFO - indexers - MainThread - Activated indexer NZBIndex
> 2017-04-09 08:34:55,356 - INFO - nzbhydra - MainThread - Debug mode enabled
> 2017-04-09 08:34:55,359 - NOTICE - nzbhydra - MainThread - Starting web app on 127.0.0.1:5075
> 2017-04-09 08:34:55,359 - INFO - nzbhydra - MainThread - Opening browser to http://127.0.0.1:5075
> 2017-04-09 08:34:55,361 - INFO - web - MainThread - Running threaded server

as soon as I try to load the page in browser though, it throws a ton of errors:

> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 89, in __call__
>     return self.app(environ, start_response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/opt/nzbhydra/libs/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1479, in full_dispatch_request
>     response = self.process_response(response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1693, in process_response
>     self.save_session(ctx.session, response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 837, in save_session
>     return self.session_interface.save_session(self, session, response)
>   File "/opt/nzbhydra/libs/flask_session/sessions.py", line 337, in save_session
>     total_seconds(app.permanent_session_lifetime))
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 694, in set
>     self._prune()
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 650, in _prune
>     expires = pickle.load(f)
> EOFError
> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 89, in __call__
>     return self.app(environ, start_response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/opt/nzbhydra/libs/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1479, in full_dispatch_request
>     response = self.process_response(response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1693, in process_response
>     self.save_session(ctx.session, response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 837, in save_session
>     return self.session_interface.save_session(self, session, response)
>   File "/opt/nzbhydra/libs/flask_session/sessions.py", line 337, in save_session
>     total_seconds(app.permanent_session_lifetime))
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 694, in set
>     self._prune()
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 650, in _prune
>     expires = pickle.load(f)
> EOFError
> Traceback (most recent call last):
>   File "/opt/nzbhydra/libs/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/opt/nzbhydra/nzbhydra/web.py", line 89, in __call__
>     return self.app(environ, start_response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/opt/nzbhydra/libs/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/nzbhydra/libs/flask/app.py", line 1479, in full_dispatch_request
>     response = self.process_response(response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 1693, in process_response
>     self.save_session(ctx.session, response)
>   File "/opt/nzbhydra/libs/flask/app.py", line 837, in save_session
>     return self.session_interface.save_session(self, session, response)
>   File "/opt/nzbhydra/libs/flask_session/sessions.py", line 337, in save_session
>     total_seconds(app.permanent_session_lifetime))
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 694, in set
>     self._prune()
>   File "/opt/nzbhydra/libs/werkzeug/contrib/cache.py", line 650, in _prune
>     expires = pickle.load(f)
> EOFError

Every time I press F5 it throws the same errors.

**Comment by theotherp** [comment]
Shutdown Hydra, delete the flask_session folder, start Hydra, try again.

**Comment by janipewter** [comment]
That's fixed it, thanks!

**Comment by theotherp** [comment]
Great.
