### ISSUE TITLE
User/Pass prompt for shutdown, restart or restore on fresh install 

### ISSUE THREAD

**Issue by h-case** [theotherp/nzbhydra#597]
When selecting _shutdown_, _restart_ or '_restore backup_' in system menu, NZBHydra prompts for a username & password. 
_i.e._ [http://127.0.0.1:5075 is requesting your username and password. The site says: “Login Required”]

_Config/Authorization/"Auth type"_ is set to 'None' (as is _settings.cfg_), so I'm not sure what user/pass it is requesting. Is there a default admin a/c? I can't find any documentation or search results that address this. Not sure if bug or feature??  ¯\_(ツ)_/¯

I tried creating a user, then using those credentials, but it just failed to authenticate. Same if blank, or any combo I guessed at.
**_Log_**:
2017-04-15 17:10:11,063 - WARNING - web - Thread-107 - IP 127.0.0.1 failed to authenticate. This was his first failed login attempt
2017-04-15 17:10:15,061 - WARNING - web - Thread-108 - IP 127.0.0.1 failed to authenticate. The last time was at 2017-04-15 07:10:11. This was his 2. failed login attempt
2017-04-15 17:10:24,440 - WARNING - web - Thread-109 - IP 127.0.0.1 failed to authenticate. The last time was at 2017-04-15 07:10:15. This was his 3. failed login attempt

Strangely, when I navigate away to another page (e.g. search), i get:

2017-04-15 17:10:47,322 - INFO - web - Thread-110 - Successful login from IP 127.0.0.1 after failed login tries. Resetting failed login counter.

This occurred in a fresh Windows installation extracted from the zip file to a machine with no previous installation. Also occurs when run with Administrator privileges. 
I manually restored the backup, but cannot shutdown or restart without killing the windows process.

**_settings.cfg:_**
    "auth": {
        "authType": "none", 
        "restrictAdmin": false, 
        "restrictSearch": false, 
        "restrictStats": false, 
        "users": []

Can you shed any light on it for me?

**Comment by theotherp** [comment]
I tried to reproduce this but couldn't. I honestly have no idea why this might be happening or how to debug this. Could you try running the python source version and see if you have the same issue?

I'm leaving for vacation tomorrow and won't be able to support this for at least two weeks. Fortunately these are sections in the program that you usually don't need that often.

If you want to restore an old backup you can just extract the ZIP into the main folder, Hydra doesn't do anything else anyway.

**Comment by theotherp** [comment]
Do you use the windows binary version by any chance?
