### ISSUE TITLE
Saving / creating settings.cfg doesn't work on Windows

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra#598]
Users on reddit are reporting problems saving settings.cfg in 214.

https://www.reddit.com/r/usenet/comments/665cqm/nzbhydra_is_not_saving_settings/

**Comment by theotherp** [comment]
Sorry guys. I'm on vacation and can't do any tests right now. I think this
happens only on the latest or latest two releases. Please try one of the
older ones. Change something in the config, save, restart and see if it was
persisted.

**Comment by theotherp** [comment]
Fixed now.
