### ISSUE TITLE
Local NZB Hydra + VPS Host SabNZB = Can't Get NZB

### ISSUE THREAD

**Issue by TBhimdi** [theotherp/nzbhydra#60]
I'm running a NZB Hydra on my PC at home and have SabNZB running on my VPS. Sab runs fine on the VPS, has been for several months with SickBeard on my PC. I've got NZBHydra up and running with Python 2.7.10 and searches and downloads work perfectly, but when I set SAB as my Downloader and click on the tiny SAB icon next to a search result, I get a red prompt.

Here's the error:

```
2015-12-18 14:03:06,694 - ERROR - downloader - Error while trying to connect to sabnzbd
Traceback (most recent call last):
  File "C:\Util\daemon\nzbhydra\nzbhydra\downloader.py", line 243, in add_nzb
    r = requests.post(f.tostr(), files=files, verify=False)
  File "C:\Util\daemon\nzbhydra\libs\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Util\daemon\nzbhydra\libs\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Util\daemon\nzbhydra\libs\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Util\daemon\nzbhydra\libs\requests\sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Util\daemon\nzbhydra\libs\requests\sessions.py", line 195, in resolve_redirects
    **adapter_kwargs
  File "C:\Util\daemon\nzbhydra\libs\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Util\daemon\nzbhydra\libs\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='localhost', port=9090): Max retries exceeded with url: /sabnzbd (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005DF3470>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',))
```

My NZBHydra host is set to the defaults (0.0.0.0, 5075, empty base, and no SSL).
Downloader setting for SABNzb is set to Proxy NZBs from indexer, Upload NZB, host example.com (domain name replaced here btw), port 9090, SSL On, API Key xxxxxx, default category stuff.

No clue why the log up there shows "localhost" instead of my example.com domain. I've tried all the combinations of NZB Access Type and NZB Adding Type as well, no go. The "Test Connection" for SABNzb is green/successful btw.

**Comment by TBhimdi** [comment]
Fix worked great, thanks.

**Comment by theotherp** [comment]
I just realized that I always add /sabnzbd/ to the entered URL. When behind a reverse proxy that probably wouldn't work. Need to fix that.

**Comment by TBhimdi** [comment]
Yup, noticed that my entered domain had changed after a git update, I just renamed it to the correct URL with port and without /sabnzbd/. Worked fine after.

Thanks for the quick fix and response btw!
