### ISSUE TITLE
Request: show IP address in place of username for API requests

### ISSUE THREAD

**Issue by mauirixxx** [theotherp/nzbhydra#600]
I have hydra used across 3 clients, and while everything is API based, it would be "nice to have" the IP address of the API user in place of the username in the Search & Download history.

Is this possible?

**Comment by nemchik** [comment]
This is an interesting ideas, but I would want the IP to be displayed in addition to the username, rather than in place of it.

Another thought;
mauirixxx could you create 3 different users in Hydra and set the username for all of your API requesting clients? That might give you the info you want?

**Comment by mauirixxx** [comment]
@nemchik looks like you can't assign an API key to specific user accounts. Oh well, again this is a nice to have feature so I'm not going to worry too much about it, if @theotherp adds it, he adds it. If not, no big deal :D

**Comment by nemchik** [comment]
You can have multiple users user the same API key but still define the username in the parameters of the API request.

I don't think we will see Hydra add the ability to have multiple API keys for multiple users because it could lead to abuse if the indexers.

**Comment by mauirixxx** [comment]
> You can have multiple users use the same API key but still define the username in the parameters of the API request.

I don't know how to do this - is there instructions somewhere or do I need to hack sonarr/couchpotato/headphones code?

**Comment by nemchik** [comment]
Add the extra users to Hydra first, then in Sonarr/Radarr open the indexer config for Hydra and look for the additional parameters box and put `username=YOURUSERNAME` (I'm not positive about that, but I'm pretty sure that's it).

**Comment by nemchik** [comment]
For curiosity I tried this out and found the setting needed an & in front (`&username=YOU`) which works, but doesn't show as expected in Hydra.

**Comment by cjackson234** [comment]
Can you just change it to allow each user to have a unique api key? This way you can display the corresponding user.

**Comment by nemchik** [comment]
That's getting discussed in another issue.

**Comment by mauirixxx** [comment]
@cjackson234 the reason I requested the IP instead of the username is because in my specific scenario, I manage all 3 locations personally. Making separate accounts for each location is obviously very doable, but since I'm the only person who has access it felt like extra work, and an IP address would suffice :D

**Comment by theotherp** [comment]
Implemented in v2 which will be released soon.
