### ISSUE TITLE
Restart loop after upgrade

### ISSUE THREAD

**Issue by wosl** [theotherp/nzbhydra#602]
I have updated to the latest version (both via the application and a clean install) and on running the tray tool it constantly restarts ever second or so and the log is filled with this:

```
NZBHydra updated itself. Restarting tray tool now using command line: /C ping 127.0.0.1 -n 2 && "C:\nzbhydra\NZBHydraTray.exe" isrestart
NZBHydra updated itself. Restarting tray tool now using command line: /C ping 127.0.0.1 -n 2 && "C:\nzbhydra\NZBHydraTray.exe" isrestart
NZBHydra updated itself. Restarting tray tool now using command line: /C ping 127.0.0.1 -n 2 && "C:\nzbhydra\NZBHydraTray.exe" isrestart
```

If I leave it it carries on.

**Comment by theotherp** [comment]
This seems to happen on Windows 7 but not on Windows 10 which is why I never caught it. That's weird.

**Comment by theotherp** [comment]
Fixed now. Sorry about that.
