### ISSUE TITLE
Search history on front page no longer displaying searches

### ISSUE THREAD

**Issue by jaywk** [theotherp/nzbhydra#603]
* What do you expect to happen? What does happen? 

After a manual search is conducted from the front page, those search terms should be saved and accessible from the Search History button available on the right hand side of the search box. Instead, past searches aren't visible there; however, they do show up if you click through to the dedicated History & Stats page.

* Can the problem be reproduced? How?

Conduct a manual search, wait for the results to load then verify that those search terms aren't showing up in the the quick search history box.

* Log file: [nzbhydra-debuginfo-2017-05-03-15-46.zip](https://github.com/theotherp/nzbhydra/files/974529/nzbhydra-debuginfo-2017-05-03-15-46.zip)

* Other information

http://127.0.0.1:5075/internalapi/getsearchrequestsforsearching continues to return only one result no matter how many manual searches are performed. 
```
{
  "searchRequests": [
    {
      "author": null,
      "category": "TV",
      "episode": "13",
      "identifier_key": "tvdbid",
      "identifier_value": "276526",
      "internal": true,
      "movietitle": null,
      "query": "",
      "season": "3",
      "time": "Fri, 14 Apr 2017 19:26:40 GMT",
      "title": "The Legend of Mick Dodge",
      "tvtitle": "The Legend of Mick Dodge",
      "type": "tv",
      "username": "nzbhydra"
    }
  ],
  "totalRequests": 1
```

**Comment by theotherp** [comment]
Please post a screenshot of your search history. To be honest I have no idea what could be going on...

**Comment by jaywk** [comment]
I restored backups one by one (something like 15 or so) all the way back to November and performed a manual search after each restore and those searches still never showed up in the search history accessible from the search bar.

**Comment by jaywk** [comment]
I misspoke in my original post when I stated that the manual searches were showing up in the dedicated Search and History tab. I thought they were but I double-checked and only API searches are actually showing up there. Manual searches aren't being written to the database at all. I can't figure out why as the logs don't seem to provide a reason. Is there some type hidden verbose logging function available to try to further investigate this?

**Comment by theotherp** [comment]
That makes it even more mysterious... Perhaps you could try and open the nzbydra.db sqlite database and see if the searches are stored there. It might just be a display issue.

**Comment by jaywk** [comment]
So it is definitely only a display issue. The searches are being written to the database but they do not show up in the quick search history box on the front page. Any idea why those manual searches aren't displaying even though they are being written to the database? Anything I can potential do to the database to make them show up in the program?

**Comment by theotherp** [comment]
I'll get some SQL queries and would like you to execute them on the database. Stay tuned.

**Comment by theotherp** [comment]
```
SELECT
  t1.*,
  t2.title AS tvtitle,
  t3.title AS movietitle
FROM search AS t1 LEFT OUTER JOIN tvidcache AS t2 ON (((t1.identifier_value = t2.tvdb) AND (t1.identifier_key = 'tvdbid')) OR ((t1.identifier_value = t2.tvrage) AND (t1.identifier_key = 'rid')))
  LEFT OUTER JOIN movieidcache AS t3 ON (((t1.identifier_value = t3.imdb) AND (t1.identifier_key = 'imdbid')) OR ((t1.identifier_value = t3.tmdb) AND (t1.identifier_key = 'tmdbid')))
WHERE t1.internal
GROUP BY t1.internal, t1.query, t1.identifier_key, t1.identifier_value, t1.category, t1.season, t1.episode, t1.type, t1.username, t1.title, t1.author
ORDER BY t1.time
  DESC
LIMIT 10
```

```
SELECT internal, query, time, identifier_key, identifier_value, category, season, episode, type, title, author
FROM search t
LIMIT 10;
```

```
SELECT distinct internal, query, identifier_key, identifier_value, category, season, episode, type, title, author
FROM search t
LIMIT 10;
```

**Comment by theotherp** [comment]
Results as CSV would be ideal, but any humanly readable format is ok.

**Comment by jaywk** [comment]
Database queries attached in zip file.
[SQL queries.zip](https://github.com/theotherp/nzbhydra/files/994824/SQL.queries.zip)

**Comment by theotherp** [comment]
What the hell. The results of the first query is what should be shown in the box. It's the query that the web call to http://127.0.0.1:5075/internalapi/getsearchrequestsforsearching executes and should get back.

Query1.csv is the content of the first query, right...?

**Comment by jaywk** [comment]
Yes, Query1.csv is the content of the first query, query2 the second and query3 the third.  http://127.0.0.1:5075/internalapi/getsearchrequestsforsearching only shows the one result (as indicated in the original post) yet there are plenty of other manually searched results stored in my database. Any idea why it isn't displaying correctly?

**Comment by jaywk** [comment]
I deleted and set up the git repo again then set everything up from scratch and this is no longer a problem. The search history dropbox on the front page is now working as expected.

**Comment by jaywk** [comment]
This bug has reared its ugly head again. Manually searches are no longer be saved. This was working after purge the program, reinstalling, and setting up my settings again but stopped saving manual searches. I did not change any settings in between the time it was working and then noticing that it wasn't.

**Comment by theotherp** [comment]
I'm afraid I don't know how to help you right now. In a couple of months I'll release a rewrite of Hydra, that hopefully fixes it.

**Comment by theotherp** [comment]
Fixed in v2 which will be released soon.
