### ISSUE TITLE
[Feature Request] Ability to remove certain endings from the nzb title

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#604]
Hydra already has the ability to remove "-Obfuscated" from the nzbs from nzbgeek, but I'd like to be able add a list that can expand what can be removed from end of the name.

Some indexers add a tag to reuploaded nzbs, such as -Obfuscated.  However, I don't like my media to have this added information to the original name.  Some examples are also -Scrambled, -AsRequested, repost, Reup, -RP, etc.  In addition, some torrent trackers' tags get added to an nzb, like [rartv], [rarbg], and [eztv].

Also, some indexers don't properly remove some extensions from the name, such as .mkv, .par2, .subs, .part01.rar, etc.

When manually searching and you have a lot of results, it helps to have the better grouping to reduce the number of rows. I have been modifying the code myself to do this, but I think it might be useful to other people. 

This is the code I add manually after each update to https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/searchmodules/newznab.py#L554

```python
for word in [".mp4", ".mkv", ".subs", ".REPOST", "repost", "~DG~", ".DG", "-DG", "-1", ".1", "(1)", "ReUp", "ReUp2", "-RP", "-AsRequested", "-Obfuscated", "-Scrambled", "-Chamele0n", "-BUYMORE", "-[TRP]", "-DG", ".par2", ".part01", "part01.rar", ".part02.rar", ".jpg", "[rartv]", "[rarbg]", "[eztv]"]:
     if entry.title.endswith(word):
          self.debug("Removing trailing %s from title %s" % (word, entry.title))
          entry.title = entry.title[:-len(word)]
          break
```
I add the code to nzbhydra/searchmodules/jackett.py as well, so the jacket results are also refined.

This is a little different from the above request, but I also modify the title two more ways to help with better grouping. I replace spaces with a dot and remove parentheses from around the names.  I do a lot of manual searches, and these three modifications have helped to search through the results.
```python
entry.title = entry.title.replace(" ", ".")
#sometimes this causes a period to be at the end
if entry.title.endswith("."):
     entry.title = entry.title[:-1]
# remove parenthesis
if entry.title.startswith('(') and entry.title.endswith(')'):
     self.debug("Removing parenthesis from beginning and end of title %s" % entry.title)
     # remove the first and last character
     entry.title = entry.title[1:-1]
```
I don't know if many other people would find this useful, but some might.

**Comment by theotherp** [comment]
Good idea. I'll add it but it won't be for a while, I'm currently working on something else.

**Comment by theotherp** [comment]
By the way, grouping should already ignore whitespaces and dots.

**Comment by judhat2** [comment]
Just got around to updating to the new version. Works great! Thanks!
