### ISSUE TITLE
Hydra not obeying timeout in settings

### ISSUE THREAD

**Issue by bnevets27** [theotherp/nzbhydra#605]
I'm not getting any results from Jackett. I tried copying the url into a browser and I do get results so I suspected that the response from Jackett takes too long and therefore Hydra times out. 

I tried a few different timeout's in the Jackett config (120,90,60) and every time the log sill showed  (read timeout=20)

I even changed the global timeout to 40 but still get (read timeout=20)

2017-05-24 12:17:12,012 - ERROR - search_module - Thread-6206 - Jackett: Error while connecting to URL http://192.168.1.111:1111/torznab/all/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&cat=2000,2010&password=<PASSWORD>&q=name+of+the+movie+vol+2: HTTPConnectionPool(host='192.168.1.111', port=1111): Read timed out. (read timeout=20)

**Comment by theotherp** [comment]
You don't have set an indexer specific timeout in the settings?

**Comment by bnevets27** [comment]
Indexer timeout is currently set at 60
Global timeout is set to 40

Hydra reports Read timed out. (read timeout=20) in logs. Which I assume means it thinks I have timeout set to 20, which it is not.

**Comment by theotherp** [comment]
Please enable debug log level, try again and post your debug infos.

**Comment by bnevets27** [comment]
Well I'll be damned. After turning on debugging (which asks for a restart) I set Jackett timeout to 90. Then performed a search and it was successful. Turned debugging off and Jackett still works. 

I had restarted hydra after checking the settings previously just to see if it would help and it didn't before. Maybe the right combination of setting in restart got it to work.

**Comment by theotherp** [comment]
Well that's mysterious but as long as it's working now...
