### ISSUE TITLE
422: UNPROCESSABLE ENTITY when manually searching for daily type TV show

### ISSUE THREAD

**Issue by RikuXan** [theotherp/nzbhydra#607]
When clicking on the magnifying glass in the search history on an API call for a show with daily season numbering, the manual search returns a window with a `422: UNPROCESSABLE ENTITY` error.

Example URL (as recorded by Chrome): `https://nzbhydra.host.com/internalapi/tvsearch?rid=5714&season=2016&episode=09%2F06&title=The+Daily+Show+with+Jon+Stewart&category=tvhd`

I assume that the slash in the episode name is the culprit, but strangely the API call seems to work, i.e. I'm getting results in Sonarr, only the manual search with the same parameters fails.

**Comment by theotherp** [comment]
Works fine for me. Please post a log file with debug level and the described error message.

**Comment by RikuXan** [comment]
The relevant lines from a debug-level log are:
```
2017-05-30 18:49:04,786 - DEBUG - web - Thread-35 - Call to method internalapi_tvsearch
2017-05-30 18:49:04,787 - DEBUG - web - Thread-35 - Requiring auth for method internalapi_tvsearch
2017-05-30 18:49:04,788 - ERROR - web - Thread-35 - Invalid request: {"episode": ["Not a valid integer."]}
```

This coincides with the result of the requested URL being 
```
{
  "messages": {
    "episode": [
      "Not a valid integer."
    ]
  }
}
```

**Comment by theotherp** [comment]
Got it. Fixed in current version. If you've already updated you can do a "force update" via the system section. Not yet updated for windows, though.
