### ISSUE TITLE
problem using hydra API

### ISSUE THREAD

**Issue by superjcvd** [theotherp/nzbhydra#609]
Hello,

I'm a new user of nzbhydra and my question is maybe dumb.
But anyway I give it a try :)

I wanted to use the API in order to query Hydra from FLEXGET tool.
But everytime I launch a query from FLEXGET I get this error message:
"Disabled for API searches: Binsearch, NZBClub, NZBIndex"

I tried the same from Sickbeard and Sickrage. And I always get the same message.
Does it mean API search is not supported by the 3 sites ?

**Comment by theotherp** [comment]
No, as it says these indexers are disabled for API searches. Check their settings in the config, see "Enable for...".

Even if enabled when searching using IDs (like IMDB) you will need to enable query generation so they'll be used.

You should get a "proper" newznab compatible indexer.

**Comment by superjcvd** [comment]
Thanks a lot for your answer. I added www.usenet-crawler.com in the providers and this is working fine :)

**Comment by theotherp** [comment]
You're welcome.
