### ISSUE TITLE
Button to select all results

### ISSUE THREAD

**Issue by eastons9** [theotherp/nzbhydra#610]
Hello,

Would it be possible to have a button that ticks all the results' checkboxes on a page?

Thanks.

**Comment by theotherp** [comment]
Use the "Invert selection" button or whatever it's called.

**Comment by eastons9** [comment]
Thanks for the reply, theotherp; however, I don't seem to have an "invert selection" option in NZBHydra.

**Comment by albino1** [comment]
![invert](https://user-images.githubusercontent.com/12164957/26907162-4e1dce4a-4ba6-11e7-8755-863aa54a7088.jpg)

**Comment by theotherp** [comment]
There should be another one on the upper left of the results table.

**Comment by eastons9** [comment]
Thanks for the reply, albino1. There must be something wrong with my installation, as I don't have any invert buttons. 
![untitled-1](https://user-images.githubusercontent.com/29088147/26954642-7fda6bec-4cf4-11e7-8f73-ff4b01268efb.png)

**Comment by theotherp** [comment]
Check your version in the updates tab of the system section. It might be
really old.

**Comment by albino1** [comment]
It's definitely old, those links in the bottom right haven't looked like that in ages.

@eastons9, you should backup your stuff before updating in case jumping that many versions breaks your installation.

**Comment by eastons9** [comment]
It said that I was up-to-date, but after I deleted it and started from scratch, I now see the updated page layout. Thanks for all the help. Not sure what was going on before.

**Comment by theotherp** [comment]
Well, I'm glad it's fixed.
