### ISSUE TITLE
Hydra doesn't display correctly on mobile

### ISSUE THREAD

**Issue by nemchik** [theotherp/nzbhydra#611]
* What do you expect to happen? What does happen? 
Expect Google chrome on Android to be able to access NZB Hydra.
Instead the navigation is invisible unless I switch the tab to desktop mode and the logo is about two times wider than my screen.
* Have you searched for this problem?
Checked other open issues here, didn't check closed issues (should have) 
* Can the problem be reproduced? How?
Yes. Visit Hydra from Google chrome on an Android phone.

Here is an imgur gallery of what I'm seeing (just a free screens with nothing personal) NZB Hydra on mobile https://imgur.com/gallery/yJl2U

**Comment by theotherp** [comment]
I know. Use nzb 360.

**Comment by theotherp** [comment]
See #189

**Comment by nemchik** [comment]
I've got NZB 360, it's lovely, but I only ide Hydra for API and stats, so adding it to 360 doesn't really do much for me. I'm trying to check stats from mobile.

I'll close this and keep up with #189, thanks!

**Comment by theotherp** [comment]
I'd like to have a better layout on mobile, but it took me ages to get it to look even reasonably ok on a big screen. CSS is not my strong suit.

**Comment by nemchik** [comment]
I may be able to help with that. It'll take some time to familiarize myself with your repo. Also I'm not a designer by any means, but a developer for sure, CSS is pretty familiar for me.

I won't have any free time to look at this right away, but once I've finished a few other projects I'll be a little more available to try contributing here.
