### ISSUE TITLE
Arch Linux Errno 13

### ISSUE THREAD

**Issue by vT0K3N** [theotherp/nzbhydra#612]
Hello,
I intalled nzbhydra from here:
https://aur.archlinux.org/packages/nzbhydra/
then I started it with "nzbhydra" in the terminal an get this following error:

2017-06-08 12:26:22,674 - NOTICE - nzbhydra - MainThread - Starting NZBHydra 0.2.217
2017-06-08 12:26:22,674 - NOTICE - nzbhydra - MainThread - Base path is /usr/lib/nzbhydra
2017-06-08 12:26:22,674 - NOTICE - nzbhydra - MainThread - Loading settings from /usr/lib/nzbhydra/settings.cfg
An error occured during migrating the old config. Sorry about that...: 
Traceback (most recent call last):
  File "/usr/lib/nzbhydra/nzbhydra.py", line 92, in run
    config.save(settings_file)  # Write any new settings back to the file
  File "/usr/lib/nzbhydra/nzbhydra/config.py", line 891, in save
    with open(filename, "w", encoding="utf-8") as f:
IOError: [Errno 13] Permission denied: '/usr/lib/nzbhydra/settings.cfg'
Trying to log messages from migration...

**Comment by theotherp** [comment]
Well, it cannot write to /usr/lib/nzbhydra/

Either install it somewhere else or use command line parameters to use a settings and database file in a folder where it can write.

Or just install it manually. That package was made by someone else.

**Comment by vT0K3N** [comment]
How can I install it manually? I'm relativly new to linux. Newbie friendly would be much appreciated.

**Comment by theotherp** [comment]
Download https://github.com/theotherp/nzbhydra/archive/master.zip.  unzip it somewhere. run it using python 2.7.

See https://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/ for how to run it as service and/or see the files in the contrib subfolder.

**Comment by fryfrog** [comment]
You used my AUR package, it works fine. Just do it right. :)

`sudo systemctl enable nzbhydra` to enable it, then `sudo systemctl start nzbhydra` to start it. Use `systemctl status nzbhydra` to see how it is doing. Surely you've noticed that every daemon in Arch has a systemd unit file? :)
