### ISSUE TITLE
HTTP 500 on login and no results returned with manual search from another program.

### ISSUE THREAD

**Issue by Sup3rLativ3** [theotherp/nzbhydra#615]
* I expect that upon logging in to not receive errors. I also expect results to be returned to searches performed by other applications such as sonarr. 
* Currently what happens is I get a "500 server timeout"error when I log in and when trying to do a manual search from sonarr I get no results.
* I have searched and find some mentions to the 500http status but none of the fixed solved the issue.
* unknown if the issue can be reproduced on another machine.

**Comment by Sup3rLativ3** [comment]
Seems like my upload failed so below is the relevant part of the log. I'm on mobile at the moment so please excuse the formatting. I will upload logs when I'm in front of my computer.

017-06-09 21:20:04,432 - INFO - web - Thread-6315 - Form login form user sup3rlativ3 successful
2017-06-09 21:20:24,669 - ERROR - web - Thread-6317 - results not ready, timed out.
Traceback (most recent call last):
  File "/usenet/nzbhydra/libs/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usenet/nzbhydra/libs/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usenet/nzbhydra/nzbhydra/web.py", line 474, in wrapped_function
    return f(*args, **kwargs)
  File "/usenet/nzbhydra/nzbhydra/web.py", line 1256, in internalapi_search_requestsforsearching
    searchRequests = get_search_requests(1, 20, sortModel=None, filterModel=filterModel, distinct=True, onlyUser=limitToUser)
  File "/usenet/nzbhydra/nzbhydra/stats.py", line 394, in get_search_requests
    total_requests = query.count()
  File "/usenet/nzbhydra/libs/peewee.py", line 3074, in count
    return self.wrapped_count(clear_limit=clear_limit)
  File "/usenet/nzbhydra/libs/peewee.py", line 3087, in wrapped_count
    return rq.scalar() or 0
  File "/usenet/nzbhydra/libs/peewee.py", line 2842, in scalar
    row = self._execute().fetchone()
  File "/usenet/nzbhydra/libs/playhouse/sqliteq.py", line 92, in fetchone
    self._wait()
  File "/usenet/nzbhydra/libs/playhouse/sqliteq.py", line 51, in _wait
    raise ResultTimeout('results not ready, timed out.')
ResultTimeout: results not ready, timed out.
2017-06-09 21:20:47,706 - INFO - backup_debug - Thread-6343 - Successfully wrote debugging infos to file /usenet/nzbhydra/debug/nzbhydra-debuginfo-2017-06-09-21-20.zip

**Comment by theotherp** [comment]
Try shutting down and restarting. This is currently a problem that affects some users and I haven't found a solution. I'm working on a new version of Hydra but that's not ready yet.

Unfortunately I don't really know a definitive way of fixing this.

**Comment by Sup3rLativ3** [comment]
Thanks for the quick reply. I have restarted both the service as well as the server.

Please feel free to merge if there is another issue and I will follow it for the future release.

Thanks again

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by marka65** [comment]
I have had similar issues for a long time - I just didn't worry about it. The work around for me was to retry it and eventually it would work once, or I'd manually search for it elsewhere.

Logs for my error today:
https://pastebin.com/2V2ALV6s

**Comment by Sup3rLativ3** [comment]
@marka65 I just restored the VM from a backup from before the update.

**Comment by marka65** [comment]
@Sup3rLativ3 Thanks....

**Comment by Sup3rLativ3** [comment]
Is there another error we can follow if this one is closed?

**Comment by theotherp** [comment]
Oops, sorry, I skipped over the comments and interpreted the "Thanks..." wrong.

Well, you can try the develop branch. I changed the database handling there. It seems to solve this problem but may introduce another. I know of at least one user who got everything working fine.

**Comment by theotherp** [comment]
See if the new version fixes this.

**Comment by theotherp** [comment]
Any news? Please comment if problem persists.
