### ISSUE TITLE
[SOLVED] All nzb's send from radarr to nzbget fail to download

### ISSUE THREAD

**Issue by ajkis** [theotherp/nzbhydra#617]
Version: Latest

## How to do a bug report
Manually trigger download in radarr.

debuginfo: https://drive.google.com/file/d/0B89x0Pnx4k71NkhybC1IZmFsLTQ/view?usp=sharing

**Comment by theotherp** [comment]
Well, what does "fail to download" mean? What does nzbget say?

**Comment by ajkis** [comment]
ups forgot to add it 
2017-06-20 20:56:04:0009	8922	Tue Jun 20 20:20:48 2017        ERROR   Error parsing nzb-file Abduction.2011.BluRay.1080p.AVC.DTS-HD.MA.5.1.nzb
2017-06-20 20:56:04:0009	8923	Tue Jun 20 20:20:48 2017        ERROR   Could not add collection Abduction.2011.BluRay.1080p.AVC.DTS-HD.MA.5.1.nzb to queue

If i check the actual link its pointing to details  of the video on indexer. 
Looks like wrong links are send, I tried with both proxy, redirect, send link, upload nzb under hydra settings.

p.s. If I search with hydra i can add it to nzbget normally with settings:
NZBGET: Proxy to indexer & upload nzb ( if i change it then it wont work from hydra either )

**Comment by theotherp** [comment]
Does this happen for all NZBs or just the ones from a specific indexer?

**Comment by ajkis** [comment]
Tried 8 out of 10 and it happened on all of them.

**Comment by ajkis** [comment]
I completely removed my current installation then install latest x.17 and updated to x.19 configure it from get go and its working now.
