### ISSUE TITLE
All API keys generated have 0000000000 appended

### ISSUE THREAD

**Issue by Mobrockers** [theotherp/nzbhydra#619]
I am running NZBHydra on windows 10 Pro using the windows native release. I am on the latest version. I am using Chrome Version 58.0.3029.110 (64-bit) for windows.

All the api keys I generate on my system end in 0000000000, all the time. When I execute the code used to generate this api key `(Math.random() * 1e32).toString(36)` in my js console all the generated keys also end in 0000000000. The default api key on a fresh install however does not end in 0000000000, and my previous api key also did not end in 0000000000. I could not find anything about this and have not been able to generate a key not ending in 0000000000.

**Comment by theotherp** [comment]
Hm, works fine on firefox but not on chrome.

Thanks for the report. It's a bug but a very minor one. You can just remove the zeroes or keep them or put in any alphanumeric apikey you want.
