### ISSUE TITLE
Cannot clear Newznab settings once Preset is chosen

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#62]
On the Indexers Configuration page, if you accidentally select one of the Indexer Presets then you're unable to manually create a new non-Preset entry.   All you can do is choose another Preset, but there's no way to clear it without leaving the page and coming back to it.  I suppose you can just type it out by hand, but it *feels* like you're overwriting the Preset settings.  A better solution would probably be to just have `None` as one of the Presets and then have that clear all of the fields.

I hope I'm explaining that correctly.  If not, let me know and I can attach some screen shots and try and do a better job.

**Comment by theotherp** [comment]
I cannot reproduce that problem. When I select a preset it fills the name, host and search types fields but I can then remove their content. Or do you mean there's no way to clear these three fields at once, without having to do so manually?

**Comment by albino1** [comment]
> Or do you mean there's no way to clear these three fields at once, without having to do so manually?

Right, that's what I mean.  It seems counter intuitive to leave a Preset selected, but then input different information.  It seems like it would make more sense to reset it back to None and then input the new non-Preset indexer.

**Comment by theotherp** [comment]
Right. I could add a new "None" default and whenever the user selects a preset and then changes the host or name switch back to "None" so they wouldn't contradict each other.

For me (as the developer) it seemed obvious that they would only prefill the fields and so you wouldn't need to change the preset if you changed anything.

**Comment by albino1** [comment]
That would work just fine I think.  And if they have a Preset selected and then switch to None is should clear the fields that the Preset filled in.
