### ISSUE TITLE
Indexers that get permanently disabled should still show in stats

### ISSUE THREAD

**Issue by nemchik** [theotherp/nzbhydra#620]
* What do you expect to happen? What does happen? 
I have some indexers added with trial accounts. Once they expire they tend to fail authentication and Hydra permanently disables them. They are no longer used for searches and are hidden from stats. I would like disabled indexers to remain visible in stats.

* Have you searched for this problem?
Yes. https://github.com/theotherp/nzbhydra/issues/208 requests just about the opposite of what I would expect. Maybe this can be made optional? I feel like having a toggle directly on the stats page would be perfect! It seems like an indexer only shows up in stats if it had been used during the selected time period, so over time the disabled indexers would work themselves out of the stats reported (default is past 30 days right?)

* Can the problem be reproduced? How?
Yes, see description above.

**Comment by theotherp** [comment]
I'll add a button to switch that.

**Comment by theotherp** [comment]
Implemented in v2 which will be released soon.
