### ISSUE TITLE
SSL "unable to get local issuer certificate" via NZBGet v19 and OpenSSL Client

### ISSUE THREAD

**Issue by TBhimdi** [theotherp/nzbhydra#623]
NZBGet does SSL certificate checking now:
https://nzbget.net/certificate-verification

This is the error I now get (after clicking the NZBGet icon in search results, it shows up in Downloads, then under Messages):
```
TLS certificate verification failed for foo.example.com: unable to get local issuer certificate. For more info visit http://nzbget.net/certificate-verification
```

NZB Hydra isn't sending the correct SSL response/data as far as I can tell. Here are some OpenSSL connection tests that recreate the same error outside of NZBGet (443 HTTP response works fine, 5075 NZB Hydra reproduces the error).

WORKING (non-NZB Hydra SSL):
```
>>openssl s_client -connect foo.example.com:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = bar.example1.com
verify return:1
---
Certificate chain
 0 s:/CN=bar.example1.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
.
.
.
```

NOT-WORKING (NZB Hydra SSL):
```
>>openssl s_client -connect foo.example.com:5075
CONNECTED(00000003)
depth=0 CN = bar.example2.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = bar.example2.com
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=bar.example2.com
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
---
Server certificate
-----BEGIN CERTIFICATE-----
.
.
.
```

NZB Hydra's SSL works fine when connecting via web browser, always has, no errors, green lock shows up.

**Comment by theotherp** [comment]
I'd ask you to ask the nzbget developer for advice. I wouldn't even know
where to begin to look.

**Comment by TBhimdi** [comment]
I've posted an issue in the NZBGet GitHub page (https://github.com/nzbget/nzbget/issues/403).

I'm no SSL guru, but is it possible that NZB Hydra requires the intermediate chain cert?
https://letsencrypt.org/certificates/

Also, running port 5075 through an SSL Checker (https://www.sslshopper.com/ssl-checker.html#hostname=foo.example.com:5075) gives:
```
The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate.
```

While the same machine for port 443 passes beautifully (same Let's Encrypt cert) and the "pass" logo points from Server -> Chain (which 5075 doesn't show, thus failing)

**Comment by TBhimdi** [comment]
The NZBGet dev and I went through many scenarios using the same cert provider (Let's Encrypt). NZBGet and Firefox work fine with the certificate when connecting to Apache, but using the same cert, connecting to NZB Hydra gives a warning/error.

The dev agrees it may be something with NZB Hydra at this point:
https://github.com/nzbget/nzbget/issues/403#issuecomment-311389654

**Comment by theotherp** [comment]
Alright. I'll try and take a look but it will take a while.

**Comment by TBhimdi** [comment]
I think I've got a fix. After a lot of back and forth with the NZBGet dev and getting an idea of what could be wrong, I looked into the NZB Hydra code. It turned out to be a one line addition:

In web.py, after:
```python
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
```
Add this line:
```python
context.load_verify_locations(cafile="ssl.ca")
```
"ssl.ca" is the CA Certificate that Let's Encrypt gives you (alongside the ssl cert and private key). It includes the DST Root CA needed in the chain). It should be the same one available here:
https://letsencrypt.org/certificates/

Also, I don't know if this affects anything, but the pydocs recommend using "create_default_context()" instead of creating your own context.

**Comment by TBhimdi** [comment]
The above addition would require a third SSL input box under Config->Hosting to specify the SSL Intermediate (ssl.ca). So I guess not really a one-line fix.

**Comment by TBhimdi** [comment]
hugbug had a good catch on also using the OS cert store. Redid the code block to load OS defaults after specifying the manual CA Certificate. This is the entire try block for creating the SSL context in web.py:

```python
context = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH, cafile="/path/to/ssl.ca")
context.load_default_certs(purpose=ssl.Purpose.CLIENT_AUTH)
context.load_cert_chain(config.settings.main.sslcert, config.settings.main.sslkey)
```
```load_default_certs``` is already called from within ```create_default_context```, but calling it again insures that the manual cafile isn't the only one used. The documentation only mentions falling back to OS level if all three parameters are None and doesn't go into detail otherwise.

**Comment by theotherp** [comment]
Thanks for the detailed analysis. I'll add a further box in the config and the required code when I have the time.

**Comment by theotherp** [comment]
I'm currently trying to implement this but can't really test it. What if there's no CA file? Should I do a check for the CA file setting and keep the old code if none is set and use your code if one is set?

**Comment by theotherp** [comment]
Also, why client auth?

**Comment by TBhimdi** [comment]
The CA file is optional, so a None can be sent in. It defaults to None now in the backend anyway since NZB Hydra never specifies it.

As for CLIENT_AUTH, that's if the context is acting as a Server (yeah, it's backwards and confusing). It's to specify that the server-side socket is being used to authenticate a CLIENT. So if you wanted to connect to a server, you would create a SERVER_AUTH context instead.

**Comment by theotherp** [comment]
Hm, alright. Will be included in next update. Thanks for the help.
