### ISSUE TITLE
Issue connecting to Radarr

### ISSUE THREAD

**Issue by timmy1980** [theotherp/nzbhydra#625]
Hi,

I am using nzbhydra on a Synology box. But I have trouble connecting Radarr to it. It is saying no results returned.

When I do this manual http://192.168.10.180:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=<APIKEY>&offset=0&limit=100

Then there are no results returned.

Do I something wrong?

**Comment by theotherp** [comment]
Probably, yes ;-)

First (or last) mistake was not to post any propery infos. I expect at least a log, better debug infos (see the text that you just ignored when you created this issue).

Did you check the log? Was any indexer selected? Do you have at least one newznab compatible indexer (i.e. one not preconfigured) added? If not you need to add query generation.

**Comment by timmy1980** [comment]
Hi,

Sorry, I try to add them:

[partlog.txt](https://github.com/theotherp/nzbhydra/files/1119045/partlog.txt)
![2017-07-03 11_23_52-nzb hydra - config indexers](https://user-images.githubusercontent.com/29842603/27786646-3ec3cb2a-5fe2-11e7-97f6-f90743aee629.png)
![2017-07-03 11_23_22-nzb hydra - config searching](https://user-images.githubusercontent.com/29842603/27786647-3ec82152-5fe2-11e7-95a1-e2a07afae675.png)
![2017-07-03 11_24_14-nzb hydra - config indexers](https://user-images.githubusercontent.com/29842603/27786648-3ecb9904-5fe2-11e7-9510-9c4605e245f8.png)


I hope this will help.

**Comment by theotherp** [comment]
You need to enable query generation in the searching config.

You should also get a proper indexer. You will not get any proper results without.
How and what to get would exceed the support I can give you here. I'd recommend reading https://www.reddit.com/r/usenet and its FAQ and if necessary asking there.
