### ISSUE TITLE
New api.nzb.su don't work

### ISSUE THREAD

**Issue by rjulie95** [theotherp/nzbhydra#631]
Version 0.2.220 
Docker on Synology : DSM 6.1.2-15132 Update 1
The new version of api.nzb.su return incoret result like this

![image](https://user-images.githubusercontent.com/8410772/28185113-656ea4fc-6816-11e7-9126-f6fab104fbf9.png)

In think so is a new version nzb.su

Thank

**Comment by theotherp** [comment]
That's probably an error on their side.

**Comment by theotherp** [comment]
See #635
