### ISSUE TITLE
Create 0.2.220 Release?

### ISSUE THREAD

**Issue by fryfrog** [theotherp/nzbhydra#632]
The web ui says 0.2.220 is out (also 0.2.219), but there is no actual release for it. Maybe was forgotten?

**Comment by theotherp** [comment]
There doesn't need to be a release. Just download the zip of the current
source code.

Yes, I forgot.

**Comment by fryfrog** [comment]
I maintain the stable `nzbhydra` AUR package for Arch Linux, it is based on your releases. There is an `nzbhydra-git` that does what you suggest.

If it isn't too much trouble and you consider 0.2.219 or 0.2.220 to be stable, an actual release for it would be spiffy. If they're not, then no worries.

**Comment by theotherp** [comment]
Ah, sorry, didn't know that. Will do.

**Comment by fryfrog** [comment]
Thanks :)
