### ISSUE TITLE
Performing a lot of consecutive searches too quickly results in 'list' object has no attribute 'didsearch' error

### ISSUE THREAD

**Issue by nemchik** [theotherp/nzbhydra#633]
**What do you expect to happen? What does happen?**
Searching through the API via Sonarr for many items consecutively seems to cause this error message `'list' object has no attribute 'didsearch'`. In my case I used the "Search All Missing" button on about 1200 items (I know, this isn't the best idea).

**Have you searched for this problem?**
Yes https://github.com/theotherp/nzbhydra/issues/585 hopefully I provide better information about what's happening and we can troubleshoot.

**Can the problem be reproduced? How?**
Yes. Use Sonarr (or probably Radarr) to search for all missing items if you have a lot of missing items.

**Use a proper title. Describe the problem succinctly, don't just copy and paste the error message.**
Ok :)

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**

[nzbhydra-debuginfo-2017-07-17-16-54.zip](https://github.com/theotherp/nzbhydra/files/1154116/nzbhydra-debuginfo-2017-07-17-16-54.zip)
[sonarr.logs.zip](https://github.com/theotherp/nzbhydra/files/1154121/sonarr.logs.zip)
Hopefully that covers everything you need (and hopefully there's no personal info in those logs lol).

**Comment by nemchik** [comment]
Possibly related https://github.com/theotherp/nzbhydra/issues/576 The errors here seem to be similar to what i'm seeing in my log.

**Comment by nemchik** [comment]
Ok I've done a lot more testing and found my issue seems to be with binsearch. Disabling binsearch fixes my issue. Enabling it causes errors in every search (internal and API) but Hydra doesn't disable binsearch or show any error on the indexer status page.

**Comment by theotherp** [comment]
That's interesting. I'll take a look.
