### ISSUE TITLE
ERROR - web - 'ascii' codec can't encode character u'\u0141' in position 30: ordinal not in range(128)

### ISSUE THREAD

**Issue by jeff47** [theotherp/nzbhydra#634]
```
2017-07-17 22:06:24,352 - ERROR - web - Thread-30 - 'ascii' codec can't encode character u'\u0141' in position 30: ordinal not in range(128)
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1475, in full_dispatch_request
  File "site-packages\flask\app.py", line 1461, in dispatch_request
  File "nzbhydra\web.py", line 474, in wrapped_function
  File "site-packages\webargs\core.py", line 412, in wrapper
  File "nzbhydra\web.py", line 864, in internalapi_search
  File "nzbhydra\web.py", line 824, in startSearch
  File "nzbhydra\search.py", line 382, in search
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0141' in position 30: ordinal not in range(128)
```

Full log:
[nzbhydra-debuginfo-2017-07-17-22-06.zip](https://github.com/theotherp/nzbhydra/files/1154459/nzbhydra-debuginfo-2017-07-17-22-06.zip)

I'm running into this issue when performing a search within NZBhydra.  I get a "error:500" that comes up, and I see a Unicode error in the log.  After that, searching via the API or the GUI is unresponsive until I restart NZBhydra.  This warning in the log may be related:

```
2017-07-17 22:09:23,680 - WARNING - search - Thread-48 - No indexers were selected for this search:
```

It *appears* to occur primarily when I have Jackett indexer in use, but I'm not absolutely sure.

**Comment by judhat2** [comment]
Same thing has happened to me.  I was pretty sure it was because some torrent titles had Chinese characters.  I just modified one line in the code to let the searches finish. Albeit, I don't think it totally fixes the problem, since it just skips the offending search result.

 I changed this line, https://github.com/theotherp/nzbhydra/blob/master/nzbhydra/search.py#L386, into: 
```python
except (IntegrityError, OperationalError, UnicodeEncodeError) as e:
```

If you are on linux, you can run sed to change it, then restart nzbhydra.
```bash
sed -i 's/IntegrityError, OperationalError/IntegrityError, OperationalError, UnicodeEncodeError/' ~/nzbhydra/nzbhydra/search.py
```

**Comment by jeff47** [comment]
Thanks, that option isn't feasible for the Windows binary version unfortunately.

**Comment by jeff47** [comment]
I'm curious if this regex in config/searching->"Forbidden regex" box will work:

[^\x00-\x7f]+

It should match non-English characters, but just like your solution it's far from ideal.

**Comment by theotherp** [comment]
That wouldn't help because it's used after the parsing fails. I'll try to
fix this on the weekend.

**Comment by theotherp** [comment]
@jeff47 Please call this URL in your browser:
`http://127.0.0.1:9117/torznab/limetorrents/api?extended=1&t=search&offset=0&apikey=<APIKEY>&limit=100&q=blade+runner&maxage=3500` using your correct Jackett/Cardigann API key for lime torrents.

Copy the XML to some text editor and remove your passkey from the resulting URLs. Save everything else in a file and send it to me per mail to theotherp@gmx.de

**Comment by jeff47** [comment]
Redacted XML file sent.

**Comment by theotherp** [comment]
Fixed in next version.
