### ISSUE TITLE
Assign use priority levels to each indexer

### ISSUE THREAD

**Issue by Splendid-Idea** [theotherp/nzbhydra#637]
[enhancement]

This feature would borrow the news server selection method from nzbget to better manage indexers with very limited availability (5 API hits per day, 5 downloads, etc).

This would allow the user to set up a hierarchy of groups of indexers that would only move to the next group if:

- Indexer is not accessible or not responding
- No hits
- General "continue on error or null result" toggle is selected

We can then save some API hits for the unused free indexer accounts instead of using all indexers for every called search.  I understand that there is the load balancing feature that I could set to a high value to prioritize the _chances_ that an indexer will or won't be chosen, but this is not ideal for managing more than a few indexers.

**Comment by theotherp** [comment]
Selection process and configuration are very complicated as it is. I don't see a reason to make that worse for the scenario that you describe.

**Comment by Splendid-Idea** [comment]
Okay - thanks much for considering, and also for crafting such a useful and interesting utility.

**Comment by theotherp** [comment]
You're welcome :-)
