### ISSUE TITLE
Indexer Priority and NZB Duplicate Detection

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#64]
I'm not sure the indexer priority and duplicate detection is working as it should.  Here's an example query:

`breaking bad s01e01 720p bluray`

Which brings back a lot of results, but here's a particular screenshot of a grouping of "duplicates":

![al-nzbhydra-indexerorder duplicatenzbdetection](https://cloud.githubusercontent.com/assets/12164957/11912039/5950e4a4-a5e0-11e5-9f73-efd463040800.jpg)

Obviously that's all a mess.

In regards to Indexer Priority, NZBFinder was the chosen result to display, but the score for that indexer is 10 with 6 higher priority indexers all listed below it.  Specifically, I have DOGnzb set to Indexer 0 and it's 11th on this list (ignoring the fact that few of these are true duplicates and assuming just the logic is broken).

**Comment by theotherp** [comment]
Uhm no, that looks correct. What you're seeing are no duplicates but just results grouped by name. If you click "Include duplicates" you should see a second set of buttons to expand the actual duplicate groups.

Notice how none of the shown results have the same age, so they cannot be duplicates. Duplicates are results from different indexers for the same identical upload.

The title groups are only sorted by age, not by priority. The indexer priority only decides which result of a duplicate group is displayed.

**Comment by albino1** [comment]
> What you're seeing are no duplicates but just results grouped by name. If you click "Include duplicates" you should see a second set of buttons to expand the actual duplicate groups.

When I "include duplicates" I get the additional expansion arrow, but when I click on it nothing happens.

Screenshot:

![al-nzbhydra-duplicates01](https://cloud.githubusercontent.com/assets/12164957/11912193/54b2b146-a5e7-11e5-92f2-43981ae1d21d.jpg)

**Comment by albino1** [comment]
Also, for some reason DogNZB is no longer being searched, even though it's enabled.  I've tried a bunch of searches and DogNZB never gets run, even though it was working before:

![al-nzbhydra-dognotsearched](https://cloud.githubusercontent.com/assets/12164957/11912211/202caee4-a5e8-11e5-8e7a-7262e3cf94c6.jpg)

**Comment by theotherp** [comment]
http://i.imgur.com/M0Pxy2F.png

This is what the expanded duplicates should look like.

But I can reproduce the problem where they wouldn't be expanded. It doesn't always happen but sometimes there's an exception in the JS code. Will look into it.

Is DogNZB mentioned in the logs anywhere?

**Comment by theotherp** [comment]
Uhhh I'll check it later, too hung over right now.

**Comment by albino1** [comment]
> Is DogNZB mentioned in the logs anywhere?

Well now it's showing up, I have no idea why it disappeared for a dozen searches, but it's worked for my last few tests.

There's little to no information in my log, it seems to have stopped logging stuff about a half hour after I started NZBHydra.

I know that in SABnzbd that Python has an issue logging more than a certain amount of data in Windows before it quits.  Here's a relevant link:

> **Logging stops**
> Sometimes logging stops.
> This is a notorious bug in Python logging when running on Windows. SABnzbd will function as normal.

http://wiki.sabnzbd.org/known-issues#toc15

> Uhhh I'll check it later, too hung over right now.

Hah, no problem.

**Comment by theotherp** [comment]
There's definitely something wrong with the duplicate detection. Shit, I was hoping I would never have to crawl through that part of my code again... :-(

**Comment by albino1** [comment]
> There's definitely something wrong with the duplicate detection. Shit, I was hoping I would never have to crawl through that part of my code again... :-(

Ugh, sorry to be the bearer of bad news.

**Comment by judhat2** [comment]
Something I noticed is the date that is given is, sometimes, the date that the nzb was added to the nzb indexer and not the date the nzb was posted to usenet.  Below is an example of this.

![image](https://cloud.githubusercontent.com/assets/3536802/11913175/72088984-a69e-11e5-97ec-107df9fd32fb.png)

**Comment by theotherp** [comment]
I can only rely on the data / dates from the indexers which provide the indexing date, not the upload date. What do yo expect the age on the screenshots to actually look like?

**Comment by theotherp** [comment]
I haven't found any indication that the duplicate detection doesn't work properly. I'll close this. Please reopen if you find any errors. (Some false negatives are to be expected).
