### ISSUE TITLE
Show age on the download history page

### ISSUE THREAD

**Issue by nemchik** [theotherp/nzbhydra#640]
* What do you want to happen?
See the title
* If not clear, why do you want it?
I'd love too see how often I'm downloading things past a certain point of retention
* Do you think it's something only you need or something that might be popular?
I think many people could use this information
* If need be explain the use case.
I will use this to determine whether I actually need a provider with higher retention. Depending on how often my automation tools attempt to send a high age downloads to my client will tell me if I need a high retention provider

**Comment by albino1** [comment]
I like this idea.  Some stats on the Statistics page would be welcome as well.  Average NZB age, oldest NZB downloaded, number of NZBs over a year old, over 1000 days old, over 2000 days old, etc.  Could be fun.

**Comment by theotherp** [comment]
I'll add it to the list.

**Comment by nemchik** [comment]
I'm wondering if it makes more sense to display the age of a download at the time it was downloaded and the number never changes (ex: it was 200 days old when it was downloaded) or if it's best to display the overall age of the download (ex: it was 200 days old when it was downloaded it, but the current age is 700 days old, so we see 700 for age) or somehow both?

I think if this is included in stats somehow like albino1 mentioned then the first option makes more sense (200 days when downloaded, never changes).

**Comment by theotherp** [comment]
Implemented in v2.
