### ISSUE TITLE
every indexer fails but the one i added

### ISSUE THREAD

**Issue by phynias** [theotherp/nzbhydra#641]
all the default indexers that are enabled fail every time. 

![capture](https://user-images.githubusercontent.com/10147213/28504930-4846e780-6fd3-11e7-9c1e-65d1bd654146.PNG)

**Comment by phynias** [comment]
nm looks like my fault. missing package.

**Comment by theotherp** [comment]
Alright. In the future when creating an issue please follow the
instructions and post a log.
