### ISSUE TITLE
After update to 0.2.223 problem with Proxy

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#644]
i updated to the new version. first restart is okay, after logout and re-entry of username and password, i have a problem with my proxy.

Login jumps to  127.0.0.1:5075/nzbhydra and just shows a blank page.
I can not generate a new copy of my settings and logs since i can´t use nzbhydra anymore, but the data before the update is here
[logfile.txt](https://github.com/theotherp/nzbhydra/files/1182501/logfile.txt)
[settings.txt](https://github.com/theotherp/nzbhydra/files/1182502/settings.txt)

I use hydra on a VPS running Debian 8.

**Comment by theotherp** [comment]
Make sure you call the URL with a trailing slash

**Comment by Hobbabobba** [comment]
ok, now i can use the web ui, but sickrage and couchpotato can´t reach hydra. here are the logs and settings after the update.
[logfile.txt](https://github.com/theotherp/nzbhydra/files/1184917/logfile.txt)
[settings.txt](https://github.com/theotherp/nzbhydra/files/1184918/settings.txt)

**Comment by Hobbabobba** [comment]
just had to enter nzbhydra again into Sickrage as a new search-engine. now it works

**Comment by Hobbabobba** [comment]
fixed after re-adding hydra to sickrage
