### ISSUE TITLE
Can't send to SABnzbd (Stuck on trying to fetch)

### ISSUE THREAD

**Issue by antigravity83** [theotherp/nzbhydra#648]
When trying to send the NZB from NZBHydra to SABnzbd, the file will not load in SABnzbd, and remains stuck on "Trying to fetch..."

NZBHydra Log: https://pastebin.com/DAm8f3zg

SABnzbd Log: https://pastebin.com/rFvuppiE

**Comment by theotherp** [comment]
An easy fix would be to configure hydra to upload the nzb to sabnzbd.

**Comment by antigravity83** [comment]
How would I do that?

**Comment by theotherp** [comment]
Change "NZB adding type" in the download section of the hydra config.

**Comment by antigravity83** [comment]
Unfortunately I receive an error message when attempting that

https://pastebin.com/KCPr427V

No issues with SAB as far as I know- I can use it ok with Sonarr, Radarr etc. 

I am behind a reverse proxy- but NZBHydra seems to be detecting Sabnzbd enough to attempt to push the file to it.

**Comment by theotherp** [comment]
65080 is your sabnzbd port?

**Comment by theotherp** [comment]
Well, the connection between the programs doesn't work. Can't help you with that specifically.

**Comment by antigravity83** [comment]
Yup thats the correct port.

NZBHydra is successfully detecting Sabnzbd though? And its able to start the push process, but doesn't finish it.

So the connection is there?

**Comment by theotherp** [comment]
I don't know what to say. Yes, it's apparently able to contact it but it cannot upload the NZB. sabnzbd can contact Hydra in some way but then can't download the NZB. I can't give you any details why it may not be working except that it should. Sorry.

**Comment by theotherp** [comment]
Can you download the NZB from hydra using your browser?

Enter  `http://flixnow.net:5075/nzbhydra/getnzb?apikey=<APIKEY>&searchresultid=6a8babfcaef1230cd08d93e34e0798208ee9132d&downloader=SABnzbd` in your browser (using the correct API key).
