### ISSUE TITLE
Links to internal pages sometimes not correct / truncated, contain wrong additional subfolder.

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#65]
Right now if you right-click on one of the top links, such as Config, and choose Open Link in New Tab you end up with a page that looks like this:

![al-nzbhydra-newtab](https://cloud.githubusercontent.com/assets/12164957/11912065/46a43292-a5e1-11e5-9155-f934dd6cb7a0.jpg)

Ideally you should be able to get the full normal page instead.

**Comment by theotherp** [comment]
Still fails in some cases, even with correctly set base URL. No idea how to solve this, will keep it open though.
