### ISSUE TITLE
--port undesired effect

### ISSUE THREAD

**Issue by hotio** [theotherp/nzbhydra#650]
Small bug I think.

When starting hydra with the command line arg `--port 8080`, hydra starts up and is available on port 8080.
So far so good, the configured setting for the port remains at 5075 in the UI/config.

Letting Radarr/Sonarr do a search results in releases being found, all working as expected, but when they try to download an NZB, it appears they are trying to do so on port 5075, because after changing the port in the config section of the UI to 8080, it works again.

Shouldn't the `--port` arg set the new port for the whole app?

**Comment by theotherp** [comment]
Please post your debug infos.

**Comment by theotherp** [comment]
You can also just set the external URL to the correct URL.

**Comment by hotio** [comment]
There's nothing logged, Radarr does a search on port 8080 as configured with --port 8080, this all works great, but when radarr wants to fetch the nzb, I'm guessing nzbhydra gives a url in the results which contains the wrong port.

Sure, manually editing the port in the configuration to 8080 solves the problem, but what's the point of an commandline switch if it only sorta works.

Most applications when the port is overridden with a commandline argument adjust their config accordingly and apply the new port application wide.

**Comment by hotio** [comment]
I just checked the Radarr log and my hunch is correct nzbhydra gives radarr the wrong url to fetch the nzb when started with --port 8080, but config contains 5075.

This might be intended behaviour on your part, but it's strange behaviour from my point of view....

**Comment by theotherp** [comment]
No, it's not intended behavior. But in two years I've never heard about problems with this so please post your debug infos...

Anyway, while of course the command line option should work it was just intended as an emergency switch to get Hydra started. Just set the correct port in the config and you're done.

**Comment by hotio** [comment]
Ah OK, if it's supposed to work like that I'll work around the problem in that way. Was already doing it like that. Just wanted to help...

Like I said previously I already enabled debug logs, but nothing gets logged. At the point where it goes wrong the request from Radarr is made on a port where Hydra is not listening, before the point of failure all is business as usual.

**Comment by theotherp** [comment]
The debug India also contain the settings.cfg which allows me to see if
everything is configured as it should be. I'm not saying you made a mistake
but half of the issues here are wrong configurations and not bugs.
