### ISSUE TITLE
Search results in a 500:Internal Server Error - Indexer_search

### ISSUE THREAD

**Issue by asujosh1** [theotherp/nzbhydra#651]
Trying to search for something and I consistently get this same error. I've tried turning off each of the indexers one at a time, with no change. I've tried removing log and DB to verify that's not the cause. 

Attached are settings and logfile with debug on. 

[settings.txt](https://github.com/theotherp/nzbhydra/files/1220633/settings.txt)
[logfile.txt](https://github.com/theotherp/nzbhydra/files/1220632/logfile.txt)

**Comment by theotherp** [comment]
Try disaling nzbclub.

**Comment by asujosh1** [comment]
Just tried that, no change.

**Comment by reedtaylor** [comment]
I'm able to reproduce this error on an unconfigured, vanilla install of the linuxserver.io docker container  ( https://github.com/linuxserver/docker-hydra ).  Acknowledging that that may not be an official distribution channel, it should at least make it easy for anyone to reproduce.

To reproduce:
(1) instantiate container
docker create --name=hydra \
-v <path to data>:/config \
-v <nzb download>:/downloads \
-e PGID=<gid> -e PUID=<uid> \
-e TZ=<timezone> \
-p 5075:5075 linuxserver/hydra

(2) visit the nzbhydra instance with default config  (http://hostname:5075/)

(3) issue any manual search in TV mode

In the above setup I can confirm that the nzbhydra instance reports itself as being up to date as of this writing (Current version: 0.2.225)

**Comment by theotherp** [comment]
I'll take a look but it may take some days.

**Comment by theotherp** [comment]
Ok, thanks for the instructions,  @reedtaylor 

This is an issue only with the three raw search engines (binsearch, nzbindex, nzbclub) when searching a specific season and/or episode of a TV series. As that it's relatively isolated.

I'll commit a fix in the coming days.
