### ISSUE TITLE
problem with NzbGet password 

### ISSUE THREAD

**Issue by tomtom602** [theotherp/nzbhydra#652]
I just installed NzbHydra, everything works fine expect for NzbGet, wich I can't connect.
I've found the problem, when I looked to NzbGet log : a caracter of my pasword is wrong.
My password contain the caracter | (pipe) but in the log I see %7C which this caracter encoded value.
is there an unencode missing somewhere ?
I don't want to change my password for that if it's possible...

thank you for your help

**Comment by theotherp** [comment]
No, changing your password is the only way. I haven't found a way to fix this.

**Comment by tomtom602** [comment]
I solved the problem by myself !
I modified the code in the downloader.py file 
in the get_rpc function I changed the following lines :

        if username is not None and password is not None:
            #f.path.add("%s:%s" % (username, password))
            f.username = username
            f.password = password

and now it works perfectly without changing my password ! :)

**Comment by theotherp** [comment]
Well that was easy... Nice. Thank you.
