### ISSUE TITLE
comments link doesn't use dereferer

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#653]
When using a dereferer, I noticed that an nzb's comments link doesn't use a dereferer, like the details link does. Not a big deal, but I thought it might be something that could be fixed easily.  Perhaps at this line? https://github.com/theotherp/nzbhydra/blob/master/ui-src/html/directives/search-result-non-title-columns.html#L24

**Comment by theotherp** [comment]
Sure, just a small bug easy to fix.
