### ISSUE TITLE
dognzb's "total results" and "Load more" compatibility

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#656]
Dognzb always returns "100" as the total results, if it has more than 100 results. So NZBHydra thinks that it only has 100 releases available.  Because of that, when the "Load more" button is used to get the next offset of results, dognzb isn't called again with a new offset.  

I asked on their forum several months ago if this could be changed.  Their answer was that they would ask the main admin about it, but nothing ever came of it.  I assume they are not going to change.

I do a lot of manual searches in Hydra's web interface and often use the "Load more" function.  Dognzb doesn't get searched beyond the first 100 results.  But I would like to see all that dognzb has to offer, since it usually has unique nzbs, so I have to go to their webpage to do another search.  
 
My request is this. Can you allow dognzb to be used by the "Load more" function when it gives "100" as the total results and exhaust all results.  I noticed that Binsearch doesn't return a total, and Hydra continues to search past the first 100.  It gives this message in the log: https://github.com/theotherp/nzbhydra/blob/5832d34ff79468ec7d092cf6b98c8e77179edb2a/nzbhydra/search.py#L402
Perhaps dognzb can be adapted to do something similar? I tried to modify search.py myself, but I couldn't figure it out.

I know this affects a small percentage of users (maybe just me) and may not be worth the trouble, but I love it if this could be implemented.

**Comment by theotherp** [comment]
I'm aware of that limitation and IIRC asked about the same thing once.

I'll think about it but don't think I'll get to implementing it in quite a
while, sorry. It might take a lot of work.

**Comment by theotherp** [comment]
Btw, while Bindsearch doesn't report a number of total results it reliably
reports if there are more. That's an important difference.

**Comment by judhat2** [comment]
> I'll think about it but don't think I'll get to implementing it in quite a
> while, sorry. It might take a lot of work.

Understandable.



> Btw, while Bindsearch doesn't report a number of total results it reliably
> reports if there are more. That's an important difference.

Ah, good point.  I guess the only way to know if dognzb has more is if the total ends in zeroes.  Not the best way.

**Comment by judhat2** [comment]
Just want to add that total is always "100" no matter what the offset is until the last page is reached. At that time, the total number of results on that page which is less than 100.  This could be used to check if there is more results available.

**Comment by theotherp** [comment]
Implemented in v2.
