### ISSUE TITLE
cannot do any searches at all getting "database disk image is malformed"

### ISSUE THREAD

**Issue by Menz01** [theotherp/nzbhydra#657]
i dont seem to be able to do any searching. when i do i get an error "database disk image is malformed" i see this error repeated in the logs. i am new to this and not really sure what to do to fix it.

**Comment by theotherp** [comment]
Shutdown, delete all nzbhydra.db.* files, start. You'll lose your history
and stats.

**Comment by Menz01** [comment]
that worked. thank you. just as an FYI... i tried doing what i thought was the same thing in the GUI (System --> Delete Log and Database) and it did not work. i have NZBHydra running as a service so i had to shutdown and stop the service and then it worked. thank you

**Comment by theotherp** [comment]
Noted.
