### ISSUE TITLE
Nzbhydra with Jackett Torrent download

### ISSUE THREAD

**Issue by mrlong67** [theotherp/nzbhydra#658]
So have set up jackett with nzbhydra. The search option works wonderfully. The error/or my error is the download/magnet section.

 I use transmission and the first time the torrent download button was clicked it gave me an option to open in transmission/ just once/always. In my naivety i clicked dont open an now i cant get that option back no matter what i do. So now even if the torrent is there it doesn't associate with any down loader.

Any ideas?

Thanks
mrlong67

**Comment by theotherp** [comment]
This isn't anything specific to Hydra. It depends on your browser. In Firefox go to Options -> Applications. In Chrome I don't know.

**Comment by doom1942** [comment]
i have a question related to this. Do i need to set up a Torznab with NZBhydra for the jacket search results to be sent to sonarr / radarr?

**Comment by theotherp** [comment]
Torznab results via API are not (yet) supported. You can access the torrent results from the GUI only.

**Comment by theotherp** [comment]
It's implemented in v2 which I hope to release in mid december.
