### ISSUE TITLE
umask for log files

### ISSUE THREAD

**Issue by hotio** [theotherp/nzbhydra#659]
I think you are confusing umask with permissions, from looking at the code and how the app behaves, you are setting permissions, yet you call it umask.

see: https://en.wikipedia.org/wiki/Umask

**Comment by theotherp** [comment]
True

**Comment by theotherp** [comment]
I think I understand what the difference is but in the end isn't the effect the same? Could I not just rename the option to chmod and be done with it?

**Comment by hotio** [comment]
Yes renaming to chmod is sufficient... If I were to put an actual umask value in, the effect would be entirely different.
