### ISSUE TITLE
Feature Request: The Ability to Cancel a Search

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#66]
Often times I type something and hit enter only to realize I made a typo or left off an important search term, so I have to wait out the search and then do it again.  It's not a big deal, but it would be nice to be able to just immediately hit a Cancel button and edit my search rather than having to wait.

**Comment by theotherp** [comment]
Yeah, that's not going to happen in quite some time. Because the backend is running singlethreaded I have no way of sending a request until the current one is finished, so the cancel request would only be handled when it's too late. I'll keep it open, who knows.

**Comment by albino1** [comment]
That's kind of what I suspected, since I kind of toyed with just going back to the root URL when the search was in progress, but it didn't like that.  Figured it was worth asking though.

**Comment by theotherp** [comment]
I'll close this for now.
