### ISSUE TITLE
nzbhydra.service will not start with systemd in Ubuntu 16

### ISSUE THREAD

**Issue by LettuceSnob** [theotherp/nzbhydra#663]
I gave nzbhydra its own Ubuntu 16 linux container on proxmox and used [this guide](https://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/) to install the service.

The guide worked as intended and I can start the service manually using `python nzbhydra.py --nobrowser` , but when I enabled it with systemd, the service will not start. `journalctl -xe` provides no errors.

After noticing [this systemd file on github](https://github.com/theotherp/nzbhydra/blob/master/contrib/nzbhydra.service), I tried changing the python path to `/usr/bin/python2.7`, but still no joy.

Any ideas on how to get this service to auto-start with Ubuntu 16?

**Comment by weirdcrap** [comment]
Not super helpful I know as I am not on Ubuntu 16 but with Debian 8 & 9 I had no issues using the basic systemd script from: https://www.htpcguides.com/install-nzbhydra-ubuntu-universal-usenet-searching/ 

```
[Unit]
Description=NZBHydra Daemon
Documentation=https://github.com/theotherp/nzbhydra
After=network.target

[Service]
User=htpcguides
Group=htpcguides
Type=simple
ExecStart=/usr/bin/python /opt/nzbhydra/nzbhydra.py --daemon --nobrowser

KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by LettuceSnob** [comment]
This line ultimately ended up working:

`ExecStart=/usr/bin/python2.7 /opt/nzbhydra/nzbhydra.py --daemon --nobrowser`
