### ISSUE TITLE
[REQ] A few manual search enhancements

### ISSUE THREAD

**Issue by judhat2** [theotherp/nzbhydra#665]
I do a lot of manual searches and have a few suggestions about how to make searching via the web interface a bit better.  I could make an issue for each if needed.

- Adding words to the query search box to filter the results is a great feature. However, if the results are sorted by size, name, etc, then the refined results are lost.  I have to go back to the search box and refresh the results by modifying the query once more.  Is it possible to filter the results again after a new sort has been done?

- I have an idea about a quick way to filter the results.  I got the idea from dognzb's interface.
   <img width="616" alt="snip_20170930221912" src="https://user-images.githubusercontent.com/3536802/31046090-6f1de54e-a62d-11e7-923e-ad7a4680d534.png">
What do you think about adding checkboxes or buttons to the search page here? For example, a click or two can quickly show only 720p web-dl releases or whatever is desired. 
   <img width="812" alt="snip_20170930222238" src="https://user-images.githubusercontent.com/3536802/31046114-e4e576a2-a62d-11e7-90ec-0a704a638f58.png">

- Deselect all button - There is already an invert selection button, as can be seen above.  Can a button be added to deselect all the checkboxes?  When I do a search for a show, I filter the results for season one, send them to nzbget, and forget to deselect them.  When I filter the results for season 2, the season 1 results disappear from the screen but are still selected.  I send them to nzbget, and the checked season 1 results get sent to nzbget again.  I have to re-filter the results and uncheck each box.  A button to deselect everything would be convenient. 

- When I click multiple checkboxes after a manual search, sometimes I select a Jackett torrent indexer by mistake.  When it's sent to nzbget, it obviously fails.  Anyway to not show a checkbox for Jackett indexers? I don't think a checkbox currently has any benefit for a Jackett indexer.

- Show the upload date of the nzb result as a tooltip when the mouse is hovered over the age.  Currently most indexers have this feature on the nzb's details page.

None of these are deal breakers, but implementing one or all of them would be greatly appreciated. 
 If I had the expertise, I would make a pull requests myself. 

Thanks again for this project! I use it almost everyday.

**Comment by theotherp** [comment]
Some good ideas. I'll think about it. I'm close to releasing v2 which might not be what you want but we'll see ;-)

**Comment by judhat2** [comment]
Ok, thanks. Looking forward to V2. What was the reason coding a new version? Any new features or major changes?
