### ISSUE TITLE
Language settings for indexer

### ISSUE THREAD

**Issue by jarlave** [theotherp/nzbhydra#668]
* What do you want to happen?
Indexer specific language settings to search with movie titles in german and not english

* If need be explain the use case.
German indexer doesn't always have an imdb id added to releases, the only way to find this uploads is to use the title, but this doesn't work when the original title is used.

**Comment by RaymondSchnyder** [comment]
Which Indexer do you mean specifically?
Could you specify an URL? 
@jarlave

**Comment by theotherp** [comment]
Will not be implemented, sorry.
