### ISSUE TITLE
Torrent link refers localhost instead of external url

### ISSUE THREAD

**Issue by manderss99** [theotherp/nzbhydra#670]
I have a mixture of nzb search engines and torrent sites setup (through jackett).
When I select a nzb search engine and click on resulting nzb link everything works fine.
When I select a torrent site and click on resulting torrent link it fails because the link refers localhost instead of external url.

**Comment by theotherp** [comment]
The link should refer to your hydra instance first (e.g. `http://127.0.0.1:5075/getnzb?searchresultid=0ba48e868a37412d3334eaf771e564bb40313768&internal=true`) and then Hydra should redirect to your Jackett instance (e.g. `http://127.0.0.1:9117/dl/limetorrents/abcde?path=12345&file=Some music.torrent`) and that should lead to a download.

Try manually searching via your jackett instance. The download links will also refer to a local URL. 

So it looks like this is more a jackett issue.

**Comment by manderss99** [comment]
When I access Jackett by a remote browser and do a manual search, downloading the torrent works fine.
So I do not quite understand what the problem with Jackett is.

When I access Hydra by a remote browser and click on download torrent it fails bc it refers to localhost instead of the external dns name of the server.

http://localhost:9117/dl/torrentleech/?jackett_apikey=

fails, if I change the locahost to my hostname it works.

**Comment by theotherp** [comment]
Enter the external URL to Jackett into Hydra. If you reach Jackett via `http://mydomain.com/jackett` then enter e.g. `http://mydomain.com/jackett/torznab/limetorrents` as indexer URL.

I can only use the URL that is generated by Jackett and that uses the URL you call it with. If you call Jackett with your external URL / IP then it will automatically generate externally valid URLs.

That is not my fault.

**Comment by manderss99** [comment]
got it working but I had to recreate the indexers again, simply changing the url and restarting did not work.
Anyway, thanks

**Comment by theotherp** [comment]
Great. I wasn't aware of this issue. I'll add a note somewhere.
