### ISSUE TITLE
DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by PvaI** [theotherp/nzbhydra#671]
NZBhydra will only perform a couple of searches before throwing this error. Other times it crashes or hangs, without any log entry, I've marked the place in the log where this happens.

Searched for this error and this error in combination with nzbhydra, sqllite and osx. Common SQL solutions are to verify / export the DB, but I've just started nzbhydra, there's nothing in there I'd like to keep. So deleting the DB works as well, but deleting the DB after every couple of searches isn't a workable solution.
Another SQLlite issue mentioned the disk getting clobbered by SQLlite and advised moving the DB to a faster disk. Initially I had the DB on an M.2 SSD, should've been fast enough. But I've now moved it to a HW-RAID volume, this enables me to perform a couple of searches before the error is trown.

Another error I've been seeing is 'OperationalError: cannot commit transaction - SQL statements in progress'. I've tried to avoid this one by starting nzbhydra afresh and waiting a couple of minutes to hours, but it keeps getting thrown regurlarly. I've also tried to run nzbhydra single threaded vs multi-threaded.

A python crash report included in the log-archive.

OS : Darwin Kernel Version 16.7.0 / MacOS 10.12.6, nzbhydra : 0.2.227

Mfg, 
Pval
[nzbhydra-debuginfo-2017-10-09-14-31.zip](https://github.com/theotherp/nzbhydra/files/1368551/nzbhydra-debuginfo-2017-10-09-14-31.zip)

**Comment by theotherp** [comment]
Unfortunately I don't have a solution for this now. I'm hoping to release a new major version soonish which should solve this. Sorry, I don't have better news for now.

**Comment by Alrescha-git** [comment]
You did not mention python, so I will point out that NZBHydra is simply not compatible with the shipping version of Python in macOS (and has not been for quite a while now).  If you want to use the latest NZBHydra release, you need MacPorts or Homebrew to install the latest 2.7.x python and run with /path/yourpython27 nzbhydra.py

A.

**Comment by PvaI** [comment]
This, installed 2.7.14 via Homebrew, no more issues. 
Might want to add this to the readme, Python included with Sierra (10.12.6) is 2.7.10, meeting the requirement of 2.7.9+.

**Comment by theotherp** [comment]
Nice! Thanks for the hint, @Alrescha-git
