### ISSUE TITLE
Downloads added by Headphones doesn't start.

### ISSUE THREAD

**Issue by meganugen** [theotherp/nzbhydra#672]
When I'm adding albums for download from Headphones the download is added to the "Download history" tab in NZB Hydra. Problem is that the download isn't sent to SABnzbd by NZB Hydra. 

I can manually click the "Send to SABnzbd" button next to the album name in NBZ Hydra and the download starts right away in SABnzbd. 

So why doesn't NZB Hydra start the download automatically when added by Headphones?

Thanks for any help!

**Comment by theotherp** [comment]
That's an issue with Headphones, not Hydra. If the download is listed in Hydra's history then everything is fine on its part.

**Comment by meganugen** [comment]
Ok. Seems logical. I know this is not your thing to comment but I ran debug
in Headphones and does this tell you anything? This happens when I ask
Headphones to download an album from NZB Hydra.

2017-10-11 22:26:09 DEBUG Server responded with message: 403 Forbidden
nginx
2017-10-11 22:26:09 ERROR Request raise HTTP error with status code 403
(local client error).
2017-10-11 22:26:08 DEBUG Requesting URL via GET method:
http://localhost:5075/getnzb?apikey=ab00y7qye6u84lx4eqhwd0yh1wp423&searchresultid=2960db402ac334da6d388c76c319e546bd4e2665
2017-10-11 22:26:08


tors 12 okt. 2017 kl. 09:01 skrev theotherp <notifications@github.com>:

**Comment by theotherp** [comment]
That would mean that the download of the NZB from Hydra didn't actually work and in that case it shouldn't be logged. The excerpt is a bit short, hard to say if these three messages actually belong to each other.

The error message is caused by nginx, meaning that the call to `http://localhost:5075` was prevented by that, not by Hydra. No idea why that would happen. Try to change the URL to Hydra in Headphones to `http://127.0.0.1:5075`. It shouldn't be a difference, but who knows.

**Comment by meganugen** [comment]
​Thanks for the answer. I changed the ​URL in Headphones to Hydra to:
http://127.0.0.1:5075 but as you said there's no difference. It's adding
the download in Download History in Hydra. There's a question mark in the
"successful" table. But as before SABnzbd hasn't start downloading but
clicking "send to SABnzbd" starts the download.

As a side note why I started to use NZB Hydra is because NZB.su has banned
Headphones to use their API because of an old issue when Headphones was
abusing the API request. NZB.su calls Headphones an "API hammer". But
Headphones author says this issue has been resolved years ago but NZB.su is
still banning Headphones from using their API to this day.

So I thought I could use NZB Hydra as a workaround to access NZB.su from
Headphones. Does Hydra just pass through the client information to NZB.su
so they still know that it is Headphones doing the downloads? And that can
be the problem? Can I in that case change any settings to "hide" Headphones
behind Hydra? :)

Once again, I'm happy for all the info I can grab to figure out the issue.
:)



2017-10-12 11:19 GMT+02:00 theotherp <notifications@github.com>:

**Comment by theotherp** [comment]
It's not visible to the indexer that it's Headphones requesting the search.

You'll need to contact the headphones developer.

**Comment by meganugen** [comment]
I've changed the indexer in Hydra to another one and done the exact same
search and it starts downloading. So it still seems that NZB.su still knows
that it is Headphones doing the download request. It works with
i.e. omgwtfnzbs as an indexer.

If there's anything you can do to work around that I'd be happy.

2017-10-12 13:01 GMT+02:00 theotherp <notifications@github.com>:

**Comment by theotherp** [comment]
No, that only means that HP isn't able to send the NZB from Hydra to sabnzbd. I don't know why.

**Comment by meganugen** [comment]
Ok. And that can differ between two indexer? One works and the other one
doesn't with the same NZB? I mean that's strange. Is there any debug log or
anything I can send to the HP developer to have a look at from Hydra?


tors 12 okt. 2017 kl. 18:13 skrev theotherp <notifications@github.com>:
