### ISSUE TITLE
SSL Cert Verification Failures

### ISSUE THREAD

**Issue by cmacrae** [theotherp/nzbhydra#675]
Hey @theotherp 👋 

Thanks so much for nzbhydra ❤️ 

So, I’m experiencing a rather annoying issue with SSL certificate verification.
The indexer I’m trying to use is using a Let’s Encrypt cert issued from their X3 intermediate cert:  https://letsencrypt.org/certificates/

I’ve installed the cert on my server into my trusted certificates. I’m able to establish secure, verified SSL connections with the indexer using cURL & the OpenSSL CLI.

So, the operating system obviously trusts it.

However, when nzvhydra is attempting to establish connectivity over HTTPS, it fails with the following:
```
2017-11-06 22:10:08,602 - INFO - search_module - Thread-13 - REDACTED: Starting search
2017-11-06 22:10:08,907 - ERROR - search_module - Thread-13 - REDACTED: Error while connecting to URL https://REDACTED.org/api?q=REDACTED: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```
It seems to be doing its own SSL verification.
How can I trust the certificate so I can use this indexer?

As you can see above, I’ve redacted the indexer’s name.
If this is something you’d like me to share, publicly or privately, please let me know.

Thanks in advance for any help on this.

**Comment by theotherp** [comment]
Hey,

there's only one indexer I know of that doesn't allow to be mentioned publicly. Feel free to post the full URL of your indexer so I can test the connection.

I know of multiple indexers using Let's Encrypt which can usually be reached from Hydra. 

I use the requests library. You can read about its CA handling here: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates 

I *think* this is the appropriate file https://github.com/theotherp/nzbhydra/blob/master/libs/requests/cacert.pem You could try adding your indexer's cert there. I know enough about SSL to get it done but not enough to describe it to you but reading your post it seems you know a bit yourself. Have a try ;-)

**Comment by cmacrae** [comment]
Cheers for the quick response @theotherp 👍 
Cool, so it's AniZB: https://anizb.org  

Ah I see! I didn't expect it to be using a static file with a list of trusted certs.  
I figured SSL verification would be left to the OS.  

I'd certainly be happy to try adding the cert to that file - however I'm at work at the moment, so won't be able to test until later.

**Comment by cmacrae** [comment]
Alright, looks like adding the LE X3 intermediate cert to `libs/requests/cacert.pem` works! 🤙   

I just appended it to the end of the file.  
How can we move forward with a fix for this? Obviously kinda sucks to have this implemented manually.  
I was going to say: I can submit a PR for it, but I'm guessing you're either pulling this in from an external module/lib, or you have an automated process to generate it.

**Comment by theotherp** [comment]
No, adapting that file would work fine. To be honest I have no idea where that file is from...

**Comment by cmacrae** [comment]
Haha 😆 Alright, I'll drop a PR in shortly

**Comment by Fidelix** [comment]
Hi @cmacrae, did you end up offering a PR for this?

Thanks,

**Comment by cmacrae** [comment]
@Fidelix @theotherp: I haven’t yet! Was in the middle of some work when I last commented. I should get some time to put a PR in today. Thanks for the reminder 👍🏻

**Comment by theotherp** [comment]
I would've done this myself but unfortunately I wasn't able to get it to work...

**Comment by theotherp** [comment]
Issue fixed by anizb.

**Comment by cmacrae** [comment]
@theotherp Oh? Great - well that saves me the 2 minutes I should have taken to put that little PR in then! 😉
