### ISSUE TITLE
HTTPS issue (links to http)

### ISSUE THREAD

**Issue by Miicker** [theotherp/nzbhydra#676]
I am running Hydra on my XPenology (Synology emulation) custom build NAS. I am running it in Docker and have the following problem. I am running Hydra in HTTP with an SSL certificate from lets encrypt.
When i go to https://hydra.MYDOMAIN.com/
I get redirected to:
http://hydra.MYDOMAIN.nl/login

Which gives me a 404 error (page not found). When I replace http:// with https:// I can login.  When I fill in my username and password I return to the same page (https://hydra.MYDOMAIN.nl/login) and I can log in again. So I don't get redirected to the hydra home page.
After I pressed log in one time (when I filled in the username and password) and Hydra asks me to log in again, I can simply go to https://hydra.MYDOMAIN.com/ and it works. But after the cookie expires, I have to do the same ritual again.

How do I fix this problem?

Thanks in advance!

**Comment by theotherp** [comment]
I currently don't have time to take a closer look but would basic Auth be
an option?

**Comment by Miicker** [comment]
@theotherp it's an option.. But definitely not my preferred option if I'm being honest. I use Hydra also within Organizr (don't know if you know it) but if I use basic auth it looks pretty bad.

**Comment by theotherp** [comment]
I can't reproduce that behavior. Running SSL directly or via nginx in both cases I get redirected to the correct page.

**Comment by Miicker** [comment]
@theotherp the option "Use SSL" is turned off in Hydra. The SSL certificate is managed trough my NAS. It works for SickRage, NZBGet, Radarr, HeadPhones and LazyLibrarian.
I am using a SSL connection trough a reversed proxy. So all incoming traffic from https://hydra.MYDOMAIN.com is internally redirected to http://localhost:*what ever port Hydra uses*

**Comment by theotherp** [comment]
It might be caused by some setting in your NAS. No idea how the reverse proxy there works. As I said I can't reproduce it and don't know how to solve your problem, sorry.

**Comment by Miicker** [comment]
@theotherp I looked into the problem further. I've reinstalled Hydra but after installation and activating the reverse proxy and the authentication form I run into the same problem. When I activate basic authentication the problem does not occur.

Is there any way to look into the code/html files myself? I guess it has something to do with redirecting. Where are these folders located when I installed Hydra on Synology using Docker?
In the config folder I only find a nzbhydra.db file and some of these files:
nzbhydra.db-shm
nzbhydra.db-wal
nzbhydra.log

And of course: settings.cfg, but I can't find any of these settings there.

**Comment by theotherp** [comment]
You can try this:

In the file nzbhydra\web.py change the line 573 from this:
`return redirect(base_url + "login")`
to this:
`return redirect(base_url + "/login")`

I tried to reproduce your problem but it worked fine in my case.

When you try to access any page which you're not authorized to the line above is called. You're redirected to the URL "/login". That should keep you in the same scheme (HTTPS) and just change the path.

I tested it with nginx with HTTPS and a subdomain.  For reference, these are the parameters I used:
```
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass http://127.0.0.1:5075/nzbhydra/;
proxy_set_header X-Real-IP $remote_addr;
```

The line I mentioned above is what does the redirecting. You could also check the network tab in the debug tools (F12 button) in your browser to see where you're redirected to.

**Comment by Miicker** [comment]
@theotherp where do I find the file web.py, I've installed Hydra through Docker, so I can only access certain files. Maybe I can access them through SCP, but I don't know where to look.

**Comment by theotherp** [comment]
I have no idea. I guess it would be easier to run a new instance from source using your database and settings files.

**Comment by Miicker** [comment]
@theotherp the point is that when I create a new instance from linuxserver.io (also tried another one, same error) that the error also occurs, right away when I enable the authentication form.

**Comment by theotherp** [comment]
No, don't use docker. Download https://github.com/theotherp/nzbhydra/archive/master.zip, extract it somewhere and run it using python.

**Comment by Miicker** [comment]
@theotherp I don't think that is possible on a Synology, at least I don't know how..

**Comment by theotherp** [comment]
In that case I don't know how to help you, sorry.

**Comment by theotherp** [comment]
I could add an option how long the remember-me cookie lasts. If it never expires then you wouldn't need ever login again.

**Comment by Miicker** [comment]
That would be a nice workaround :)

**Comment by theotherp** [comment]
Et voilà.

**Comment by Miicker** [comment]
So I finally found a permanent solution for this problem! I was able to edit the reverse proxy config file and edited the reverse proxy for Hydra:

`server {
    listen 80;
    listen [::]:80;

    server_name domain.com;

    location / {
        proxy_set_header        Host                $http_host;
        proxy_set_header        X-Real-IP           $remote_addr;
        proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto   $scheme;
        proxy_intercept_errors  on;
        proxy_http_version      1.1;

	return         301 https://$server_name$request_uri;
    }
	
    location ^~ /.well-known/acme-challenge {
        root /var/lib/letsencrypt;
        default_type text/plain;
    }
}`

Maybe this is helpful for others.
