### ISSUE TITLE
Logs keeps requested after leaving System->Log

### ISSUE THREAD

**Issue by milefork** [theotherp/nzbhydra#677]
If you watch the logs under System->Log and check "Update every five seconds and scroll to end", then hit the Update button.
This works fine but when you go to another page like Search or someting and you look at the Request Tab of your Developer Tools you will see that getlogs is still beeing requested every 5 seconds.

I dont think this is intended.

Greetings

**Comment by theotherp** [comment]
No it's not. I consider it a minor inconvenience, just reload the page. I'll fix it some time.
