### ISSUE TITLE
NZBhydra does not proxy HTTP codes

### ISSUE THREAD

**Issue by enilfodne** [theotherp/nzbhydra#678]
I've noticed that when downloading in proxy mode and an error occurs, `NZBhydra` does not set the correct HTTP code, but its rather using the generic `500 Internal Server Error`. Some errors are due to rate-limiting or missing files (`404`) and doing so it may help the programs (fetching the file), to know that the content may not even be there.

For example some indexers are using both:

- `429 No Reason Phrase`
- `503 Service Temporarily Unavailable`

to tell their customers that they've hit a limit.

The logs are indicating the following:

```
2017-XX-XX XX:XX:XX,XXX- ERROR - api - MainThread - Error while trying to download NZB XXX from Drunken Slug
2017-XX-XX XX:XX:XX,XXX- ERROR - api - MainThread - Error while connecting to URL https://XXXX: 429 Client Error: Too Many Requests for url: https://XXX
```

As im not sure this is an actual issue, feel free to close/ignore this if not applicable.

**Comment by theotherp** [comment]
That would require some major changes in the codebase. I'll see what I can do.
