### ISSUE TITLE
Set indexer to only be scanned during a set period of time

### ISSUE THREAD

**Issue by thesmj** [theotherp/nzbhydra#680]
It would be nice if we could configure certain indexers to only be updated during a specific period of time. For example, I have a tracker that only allows 100 API calls. The tracker is only useful to me between the hours of 1 PM and 12 AM. Making API calls to it outside of these hours would be a waste.

**Comment by theotherp** [comment]
I'll think about it, that's extremely specific. Are all these semi-free indexers really worth it? Either they're good enough to pay for or just don't use them. I don't understand all this miserliness when it comes to API hits.

**Comment by thesmj** [comment]
I'm not saying I want or expect that specific range to be the only one available. I was only using it as an example.

 I can tell you it would be a nice feature if it isn't too much trouble to implement. I don't know Python, so I can't tell how hard it would be to pull off. I also don't particularly know the worth of a semi-free indexer if I'm always using up the API hits before the results I need tend to be posted.

**Comment by theotherp** [comment]
It's not much work, it would just make the configuration even more complicated. Most people already don't understand what's going on there.

If I ever manage to get a "Show advanced options" feature working I might add this.

**Comment by theotherp** [comment]
Feature is implemented in v2 which will be released soon-ish.
