### ISSUE TITLE
Unable to access system tab

### ISSUE THREAD

**Issue by tehniemer** [theotherp/nzbhydra#681]
* What do you expect to happen? 
Try to access system tab by clicking the link in the WebUI, or typing in the address http://192.168.29.2:5075/system

* What does happen? 
The link does not exist, and typing in the address shows a empty page below the NZBhydra logo.

* Have you searched for this problem? You don't have to answer, just make sure.
yes

* Can the problem be reproduced? How?
Not sure, this started after uninstalling and reinstalling a few times.

**Set your log file level to debug, repeat the steps that cause the problem and post the debug info which can be retrieved in the [System / Bugreport section](http://127.0.0.1:5075/nzbhydra/system/bugreport). If other tools are involved post their logs as well.**

I am unable to access the bug report. This issue persists after many reinstallation attempts. 
QNAP TS-251+ and 0.2.140 and 0.2.167 versions of NZBHydra.

**Comment by theotherp** [comment]
Please check your browser's console for errors (press F12).

**Comment by tehniemer** [comment]
angular.js:13550 Error: Could not resolve 'root.config.main' from state 'root'
    at Object.transitionTo (http://192.168.29.2:5075/static/js/alllibs.js:59522:17)
    at Object.go (http://192.168.29.2:5075/static/js/alllibs.js:59450:21)
    at http://192.168.29.2:5075/static/js/alllibs.js:60563:20
    at http://192.168.29.2:5075/static/js/alllibs.js:28368:31
    at completeOutstandingRequest (http://192.168.29.2:5075/static/js/alllibs.js:15080:10)
    at http://192.168.29.2:5075/static/js/alllibs.js:15356:7 undefined
(anonymous) @ angular.js:13550
(anonymous) @ angular.js:10225
(anonymous) @ angular-block-ui.js:29
(anonymous) @ nzbhydra.js:616
(anonymous) @ angular.js:19160
completeOutstandingRequest @ angular.js:5869
(anonymous) @ angular.js:6145
setTimeout (async)
Browser.self.defer @ angular.js:6143
timeout @ angular.js:19155
(anonymous) @ angular-ui-router.js:4180
dispatch @ jquery.js:4435
elemData.handle @ jquery.js:4121
nzbhydra.js:618 Error: Could not resolve 'root.config.main' from state 'root'
    at Object.transitionTo (angular-ui-router.js:3140)
    at Object.go (angular-ui-router.js:3068)
    at angular-ui-router.js:4181
    at angular.js:19157
    at completeOutstandingRequest (angular.js:5869)
    at angular.js:6145

**Comment by theotherp** [comment]
Have you set a URL base in the settings.cfg?

**Comment by theotherp** [comment]
By the way, version 0.2.167 is more than a year old. Is there a reason why you don't / can't use the newest version?

**Comment by tehniemer** [comment]
I did set a base URL, and come to think of it, I believe that's when the issues started. I set the URL to /nzbhydra/ then I had issues with the webUI loading so I tried reinstalling. 

I'm using the older version because that's the latest version that's been compiled to a .Qpkg that I can easily install on my QNAP NAS. Since I can't get to the system tab I cannot upgrade to the latest version easily. I'm unsure how to manually install the latest version on my system.

**Comment by theotherp** [comment]
When you set a base URL you need to use it: http://192.168.29.2:5075/nzbhydra/system

**Comment by theotherp** [comment]
I can't support a version that old, sorry. You'll need to ask the package maintainer to update the package.

**Comment by tehniemer** [comment]
Using your link I was able to get to the system settings, I could have sworn I tried the base URL, but maybe I left off the trailing "/" all seems well now and I've updated to the latest version. Thanks for your help.
