### ISSUE TITLE
Cannot update ERROR - update - No git specified, can't use git commands

### ISSUE THREAD

**Issue by Menz01** [theotherp/nzbhydra#683]
I am running NZBHydra on a windows 10 box. I have it set to run as a service using NSSM. I have been running like this for awhile and never an issue. but now I can no longer update my client. I get the error "ERROR - update - No git specified, can't use git commands" my git is in my windows path statement. I have tried with the GIT executable as blank, with "C:\Program Files\Git\cmd", and "C:\Program Files\Git\" and none worked.

what can I do to update?

thank in advance

**Comment by theotherp** [comment]
Easiest workaround would be to delete the .git folder. That way the update is done by downloading a ZIP and extracting it.

**Comment by Menz01** [comment]
thank you. I am really wondering why the update through the console did not work though
