### ISSUE TITLE
Frontend assets aren't optimized

### ISSUE THREAD

**Issue by Chiron1991** [theotherp/nzbhydra#685]
I was wondering about the loading time of the web interface being so high. A quick look at the dev console and your gulpfile showed that there is no minification of JS + CSS and optimization of images. That means unnecessary loading time for people on low-bandwidth connections (and minor parsing performance too).

If you're willing I might file a pull request in the next few days. I'm pretty familiar with gulp.

Edit: You said you did minification for JS [here](https://github.com/theotherp/nzbhydra/issues/114#issuecomment-178116128). You also import gulp-uglify in your gulpfile but never use it. I think you had a little merge issue somewhere in time. :)

**Comment by theotherp** [comment]
Yeah, that's just me being lazy. I commented out the minification and
didn't re-enable it... Will fix it some time.

**Comment by theotherp** [comment]
Should be fixed.

**Comment by Chiron1991** [comment]
It is. Thank you very much. Performs much better on mobile devices now.
