### ISSUE TITLE
Feature Request: Ability to schedule a time frame for when an indexer can be used

### ISSUE THREAD

**Issue by heymoe** [theotherp/nzbhydra#688]
## How to request a new feature
* What do you want to happen?

The ability to define a schedule when an indexer can be used. For example, Internal / API searches will only get sent to indexer XYZ between 9am-12pm Mon-Friday. All other times no searches are sent to it.

* If not clear, why do you want it?

Prevent scheduled mass queries from hitting a particular index. Work around peek time issues with an indexer. etc..

* Do you think it's something only you need or something that might be popular?

Something I know I could use. Could be popular with others if given the option / flexibility.

* If need be explain the use case.

I think the "What do you want to happen" explains the use case. If not let me know.

**Comment by theotherp** [comment]
IIRC you proposed this on reddit, right? Still not sure how I feel about
it. But I'll leave this one open, who knows.

Am 08.12.2017 05:24 schrieb "heymoe" <notifications@github.com>:

**Comment by heymoe** [comment]
I don't think I post this request on reddit. This really just came up as a "this would be a nice feature to have" for my situation maybe within the last few days.

Thanks for taking it into consideration. Hopefully others that think it might me a nice feature will post as such here too.

**Comment by theotherp** [comment]
Hm well, there seem to be at least two people who want this. That's more
than for some other features I've implemented...

Am 08.12.2017 16:01 schrieb "heymoe" <notifications@github.com>:

**Comment by theotherp** [comment]
Feature is implemented in v2 which will be released soon-ish.

**Comment by theotherp** [comment]
Also a duplicate, see #680
