### ISSUE TITLE
"An error occured : 500:   hour must be in 0..23" when performing a manual search

### ISSUE THREAD

**Issue by the1poet** [theotherp/nzbhydra#690]
I am running NZBHydra from an UNRaid docker made by Linuxserver.
Recently, whenever I log into NZBHydra and perform a search, I get the following error message:
> An error occured :
> 500: 
> 
> hour must be in 0..23

It doesn't matter what the search is. Always the same error.

See the log file: [logfile.txt](https://github.com/theotherp/nzbhydra/files/1573613/logfile.txt)

**Comment by theotherp** [comment]
Check your hit limit reset times. They must be between 0 and 23.

Am 20.12.2017 00:34 schrieb "the1poet" <notifications@github.com>:

**Comment by theotherp** [comment]
New version prevents this from happening.
