### ISSUE TITLE
Hydra and Headphones/feedparser

### ISSUE THREAD

**Issue by phit42** [theotherp/nzbhydra#692]
My HZBHydra installation on a Synology NAS seems to work fine, however I was never getting results in Headphones. With a little debugging I found that Headphones uses feedparser.py in the version "5.0.1" which throws a [bozo](https://pythonhosted.org/feedparser/bozo.html#advanced-bozo) for every single result from Hydra with the following bozo error message: 

> :14:2: mismatched tag

It seems regardless if entries were found or not. 
The URL params can be seen from the log file excerpt:

> 2018-01-01 19:40:26 | INFO | No more results found for: Kelly Clarkson - Meaning of Life
-- | -- | --
> 2018-01-01 19:40:26 | INFO | No results found from http://localhost:5075/ for Kelly Clarkson Meaning of Life
> 2018-01-01 19:40:26 | DEBUG | Parsing error: :14:2: mismatched tag
> 2018-01-01 19:40:25 | DEBUG | Parse content...
> 2018-01-01 19:40:25 | DEBUG | Response statuscode: 200
> 2018-01-01 19:40:25 | DEBUG | Requesting URL via GET method: http://localhost:5075//api? with kwargs: {'headers': {'User-Agent': 'Headphones/-master (Linux 3.10.102)'}, 'params': {'q': 'Kelly Clarkson Meaning of Life', 'maxage': 900, 'apikey': u'xxxxxxxxxxxxxxxxxxxx', 't': 'search', 'cat': '3010'}, 'verify': True}
> 2018-01-01 19:40:25 | INFO | Parsing results from http://localhost:5075/ using search term: Kelly Clarkson Meaning of Life

I can manually query NZBHydra and get a number of hits as you can see from the example XML attached using "http://diskstation:5075/api?t=search&q=Kelly%20Clarkson%20Meaning%20of%20Life&maxage=900&cat=3010&apikey=xxxxx".

Any ideas?

[api.zip](https://github.com/theotherp/nzbhydra/files/1596478/api.zip)

**Comment by theotherp** [comment]
I guess headphones works with any of rg and indexers called directly?

I'll need to download and debug headphones or the parser library to find
out what's causing this.

Am 02.01.2018 00:05 schrieb "phit42" <notifications@github.com>:

**Comment by theotherp** [comment]
Well, I installed Headphones but I can't get it to actually search Hydra (or any other Indexer).

I parsed a normal response from Hydra using feedparser and got no bozo exception. I think you should contant the headphones dev and ask him if he has an idea what tag is causing the issue or if he can implement a better error message that says which tag causes the problem.

**Comment by theotherp** [comment]
I can't reproduce that error. I'm unable to get Headphones to actually search Hydra (or any other indexer).

Using feedparser to parse a regular Hydra output does not result in a bozo exception. You should contact the headphones dev, he might have an idea what causes the issue and should probably implement a better exception that says which tag causes the issue. I don't know of any other programs which have an issue with Hydra's output.

**Comment by phit42** [comment]
Thanx for testing. Yes other indexers (eg usenetcrawler) work fine. Your test mit HP might be a verify_ssl_cert topic!?
Does your regular Hydra output that you used to test feedparser look any different than mine? Only obvious thing that I recognized was that UC added an additional "xmlns:atom="http://www.w3.org/2005/Atom" into its rss tag.

**Comment by theotherp** [comment]
Your output was already processed by your browser (added comment, formatted ampersands, etc). Please call the page again, select "Show source code", remove the API keys and post that.

HP doesn't show any error when searching. It says it searches and then it does nothing. I'm running it against my local dev hydra instance without SSL or anything.

**Comment by phit42** [comment]
Hope this output is better.
[api.zip](https://github.com/theotherp/nzbhydra/files/1597983/api.zip)

**Comment by phit42** [comment]
When you toggle debug in the log view, it should show at least the Requesting URL via GET method part (without the params unfortunately), the rest was my adding. And it needs the "custom newznab providers" checked and the link to local enabled of course.

**Comment by theotherp** [comment]
That XML can be parsed by feedparser without bozo exception.

This is what my config looks like: https://i.imgur.com/Kll3RRY.png

and this is the log output:

```
02-Jan-2018 17:16:36 - INFO :: CP Server Thread-2 : Marking album: c0a955eb-da05-4967-8872-73d6360de6e8 as wanted...
02-Jan-2018 17:16:36 - INFO :: CP Server Thread-2 : Searching for wanted albums
02-Jan-2018 17:16:36 - INFO :: CP Server Thread-2 : Searching for "Lonely the Brave - Things Will Matter" since it was marked as wanted
02-Jan-2018 17:16:36 - INFO :: CP Server Thread-2 : No appropriate matches found for Lonely the Brave - Things Will Matter
```

**Comment by theotherp** [comment]
Nvm, I didn't configure a downloader. I hate it when programs just don't do stuff and not log it...

Anyway, it works fine. I don't get any errors. I could only debug the problem further with access to nzb.cat to get the exact same XML.

In any case I think you should contact the HP dev, I don't know how to help, sorry.

**Comment by phit42** [comment]
Damn, this is a completely stupid error. With a lot of debugging I figured out that Hydra does not return an XML at all, but rather a HTML (see attached zip).
[Taylor Swift reputation.zip](https://github.com/theotherp/nzbhydra/files/1598359/Taylor.Swift.reputation.zip)

Then I wondered why and your screenshot gave me the key: there is a trailing slash at the end of my hostname:port combination for NZBHydra, so the built url is wrong. Apparently headphones does not check for that. Strangely enough, my usenet-crawler config does work with the trailing slash. Go figure.

Anyway, thank you very much for your help, it did help a lot!

**Comment by theotherp** [comment]
Huh. Well, at least you found it ;-)
