### ISSUE TITLE
Sonarr receives 500 error from nzbhydra maybe related to the last update

### ISSUE THREAD

**Issue by mitchelp** [theotherp/nzbhydra#694]
Sonarr keeps on dropping my nzbhydra (temp disable it) and I couldn't find out why. Cause the manual test just works fine. So I started looking in the log files:

> HTTP Error - Res: [GET] http://localhost:5075/nzbhydra/getnzb?apikey=(removed)&searchresultid=7c24fb37ce7fdbd9df06bcee4c74bf812459a293: 500.InternalServerError
> Instance matching query does not exist:
> SQL: SELECT "t1"."id", "t1"."indexer_id", "t1"."firstFound", "t1"."title", "t1"."guid", "t1"."link", "t1"."details" FROM "searchresult" AS t1 WHERE ("t1"."id" = ?)
> PARAMS: [u'7c24fb37ce7fdbd9df06bcee4c74bf812459a293']

This happens more often and when I check it manual it give me the same error.
Is there just something broken in my hydra or is it affecting more people.

Trying to resolve this issue, I removed my nzbhydra .db* files. and empty'ed my flask_session dir.
Already thanks for the help 👍

**Comment by theotherp** [comment]
Post the debug infos.

**Comment by theotherp** [comment]
But usually this only happens when a program (in this case Sonarr) tries to download an NZB which it found more than 7 days ago. Search results are deleted from the database after that period.

If you deleted your .db file old references to search results do not work anymore. But that would only explain why it could fail now, not previously.

I haven't had any issues in sonarr so it's probably not a general issue.

**Comment by mitchelp** [comment]
Well there was one activity that could be related to it, I have removed it now.. Let's see if it fixed the issue. I will update or close this issuetomorrow. Thanks for the help.

**Comment by mitchelp** [comment]
@theotherp thanks for putting me on the right track. It was due sonarr trying to pick a NZB from nzbhydra that wasn't available in the history anymore. So the response of nzbhydra was a 500. Maybe that it can be changed to something that sonarr understands as unavailable instead of putting the indexer into a unavailable state.

**Comment by theotherp** [comment]
Yeah, good idea.
