### ISSUE TITLE
Can't add Torznab servers to Radarr

### ISSUE THREAD

**Issue by PearsonFlyer** [theotherp/nzbhydra#698]
I was able to add /torznab to Sonarr, and it works great.  When adding the exact same settings to Radarr, the "test" fails and it won't add.

Everything in Hydra looks fine, it's getting results from each tracker, etc. during the test.

But in Radarr, the log shows:

>  An error occurred while processing feed item from http://127.0.0.1:5076/torznab/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100: Feed contains application/x-nzb instead of application/x-bittorrent

> NzbDrone.Core.Indexers.Exceptions.UnsupportedFeedException: Feed contains application/x-nzb instead of application/x-bittorrent
>   at NzbDrone.Core.Indexers.Torznab.TorznabRssParser.PostProcess(XElement item, ReleaseInfo releaseInfo) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Torznab\TorznabRssParser.cs:line 60
>   at NzbDrone.Core.Indexers.RssParser.ProcessItem(XElement item) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:line 129
>   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:line 58

I have confirmed the setup is accurate, and should be working properly. It looks like the mime-type is not being changed properly?

**Comment by theotherp** [comment]
Looks like it yes.

Am 10.01.2018 00:03 schrieb "PearsonFlyer" <notifications@github.com>:

**Comment by theotherp** [comment]
Wrong project. See https://github.com/theotherp/nzbhydra2/issues/50
