### ISSUE TITLE
Error while generating stats - error 500

### ISSUE THREAD

**Issue by chqshaitan** [theotherp/nzbhydra#702]
Hi Bud,

I attempted to generate stats and received a 500 error, the logs are attached. Excellent work, I love the software :)

Thanks

Ray

[nzbhydra-debuginfo-2018-01-19-21-21.zip](https://github.com/theotherp/nzbhydra/files/1647940/nzbhydra-debuginfo-2018-01-19-21-21.zip)

**Comment by theotherp** [comment]
This is a known problem for which unfortunately no fix exists.

You can migrate to [NZBHydra 2](https://github.com/theotherp/nzbhydra2/) which isn't as mature as v1 yet but doesn't have that problem.
