### ISSUE TITLE
NZB Hydra can't access SABnzbd from within Docker

### ISSUE THREAD

**Issue by spacecakes** [theotherp/nzbhydra#703]
I've set up NZBHydra to run on a Synology NAS from within Docker and this is also how SABnzbd runs.  For some reason NZBHydra refuses to connect, logging this:

```2018-02-01 11:49:04,988 - ERROR - downloader - Thread-80 - Error while trying to connect to sabnzbd: HTTPConnectionPool(host='10.0.1.50', port=7890): Max retries exceeded with url: /api?apikey=<APIKEY>&output=json&mode=queue (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe7854ae690>, 'Connection to 10.0.1.50 timed out. (connect timeout=15)'))```

Both containers run on Docker bridge network on the server using`10.0.1.50` and both have their ports mapped. SABnzbd has to have `8080` mapped to `7890` due to port conflicts. I am able to access the SABnzbd interface and  `http://10.0.1.50:7890/api?apikey=YOURAPIKEY&output=json&mode=qstatus` works as well within the browser.

NZBHydra v0.2.232
SABnzbd v1.1.1RC2 [01d668a]

I was thinking the port re-mapping could the issue, but disabling UniFi Controller (which too needs `8080`) and resetting SABnzbd's default port did not help. CouchPotato and Sonarr (also Dockerized) has no issues accessing SABnzbd with the current setup.

Any ideas?

**Comment by theotherp** [comment]
No ideas, sorry.

**Comment by spacecakes** [comment]
This seems to have to do with the bridge network not allowing access from containers. It works when they're using the Docker host network or by linking the containers (but then the IP changes every time). Good to know. :-)
