### ISSUE TITLE
settings.cfg is cleared sometimes, download from Medusa not working anymore

### ISSUE THREAD

**Issue by Miicker** [theotherp/nzbhydra#704]
Hi everyone,

Two or three days ago, out of the blue, Hydra stopped working. I use Hydra with Medusa and NZBGet. When I wanted to check what was wrong, I could not enter the interface of Hydra, I got this error:
502 Bad Gateway

So I took a look at the config file, and I saw that it was completely empty. I've reinstalled Hydra, restored the settings from a previous backup and had the same problem again. So than I reinstalled Hydra, manually changed all settings, set up new search providers, etc, it seemed to work, I could send downloads when searchin in Hydra to NZBGet and NZBGet would start downloading. But I still had a problem, when I downloaded with Medusa, NZBGet would just keep fetching the file.
After a reboot, the settings.cfg file was empty again. Whatever I do or change in the settings, sometimes when I reboot, the settings file is empty again.

So it not always happens, only some times. But the most annoying part is that I can't download with Medusa anymore. When I use Hydra directly, it works fine (at least when I choose to upload the file to NZBGet, sending the link also stopped working, this worked fine before).

I am using Hydra on a Synology NAS in a Docker container behind a reverse proxy. Until two or three days ago (not sure when) it all worked fine..

Thanks in advance!

**Comment by theotherp** [comment]
What do you mean, Medusa doesn't work anymore? What's the problem? Where
are the logs?

Am 02.02.2018 10:27 vorm. schrieb "Miicker" <notifications@github.com>:

**Comment by Miicker** [comment]
Which logs do you need?
So after I've reinstalled Hydra, whenever Medusa snatches an episode and tries to download it, it gets send to NZBGet, but NZBGet just keeps fetching the file for a few seconds and then fails. NZBGet gives me this error:
Connection to 192.168.X.XXX failed: ErrNo 111, Connection refused
(This is the IP address of Hydra)

**Comment by theotherp** [comment]
Perhaps you had set the external URL before and now you didn't? That's used to build the URL that hydra will use in its external results which are parsed by medusa and then sent to nzbget.

Post Hydra's debug infos ZIP (from the bug report infos), the log from Medusa and from nzbget. 

I can't debug the situation if I know next to nothing about the details.

If sending links to NZBGet doesn't work that means that the link that is sent is not the link under which Hydra is actually reachable. So you (or I) need to compare what the link looks like and what it should look like.

Sentences like "stopped working" don't really help me help you. A proper bug report should always contain concrete error messages, logs, specific data, etc-.

**Comment by Miicker** [comment]
[nzbhydra-debuginfo-2018-02-02-13-12.zip](https://github.com/theotherp/nzbhydra/files/1689279/nzbhydra-debuginfo-2018-02-02-13-12.zip)

I've attached the file you requested. I've replaced the name of the domainname I use to MYDOMAIN, thats the only thing I've changed.

I also did some more investigating, and I can send a NZB link to NZBGet when I change the external URL to https://hydra.MYDOMAIN.nl), which is where Hydra can be accessed. But it should also work when I use the local IP address (which is 192.168.5.254:44446). NZBGet runs on 192.168.5.254:33334 (same machine). So does Medusa (on 192.168.5.254:33331).

Another thing I've just tried was using Hydra2, also within Docker. The option to set an external URL seems to be missing (or I can't find it). It has the same problem as Hydra 1.

**Comment by theotherp** [comment]
V2 doesn't need the external URL. You only need to make sure that you enter the IP under which Hydra is actually reachable from outside.

Simple test: Call `http://<yourhydrainstance>/api?apikey=<yourapikey>&t=tvsearch` in your browser. If that works then the whole URI `http://<yourhydrainstance>` is what you set as external URL in Hydra. Click one of the links in the search result. Can you download it? Then other programs (like NZBGet and Medusa) should also be able to. If not it's an error in your network or docker or whatever. That link is what Medusa sends to NZBGet.

In the future when your settings.cfg goes blank don't reinstall Hydra or if you do keep your old log. I can't even guess what might've happened without log file.

**Comment by Miicker** [comment]
If I enter https://hydra.MYDOMAIN.nl/api?apikey=MYAPI&t=tvsearch
I get this:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>NZB Hydra</title>
<description>NZB Hydra - the meta search</description>
<link>https://github.com/theotherp/nzbhydra</link>
<language>en-gb</language>
<webMaster>TheOtherP@gmx.de (TheOtherP)</webMaster>
<newznab:response offset="0" total="185000"/>
<item>
<title>`

And a whole lot of other information about for example the indexers, is that what should happen?

**Comment by theotherp** [comment]
Yes... that's the search results. Click one of the links. Does it work? Yes? Great. Copy the link to the clipboard and add it to NZBGet. If it works then great. If not you need to experiment with the external URL setting until it does.

**Comment by Miicker** [comment]
It works, in some cases, I've reached the request limit for some indexers. But still, when I now search for an episode of a tv show on Hydra and click "Send to NZBGet", it starts downloading. When I perform a manual search in Medusa for the same episode and select the same file as I've downloaded directly from Hydra and send it to NZBGet, it doesn't succeed. It keeps on fetching the file.

The difference between downloading through Medusa en Hydra is that when I start a download with Hydra, NZBGet shows for example:
Queue The.Big.Bang.Theory.S11E15.1080p.WEB.x264-TBS @ hydra.MYDOMAIN.nl

When I do the same with Medusa it shows:
Queue The.Big.Bang.Theory.S11E15.1080p.WEB.x264-TBS @ 192.168.5.254
So when I download trough Medusa it somehow uses the local IP address, which seems to fail. Again, this all started after I reinstalled Hydra, before, everything was working fine.

**Comment by theotherp** [comment]
What URL did you enter for Hydra in Medusa? Use your hydra.mydomain.nl one, not the local one.

**Comment by Miicker** [comment]
This is what I've entered in Medusa for Hydra:
Site URL: https://hydra.MYDOMAIN.nl/

It successfully connects and retrieves the categories. 

For NZBGet in Medusa I also used the external URL (but also tested local URL, same issue).

**Comment by theotherp** [comment]
The links in the RSS that you opened in your browser, did they use the domain or the IP? If they use the domain then hydra does everything correctly and it's something related to medusa. If they contain the IP then I can't really explain it...

**Comment by Miicker** [comment]
I think I've fixed the problem. I have no idea how. But I tested some different indexers, and it seemed like some indexers did not seem to work and some did.. Very strange, but I've added a bunch of indexers and it seems to be working now.

Hopefully the problem of the cleared config file does not come back, if so, I won't do a complete reinstall but collect the logs and create a new issue.
