### ISSUE TITLE
Questions re "secret" key in config file, backups via API, and update mechanism

### ISSUE THREAD

**Issue by coaxial** [theotherp/nzbhydra#710]
This is not a bug report but three questions:

- What is the `secret` key for under `main` in `settings.cfg`?
- How does updating works, is it automaticly updating to the latest version or is it manually triggered?
- Is it possible at all to trigger a backup from the API? It seems I can receive a zip file from calling `/internalapi/getbackup`?

I run hydra in a docker container and so it isn't desirable to have it auto-update; it's best to rebuild the container with a new version. Ensures consistent deployments.

I also use another container to backup hydra settings (using tarsnap). It would be helpful to trigger backups via the API so I have the latest settings available to backup. Finally I'm asking about the config file because I need to edit it from its defaults: it won't work with my reverse proxy otherwise, and I don't want to commit a secret if I don't have to.

Thanks,

**Comment by theotherp** [comment]
1) The secret key is used to authorize the windows runner to make API calls. It doesn't matter on linux.

2) Updates are and always will be manually triggered by the user.

3) You can call `/internalapi/getbackup`. It will return a backup ZIP which you can save or just ignore.

I don't understand your last question or even if it is a question: 

> Finally I'm asking about the config file because I need to edit it from its defaults: it won't work with my reverse proxy otherwise, and I don't want to commit a secret if I don't have to.

**Comment by coaxial** [comment]
Thank you.

In the last part, I meant that I am using hydra as part of a bunch of docker containers. I am not exposing port 5075 directly, the only interface to hydra is via a reverse proxy (in another container) at the url `/aggregator/nzb`. When hydra launches for the first time, it creates a config file with `baseUrl: null`. With that behavior, I am unable to access hydra ever because it doesn't work through the proxy. So I have to include a `settings.cfg` file in the repo where I keep my `docker-compose.yml` with the `baseUrl` properly set, so that I can access hydra once my containers are up and running. But that also forced me to commit a `secret`, and since the repo is public that bothered me. In short, it was not a question but my rationale for why I was asking the three other questions.

Does that make sense?

**Comment by theotherp** [comment]
Yes. I never considered a scenario where you would need to set the URL base as a command line parameter but I could add it. That would make it easier for you.

I'm currently mainly working on NZBHydra 2 but when I have time I'll see what I can do.

**Comment by coaxial** [comment]
That's awesome, thanks! You could also allow to optionally set it up from an env var, maybe that would be more straightforward? i.e. the env var takes precedence if set, otherwise whatever is in the config file, otherwise the default value.
