### ISSUE TITLE
How to run on port 80?

### ISSUE THREAD

**Issue by dohlin** [theotherp/nzbhydra#712]
Hey guys,

Had this working somehow before but it broke after my most recent round of patching and I can't for the life of my remember how I got it working before, and my Google-fu is failing me.

I'm on Ubuntu 16.04...does anyone have any idea what commands I'd have to run to get NZB running on port 80 again?  Its gotta be related to the priveleged port...any ideas would be much appreciated.  Many thanks!

**Comment by theotherp** [comment]
You didn't say why it doesn't work so I can only guess. Generally one port is like the other - but if it's already used by any other process you can't use it. So you need to find out if there's already another process listening on that port:

`lsof -i :80`

**Comment by dohlin** [comment]
The sole purpose of this VM is running NZBHydra, so there's definitely nothing else listening on port 80.  I'm far from an expert, but I've always had the experience and read that ports below 1024 are 'privileged' ports and therefore require running as root or similar to allow binding to.  Are you saying in this instance that's not correct?

**Comment by dohlin** [comment]
EDIT: Got it!!

I was going to say that it was so unlike me to not save the solution once I found it before!  I went digging down that black hole that is my NAS and found that I had indeed documented it somewhere!  Here is what worked for me, will work for anyone else with a similar setup to me, or can be modified slightly depending on your needs:

- Change "Port=5075" in /opt/nzbhydra/settings.cfg to "Port=80"

- Run 'sudo setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python2.7'

- Run 'sudo systemctl restart nzbhydra.service' (or simply reboot)


Hopefully this helps anyone else with the same issue, or me when I'm back here after my next round of patches breaks it again lol!! 👍
