### ISSUE TITLE
Search History - Display Show and Episode Name instead of numeric ID

### ISSUE THREAD

**Issue by m3ki** [theotherp/nzbhydra#715]
It would be great to be able to see a Show and Episode name in the search history instead of simply a numeric TVDBID.

Current behavior:
TVDB ID: 73762, Season: 11, Episode: 4
Expected Behavior:
Grey's Anatomy - S11E04 - Only Mama Knows

**Comment by theotherp** [comment]
Yes, that would be nice. For queries where the title is known it will be displayed. For all other queries I would need to make a call to TVMaze just to get the title which would massively slow down the history.

**Comment by m3ki** [comment]
What if you were to create a cache of at least if tv show names? And even ask a user to do "update names", if needed?
