### ISSUE TITLE
NZBClub 404 Errors

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#72]
I get a lot of 404 Errors from NZBClub, which leads to it being disabled.  Example:

````python
2015-12-19 21:47:54,176 - ERROR - search_module - Error while connecting to URL
https://nzbclub.com/nzbrss.aspx?rpp=250&ns=1&sn=1&ig=2&st=5&q=term1+term2:
404 Client Error: Not Found for url: https://nzbclub.com/nzbrss.aspx?rpp=250&ns=
1&sn=1&ig=2&st=5&q=term1+term2
````

I can re-enable it, but it just get disabled again.

I know NZBM had a similar issue in the past, and I believe this was the code that fixed it:

https://github.com/benoit934/usntssearch/commit/0fd1db461e73401df819b44d911ef2bd1d7df31c

Also mentioned here:

https://github.com/pillone/usntssearch/issues/146

Not sure if that's applicable in this situation, but thought I'd mention it.

Also, only slightly related, in your README.md you have NZBClub listed twice:

> Searches Binsearch, **NZBClub**, NZBIndex, **NZBClub**, omgwtfnzbs.org, Womble and most newznab compatible indexers

**Comment by theotherp** [comment]
Yeah, it seems to work with https://member.nzbclub.com/nzbfeeds.aspx?rpp=250&ns=1&sn=1&ig=2&st=5&q=term as well as https://www.nzbclub.com/nzbrss.aspx?rpp=250&ns=1&sn=1&ig=2&st=5&q=term

**Comment by albino1** [comment]
Yup, works now.  Thanks :)
