### ISSUE TITLE
Missing shows - how to update them

### ISSUE THREAD

**Issue by Tiwas** [theotherp/nzbhydra#722]
There are a few shows not coming up when I search. One of these is Condor (https://www.thetvdb.com/series/342107). I can see from the search history that SR has searched through an API call for the show id, but if I try to enter the name into the search box there's no suggestions. Is there a way to either search using show id or force it to update the show list?

**Comment by theotherp** [comment]
While not officially deprecated I've stopped developing NZBHydra. I recommend upgrading to https://github.com/theotherp/nzbhydra2/

**Comment by Tiwas** [comment]
Thanks, and thanks for letting me know.

I've emailed the developer of the new project to check if there's an easy upgrade path.

**Comment by theotherp** [comment]
I am the developer of the new project :-)

Just follow the instructions in the readme. On startup you will be asked if you want to migrate from v1.
