### ISSUE TITLE
No results were returned from your indexer, please check your settings.

### ISSUE THREAD

**Issue by shadi1989** [theotherp/nzbhydra#723]
I'm trying to add NZBHydra into my Sonarr but within Sonarr i get the error "No results were returned from your indexer, please check your settings.".
Both Sonarr as NZBHydra run in Docker.

Name: NZBHydra
Enable RSS Sync: Yes
Enable Search: Yes
URL: http://192.168.192.3:5075
API Key: copied from NZBHydra
Categories: 5030,5040
Anime Categories: <empty>

Already tried restarting the Docker instances, no effect.
Rebooted the Synology NAS, no effect

http://192.168.192.3:5075/api?t=caps&apikey=<apikey>
Does work:
```
<caps>
<server appversion="0.0.1" version="0.1" title="NZBHydra" email="theotherp@gmx.de" url="https://github.com/theotherp/nzbhydra"/>
<limits max="100" default="100"/>
<retention days="2500"/>
<searching>
<search available="yes" supportedParams="q"/>
<tv-search available="yes" supportedParams="q,rid,tvdbid,season,ep"/>
<movie-search available="yes" supportedParams="q,imdbid"/>
<audio-search available="no"/>
<book-search available="yes"/>
</searching>
<categories>
etc
etc
```

**Comment by theotherp** [comment]
Please follow the instructions and post the debug infos zip.

**Comment by shadi1989** [comment]
Bugreport attached.

Removed the Docker container, removed settings folder and reinstalled again. same issue.

[nzbhydra-debuginfo-2018-07-21-20-20.zip](https://github.com/theotherp/nzbhydra/files/2216397/nzbhydra-debuginfo-2018-07-21-20-20.zip)

**Comment by shadi1989** [comment]
I've edited all default indexers to "internal and API searches" and saved = same result
Added 6box with api key and saved = Sonarr test successfull.

Looks like its solved.

**Comment by meoz** [comment]
Did you manage to solve this ?
All of a sudden I'm getting the same "No results were returned from your indexer, please check your settings." message when trying to add Nzbhydra as indexer.  Both are running in Docker as well.

Has run fine for quite some time, something changed ?

**Comment by theotherp** [comment]
I recommend switching to NZBHydra 2.

**Comment by shadi1989** [comment]
@meoz solution is 1 post higher.
Enabled 6box with api-key, then saved config. solved this error.

@theotherp is there a docker image for v2?

**Comment by theotherp** [comment]
Yes, see https://github.com/theotherp/nzbhydra2
