### ISSUE TITLE
Issues connecting Sonarr to Hydra2

### ISSUE THREAD

**Issue by conrad-nash** [theotherp/nzbhydra#727]
I'm not sure if this is a Hydra or a Sonarr issue, but I'm struggling to set Hydra2 as an indexer in Sonarr. I had Hydra1 working but I stupidly deleted it before configuring the new indexer so I don't have the config to copy from.

* What do you expect to happen? What does happen? 
I want to add Hydra2 as an indexer. I've set Sonarr up with my local server address, and an APIKey but I get "Unable to connect to indexer, check the log for more details" in Sonarr. When I access http://192.168.86.54:5076/api?apikey=(removed)&t=caps

I get results:

`<caps>
<server title="NZBHydra 2" email="theotherp@gmx.de" url="https://github.com/theotherp/nzbhydra2"/>
<limits max="100" default="100"/>
<retention days="3000"/>
<searching>
<search available="yes" supportedParams="q,cat,limit,offset,minage,maxage,minsize,maxsize"/>
<tv-search available="yes" supportedParams="q,rid,tvdbid,tvmazeid,traktid,season,ep,cat,limit,offset,minage,maxage,minsize,maxsize"/>
<movie-search available="yes" supportedParams="q,imdbid,tmdbid,cat,limit,offset,minage,maxage,minsize,maxsize"/>
<audio-search available="no" supportedParams=""/>
<book-search available="yes" supportedParams="q,author,title,cat,limit,offset,minage,maxage,minsize,maxsize"/>
</searching>
<categories>
<category id="1000" name="Console">
<subcat id="1010" name="NDS"/>
<subcat id="1020" name="PSP"/>
<subcat id="1030" name="Wii"/>
<subcat id="1040" name="XBox"/>
<subcat id="1050" name="Xbox 360"/>
<subcat id="1060" name="Wiiware"/>
<subcat id="1070" name="Xbox 360 DLC"/>
</category>
<category id="2000" name="Movies">
<subcat id="2010" name="Foreign"/>
<subcat id="2020" name="Other"/>
<subcat id="2030" name="SD"/>
<subcat id="2040" name="HD"/>
<subcat id="2045" name="UHD"/>
<subcat id="2050" name="Bluray"/>
<subcat id="2060" name="3D"/>
</category>
<category id="3000" name="Audio">
<subcat id="3010" name="MP3"/>
<subcat id="3020" name="Video"/>
<subcat id="3030" name="Audiobook"/>
<subcat id="3040" name="Lossless"/>
</category>
<category id="4000" name="PC">
<subcat id="4010" name="0day"/>
<subcat id="4020" name="ISO"/>
<subcat id="4030" name="Mac"/>
<subcat id="4040" name="Mobile Oher"/>
<subcat id="4050" name="Games"/>
<subcat id="4060" name="Mobile IOS"/>
<subcat id="4070" name="Mobile Android"/>
</category>
<category id="5000" name="TV">
<subcat id="5020" name="Foreign"/>
<subcat id="5030" name="SD"/>
<subcat id="5040" name="HD"/>
<subcat id="5045" name="UHD"/>
<subcat id="5050" name="Other"/>
<subcat id="5060" name="Sport"/>
<subcat id="5070" name="Anime"/>
<subcat id="5080" name="Documentary"/>
</category>
<category id="6000" name="XXX">
<subcat id="6010" name="DVD"/>
<subcat id="6020" name="WMV"/>
<subcat id="6030" name="XviD"/>
<subcat id="6040" name="x264"/>
<subcat id="6050" name="Pack"/>
<subcat id="6060" name="Imgset"/>
<subcat id="6070" name="Other"/>
</category>
<category id="7000" name="Books">
<subcat id="7010" name="Mags"/>
<subcat id="7020" name="Ebook"/>
<subcat id="7030" name="COmics"/>
</category>
<category id="8000" name="Other">
<subcat id="8010" name="Misc"/>
</category>
</categories>
</caps>`

Playing around with the settings gives me different results. If I put the values into the appropriate fields in Sonarr it doesn't seem to construct the URL and it tries to parse the main Hydra webpage (as an aside, I think the link tag on line ten is missing a trailing slash).

If I fill in the full URL as above, I get the error in the logs. That's the only way to configure Sonarr to make it connect to Hydra at all.

As I say, this might be a Sonarr issue, but I wondered if there's anything obvious I'm doing wrong.

Hydra2 has multiple indexers set up and when performing searches directly in the application I get results. I got an error from one and it was disabled, but that seems to make no difference.

This is the info from the Sonarr log:

`18-9-2 16:06:46.0|Debug|NewznabCapabilitiesProvider|Failed to parse newznab api capabilities for http://192.168.86.54:5076/api?t=caps&apikey=(removed) System.Xml.XmlException: Unexpected XML
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 99
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 67

18-9-2 16:06:46.0|Warn|Newznab|Unable to connect to indexer

[v2.0.0.5228] System.Xml.XmlException: Unexpected XML
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 99
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 74
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Common\Cache\Cached.cs:line 81
   at NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:line 35
   at NzbDrone.Core.Indexers.Newznab.Newznab.get_PageSize() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 22
   at NzbDrone.Core.Indexers.Newznab.Newznab.GetRequestGenerator() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\Newznab\Newznab.cs:line 26
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\BuildAgent\work\5d7581516c0ee5b3\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 334

18-9-2 16:06:46.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
18-9-2 16:06:46.0|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (36 ms)`

I've attached the Hydra Logs as well. Let me know if this is something you can help with.

[nzbhydra-debuginfos-2018-09-02-16-08.zip](https://github.com/theotherp/nzbhydra/files/2343481/nzbhydra-debuginfos-2018-09-02-16-08.zip)

**Comment by theotherp** [comment]
I don't think this is strictly hydra related if the URL called by sonarr
returns the expected results when called in the browser. You should enable
trace logging in sonarr, try again and check the log in sonarr. It should
show the return of the api call to hydra.

**Comment by theotherp** [comment]
Oh, go to the hydra config and click the "api?" button. Copyright the shown
api URL and paste it into the URL input in sonarr. Do the same for the api
key. You shouldn't need to enter any other values.

**Comment by conrad-nash** [comment]
Thanks for the reply. I was able to get a backup of sonarr re-imported and I checked the config. FOr reference:

URL is http://<IP>:5076
API Path is /api (you have to enable advanced settings to be able to see this)
apikey is your apikey

Then it works. Simple, when you know how.

Thanks, please close this issue :)

**Comment by theotherp** [comment]
That URL looks a bit weird. And you don't have to manually change or set
the api path. But as long as it works...

**Comment by conrad-nash** [comment]
Sorry, I meant that as a placeholder, mine is http://192.168.86.54:5076/
Sonarr won't work without the /api in the path.
