### ISSUE TITLE
Error after second start due to failed migration 

### ISSUE THREAD

**Issue by Hobbabobba** [theotherp/nzbhydra#73]
Hydra started once in daemon-mode. When i shut it down and try to restart, i get this error-message:

Loading settings from settings.cfg
Traceback (most recent call last):
  File "nzbhydra.py", line 136, in <module>
    run()
  File "nzbhydra.py", line 94, in run
    config.load(settings_file)
  File "/opt/nzbhydra/nzbhydra/config.py", line 283, in load
    migrate(loaded_config)
  File "/opt/nzbhydra/nzbhydra/config.py", line 255, in migrate
    if sabnzbd["host"] and sabnzbd["port"]:
KeyError: u'host'

**Comment by theotherp** [comment]
Does this only happen in daemon mode? The area of the code is related to config migration which I added tomorrow.

**Comment by Hobbabobba** [comment]
not just in daemon mode

**Comment by theotherp** [comment]
Crap. Will fix it later.

**Comment by Hobbabobba** [comment]
i will try with a fresh VM (happy user of ESXI), will give you an update, soon!

**Comment by theotherp** [comment]
Take a look at your settings.cfg. Which configVersion does it say?

**Comment by Hobbabobba** [comment]
0.0.1a38

**Comment by theotherp** [comment]
Uhm no  in the settings.cfg there should be an entry titled configVersion.

**Comment by Hobbabobba** [comment]
I can find this line:
"configVersion": 1,

**Comment by theotherp** [comment]
Ahhhh I know why. Sorry, will fix it.

**Comment by theotherp** [comment]
Need to set default value for configVersion to 3 but cannot do that on mobile.

**Comment by Hobbabobba** [comment]
changed the version to "3" instead of "1", now it starts!
