### ISSUE TITLE
Displayed Log vs. Actual Log

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#74]
I did a fresh install of NZBHydra two days ago, but the information displayed in the Current Log in Config is only 606 lines and hasn't been updated in ~24 hours.

However, the actual `nzbhydra.log` file is 1253 lines long and up-to-date with my latest restart from a few minutes ago.

I'm not sure why there's a discrepancy between the displayed log and the actual log, but I thought it worth mentioning, particularly for people trying to debug.

**Comment by theotherp** [comment]
That's weird. Will take a look, thanks.

**Comment by theotherp** [comment]
I'm gonna close this.
