### ISSUE TITLE
Will it be possible to leave out Password protected archives/ NZBs?

### ISSUE THREAD

**Issue by groentebroer** [theotherp/nzbhydra#83]
Will it be possible to leave out Password protected archives?

**Comment by theotherp** [comment]
Where indexers provide this information, yes. I'll add it at some point.

**Comment by judhat2** [comment]
I have noticed that some indexers returns results with the password field as -1 (unknown).  Do you think it's better to ignore these releases, too?  I was thinking maybe to just make the releases with a password attribute as 1 or 2.  The [Newznab docs](http://newznab.readthedocs.io/en/latest/misc/api/#predefined-attributes) say: _“0” no, “1” rar pass, “2” contains inner archive._

I think this is part of the code that I am referring to.
```
elif attribute_name == "password" and attribute_value != "1":
     entry.passworded = True
```
I see results like this sometimes.  I checked, and 99% of these the password field says -1 (unknown).  I know this is probably a problem with the indexers not being high quality, but I thought it would at least be worth mentioning.
<img width="689" alt="capture"src="https://cloud.githubusercontent.com/assets/3536802/15433768/a775d3ba-1eee-11e6-8961-c2272f3478ff.PNG">

**Comment by theotherp** [comment]
I felt false negatives were not as bad as false positives. Most downloaders recognize downloaded releases, don't they? I could probably make it configurable and let the user decide.

**Comment by albino1** [comment]
I can't remember ever getting a passworded release from NZBH that wasn't from one of the open indexers like Binsearch or NZBClub.  FreeNZBs is new, so maybe they haven't figured out how to filter yet.  The bigger loss from that screenshot is Usenet-Crawler continuing its death spiral.

**Comment by judhat2** [comment]
I didn't realize usenetcrawler was falling apart. I just checked their forum, and it seems the admin hasn't been seen in a while. That probably explains why the results were like that. And your probably correct about free freenzbs. Now that I think about it, the way the code is now is probably the best. I don't think making that configurable would be necessary.

**Comment by albino1** [comment]
Yeah, the Usenet Crawler admin went absent last year for a few months, supposedly due to drug problems.  Then he came back all charged up, made a bunch of improvements, did some shady stuff to get the site banned from Reddit, and eventually disappeared again a couple months ago.  The site's been on autopilot ever since.  A shame really.
