### ISSUE TITLE
Alternating Row Colors

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#86]
I like the new design, but it would be nice if the rows were alternating colors like it was before.  Same with expanding the grouped titles, and the table header.  Right now it's all just black on white and it's a little hard to read when there's lots of rows.  Just a basic white/light grey would be a big improvement.

**Comment by theotherp** [comment]
Yeah, I'm not done with the table, still tinkering.

**Comment by albino1** [comment]
Yeah, I didn't figure you were, but thought I'd bring it up just to be sure :)

**Comment by theotherp** [comment]
By the way, the old layout didn't have alternating row colors either.
