### ISSUE TITLE
Change Clicking Search to Root URL

### ISSUE THREAD

**Issue by albino1** [theotherp/nzbhydra#87]
Right now if you click search it returns to the search page, but the URL remains the long `http://127.0.0.1:5075/?category=All&query=etcetcetcetc` search string.  Not a big deal, but if that tab is unloaded (via restart or whatever) and you re-activate it you now have to wait for the old search to complete again before you can search for a new one.  It might make more sense then when you click the Search button on the top it acts as a full "reset" of NZBHydra returning the URL to just plain old `http://127.0.0.1:5075/`.  Whether you'd want to also clear the search box or not, I'm not sure it matters, but it might be more in line with the "reset" idea.  I think that was the behavior before the re-design, but I could be wrong.

Not a big deal, just something I've hit a few times and thought I'd mention.

**Comment by theotherp** [comment]
You're right  it should reset.
