### ISSUE TITLE
Raise amount of indexer or n-indexer

### ISSUE THREAD

**Issue by FailOPS** [theotherp/nzbhydra#88]
I would like to have more and it seems that there is a hard coded limit, as I can't add more then 20 indexer.

Possible solutions would be to set it to a higher limit or make it infinite (n-indexer)

**Comment by theotherp** [comment]
Jesus... 

I'd rather not have a limit, too, but unfortunately the code doesn't allow it. What do you propose? 647? 2^32 - 1?
