### ISSUE TITLE
Run as daemon (linux)

### ISSUE THREAD

**Issue by theotherp** [theotherp/nzbhydra#9]
Add option to run as daemon (via command line)

**Comment by staticn0de** [comment]
You could use this init script (it's just about the same as the one I use to start nzbmegasearch) but you may be looking for something more technical.

#start nzbhyrda at boot

setuid USERNAMEFORNZBHYDRA
setgid nogroup

start on runlevel [2345]
stop on runlevel [016]

respawn

exec python /path/to/nzbhydra.py

**Comment by theotherp** [comment]
Thanks for the tip, I'm indeed looking for something to include in the script. I already know where to get the code, just would prefer for somebody to implement it who has some more *nix knowledge than me.
