### ISSUE TITLE
missing module requests

### ISSUE THREAD

**Issue by Bilbo** [theotherp/nzbhydra#94]
Thanks for the updates... Great application.
After the latest updates on Jan 10 though, I'm now getting the following error on startup of the application.

C:\Program Files\nzbhydra>python nzbhydra.py
Traceback (most recent call last):
  File "nzbhydra.py", line 6, in <module>
    import requests
ImportError: No module named requests

**Comment by theotherp** [comment]
I thought my CI tests would catch that :-(

Please check the newest revision.

**Comment by Bilbo** [comment]
Thanks,

the develop version ff490b6b75441ec0a130f628b67cc3e9267da0ab worked.
